### PR TITLE
Make sure old LiveUpdate flow works fine

### LINKED ISSUE #7864: collectionproxy.missing_resources() and ...get_resources() always return table with one resource
**Describe the bug (REQUIRED)**
collectionproxy.missing_resources() and collectionproxy.get_resources() always return a table with a single resource when there should be more than one.

**To Reproduce (REQUIRED)**
I've attached a minimal version of the project. You need to bundle the MacOS application and run it. In the console you can see that the table consists of a single missing resource, whereas in version 1.4.6 the table consists of 5 missing resources.

**Expected behavior (REQUIRED)**
collectionproxy.missing_resources() and collectionproxy.get_resources() must return a table with more than one resource.

**Defold version (REQUIRED):**
  - Version Defold 1.5.0 BETA

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: Ventura 13.4
 - Device: MacBook Pro

**Minimal repro case project (OPTIONAL):**
[test_resources.zip](https://github.com/defold/defold/files/12269729/test_resources.zip)

### PR DESCRIPTION
**Pull request by AGulev**
fix https://github.com/defold/defold/issues/7864
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/liveupdate/src/liveupdate.cpp [hunk 1]
```diff
@@ -391,7 +391,7 @@ namespace dmLiveUpdate
             dmLogWarning("Failed to set manifest to mounted archive uri: %s:%s/%s\n", uri.m_Scheme, uri.m_Location, uri.m_Path);
             return dmResource::RESULT_INVALID_DATA;
         }
-
```
Comment (AGulev) [inline engine/liveupdate/src/liveupdate.cpp:394]: `dmResourceProvider::SetManifest()` removes the old one, that means we need to update pointer to the new manifest in `g_LiveUpdate`

File: engine/resource/src/providers/provider_archive_mutable.cpp [hunk 2]
```diff
@@ -565,7 +565,7 @@ namespace dmResourceProviderArchiveMutable
             dmResource::WriteManifest(manifest_path, archive->m_Manifest);
             dmLogInfo("Wrote manifest to '%s'", manifest_path);
         }
-
+        CreateEntryMap(archive);
```
Comment (AGulev) [inline engine/resource/src/providers/provider_archive_mutable.cpp:568]: Removing of the old manifest also removes all the hashes which we use as `m_EntryMap` keys. So we need to create a new `m_EntryMap `

File: engine/resource/src/resource_mounts.cpp [hunk 3]
```diff
@@ -482,7 +482,7 @@ static dmResource::Result GetDependenciesInternal(DependencyIterContext* ctx, co
 
         for (uint32_t d = 0; d < dependencies.Size(); ++d)
         {
-            dmhash_t dep_hash = dependencies[i];
+            dmhash_t dep_hash = dependencies[d];
```
Comment (AGulev) [inline engine/resource/src/resource_mounts.cpp:485]: The initial issue with one type where iterator should use internal for-loop variable `d` instead of the variable `i` from an external for-loop

**Review by britzl — APPROVED** [review]
