### PR TITLE
Fix template property flattening regression when building

### LINKED ISSUE #7213: The GUI template location is not applied when changing the layout if there has been no change in the position of the parent node.
**Describe the bug (REQUIRED)**
The location of the GUI template is not applied when changing the layout unless there has been a change in the position of the parent node (when running in the editor). In the build it works as expected.

**To Reproduce (REQUIRED)**
1. Create gui template.
2. Move the template to the desired positions for different layouts, and do not change the position of the parent node in the template.
3. Run project (ctrl-b)
4. When the window is resized after switching the layout, the template stays in place in the default position.

**Expected behavior (REQUIRED)**
The template is expected to move to the specified position.

**Defold version (REQUIRED):**
  - Version 1.4.0.

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Minimal repro case project (OPTIONAL):**
[layout_with_template_bug.zip](https://github.com/defold/defold/files/10183906/layout_with_template_bug.zip)

**Screenshots (OPTIONAL):**
image
image

### PR DESCRIPTION
**Pull request by matgis**
Fixed a regression when building GUI scenes that would cause certain properties (such as transform-related ones) to not be correctly applied to the imported nodes unless they had layout overrides.

Fixes #7213
Fixes #11110

### Technical changes
* Added `update-vals` and `update-vals-kv` to `coll` module. Our `update-vals` retains the input collection type and accepts additional arguments to the transform function.
* Added `map-vals` and `map-vals-kv` to `coll` module.
* Added extensive tests around template gui node flattening during build.

### CODE REVIEW

File: editor/src/clj/editor/gui.clj [hunk 1]
```diff
@@ -3209,24 +3209,28 @@
...
+                                            (select-keys [:custom-type :id :parent :template-node-child :type])
+                                            (into (map prop-entry->pb-field-entry)
+                                                  prop->value)
+                                            (node-desc->rt-node-desc layout-name))
+                                        (protobuf/clear-defaults Gui$NodeDesc))]
+                     (let [id (:id node-desc-for-layout)
+                           node-desc-for-default-layout (id->node-desc-for-default-layout id)]
+                       (assert (map? node-desc-for-default-layout))
+                       (when (not= node-desc-for-default-layout node-desc-for-layout)
+                         node-desc-for-layout)))))))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3233]: The fix: We were only looking at property overrides to determine if we need to include a layout-specific `NodeDesc` for the node in the build output. However, template nodes apply their properties to the imported children before removing themselves from the built hierarchy, and we weren't seeing those property changes. In the new code, we apply the template flattening before this and compare the output of the layout-specific `NodeDesc` to that instead,

File: editor/src/clj/internal/node.clj [hunk 2]
```diff
@@ -1029,7 +1029,7 @@
                                                                (update :default f)
 
                                                                (some? (-> propdef :dynamics))
-                                                               (update :dynamics (partial util/map-vals f)))]))
+                                                               (update :dynamics (partial coll/map-vals f)))]))
```
Comment (matgis) [inline editor/src/clj/internal/node.clj:1032]: I've moved `util/map-vals` into `util.coll`, but kept `util/map-vals` as a macro so this PR wouldn't baloon in size. However, we used it as a function in this one file.

File: editor/test/integration/gui_test.clj [hunk 3]
```diff
@@ -535,13 +535,6 @@
   (-> (gui-node scene id)
       (g/node-value :text)))
 
-(defn- trans-x [root-id target-id]
-  (let [s (tree-seq fn/constantly-true :children (g/node-value root-id :scene))]
-    (when-let [^Matrix4d m (some #(and (= (:node-id %) target-id) (:transform %)) s)]
-      (let [t (Vector3d.)]
-        (.get m t)
-        (.getX t)))))
-
```
Comment (matgis) [inline editor/test/integration/gui_test.clj:544]: Removed unused function.

File: editor/test/integration/gui_test.clj [hunk 4]
```diff
@@ -3026,3 +3019,549 @@
...
+
+(def ^:private gui-alpha-pb-field-index (gui/prop-key->pb-field-index :alpha))
+(def ^:private gui-enabled-pb-field-index (gui/prop-key->pb-field-index :enabled))
+(def ^:private gui-inherit-alpha-pb-field-index (gui/prop-key->pb-field-index :inherit-alpha))
+(def ^:private gui-layer-pb-field-index (gui/prop-key->pb-field-index :layer))
+(def ^:private gui-position-pb-field-index (gui/prop-key->pb-field-index :position))
+(def ^:private gui-rotation-pb-field-index (gui/prop-key->pb-field-index :rotation))
+(def ^:private gui-scale-pb-field-index (gui/prop-key->pb-field-index :scale))
+
+(deftest template-props-baked-into-imported-node-descs-test
```
Comment (matgis) [inline editor/test/integration/gui_test.clj:3051]: There are sooo many combinations to test! 😮‍💨

File: editor/src/clj/util/coll.clj [hunk 5]
```diff
@@ -225,6 +225,50 @@
...
+   (when coll
+     (let [use-transient (supports-transient? coll)
+           rf (if use-transient
+                #(assoc! %1 %2 (f %3))
+                #(assoc %1 %2 (f %3)))
+           init (cond-> (empty coll)
+                        use-transient transient)]
+       (with-meta (cond-> (reduce-kv rf init coll)
+                          use-transient persistent!)
+                  (meta coll))))))
```
Comment (vlaaad) [inline editor/src/clj/util/coll.clj]: Why use this over `clojure.core/update-vals`? Is it to keep the type?

File: editor/src/clj/internal/node.clj [hunk 6]
```diff
@@ -1017,7 +1017,7 @@
 
 (defn- update-fn-maps [tree f]
   (-> tree
-      (update :output (partial util/map-vals f))
+      (update :output (partial coll/map-vals f))
```
Comment (vlaaad) [inline editor/src/clj/internal/node.clj:1020]: If `coll` was a first argument to `map-vals` (like in `clojure.core/update-vals`), we wouldn't need to create a throw-away partial function; instead, we could use `(update :output coll/map-vals f)`

File: editor/src/clj/util/coll.clj [hunk 7]
```diff
@@ -225,6 +225,50 @@
...
 
+(defn map-vals
+  "Applies f to all values in the supplied associative collection. Returns a new
+  associative collection of the same type with all the same keys, but the values
+  being the results of applying f to each previous value. Preserves metadata. If
+  coll is nil, returns nil without calling f."
+  ([f]
+   (map (fn [entry]
+          (pair (key entry)
+                (f (val entry))))))
```
Comment (vlaaad) [inline editor/src/clj/util/coll.clj:281]: Weird to have transducer arity here at all. It's unused, right? I prefer the semantics of `update-vals` more — it's a map-specific operation, not a collection processing operation.

**Review by vlaaad — DISMISSED** [review]
LGTM! Minor nitpick about `map-vals` — I think it would be better if it didn't pretend to be a generic collection processor with a transducer arity and coll as a last argument. Its purpose is maps, right?

File: editor/src/clj/util/coll.clj (hunk 5 above)
Comment (matgis) [reply editor/src/clj/util/coll.clj]: Ohh, I was not aware of `update-vals`! 👍 It suits my use-case perfectly, so I will change the test function to use it.

I still think `map-vals` and `map-vals-kv` has a place, though. The transducer arity is useful when you would use `(map (fn [[k v]] (pair k (f v)))`, which I've done plenty of times as part of a transformation.

However, looking at the source for `update-vals`, it also strikes me that while `map-vals` will retain the input map type, that probably doesn't work for records. I'll fix!

File: editor/src/clj/internal/node.clj (hunk 6 above)
Comment (matgis) [reply editor/src/clj/internal/node.clj:1020]: Yeah, `update-vals` looks like just what I need! I must have missed them adding it to `clojure.core`. It'll be a lot more readable that way. Thanks! ❤️

**Review by vlaaad — APPROVED** [review]
Awesome!
