### PR TITLE
Fix json parsing load times for large files

### LINKED ISSUE #7005: Extremely slow loading of large json files
Currently, we try to incrementally guess the number of tokens needed to allocate memory.
Then we allocate and parse the file. If the parse fails due to out of buffer, then we increase the memory somewhat and do it again...

### PR DESCRIPTION
**Pull request by JCash**
This fixes loading of large json files. A file that previously would take minutes now takes a second.

Fixes #7005

### CODE REVIEW

File: engine/dlib/src/dlib/json.cpp [hunk 1]
```diff
@@ -211,15 +207,24 @@ namespace dmJson
...
         jsmnerr_t err = (jsmnerr_t) 0;
         jsmntok_t* tokens = 0;
-        do {
-            jsmn_init(&parser);
-            token_count += dmMath::Min(256U, token_count);
-            free(tokens);
+
+        jsmn_init(&parser);
+        int token_count = (uint32_t)jsmn_parse(&parser, buffer, buffer_length, 0, 0);
+        if (token_count >= 0)
```
Comment (JCash) [inline engine/dlib/src/dlib/json.cpp:216]: Not sure why I didn't see this last time I updated this code.
THe api _does_ have a way to query the number of required tokens.

4mb test file went from many minutes down to 1.4s.

**Review by britzl — APPROVED** [review]
Wow, great find!
