### PR TITLE
Fix multipage atlas issue on HTML5 target running on Chrome on Android

### LINKED ISSUE #11009: Mobile web build error when using paged atlas
**Describe the bug (REQUIRED)**
When run project with a multipage atlas there are errors
>ERROR :GL_INVALID_VALUE :
glCompressedTexImageD: size is not correct for dimensions

>RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?

Sprite doesn't render

**To Reproduce (REQUIRED)**

[skin test.zip](https://github.com/user-attachments/files/21408498/skin.test.zip)
1. Build project for html5 (cmd+M) and oepn in browser on android

**Expected behavior (REQUIRED)**
sprite in the middle of the screen should be rendered, but it's not

**Defold version (REQUIRED):**
  - 1.10.3, 1.10.4

**Platforms (REQUIRED):**
 - Platforms: Android web (html5 on mobile)
 - OS: Android 12
 - Device: Samsung S10

### PR DESCRIPTION
**Pull request by AGulev**
Fixed an issue where multipage atlas can't be transcoded and used in HTML5 on Chrome on Android. In such cases, the ASTC format will be marked as unsupported, and the next suitable format will be used (ETC2 in most cases).

Fix https://github.com/defold/defold/issues/11009

### CODE REVIEW

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 1]
```diff
@@ -1346,27 +1373,6 @@ static void LogFrameBufferError(GLenum status)
...
-                0x2a, 0xcc, 0x90, 0x01, 0x04, 0x04, 0x01, 0x04, 0x04, 0x01, 0x04, 0x04, 0x01
-            };
-            GLuint texture;
-            glGenTextures(1, &texture);
-            glBindTexture(GL_TEXTURE_2D_ARRAY, texture);
-            DMGRAPHICS_COMPRESSED_TEX_IMAGE_3D(GL_TEXTURE_2D_ARRAY, 0, DMGRAPHICS_TEXTURE_FORMAT_RGBA_ASTC_4x4_KHR, 4, 4, 2, 0, 32, &fakeZeroBuffer);
-            GLint err = glGetError();
-            if (err != 0)
-            {
-                context->m_TextureFormatSupport &= ~(1 << TEXTURE_FORMAT_RGBA_ASTC_4X4);
```
Comment (AGulev) [inline engine/graphics/src/opengl/graphics_opengl.cpp:1365]: This is outdated, one of the updates anciently removed this old workaround so I restore it using `context->m_ASTCSupport` instead.

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 2]
```diff
@@ -1321,10 +1321,37 @@ static void LogFrameBufferError(GLenum status)
...
+            // Workaround for some old phones which don't work with ASTC in glCompressedTexImage3D
+            // see https://github.com/defold/defold/issues/8030
+            // and https://github.com/defold/defold/issues/11009
+            if (context->m_IsGles3Version && OpenGLIsTextureFormatSupported(context, TEXTURE_FORMAT_RGBA_ASTC_4X4)) {
+                unsigned char fakeZeroBuffer[] = {
+                    0xFC, 0xFD, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
+                    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
+                    
+                    0xFC, 0xFD, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
+                    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
```
Comment (AGulev) [inline engine/graphics/src/opengl/graphics_opengl.cpp:1335]: I changed buffer to match size

**Review by ekharkunov — APPROVED** [review]
