### PR TITLE
Fix frustrum culling for sprites with pivot point

### LINKED ISSUE #9917: Frustum culling does not take into account sprite pivot points
**Describe the bug**
Modifying a sprite's pivot point means frustum culling behaves incorrectly, e.g. objects being culled even though they should be visible.

In this example I have created two versions of a sprite, one with a default y pivot (0.5) and one of a y pivot of 1.

All of these sprites should be visible, but the leftmost two should be mostly off screen:
image

In practice, the second sprite is incorrectly culled:
image

**Defold version:**
1.9.5

**Minimal repro case project:**
[Frustum_pivot.zip](https://github.com/user-attachments/files/18125875/Frustum_pivot.zip)

### PR DESCRIPTION
**Pull request by ekharkunov**
Fixed culling for sprites with pivot points. Also implemented some optimization on how geometry data calculated and stored between batches. So no it should be a bit faster in terms of calculation but consume some memory to store cached information.

Fixes #9917 

### Technical notes
Implementation the same as it was https://github.com/defold/defold/pull/9943
+ fix from https://github.com/defold/defold/pull/11283
+ fix for untextured sprites
+ fix of render sorting problem for sprites with pivot point #11313
+ fix of crash #11320

**Notes for reviewer:**
I've commented all places which were presented in reverted PRs.

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -608,21 +682,24 @@ namespace dmGameSystem
...
                 component->m_Resource->m_DDF->m_SizeMode == dmGameSystemDDF::SpriteDesc::SIZE_MODE_MANUAL;
 
         component->m_DynamicVertexAttributeIndex = INVALID_DYNAMIC_ATTRIBUTE_INDEX;
         component->m_Size = Vector3(0.0f, 0.0f, 0.0f);
         component->m_AnimationID = 0;
+        component->m_AnimationPlayback = dmGameSystemDDF::PLAYBACK_NONE;
+        component->m_AnimationFrameCount = 1;
 
-        if (component->m_Resource->m_DDF->m_SizeMode == dmGameSystemDDF::SpriteDesc::SIZE_MODE_MANUAL)
+        if (component->m_Resource->m_DDF->m_SizeMode == dmGameSystemDDF::SpriteDesc::SIZE_MODE_MANUAL || component->m_NumTextures == 0)
```
Comment (ekharkunov) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:696]: In case if sprite has "auto size" in the editor and doesn't have assigned texture - sprite size was 0. That is the first fix for untextured sprites.

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 2]
```diff
@@ -1394,15 +1518,18 @@ namespace dmGameSystem
                     const float* local_position_channels[] = { (float*) &positions_local };
                     const float* world_position_channels[] = { (float*) &positions_world };
 
+                    const uint8_t uv_channels_count = textures_num != 0 ? textures_num : 1;
```
Comment (ekharkunov) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:1521]: Is sprite has no assigned texture - we don't write uvs information because channels count was 0. The second fix for untextured sprites

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 3]
```diff
@@ -1605,212 +1717,160 @@ namespace dmGameSystem
...
-                textures.m_Resources[i] = GetTextureSetByIndex(component, i);
-                textures.m_TextureSets[i] = textures.m_Resources[i]->m_TextureSet;
-            }
+        // We need to pad the buffer if the vertex stride doesn't start at an even byte offset from the start
+        vertex_memsize += vertex_stride - vertex_memsize % vertex_stride;
 
-            // Get the correct animation frames, and other meta data
-            ResolveAnimationData(&textures, component->m_CurrentAnimation, component->m_CurrentAnimationFrame);
+        // Get the correct animation frames, and other meta data
+        AnimationData* anim_data = GetOrCreateAnimationData(sprite_world, component);
```
Comment (ekharkunov) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:1807]: Now we count vertex and indices count here instead of counting it once when create AnimationData because it can be case when in the project we have two different sprites which shares the same atlas and use the same texture from atlas, but one of them is quad, another one is slice9. So now we check if sprite use slice9 and set appropriate number of vertexes and indices. In other case - we use precalculated counters from AnimationData. Fix for crash https://github.com/defold/defold/issues/11320

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 4]
```diff
@@ -1851,7 +1961,14 @@ namespace dmGameSystem
 
             float radius_sq = radiuses[entry->m_UserData];
 
-            bool intersect = dmIntersection::TestFrustumSphereSq(frustum, entry->m_WorldPosition, radius_sq);
+            SpriteComponent* component = &sprite_world->m_Components.Get(entry->m_UserData);
```
Comment (ekharkunov) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:1964]: Use pivot point only for frustrum culling because for culling we need the center of the sprite, but for render sorting - just position of the sprite. Fix for https://github.com/defold/defold/issues/11313

**Review by ekharkunov — COMMENTED** [review]
+

**Review by JCash — APPROVED** [review]
lgtm!
