### PR TITLE
Fix issue with mouse wheel events in HTML5 builds

### LINKED ISSUE #6201: Chromium based browsers event issue onMouseWheel, but not affecting work
**Describe the bug**
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>
"onMouseWheel"

**To Reproduce**
scroll the wheel over the canvas

**Expected behavior**
do not see this error in the console

**Defold version:**
  - Version 1.2.187 - 1.2.188

**Platforms:**
 - Platforms: `HTML5`
 - OS: Windows 10, Linux Mint 19.3
 - Chromium based browsers
 
**Workaround:**
in **game-name_wasm.js** replace
`GLFW.addEventListener("DOMMouseScroll",GLFW.onMouseWheel, true);
GLFW.addEventListener("mousewheel",GLFW.onMouseWheel,true);
...
GLFW.removeEventListener("DOMMouseScroll",GLFW.onMouseWheel,true);
GLFW.removeEventListener("mousewheel",GLFW.onMouseWheel,true);`

 with

`GLFW.addEventListener("DOMMouseScroll",GLFW.onMouseWheel,{ passive: false });
GLFW.addEventListener("mousewheel",GLFW.onMouseWheel,{ passive: false });
...
GLFW.removeEventListener("DOMMouseScroll",GLFW.onMouseWheel,{ passive: false });
GLFW.removeEventListener("mousewheel",GLFW.onMouseWheel,{ passive: false });`

**Screenshots:**
image
image

**Additional context:**
Mozilla firefox has no such problem

### LINKED ISSUE #6964: Using the scrollwheel on HTML5 builds causes an error
When attempting to use the mousewheel on a HTML5 build of Defold, the following error occurs:

Screenshot_20220908_081805

Version: 1.3.5
Platform: Linux Manjaro
Browser: Brave Browser

Should be reproducable on any client.

The error links to this url: https://www.chromestatus.com/feature/6662647093133312

### PR DESCRIPTION
**Pull request by britzl**
Capturing mouse wheel events in HTML5 builds generated errors in the browser console. This fix ensures that mouse wheel events no longer generate errors.

Fixes #6964
Fixes #6201

### CODE REVIEW

File: engine/glfw/js/library_glfw.js [hunk 1]
```diff
@@ -444,7 +444,9 @@ var LibraryGLFW = {
         if (GLFW.mouseWheelFunc) {
           {{{ makeDynCall('vi', 'GLFW.mouseWheelFunc') }}}(GLFW.wheelPos);
         }
-        event.preventDefault();
+        if (event.cancelable) {
```
Comment (britzl) [inline engine/glfw/js/library_glfw.js:447]: Checking if the event can be cancelled before calling preventDefault() solves half of the problem.

File: engine/glfw/js/library_glfw.js [hunk 2]
```diff
@@ -588,8 +590,8 @@ var LibraryGLFW = {
     GLFW.addEventListener("mousemove", GLFW.onMousemove, true);
     GLFW.addEventListener("mousedown", GLFW.onMouseButtonDown, true);
     GLFW.addEventListener("mouseup", GLFW.onMouseButtonUp, true);
-    GLFW.addEventListener('DOMMouseScroll', GLFW.onMouseWheel, true);
-    GLFW.addEventListener('mousewheel', GLFW.onMouseWheel, true);
+    GLFW.addEventListener('DOMMouseScroll', GLFW.onMouseWheel, { capture: true, passive: false });
```
Comment (britzl) [inline engine/glfw/js/library_glfw.js:593]: Setting capture to true is the same as passing true to the third argument (done for the rest of the event listeners)

If passive is true it means that the function called by the even listener must not call preventDefault (will generate a warning otherwise). This is the opposite of what we want, so we set passive to false.

Comment (britzl) [reply engine/glfw/js/library_glfw.js:593]: According to docs wheel, mousehweel, touchstart and touchmove default to passive = true. I did not notice any warning from a call to preventDefault() for touchstart though.

**Comment by AGulev** [comment]
LGTM 

these one is also related
https://github.com/defold/defold/issues/6201

**Review by AGulev — APPROVED** [review]
