### PR TITLE
Fix for when bitmap font uses 4 channels which caused a crash

### LINKED ISSUE #11397: Unable to build and run due to font issue
Hi guys, I have been trying to find out the issue for some time and managed to isolate it to a font issue. It sometimes builds without any issues while at other times, it shows error and just crashes. Sadly, I am not that good a debugger and any help is appreciated.

I have created a simple project which consisted only the main collection with a gui having a bitmap fnt just to simulate the error. I am using v1.11.1

It was working with on older version of Defold

image
[image1920×1037 38.4 KB](https://defold-forum-bucket.nbg1.your-objectstorage.com/original/3X/6/2/6277aff30966efb777f4b2d72cda523486ec8839.png)

image
[image1920×1013 68 KB](https://defold-forum-bucket.nbg1.your-objectstorage.com/original/3X/5/2/52089e72445f46e0e7edf739c5662c63d1b82c09.png)

If you change the font to “default” it works.

image
[image425×909 11.8 KB](https://defold-forum-bucket.nbg1.your-objectstorage.com/original/3X/4/b/4bfcefa4fc867ff687887f023b2f3a8ba5381ed9.png)

I have looked through the fnt file of the “invader_font” and I could not find anything weird in it.

The raw images 0-9 is provided in the “invader-font-images” folders before it’s converted into the bitmap font.

Project file is attached.
[FontError.zip](https://forum.defold.com/uploads/short-url/us3Q9iNC2M5PmVuogvLWt5hDeQb.zip) (109.1 KB)

I have tried deleting the appData of Defold which some say might be version conflict.
Enable / disable “Runtime Generation” of fonts in the game.project.
Changing font materials

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/11397

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/render/src/render/font.cpp [hunk 1]
```diff
@@ -217,7 +217,7 @@ namespace dmRender
         SetupCache(font_map, font_map->m_CacheWidth, font_map->m_CacheHeight,
                                 cell_width, cell_height, params.m_CacheCellMaxAscent);
 
-        switch (params.m_GlyphChannels)
+        switch (font_map->m_CacheChannels)
```
Comment (JCash) [inline engine/render/src/render/font.cpp:220]: May just as well check the variable that ends up storing the value (which was the bug)

File: engine/render/src/render/font_renderer_private.h [hunk 2]
```diff
@@ -108,7 +109,7 @@ namespace dmRender
         uint8_t                 m_IsCacheSizeDirty:1;   // if the glyph cell size has changed, or if the layout needs to be recalculated
         uint8_t                 m_DynamicCacheSize:1;
         uint8_t                 m_IsCacheSizeTooSmall:1;
-        uint8_t                 m_CacheChannels:2;      // Number of channels
+        uint8_t                 m_CacheChannels:3;      // Number of channels (1-4)
```
Comment (JCash) [inline engine/render/src/render/font_renderer_private.h:112]: The bug: `4` stored in 2 bits -> `0`

File: engine/render/src/render/font_renderer_private.h [hunk 3]
```diff
@@ -54,7 +54,8 @@ namespace dmRender
             free(m_CellTempData);
             m_CellTempData = 0;
 
-            dmGraphics::DeleteTexture(m_GraphicsContext, m_Texture);
+            if (m_Texture)
+                dmGraphics::DeleteTexture(m_GraphicsContext, m_Texture);
```
Comment (JCash) [inline engine/render/src/render/font_renderer_private.h:58]: If a font fails early, this also broke.

**Review by ekharkunov — APPROVED** [review]
