### PR TITLE
Crash fix for empty profile scope name

### LINKED ISSUE #6773: Crash when reloading texture asset
The new profiler scope wasn't properly handling a scope without a name.

https://forum.defold.com/t/resource-set-texture-example-code-crashes/71207/2

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/dlib/src/dlib/profile/profile_remotery.cpp [hunk 1]
```diff
@@ -186,11 +186,13 @@ namespace dmProfile
     void ProfileScope::StartScope(const char* name, uint64_t* name_hash)
     {
         if (g_Remotery == NULL) {
-            valid = 0;
             return;
         }
-        valid = 1;
-        _rmt_BeginCPUSample(name, RMTSF_Aggregate, (uint32_t*)name_hash);
+        if (name != 0)
```
Comment (JCash) [inline engine/dlib/src/dlib/profile/profile_remotery.cpp:191]: When setting the texture resource, the filename was `0`.

File: engine/dlib/src/dmsdk/dlib/profile.h [hunk 2]
```diff
@@ -587,7 +587,7 @@ namespace dmProfile
     /// Internal, do not use.
     struct ProfileScope
     {
-        inline ProfileScope(const char* name, uint64_t* name_hash)
+        inline ProfileScope(const char* name, uint64_t* name_hash) : valid(0)
```
Comment (JCash) [inline engine/dlib/src/dmsdk/dlib/profile.h:590]: Another issue. The scope might be accidentially "valid" due to garbage in the `valid` flag.

File: engine/dlib/src/test/test_profile.cpp [hunk 3]
```diff
@@ -159,6 +160,14 @@ static void PropertyTreeCallback(void* _ctx, dmProfile::HProperty root)
     }
 }
 
+TEST(dmProfile, SmallTest)
+{
+    dmProfile::Initialize(0);
+        DM_PROFILE(0);
+        DM_PROFILE_DYN(0, 0);
```
Comment (JCash) [inline engine/dlib/src/test/test_profile.cpp:167]: Make sure we test the empty values.
