### PR TITLE
Less aggressive rounding of numeric values in the editor

### LINKED ISSUE #6414: Editor rounds values when moving objects
**Describe the bug (REQUIRED)**
The editor rounds values when moving objects. 

**To Reproduce (REQUIRED)**

https://user-images.githubusercontent.com/193258/154264998-9bf5deec-2e9a-4efb-b978-4c2500fbe067.mp4

**Expected behavior (REQUIRED)**
The editor should not affect the values after the decimal point, i.e.:
- `0.454545 + 1` should be `1.454545`, but not `1.455`.
- `0.454545 - 1` should be `-0.545455`, but not `-0.545`.

**Defold version (REQUIRED):**
  - Version 1.2.192

**Platforms (REQUIRED):**
 - OS: Windows 10

### PR DESCRIPTION
**Pull request by matgis**
Fixes #6414.

### User-facing changes
* Less aggressive rounding of numeric values in the editor.

### CODE REVIEW

File: editor/src/clj/editor/field_expression.clj [hunk 1]
```diff
@@ -45,7 +45,7 @@
 
 (defn to-double [s]
  (try
-   (evaluate-expression #(Double/parseDouble %) 0.01 s)
+   (evaluate-expression #(Double/parseDouble %) math/precision-general s)
```
Comment (matgis) [inline editor/src/clj/editor/field_expression.clj:48]: Use the same rounding as everything else for the results of expressions typed into numeric fields.

File: editor/src/clj/editor/gui.clj [hunk 2]
```diff
@@ -336,7 +336,7 @@
   (-> (doto (Quat4d.)
         (math/clj->vecmath clj-quat))
       math/quat->euler
-      properties/round-vec
+      properties/round-vec-coarse
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:339]: Use coarse rounding when converting quaternions to euler angles for better value stability.

Prior to this PR, we used coarse rounding (three significant decimal places) everywhere. With this change, we use moderate rounding (six significant decimal spaces) for everything but the quaternion to euler angle conversion.

**Review by vlaaad — APPROVED** [review]
LGTM!
