### PR TITLE
Fix uploading basis compressed texture array data

### LINKED ISSUE #7628: Paged atlas doesn't work with texture compression
**Describe the bug (REQUIRED)**
If use texture compression for multi-page atlas it doesn't render in the game (black rectangles). If turn on `graphics.verify_graphics_calls = 1` - game crash. Latest message in the log is `ERROR:GRAPHICS: OpenGLSetTexture(3006): gl error 1281`.
If no texture compression is applied to multi-page atlas - error doesn't reproduce.

**To Reproduce (REQUIRED)**
1. Open example project (see attachment)
2. Bundle it for iOS, debug variant with texture compression 'Enabled'
3. Install and run game

**Expected behavior (REQUIRED)**
Multi-page atlases with texture compression render correctly.

**Defold version (REQUIRED):**
  - Version 1.4.4 f5e114aaebe25c5242db5f0066af2f5189c09f99
  - Editor 36f9bd22f8a5d442728986d23a96794004ed0640

**Platforms (REQUIRED):**
 - Platforms: iOS (I don't check for other platforms)

**Minimal repro case project (OPTIONAL):**
[liverunner_paged_atlas.zip](https://github.com/defold/defold/files/11383168/liverunner_paged_atlas.zip)

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
Do not use texture compression.

**Additional context (OPTIONAL):**
* If run from editor - works ok (no texture compression applied)
* game/main.texture_profiles - generic profile to apply texture compression for all sprites (COMPRESSION_TYPE_BASIS_UASTC)
* assets/materials/paged_sprite.material - main material

### PR DESCRIPTION
**Pull request by Jhonnyg**
Fixed an issue with uploading basis compressed textures to a texture array, which is primarily used for paged atlases in the engine.

Fixes #7628 

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [x] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 1]
```diff
@@ -3169,33 +3181,37 @@ static void LogFrameBufferError(GLenum status)
...
+                    }
+                    else if (tex->m_Type == TEXTURE_TYPE_2D_ARRAY)
+                    {
+                        if (params.m_SubUpdate)
+                        {
+                            DMGRAPHICS_COMPRESSED_TEX_SUB_IMAGE_3D(GL_TEXTURE_2D_ARRAY, params.m_MipMap, params.m_X, params.m_Y, params.m_Z, params.m_Width, params.m_Height, params.m_Depth, gl_format, gl_type, params.m_Data);
+                        }
+                        else
+                        {
+                            DMGRAPHICS_COMPRESSED_TEX_IMAGE_3D(GL_TEXTURE_2D_ARRAY, params.m_MipMap, gl_format, params.m_Width, params.m_Height, params.m_Depth, 0, params.m_DataSize * params.m_Depth, params.m_Data);
```
Comment (Jhonnyg) [inline engine/graphics/src/opengl/graphics_opengl.cpp:3206]: This is the actual issue that is fixed - when we create the texture we need to pass in the data size of the ENTIRE texture with all the slices and so forth, but the params struct only contains the data size for ONE slice.

**Review by JCash — APPROVED** [review]
