### PR TITLE
Make `/command/build` respond on build completion

### LINKED ISSUE #11733: Make editor's `build` command more useful by returning build errors
**Task (REQUIRED):**
Now when calling

>http://localhost:64453/command/build

The editor's server return OK immediately and there is no way to receive build errors from it.
It would be nice if  response contain such info

**Expected outcome (REQUIRED):**
A way to get logs if build fails and know when the build is done

### PR DESCRIPTION
**Pull request by vlaaad**
We made the HTTP command that triggers the editor build block until the build completes, and made it respond with the build status + compilation issues. This should make it much more useful for AI agents and third-party IDE integrations.

### Successful build
```sh
curl -X POST "http://127.0.0.1:$(cat .internal/editor.port)/command/build" --silent | jq
{
  "success": true,
  "issues": []
}
```
### Failed build
```sh
curl -X POST "http://127.0.0.1:$(cat .internal/editor.port)/command/build" --silent | jq
{
  "success": false,
  "issues": [
    {
      "severity": "error",
      "message": "go.property declaration should be a top-level statement",
      "resource": "/main/logo.script",
      "range": {
        "start": {
          "line": 3,
          "character": 4
        },
        "end": {
          "line": 3,
          "character": 35
        }
      }
    }
  ]
}
```
### Minimal AGENTS.md to get started
```md
# Docs
https://defold.com/llms.txt

# Build
- Read editor port from `.internal/editor.port`
- Build game: `curl -X POST http://127.0.0.1:<PORT>/command/build`

# Console
- After launch, check logs at `http://127.0.0.1:<PORT>/console`.
```

Fix #11733

### CODE REVIEW

**Comment by vlaaad** [comment]
Vibe-coded a small demo while waiting for CI:

https://github.com/user-attachments/assets/2fd1d1b3-f134-4278-aaf0-0cded670cc4a

File: editor/src/clj/editor/app_view.clj [hunk 1]
```diff
@@ -1132,11 +1133,13 @@
                       (reset! build-in-progress-atom false)
                       (render-progress! progress/done)
                       (cancel-engine-build!)
+                      (future/fail! result-future error)
                       (throw error)))))
               (catch Throwable error
                 (reset! build-in-progress-atom false)
                 (render-progress! progress/done)
                 (cancel-engine-build!)
+                (future/fail! result-future error)
```
Comment (matgis) [inline editor/src/clj/editor/app_view.clj]: This `catch` block is running on a background thread. Does this call to `future/fail!` need to be wrapped in a `(ui/run-later)` scope? The other calls to `future/fail!` or `future/complete!` all seem to be called on the UI thread.

File: editor/src/clj/editor/command_requests.clj [hunk 2]
```diff
@@ -17,15 +17,33 @@
...
+    result
+    (fn [{:keys [error warning]}]
+      (let [issues (coll/into-> [error warning] []
+                     (filter some?)
+                     (mapcat #(:children (build-errors-view/build-resource-tree %)))
+                     (mapcat :children)
+                     (map (fn [{:keys [message severity parent cursor-range]}]
+                            (let [maybe-resource (:resource parent)]
+                              (cond-> {:severity (case severity :fatal :error :info :information severity)
+                                       :message (localization-state message)}
```
Comment (matgis) [inline editor/src/clj/editor/command_requests.clj]: Style: Break `case` across multiple lines for clarity & move `:message` key to the top?

File: editor/src/clj/editor/command_requests.clj [hunk 3]
```diff
@@ -236,3 +264,16 @@
...
+  (-> @(util.http-client/request
+         (str "http://localhost:"
+              (slurp (str (g/node-value (dev/workspace) :root) "/.internal/editor.port"))
+              "/command/build")
+         :method "POST"
+         :as :string)
+      :body
+      (clojure.data.json/read-str :key-fn keyword))
+
+  #__)
```
Comment (matgis) [inline editor/src/clj/editor/command_requests.clj:282]: Left intentionally?

**Review by matgis — DISMISSED** [review]
Looks good! I had one concern about failing a future that may be making UI calls on a background thread in a `catch` block that is very unlikely to be hit.

File: editor/src/clj/editor/command_requests.clj (hunk 3 above)
Comment (vlaaad) [reply editor/src/clj/editor/command_requests.clj:282]: Yes, so it's easy to try if you have an open project :)

File: editor/src/clj/editor/app_view.clj (hunk 1 above)
Comment (vlaaad) [reply editor/src/clj/editor/app_view.clj]: Hmm, I think it would be better if we always complete this future on the UI thread to prevent surprises... Good catch!
