### PR TITLE
Editor: Fix exception when showing Context Menu for a missing resource

### LINKED ISSUE #11619: Right-clicking missing resource to delete throws exception instead
**Describe the bug (REQUIRED)**
Right-clicking on a resource (in this example, an Atlas image) that Defold already knows is missing (red X icon) throws an exception.

**Expected behavior (REQUIRED)**
No exception should be thrown.

**Logs (OPTIONAL):**
```
clojure.lang.ExceptionInfo: handler ':file.open-as' in context ':global' failed at ':options' with message '/Users/hunter/github.com/hunterloftis/kiss/assets/emotes/emote_cloud.png (No such file or directory)'
java.io.FileNotFoundException: /Users/hunter/github.com/hunterloftis/kiss/assets/emotes/emote_cloud.png (No such file or directory)
```

**Workaround (OPTIONAL):**
After the first exception is thrown, on any file, Defold behaves as expected (subsequent right-clicks work).

**Screenshots (OPTIONAL):**

Image

https://github.com/user-attachments/assets/85a6dfd0-5012-4697-a69b-c3b20084e594

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2025-11-05T11:28:35.892962</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cddb6eb43c32e4930257fcbbb30f19cf28deb081</td></tr>
<tr><td>Defold engine sha</td><td>cddb6eb43c32e4930257fcbbb30f19cf28deb081</td></tr>
<tr><td>Defold version</td><td>1.11.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2ad4dee0018e4c469621aa12a65d60cd"'>2ad4dee0018e4c469621aa12a65d60cd</a></td></tr>
<tr><td>GPU</td><td>Apple M3 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 90.5</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>26.1</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Accessing the Context Menu for a deleted image file referenced from an Atlas no longer throws an exception.

Fixes #11619.

### CODE REVIEW

File: editor/src/clj/editor/app_view.clj [hunk 1]
```diff
@@ -2374,45 +2374,45 @@
...
+                                              {:selected-view-type view-type})
+                                 (make-option (localization/message "command.file.open-as.option.in-defold-editor" {"view" label})
+                                              {:selected-view-type view-type
+                                               :use-custom-editor false})]
+                                [(view-type->option view-type)])))
+                    (map view-type->option))
+                  (cond->> (view-types resource)
+
+                           active-view-type-id
+                           (e/filter #(not= active-view-type-id (:id %)))))))))))
```
Comment (matgis) [inline editor/src/clj/editor/app_view.clj:2415]: Mostly an indentation change, but we now check `(and (resource/openable-resource? resource) (resource/exists? resource))` before evaluating anything. Note that `resource/openable-resource?` returns `false` for `nil`, but `true` for a `Resource` that does not exist, so we must check `resource/exists?` separately. We also now use the `evaluation-context` supplied to the `options` handler instead of creating our own.

**Review by vlaaad — APPROVED** [review]
LGTM!
