### PR TITLE
Issue-5389: Fixed crash in liveupdate zip archive

### LINKED ISSUE #5389: Crash in liveupdate zip archive
When closing one of the liveupdate zip archive, it crashes due to a calling an invalid file handle (null).

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

**Review by britzl — DISMISSED** [review]

File: engine/resource/src/mount/mount_android.cpp [hunk 1]
```diff
@@ -122,11 +124,27 @@ namespace dmResource
...
+            }
+        } else
+        {
+            r = MapFile(data_path, data_map, data_length);
+            if (r != RESULT_OK)
+            {
+                dmLogError("Error mapping liveupdate data file, result = %i", r);
+                return RESULT_IO_ERROR;
+            }
+            mem_mapped_data = true;
```
Comment (JCash) [inline engine/resource/src/mount/mount_android.cpp:147]: My use case was simple:
1. Download resource -> we create liveupdate.arcd/.arci
2. Reboot
3. Fails to MapAsset when using file on disc (liveupdate.arcd)

**Review by britzl — APPROVED** [review]
Looks good
