### PR TITLE
Fixed index buffer lookup in headless graphics backend

### LINKED ISSUE #7339: Crash windows headless app
**Describe the bug (REQUIRED)**
I create headless assembly for Windows - 32/64 (it doesn't matter).
It almost always crashes on startup. Sometimes it seems to start without a crash (but rarely).

**To Reproduce (REQUIRED)**
I'm creating a headless assembly for Windows.

**Expected behavior (REQUIRED)**
Terminal app.

**Defold version (REQUIRED):**
  - Version 1.4.2

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS:  Windows 10

**Logs (OPTIONAL):**
```
ERROR:CRASH: CALL STACK:
ERROR:CRASH:  0 0x7FF60A736E00 _snscanf_s <unknown>:0
ERROR:CRASH:  1 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  2 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  3 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  4 0x7FFBDB9911F0 __chkstk <unknown>:0
ERROR:CRASH:  5 0x7FFBDB93B1B0 RtlRaiseException <unknown>:0
ERROR:CRASH:  6 0x7FFBDB98FE10 KiUserExceptionDispatcher <unknown>:0
ERROR:CRASH:  7 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  8 0x7FF60A70E7B0 sprintf <unknown>:0
ERROR:CRASH:  9 0x7FF60A744450 dmHashReverseErase64 <unknown>:0
ERROR:CRASH: 10 0x7FF60A744450 dmHashReverseErase64 <unknown>:0
ERROR:CRASH: 11 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH: 12 0x7FF60A8029D0 DecryptXTeaCTR <unknown>:0
ERROR:CRASH: 13 0x7FF60A7BA770 Particle_Hash <unknown>:0
ERROR:CRASH: 14 0x7FF60A7BA770 Particle_Hash <unknown>:0
ERROR:CRASH: 15 0x7FF60A7BA770 Particle_Hash <unknown>:0
ERROR:CRASH: 16 0x7FF60A70E7B0 sprintf <unknown>:0
ERROR:CRASH: 17 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH: 18 0x7FFBDB7D7020 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 19 0x7FFBDB93D0B0 RtlUserThreadStart <unknown>:0
```
[crash + debug symbols](https://disk.yandex.ru/d/DgEwsVA1kpkjBw)

### PR DESCRIPTION
**Pull request by JCash**
This fixes a buffer overrun issue when using index buffers with the headless graphics backend.

Fixes #7339

### CODE REVIEW

File: engine/graphics/src/null/graphics_null.cpp [hunk 1]
```diff
@@ -593,33 +593,13 @@ namespace dmGraphics
     {
         const void* index_buffer = ((IndexBuffer*) ib)->m_Buffer;
 
-        if (type == dmGraphics::TYPE_BYTE)
+        if (type == dmGraphics::TYPE_UNSIGNED_SHORT)
```
Comment (JCash) [inline engine/graphics/src/null/graphics_null.cpp:596]: We only support two types of index buffers uint16_t/uint32_t

File: engine/graphics/src/test/test_graphics.cpp [hunk 2]
```diff
@@ -342,15 +342,15 @@ TEST_F(dmGraphicsTest, Drawing)
     dmGraphics::HIndexBuffer ib = dmGraphics::NewIndexBuffer(m_Context, sizeof(i), i, dmGraphics::BUFFER_USAGE_STREAM_DRAW);
 
     dmGraphics::EnableVertexDeclaration(m_Context, vd, vb);
-    dmGraphics::DrawElements(m_Context, dmGraphics::PRIMITIVE_TRIANGLES, 0, 3, dmGraphics::TYPE_UNSIGNED_INT, ib);
+    dmGraphics::DrawElements(m_Context, dmGraphics::PRIMITIVE_TRIANGLES, 0, 6, dmGraphics::TYPE_UNSIGNED_INT, ib);
```
Comment (JCash) [inline engine/graphics/src/test/test_graphics.cpp:345]: The tests would have caught it if we had used the full buffer :/

File: engine/graphics/src/null/graphics_null.cpp [hunk 3]
```diff
@@ -593,33 +593,13 @@ namespace dmGraphics
...
-            return ((short*)index_buffer)[index];
-        }
-        else if (type == dmGraphics::TYPE_UNSIGNED_SHORT)
-        {
-            return ((unsigned short*)index_buffer)[index];
-        }
-        else if (type == dmGraphics::TYPE_INT)
-        {
-            return ((int*)index_buffer)[index];
+            return ((unsigned short*)index_buffer)[index/2];
```
Comment (JCash) [inline engine/graphics/src/null/graphics_null.cpp:598]: Since the cast to the correct type is done first, then the byte offset isn't the correct index.

**Review by Jhonnyg — APPROVED** [review]
LGTM!
