### PR TITLE
Issue 4862: sys.reboot now supported on HTML5

### LINKED ISSUE #4862: sys.reboot() not working in HTML5 (browser)
**Describe the bug (REQUIRED)**
In preview mode `sys.reboot()` reload game but in browser it do nothing.

**To Reproduce (REQUIRED)**
1. Attach any script to `main` collection `go`
```lua
function init() 
	msg.post('.', 'acquire_input_focus')
end


function on_input(self, action_id, action)
	if action_id == hash('touch') and action.pressed then
		print('rebooted')
		sys.reboot()
	end
end
```
Screenshot 2020-05-29 at 12 10 33
2. Select **Project -> Build HTML5** 
3. Click on **go** with attached script. Nothing happens

**Expected behavior (REQUIRED)**
I don't know. Maybe reload only canvas with game or maybe whole page.

**Defold version (REQUIRED):**
  - Version: 1.2.168

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: MacOS Catalina
 - Device: MacBook

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -1509,6 +1567,8 @@ namespace dmEngine
 
     static void Reboot(HEngine engine, dmSystemDDF::Reboot* reboot)
     {
+        dmLogWarning("ENGINE REBOOT");
```
Comment (britzl) [inline engine/engine/src/engine.cpp:1570]: I guess it's ok with a log here but why a warning? Something left over from testing?

**Review by britzl — DISMISSED** [review]

File: engine/engine/src/engine.cpp (hunk 1 above)
Comment (JCash) [reply engine/engine/src/engine.cpp:1570]: no, it shouldn't be there (it's a debug print)

**Review by britzl — APPROVED** [review]
