### PR TITLE
Editor: Fix load crash resulting from missing Gui template resource

### LINKED ISSUE #8437: Editor crashes during load if a GUI with layouts refers to a missing .gui resource
If the `node-ids` output of a gui `NodeTree` produces an `ErrorValue`, the `nodes` property of `LayoutNode` will throw an exception that crashes the editor during project load.

1. Set up a gui to reference another gui as a template.
2. Add a layout to the gui.
3. Save and exit the editor.
4. Delete the referenced gui from disk.
5. Try to load the project.

```
2024-01-22 12:14:49.108 467254 [clojure-agent-send-off-pool-0] ERROR editor.dialogs - {:line 442}
java.lang.ClassCastException: class internal.graph.error_values.ErrorValue cannot be cast to class clojure.lang.IFn (internal.graph.error_values.ErrorValue and clojure.lang.IFn are in unnamed module of loader 'app')
    at clojure.core$comp$fn__5792.invoke(core.clj:2569)
    at editor.gui$LayoutNode$property$nodes$setter$fn__90276$iter__90315__90321$fn__90322.invoke(gui.clj:1842)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core$concat$cat__5480$fn__5481.invoke(core.clj:734)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
    at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
    at clojure.lang.RT.next(RT.java:709)
    at clojure.core$next__5371.invokeStatic(core.clj:64)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:802)
    at internal.transaction$apply_tx.invoke(transaction.clj:795)
    at internal.transaction$fn__9846.invokeStatic(transaction.clj:374)
    at internal.transaction$fn__9846.invoke(transaction.clj:348)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn__10015.invoke(transaction.clj:805)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:803)
    at internal.transaction$apply_tx.invoke(transaction.clj:795)
    at internal.transaction$invoke_setter.invokeStatic(transaction.clj:569)
    at internal.transaction$fn__9926.invokeStatic(transaction.clj:622)
    at internal.transaction$fn__9926.invoke(transaction.clj:610)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn__10015.invoke(transaction.clj:805)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:803)
    at internal.transaction$apply_tx.invoke(transaction.clj:795)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:802)
    at internal.transaction$apply_tx.invoke(transaction.clj:795)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:802)
    at internal.transaction$apply_tx.invoke(transaction.clj:795)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:802)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:886)
    at dynamo.graph$transact.invokeStatic(graph.clj:164)
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:204)
    at editor.defold_project$load_project$fn__32148.invoke(defold_project.clj:275)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invokeStatic(core.clj:665)
    at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at editor.defold_project$load_project.invokeStatic(defold_project.clj:275)
    at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:957)
    at editor.boot_open_project$open_project_BANG_.invokeStatic(boot_open_project.clj:388)
    at editor.boot_open_project$open_project_BANG_.invoke(boot_open_project.clj:386)
    at clojure.lang.AFn.applyToHelper(AFn.java:171)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invokeStatic(core.clj:665)
    at editor.boot$open_project_with_progress_dialog$fn__108320.invoke(boot.clj:70)
    at editor.dialogs$make_load_project_dialog$fn__25884$fn__25887.invoke(dialogs.clj:440)
    at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
2024-01-22 12:14:49.119 467265 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 116}
```

### PR DESCRIPTION
**Pull request by matgis**
Fixed editor crash when loading a Gui scene that overrides properties on nodes inside a missing template resource.

Fixes #8437

### CODE REVIEW

File: editor/src/clj/editor/gui.clj [hunk 1]
```diff
@@ -1446,8 +1455,7 @@
                                                                   [:resource-names :aux-resource-names]
                                                                   [:template-prefix :id-prefix]
                                                                   [:current-layout :current-layout]]]
-                                                   (g/connect self from or-scene to)))))))))
-                         []))))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1450]: Remnant of `false` branch of `if`-clause, now changed to a `when`-clause.

File: editor/src/clj/editor/gui.clj [hunk 2]
```diff
@@ -1389,21 +1389,30 @@
...
+                             (let [properties-by-node-id
+                                   (or (when-not created-in-tx
+                                         (when-let [properties-by-id (coll/not-empty (:overrides new-value))]
+                                           (let [node-ids-by-id (g/node-value scene-node :node-ids evaluation-context)]
+                                             (when (and (not (g/error-value? node-ids-by-id))
+                                                        (coll/not-empty node-ids-by-id))
+                                               (comp properties-by-id
+                                                     (into {}
+                                                           (map (fn [[id node-id]]
+                                                                  (pair node-id id)))
```
Comment (vlaaad) [inline editor/src/clj/editor/gui.clj:1413]: I was about to suggest using `flipped-pair`, but then I realized it's 2-arity, while this function is 1-arity. Maybe we could add 1-arity variant of `flipped-pair`?

**Review by vlaaad — APPROVED** [review]
LGTM!
