### PR TITLE
Issue 5069: Fix for world space mesh component

### LINKED ISSUE #5069: FIx world space transform for mesh component
Meshes rendered with a world space material were'nt transformed properly.

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_mesh.cpp [hunk 1]
```diff
@@ -345,7 +345,7 @@ namespace dmGameSystem
         dst_data_ptr = (T*)((uint8_t*)dst_data_ptr + ptr_offset);
 
         Vector4 v(0.0f);
-        float w = !is_point;
```
Comment (britzl) [inline engine/gamesys/src/gamesys/components/comp_mesh.cpp:348]: Oh yes, that doesn't look quite right :-)

**Review by britzl — APPROVED** [review]
