### PR TITLE
Issue 5200: Fixed gui particle crash after deletion

### LINKED ISSUE #5200: Investigate particle fx related crash
**Describe the bug (REQUIRED)**
@subsoap and @JCash are discussing this. At first the crash was believed to be in the Steamworks extension but that was dismissed when it was reproduced in a small project without Steamworks. https://github.com/britzl/steamworks-defold/issues/19

### PR DESCRIPTION
**Pull request by JCash**
Unlinks the node directly, but doesn't delete it

### CODE REVIEW

File: engine/gui/src/gui.cpp [hunk 1]
```diff
@@ -2111,7 +2112,6 @@ Result DeleteDynamicTexture(HScene scene, const dmhash_t texture_hash)
                         }
 
                         ResetInternalNode(scene, n);
```
Comment (JCash) [inline engine/gui/src/gui.cpp:2114]: Reset removes it, and unlinks it, but it's too late to do it here.

File: engine/gui/src/gui.cpp [hunk 2]
```diff
@@ -2494,6 +2494,10 @@ Result DeleteDynamicTexture(HScene scene, const dmhash_t texture_hash)
 
         if (!delete_headless_pfx && n->m_Node.m_HasHeadlessPfx)
         {
+            RemoveFromNodeList(scene, n);
+            n->m_ParentIndex = INVALID_INDEX;
+            n->m_PrevIndex = INVALID_INDEX;
+            n->m_NextIndex = INVALID_INDEX;
```
Comment (JCash) [inline engine/gui/src/gui.cpp:2500]: Unlink it from the parent/siblings directly upon the DeleteNode() call

**Review by britzl — APPROVED** [review]
