### PR TITLE
Fixed 180-degree rotation issues in the editor

### LINKED ISSUE #12222: Model rotation different in Editor and Runtime [1.12.4-beta]
**Describe the bug (REQUIRED)**
In 1.12.4-beta Model rotation in editor and runtime looks different (90-180 deg change)

**To Reproduce (REQUIRED)**
1. Open project from "Minimal repro case project" in 1.12.3. Note how "paladin" and "skeleton_minion" looks in editor (viewed top-down).
2. Run project. Note how models are viewed (top-down).
3. Open same project in 1.12.4.
4. Note how in editor "paladin" is rotated "shield-up".
5. Run project. Note: "paladin" rotation is same as 1.12.3. But "skeleton" is 90 deg rotated and scaled up.

**Expected behavior (REQUIRED)**
Model rotation in Editor and Runtime 1.12.4 same as in 1.12.3.

**Defold version (REQUIRED):**
  - 1.12.4-beta SHA1 69145457f80a3f96edee1080184744c227dc13d2

**Platforms (REQUIRED):**
 - Platforms: macOS, HTML5
 - OS: Sequoia 15.7.4 (24G517)
 - Device: macbook air M2

**Minimal repro case project (OPTIONAL):**

[model_rotation.zip](https://github.com/user-attachments/files/26747739/model_rotation.zip)

**Screenshots (OPTIONAL):**

Editor. First - 1.12.3, Second - 1.12.4-beta:

Image
Image

Runtime. First - 1.12.3, Second - 1.12.4-beta:

Image
Image

### LINKED ISSUE #12278: GUI Editor does not reflect negative scale (mirroring) and rotation on textured nodes
Describe the bug (REQUIRED)
In the GUI editor, applying a negative scale (e.g. scale.x = -1) to a node with a texture does not visually reflect in the editor. The node appears unchanged. However, when running the project, the node is correctly flipped at runtime.

Additionally, if the node has a rotation applied, the rotation is also not visually updated in the editor when negative scale is set.

⸻

To Reproduce (REQUIRED)

1. Create a new GUI scene
2. Add a box node (or any node with a texture)
3. Assign a texture to the node
4. Set the node’s scale.x to -1 in the editor
5. (Optional) Apply a rotation to the node
6. Observe that the node does not visually flip or reflect rotation changes in the editor
7. Run the project
8. See that the node is correctly flipped and rotated at runtime

⸻

Expected behavior (REQUIRED)
The GUI editor should visually reflect negative scaling (mirroring) of nodes, including correct display of rotation when combined with negative scale, matching the runtime behavior.

⸻

Defold version (REQUIRED):

* Version: 1.12.4 (beta)

⸻

Platforms (REQUIRED):

* Platforms: All (editor-related)
* OS: macOS (reproduced)
* Device: Mac (Apple Silicon)

### PR DESCRIPTION
**Pull request by matgis**
Fixed various issues around 180-degree axis rotations.

Fixes #12222.
Fixes #12278.

### Technical changes
* Reworked matrix decomposition for editor transforms so `split-mat4` handled non-uniform, negative, and zero scale more reliably.
* Added `VecmathUtils` helpers for extracting translation, rotation, and scale, completing missing rotation axes for zero-scale matrices, correcting handedness, and assigning quaternions from orthonormal matrices.
* Canonicalized quaternion-to-Euler conversion to produce stable YZX Euler values, updating affected expectations to normalized equivalents like `-90` instead of `270`.
* Updated particle FX scene-preview transform extraction to match runtime behavior for negative parent scales.
* Expanded math coverage for Euler/quaternion round-trips and matrix decomposition/reconstruction, including the non-unit zero-scale regression.
* Fixed boxed math warnings in `math` module.

### CODE REVIEW

File: editor/src/java/javax/vecmath/VecmathUtils.java [hunk 1]
```diff
@@ -0,0 +1,275 @@
...
+//
+// You may obtain a copy of the License, together with FAQs at
+// https://www.defold.com/license
+//
+// Unless required by applicable law or agreed to in writing, software distributed
+// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
+// CONDITIONS OF ANY KIND, either express or implied. See the License for the
+// specific language governing permissions and limitations under the License.
+
+package javax.vecmath;
```
Comment (matgis) [inline editor/src/java/javax/vecmath/VecmathUtils.java:15]: Initially, we made use of internal static methods in `javax.vecmath` to perform singular value decomposition, but it appears to be overkill for what we need at the moment. I decided to keep the code in the same package in case we want to access these package-private methods in the future.

File: editor/test/editor/lua_parser_test.clj [hunk 2]
```diff
@@ -254,7 +254,7 @@
                                        "go.property(\"test\", vmath.vector4(4))"
                                        "go.property(\"test\", vmath.vector4(1, 2, 3, 4))"
                                        "go.property(\"test\", vmath.quat())"
-                                       "go.property(\"test\", vmath.quat(1, 2, 3, 4))"
+                                       "go.property(\"test\", vmath.quat(0.0, 0.0, 0.707, 0.707))"
```
Comment (matgis) [inline editor/test/editor/lua_parser_test.clj:257]: Changed this to be a well-formed quaternion and updated the expected values as a result.

File: editor/test/integration/gui_test.clj [hunk 3]
```diff
@@ -3550,16 +3550,16 @@
...
                                 "untransformed/box" {:position [20.0 0.0 0.0 1.0]
                                                      :rotation [0.0 0.0 180.0 0.0]
                                                      :scale [3.0 3.0 1.0 1.0]}}
               "Altered Child" {"transformed/box" {:position [10.0 40.0 0.0 1.0]
-                                                  :rotation [0.0 0.0 270.0 0.0]
+                                                  :rotation [0.0 0.0 -90.0 0.0]
                                                   :scale [6.0 6.0 1.0 1.0]}
                                "untransformed/box" {:position [10.0 40.0 0.0 1.0]
-                                                    :rotation [0.0 0.0 270.0 0.0]
+                                                    :rotation [0.0 0.0 -90.0 0.0]
```
Comment (matgis) [inline editor/test/integration/gui_test.clj:3562]: We now use a canonical Euler angle representation, so 270.0 wraps around to -90.0.

File: editor/test/resources/build_project/SideScroller/script/props.script [hunk 4]
```diff
@@ -25,6 +25,6 @@ go.property("hash", hash("hash"))
 go.property("hash1", hash(""))
 go.property("vec3", vmath.vector3(1, 2, 3))
 go.property("vec4", vmath.vector4(4, 5, 6, 7))
-go.property("quat", vmath.quat(8, 9, 10, 11))
+go.property("quat", vmath.quat(0, 0, 0.707, 0.707))
```
Comment (matgis) [inline editor/test/resources/build_project/SideScroller/script/props.script:28]: Use a well-formed quaternion.

**Review by vlaaad — APPROVED** [review]
LGTM!
