### PR TITLE
Fix debugger on mobile devices

### LINKED ISSUE #10110: Can't debug on android
### **Describe the bug:**
When debugging for Android, an error occurs in `debugger.lua` and the debug fail.

### **To Reproduce:**
debug any project to a debug and contentless build installed on android and see the error.

### **Expected behavior:**
debug execute normally

### **Defold version:**
  - Version 1.9.6
  - Version 1.9.7 beta

### **Platforms:**
 - Platforms: Android
 - OS: Android 14
 - Device: A15 5g; M35 5g

## **Screenshots:**
Image

### PR DESCRIPTION
**Pull request by AGulev**
Fixed issues with debugger on mobile devices and contentless bundles.

Fix https://github.com/defold/defold/issues/10110

### CODE REVIEW

File: editor/src/clj/editor/app_view.clj [hunk 1]
```diff
@@ -1215,7 +1215,7 @@
         skip-engine (target-cannot-swap-engine? (targets/selected-target prefs))]
     (build-errors-view/clear-build-errors build-errors-view)
     (async-build! project
-                  :debug false
+                  :debug true
```
Comment (AGulev) [inline editor/src/clj/editor/app_view.clj:1218]: we have to build debugger all the time

File: editor/src/clj/editor/debug_view.clj [hunk 2]
```diff
@@ -524,9 +524,13 @@
...
   (some? (current-session debug-view evaluation-context)))
 
+(defn- contentless? [state]
+  (and state (:connection_mode state)))
+
 (defn can-attach? [prefs]
   (if-some [target (targets/selected-target prefs)]
-    (targets/controllable-target? target)
+    (and (targets/controllable-target? target)
+         (not (contentless? (engine/get-engine-state! target))))
```
Comment (AGulev) [inline editor/src/clj/editor/debug_view.clj:533]: can't attach to a contentless bundle

File: editor/src/clj/editor/engine.clj [hunk 3]
```diff
@@ -85,6 +85,15 @@
       (finally
         (.disconnect conn)))))
 
+(defn get-engine-state! [target]
```
Comment (AGulev) [inline editor/src/clj/editor/engine.clj:88]: this funciton returns the engine state from the `state` endpoint

File: engine/engine/src/engine_service.h [hunk 4]
```diff
@@ -59,6 +59,13 @@ namespace dmEngineService
         dmResource::HFactory      m_Factory;
         dmGameObject::HRegister   m_Regist;
     };
+
+    struct EngineState
+    {
+        bool   m_ConnectionAppMode;
```
Comment (AGulev) [inline engine/engine/src/engine_service.h:65]: for now we need only one variable, but in the future we are able to add more when we need it

**Review by vlaaad — APPROVED** [review]
LGTM!

File: engine/engine/src/engine_service.cpp [hunk 5]
```diff
@@ -453,6 +467,11 @@ namespace dmEngineService
             upnp_params.m_Userdata = this;
             dmWebServer::AddHandler(web_server, "/upnp", &upnp_params);
 
+            dmWebServer::HandlerParams state_params;
+            state_params.m_Handler = StateHandler;
+            state_params.m_Userdata = this;
+            dmWebServer::AddHandler(web_server, "/state", &state_params);
```
Comment (AGulev) [inline engine/engine/src/engine_service.cpp:473]: New endpoint `state`, because info provides static data we have even before engine initialization, but I need information we have only after the engine initialization.

**Review by JCash — APPROVED** [review]
