### PR TITLE
Fixed line height calculations for the Skribidi text layout

### LINKED ISSUE #12302: Skribidi dynamic font text height calculation is incorrect
When dynamic font is used, if you activate skribidi in .appmanifest, resource.get_text_metrics() returns incorrect text height value.

**To Reproduce**
Open the project attached, and make sure the following lines are present in the game.project:
[native_extension]
app_manifest = /appmanifest.appmanifest

**Expected behavior**
The text box is rendered correctly

**Actual behavior**
The calculated text height is too small

**Defold version**
1.12.4 Beta 3ddc9e1f2b6404ea0f47555978d9845474a795fe

**Platforms**
macOS (at least) - built with the Editor

**Workaround**
Open game.project in text editor and remove the following lines:

[native_extension]
app_manifest = /appmanifest.appmanifest

As the result, the builtin appmanifest gets applied, with skribidi off, and the text height starts to be calculated correctly.

[text_metrics_demo.zip](https://github.com/user-attachments/files/27175196/text_metrics_demo.zip)

### PR DESCRIPTION
**Pull request by JCash**
This fixes an issue with `resource.get_text_metrics()` where it previously didn't return the correct bounding box of the text.

Fixes https://github.com/defold/defold/issues/12302

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/font/src/text_layout_skribidi.cpp [hunk 1]
```diff
@@ -218,13 +199,7 @@ static bool LayoutText(LayoutContext* ctx,
...
     skb_rect2_t layout_bounds = skb_layout_get_bounds(skblayout);
     layout->m_Width = layout_bounds.width - (tracking > 0 ? tracking : 0);
-    layout->m_Height = layout_bounds.height;
-    if (lines_count > 0 && settings->m_Leading > 0.0f)
-    {
-        // Normalize Skribidi line height so leading affects only inter-line spacing.
-        float base_line_height = layout_bounds.height / ((float)lines_count * settings->m_Leading);
-        layout->m_Height = layout_bounds.height - base_line_height * (settings->m_Leading - 1.0f);
-    }
+    layout->m_Height = lines_count * (line_height * settings->m_Leading) - line_height * (settings->m_Leading - 1.0f);
```
Comment (JCash) [inline engine/font/src/text_layout_skribidi.cpp]: Now it's the same calculation as text_layout_legacy.cpp.

File: engine/font/src/test/test_font.cpp [hunk 2]
```diff
@@ -944,6 +944,35 @@ TEST_F(FontTest, Layout)
...
+    ASSERT_NE((HTextLayout)0, legacy_layout);
+
+    HTextLayout skribidi_layout = 0;
+    r = TestLayout(m_FontCollection, codepoints, &settings, &skribidi_layout);
+    ASSERT_EQ(TEXT_RESULT_OK, r);
+    ASSERT_NE((HTextLayout)0, skribidi_layout);
+
+    ASSERT_EQ(10u, skribidi_layout->m_Lines.Size());
+    ASSERT_EQ(legacy_layout->m_Lines.Size(), skribidi_layout->m_Lines.Size());
+    ASSERT_NEAR(legacy_layout->m_Height, skribidi_layout->m_Height, 0.01f);
```
Comment (JCash) [inline engine/font/src/test/test_font.cpp:970]: Making sure the line height don't differ too much between legacy/Skribidi layouts

File: engine/font/src/text_layout_skribidi.cpp [hunk 3]
```diff
@@ -85,6 +80,11 @@ static bool LayoutText(LayoutContext* ctx,
     params.flags              = 0;
 
     float tracking = settings->m_Tracking * settings->m_Size;
+    HFont default_font = FontCollectionGetFont(font_collection, 0);
+    float font_scale = FontGetScaleFromSize(default_font, settings->m_Size);
+    uint32_t ascent = (uint32_t)FontGetAscent(default_font, 1.0f);
+    uint32_t descent = (uint32_t)fabsf(FontGetDescent(default_font, 1.0f));
```
Comment (AGulev) [inline engine/font/src/text_layout_skribidi.cpp:86]: I'm not sure I understand we why we do (uint32_t)fabsf  to FontGetAscent and FontGetDescent

**Review by AGulev — APPROVED** [review]
Looks good, just a small question for the future us to understand this part better

File: engine/font/src/text_layout_skribidi.cpp (hunk 3 above)
Comment (JCash) [reply engine/font/src/text_layout_skribidi.cpp:86]: well spotted!

It may be more accurate currently as we'd first get the size in `em` units, then subtract, and then do the scaling on the result. As opposed to subtracting two scaled values, potentially losing floating point precision.
