### PR TITLE
Fix for certain models not getting correct textures assigned

### LINKED ISSUE #8345: Model multi material doesn't respect the sampler names
It's the same issue from both editor/bob.

https://forum.defold.com/t/defold-1-6-3-beta/75294/12?u=mathias_westerdahl

The .modelc files look ok:
```bash
~/work/defold $ ./scripts/unpack_ddf.py ./test-samplers/build/default/main/model1.modelc
rig_scene : "/main/model1.rigscenec" len: 22
default_animation : "" len: 0
materials : {
  name : "default" len: 7
  material : "/main/model.materialc" len: 21
  textures : {
    sampler : "a" len: 1
    texture : "/assets/images/brown.texturec" len: 29
    sampler : "tex0" len: 4
    texture : "/assets/images/green.texturec" len: 29
  }
}
~/work/defold $ ./scripts/unpack_ddf.py ./test-samplers/build/default/main/model2.modelc
rig_scene : "/main/model2.rigscenec" len: 22
default_animation : "" len: 0
materials : {
  name : "default" len: 7
  material : "/main/model.materialc" len: 21
  textures : {
    sampler : "tex0" len: 4
    texture : "/assets/images/green.texturec" len: 29
    sampler : "a" len: 1
    texture : "/assets/images/brown.texturec" len: 29
  }
}
```

The material looks like this:
```bash
name: "model"
tags: "model"
vertex_program: "/main/model.vpc"
fragment_program: "/main/model.fpc"
vertex_space: VERTEX_SPACE_LOCAL
vertex_constants {
  name: "mtx_worldview"
  type: CONSTANT_TYPE_WORLDVIEW
}
vertex_constants {
  name: "mtx_view"
  type: CONSTANT_TYPE_VIEW
}
vertex_constants {
  name: "mtx_proj"
  type: CONSTANT_TYPE_PROJECTION
}
vertex_constants {
  name: "mtx_normal"
  type: CONSTANT_TYPE_NORMAL
}
vertex_constants {
  name: "light"
  type: CONSTANT_TYPE_USER
  value {
    x: 1.0
    y: 1.0
    z: 1.0
    w: 1.0
  }
}
fragment_constants {
  name: "tint"
  type: CONSTANT_TYPE_USER
  value {
    x: 1.0
    y: 1.0
    z: 1.0
    w: 1.0
  }
}
samplers {
  name: "tex0"
  wrap_u: WRAP_MODE_CLAMP_TO_EDGE
  wrap_v: WRAP_MODE_CLAMP_TO_EDGE
  filter_min: FILTER_MODE_MIN_LINEAR
  filter_mag: FILTER_MODE_MAG_LINEAR
  max_anisotropy: 1.0
  name_hash: 13017721633329230598
}
samplers {
  name: "a"
  wrap_u: WRAP_MODE_CLAMP_TO_EDGE
  wrap_v: WRAP_MODE_CLAMP_TO_EDGE
  filter_min: FILTER_MODE_MIN_LINEAR
  filter_mag: FILTER_MODE_MAG_LINEAR
  max_anisotropy: 1.0
  name_hash: 16318089785215894210
}
max_page_count: 0
```

### PR DESCRIPTION
**Pull request by JCash**
In some cases, a model with multiple textures would get them assigned to incorrect texture units.

Fixes https://github.com/defold/defold/issues/8345

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 1]
```diff
@@ -280,46 +280,56 @@ namespace dmGameSystem
         return GetMaterialResource(component, resource, index)->m_Material;
     }
 
-    TextureResource* GetTextureResource(const ModelComponent* component, uint32_t material_index, uint32_t texture_unit)
+    static TextureResource* GetTextureFromSamplerNameHash(const MaterialInfo* material_info, const MaterialResource* material, uint32_t material_texture_index, dmhash_t sampler_name_hash)
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:283]: We need to think of the sampler names, to figure out their positions in the render objects' texture array.

Here we ask using sampler name first, then using the material texture index (as we're currently looping over the material's samplers, we can use that index directly)

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 2]
```diff
@@ -280,46 +280,56 @@ namespace dmGameSystem
...
+        // If it is contains materials, use that
+        if (material_texture_index < material->m_NumTextures)
+            return material->m_Textures[material_texture_index];
 
         return 0;
     }
 
-    dmGraphics::HTexture GetMaterialTexture(const ModelComponent* component, uint32_t material_index, uint32_t texture_unit)
+    // A bit legacy, as we don't want to set textures based on index anymore, but sampler names.
+    static TextureResource* GetTextureResource(const ModelComponent* component, uint32_t material_index, uint32_t material_texture_index)
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:302]: This is for our Lua api, to get a texture by index, which makes less sense nowadays, but is still part of the lua api.

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 3]
```diff
@@ -280,46 +280,56 @@ namespace dmGameSystem
...
+        {
+            TextureResource* texture_res = component->m_Textures[i];
+            if (!texture_res)
+            {
+                texture_res = GetTextureFromSamplerNameHash(&component->m_Resource->m_Materials[material_index], material, i, material->m_SamplerNames[i]);
+            }
+
+            ro->m_Textures[i] = texture_res ? texture_res->m_Texture : 0;
+        }
+    }
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:332]: Perhaps another candidate for GameSys generalization later on, so we can more easily use the same functionality for all components.

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 4]
```diff
@@ -654,10 +663,7 @@ namespace dmGameSystem
             DM_PROPERTY_ADD_U32(rmtp_ModelVertexCount, buffers->m_VertexCount);
             DM_PROPERTY_ADD_U32(rmtp_ModelVertexSize, buffers->m_VertexCount * sizeof(dmRig::RigModelVertex));
 
-            for(uint32_t i = 0; i < MAX_TEXTURE_COUNT; ++i)
-            {
-                ro.m_Textures[i] = GetMaterialTexture(component, material_index, i);
-            }
+            FillTextures(&ro, component, material_index);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:666]: Pro: We don't iterate over MAX_TEXTURE_COUNT items anymore.
Con:  It is a more complex loop.
If it becomes a problem, we might want to cache this info in the model resource or component, and perhaps use hashtables instead.

File: engine/gamesys/src/gamesys/resources/res_model.cpp [hunk 5]
```diff
@@ -266,6 +275,9 @@ namespace dmGameSystem
                 texture_info->m_SamplerNameHash = dmHashString64(texture->m_Sampler);
             }
 
+            // We need to sort the textures on sampler units
+            SortTextures(info.m_Material->m_Material, info.m_TexturesCount, info.m_Textures);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/resources/res_model.cpp:279]: They're sorted on least uniform index first.

File: engine/gamesys/src/gamesys/components/comp_model.cpp (hunk 4 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/components/comp_model.cpp:666]: Also, another way would be to defer that sorting/lookup to the renderer.
So instead, we'd pass the sampler/texture pairs to the renderer via the RenderObject.
It might simplify all the workings around this, at the cost of the renderobject growing a little bit

**Review by Jhonnyg — APPROVED** [review]
