### PR TITLE
Fix strange sprite behavior when change atlas in runtime

### LINKED ISSUE #11930: The textures are behaving very strangely after resource.set_atlas. Beta, Alpha versions
The problem occurs after replacing sd textures with hd textures using resource.set_atlas(sd, hd_atlas)

All Defold 1.12+ versions:
Image

Defold 1.11.2 (Correct behavior):
Image

**To Reproduce**
1. Find file build_bat/html5_zip_playgama.sh
2. Change path_to_bundle (output dir) and bob variables
3. Run script and build the project. The build will happen for the html5 platform. Liveupdate resources will be included in the build
4. Launch the build using the web server. You will see that the sd textures look fine. As soon as they are replaced by the HD version, they begin to flip over and change positions

**Platforms:**
All

**Minimal repro case project:**
https://drive.google.com/file/d/1CVzgoZqLmDC8Ay6CKVDWbKPtu3rDAD5J/view?usp=sharing

**Additional context:**
This may have happened after you optimized texture loading.

Files and scripts that you may need:
collections/loader/load_hd.script (loads liveupdate)
collections/hd/hd.script (replaces atlas with another one by resource.set_atlas(sd, hd_atlas))

### PR DESCRIPTION
**Pull request by ekharkunov**
Fix sprite strange behavior when sprite atlas was changed in runtime.

Fixes #11930 

### Technical changes
Reason:
Because pointer to `TextureSetResource` isn't changed when user updates atlas in runtime no sprite rehashing triggers. As a result after texture update sprite component used cached data about geometry, etc.
Fix:
Added resource reload callback to react to `TextureSetResource` changes. Also added `m_TexturesGeneration` field to `TextureSetResource` and use it to calculate hash to keep track that underlying texture resource was updated.

## PR checklist

* [x] Code
	* [x] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [x] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [x] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [x] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -2656,6 +2673,43 @@ namespace dmGameSystem
...
+                        SpriteTexture* sprite_texture = GetSpriteTextureByIndex(component, texture_idx);
+                        if (!updated_sprite_textures.Contains(sprite_texture))
+                        {
+                            sprite_texture->m_TexturesGeneration++;
+                            if (updated_sprite_textures.Full())
+                            {
+                                updated_sprite_textures.OffsetCapacity(32);
+                            }
+                            updated_sprite_textures.Add(sprite_texture);
+                        }
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp]: The `m_ReHash=1` part is clear to me, but I don't understand the part of `m_TexturesGeneration++`?
`m_TexturesGeneration` isn't used anywhere?

**Review by JCash — CHANGES_REQUESTED** [review]
Overall good, but the texture generation counter seems redundant

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp (hunk 1 above)
Comment (ekharkunov) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp]: `m_ReHash` isn't enough to fix initial issue because even if we force hash recalculation - the result hash will be the same as it was before atlas change. And as result old geometry information will be used next frame.
`m_TexturesGeneration` is used to change result here https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_sprite.cpp#L635. Counter help to track change of underlying `TextureSetResource` without going depp inside structure and without changing hash calculation logic.

Comment (JCash) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp]: Ah, we hash the entire struct as-is, that's why I didn't find a reference to m_TexturesGeneration.

File: engine/gamesys/src/dmsdk/gamesys/resources/res_sprite.h [hunk 2]
```diff
@@ -30,13 +30,14 @@ namespace dmGameSystem
     {
         dmhash_t            m_SamplerNameHash;
         TextureSetResource* m_TextureSet;
+        uint8_t             m_TexturesGeneration;
```
Comment (JCash) [inline engine/gamesys/src/dmsdk/gamesys/resources/res_sprite.h]: I think I'd rather have the "generation" on the actual resource that changed, the TextureSetResource*.
This of course would means that the sprite's Rehash() function would change a little.

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 3]
```diff
@@ -2656,6 +2673,43 @@ namespace dmGameSystem
         pit->m_FnIterateNext = CompSpriteIterPropertiesGetNext;
     }
 
+    static void ResourceReloadedCallback(const dmResource::ResourceReloadedParams* params)
+    {
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:2685]: You can use `dmhash_t dmResource::ResourceTypeGetNameHash(params.m_Type);` to compare compare and early out if it's not a `texturesetc` resource.

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp (hunk 1 above)
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp]: If the generation is moved to the TextureSetResource, then this logic isn't needed.

**Review by JCash — CHANGES_REQUESTED** [review]
Thanks for clarifying.
I do think that the generation counter belongs with the texture set resource, as it's universal, and not unique to the sprite usage.

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp (hunk 3 above)
Comment (ekharkunov) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp:2685]: As I understand reload callback called only for requested resource type so no need to filter it additionally.
https://github.com/defold/defold/blob/dev/engine/resource/src/resource.cpp#L1267-L1289

File: engine/gamesys/src/gamesys/resources/res_textureset.cpp [hunk 4]
```diff
@@ -126,14 +126,16 @@ namespace dmGameSystem
...
 
     static uint32_t GetResourceSize(TextureSetResource* res, uint32_t ddf_size)
     {
         uint32_t size = sizeof(TextureSetResource);
         size += ddf_size;
-        size += res->m_HullCollisionGroups.Capacity()*sizeof(dmhash_t);
-        size += res->m_AnimationIds.Capacity()*(sizeof(dmhash_t)+sizeof(uint32_t));
+        size += res->m_HullCollisionGroups.Capacity() * sizeof(dmhash_t);
+        size += res->m_AnimationIds.Capacity() * (sizeof(dmhash_t) + sizeof(uint32_t));
+        size += res->m_FrameIds.Capacity() * (sizeof(dmhash_t) + sizeof(uint32_t));
```
Comment (ekharkunov) [inline engine/gamesys/src/gamesys/resources/res_textureset.cpp:138]: I assumed that it was missed.

File: engine/gamesys/src/gamesys/resources/res_textureset.cpp [hunk 5]
```diff
@@ -194,14 +196,17 @@ namespace dmGameSystem
...
         {
+            uint8_t current_generation = tile_set->m_TexturesGeneration;
             ReleaseResources(params->m_Factory, tile_set);
 
             tile_set->m_TextureSet = tmp_tile_set.m_TextureSet;
             tile_set->m_Texture = tmp_tile_set.m_Texture;
             tile_set->m_HullCollisionGroups.Swap(tmp_tile_set.m_HullCollisionGroups);
             tile_set->m_HullSet = tmp_tile_set.m_HullSet;
             tile_set->m_AnimationIds.Swap(tmp_tile_set.m_AnimationIds);
+            tile_set->m_FrameIds.Swap(tmp_tile_set.m_FrameIds);
```
Comment (ekharkunov) [inline engine/gamesys/src/gamesys/resources/res_textureset.cpp:207]: I assumed that we should also swap `FrameIds`. Let me know if it was done by design

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp (hunk 3 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp:2685]: You call the rgister function above:
```c++
dmResource::RegisterResourceReloadedCallback(sprite_context->m_Factory, ResourceReloadedCallback, sprite_world);
```

There is no additional information there, it gets called for all reloaded resources.
E.g. if someone reloads or sets a sound file?

File: engine/gamesys/src/gamesys/resources/res_textureset.cpp (hunk 5 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/resources/res_textureset.cpp:207]: this looks like a good improvement. Was this the final issue?

**Review by JCash — CHANGES_REQUESTED** [review]
overall good
see note about resource reload check

File: engine/gamesys/src/gamesys/resources/res_textureset.cpp (hunk 5 above)
Comment (ekharkunov) [reply engine/gamesys/src/gamesys/resources/res_textureset.cpp:207]: No, it doesn't relate to issue with wrong atlas animation. Just notice and add it.

File: engine/resource/src/resource.cpp [hunk 6]
```diff
@@ -1348,6 +1349,7 @@ Result SetResource(HFactory factory, uint64_t hashed_name, void* message)
                 params.m_Resource = rd;
                 params.m_Filename = 0;
                 params.m_FilenameHash = hashed_name;
+                params.m_Type = resource_type;
```
Comment (ekharkunov) [inline engine/resource/src/resource.cpp:1352]: One more missed thing

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 7]
```diff
@@ -2683,6 +2683,11 @@ namespace dmGameSystem
 
     static void ResourceReloadedCallback(const dmResource::ResourceReloadedParams* params)
     {
+        dmhash_t name_hash = ResourceTypeGetNameHash(params->m_Type);
+        if (name_hash != TEXTURE_SET_EXT_HASH)
+        {
+            return;
+        }
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:2690]: 👍

**Review by JCash — APPROVED** [review]
lgtm!
