### PR TITLE
Destroy particle fx callback early if we failed to invoke it

### LINKED ISSUE #5269: Particle callbacks cause an error if the parent collection was deleted
**Describe the bug (REQUIRED)**
If the parent collection were deleted, child particle emitters throw this error: `"ERROR:GAMESYS: Could not run particlefx callback because the instance has been deleted."`

**To Reproduce (REQUIRED)**
1. Start a particle emitter with particlefx.play() and include a callback.
2. Wait at least one frame.
3. Delete the collection.

**Expected behavior (REQUIRED)**
No error in the console. Not sure if the error causes a hard when published.

**Defold version (REQUIRED):**
  - v1.2.174.

**Platforms (REQUIRED):**
- Local testing.

**Minimal repro case project (OPTIONAL):**
[ParticleEmitterCallbackError.zip](https://github.com/defold/defold/files/5366080/ParticleEmitterCallbackError.zip)

**Additional context (OPTIONAL):**
Forum discussion: https://forum.defold.com/t/particle-end-event-like-animation-done-solved/709/25

### PR DESCRIPTION
**Pull request by britzl**
Fixes #5269

### CODE REVIEW

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp [hunk 1]
```diff
@@ -106,13 +106,15 @@ namespace dmGameSystem
 
             EmitterStateChangedCallbackArgs args(data.m_ComponentId, emitter_id, emitter_state);
 
-            if (!dmScript::InvokeCallback(data.m_CallbackInfo, EmitterStateChangedCallbackArgsCB, &args))
+            int ok = dmScript::InvokeCallback(data.m_CallbackInfo, EmitterStateChangedCallbackArgsCB, &args);
+            if (!ok)
             {
-                dmLogError("Could not run particlefx callback because the instance has been deleted.");
+                dmLogWarning("Could not run particlefx callback because the instance has been deleted.");
```
Comment (britzl) [inline engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:112]: Should we log once or not at all? I get a feeling that we are not consistent with this in the code in general.

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp [hunk 2]
```diff
@@ -106,13 +106,15 @@ namespace dmGameSystem
...
             }
 
-            // The last emitter belonging to this particlefx har gone to sleep, release lua reference.
-            if(num_awake_emitters == 0 && emitter_state == dmParticle::EMITTER_STATE_SLEEPING)
+            // Release the lua ref to the callback if we failed to invoke callback or if the last emitter
+            // belonging to this particlefx har gone to sleep.
+            if(!ok || (num_awake_emitters == 0 && emitter_state == dmParticle::EMITTER_STATE_SLEEPING))
```
Comment (britzl) [inline engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:117]: Might as well destroy the callback if we failed to invoke it. Is there any chance it will be successful the next time?

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp (hunk 1 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:112]: Not sure what's best.
Also, it's a bit different for particles since they're fire-and-forget.

Comment (JCash) [reply engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:112]: Also note that the `dmScript::InvokeCallback()` is deprecated.

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp (hunk 2 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:117]: I think that's a good approach, yes.

**Review by JCash — DISMISSED** [review]

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp (hunk 1 above)
Comment (britzl) [reply engine/gamesys/src/gamesys/scripts/script_particlefx.cpp]: I decided to not log anything. And I've changed from InvokeCallback.

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp [hunk 3]
```diff
@@ -75,52 +75,45 @@ namespace dmGameSystem
...
-        lua_pushnumber(L, args->m_EmitterState);
-    }
-
     void EmitterStateChangedCallback(uint32_t num_awake_emitters, dmhash_t emitter_id, dmParticle::EmitterState emitter_state, void* user_data)
     {
+
         EmitterStateChangedScriptData data = *(EmitterStateChangedScriptData*)(user_data);
 
-        if (data.m_CallbackInfo)
+        if (!data.m_CallbackInfo)
```
Comment (britzl) [inline engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:83]: I prefer an early return if there's nothing to do

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp [hunk 4]
```diff
@@ -75,52 +75,45 @@ namespace dmGameSystem
...
-            }
+        if (!dmScript::SetupCallback(data.m_CallbackInfo))
+        {
+            dmScript::DestroyCallback(data.m_CallbackInfo);
+            data.m_CallbackInfo = 0x0;
+            return;
         }
-        else
+
+        dmScript::PushHash(L, data.m_ComponentId);
```
Comment (britzl) [inline engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:105]: dmScript::InvokeCallback was deprecated. Setting up callback and invoking manually.

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp [hunk 5]
```diff
@@ -75,52 +75,45 @@ namespace dmGameSystem
...
+        dmScript::PushHash(L, emitter_id);
+        lua_pushnumber(L, emitter_state);
+        dmScript::PCall(L, 4, 0);
+
```
Comment (britzl) [inline engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:109]: Not sure if there's a point in checking for an error here? Since it's a Lua error in the actual callback function it might actually work the next time so I don't think we should destroy the callback.

File: engine/gamesys/src/gamesys/scripts/script_particlefx.cpp (hunk 3 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/scripts/script_particlefx.cpp:83]: The IsCallbackValid also does a null check

**Review by JCash — DISMISSED** [review]
Looks good, just a double null check
