### PR TITLE
Fixed code editor freeze when matching against very long strings

### LINKED ISSUE #11191: Language server hang when editing text
It's a 100% repro

Steps to reproduce:
* Open extension-rive
* Open loader.script
* At the top, add

    local myVar = "foo"

* Press save

* Try to rename variable to

    local myVarLongerName

* Observe a hang where the cursor going into "waiting" mode and never (?) recovers

I don't get any console info while it's happening, but when quitting the process in the terminal, I get this:

```
^C/Users/mathiaswesterdahl/work/defold/editor/tmp/unpack/arm64-macos/bin/lsp/lua/bin/lua-language-server: script/service/net.lua:270: interrupted!
stack traceback:
    [C]: in method 'wait'
    script/service/net.lua:270: in function 'service.net.update'
    script/service/service.lua:185: in local 'sleep'
    script/service/service.lua:197: in function 'service.eventLoop'
    script/service/service.lua:283: in function 'service.start'
    ...efold/editor/tmp/unpack/arm64-macos/bin/lsp/lua/main.lua:80: in main chunk
    (bootstrap.lua):85: in main chunk
    [C]: in ?
```

### PR DESCRIPTION
**Pull request by matgis**
* Rewrote the fuzzy text matching algorithm to use less memory and perform matches faster.
* Fixed a freeze that could occur in the code editor when attempting to perform a fuzzy text match against very long autocomplete suggestions originating from non-Lua files in some projects.
* Fixed an exception that would occur if a fuzzy text search term included the Turkish capital letter I (`İ`) on a machine running under a non-Turkish locale setting.

Fixes #11191.

### Technical changes
* Disabled workspace word autocomplete suggestions from the built-in Lua LSP server.

### CODE REVIEW

File: editor/src/clj/editor/lsp/server.clj [hunk 1]
```diff
@@ -263,6 +263,7 @@
                   workspace (g/node-value project :workspace evaluation-context)
                   root (g/raw-property-value (:basis evaluation-context) workspace :root)]
               {:runtime {:version "Lua 5.1" :pathStrict true}
+               :completion {:workspaceWord false}
```
Comment (matgis) [inline editor/src/clj/editor/lsp/server.clj:266]: When `true` or left at the default setting, the Lua language server will scan non-Lua files in the project for strings and suggest them as completions when there's no better alternative. This is probably not a great idea when the project directory can contain lots of large non-code files, but I'm open to leaving it on.

The alternative would be to explicitly list a bunch of file extensions that we know to cause trouble as exclusions, such as `.spinejson`, `.gltf`, `.dylib`, `.a`, `.so`, and so on.

File: editor/src/clj/editor/fuzzy_text.clj [hunk 2]
```diff
@@ -15,7 +15,8 @@
 (ns editor.fuzzy-text
   (:require [clojure.string :as string]
             [util.bit-set :as bit-set]
-            [util.coll :as coll :refer [pair]]))
+            [util.coll :as coll :refer [pair]])
+  (:import [java.util.concurrent.atomic AtomicInteger]))
```
Comment (matgis) [inline editor/src/clj/editor/fuzzy_text.clj:19]: The fuzzy text matching algorithm has been rewritten in an imperative fashion so it will perform less allocations and be more efficient.

The scoring is still only performed once we have a fully formed candidate and uses the same code as before. As a future improvement, we could sum up the score as we build up the candidate so we can bail out earlier. However, re-implementing the algorithm so it would work exactly like before was already quite tricky, so I'll leave it like this for now.

File: editor/src/clj/editor/fuzzy_text.clj [hunk 3]
```diff
@@ -242,31 +171,155 @@
...
+                  (recur (inc iteration)
+                         pending-tick-index-in-pattern))))))))))
 
 (defn prepare-pattern
   "Given a pattern string, returns a trimmed and case-agnostic prepared-pattern
   for use with the match functions."
   [^String pattern]
-  (let [trimmed-pattern (string/trim pattern)]
-    (pair (string/upper-case trimmed-pattern)
-          (string/lower-case trimmed-pattern))))
```
Comment (matgis) [inline editor/src/clj/editor/fuzzy_text.clj:263]: Fun fact: If you run `string/lower-case` on a string that contains the Turkish capital letter İ like `"İpek"` under a non-Turkish locale, you end up with a string that prints like `"ipek"`, but includes a hidden code point remnant and has a length of five.

Converting the code points individually solves the issue (it's not a surrugate-pair situation either - `İ` is a single code point in the input string, and its lower-case equivalent is also a single code point if converted under the Turkish locale).

File: editor/src/clj/editor/lsp/server.clj (hunk 1 above)
Comment (vlaaad) [reply editor/src/clj/editor/lsp/server.clj:266]: Ohhhh, great find!

**Review by vlaaad — APPROVED** [review]
Wonderful work!

File: editor/src/clj/editor/lsp/server.clj (hunk 1 above)
Comment (AGulev) [reply editor/src/clj/editor/lsp/server.clj:266]: hmm, maybe it's the reason of https://github.com/defold/defold/issues/8989
