### PR TITLE
Show an error if the wrong script type is used

### LINKED ISSUE #8005: Create a build error if a .script file is used as a .gui_script file
Both editor and bob fail to catch this issue.
Editor built content produces a hard crash, bob built content produces an error related to resources: "Unknown resource type: script"

Repro:
https://forum.defold.com/t/colorslide-tutorial-build-fail/74076

### PR DESCRIPTION
**Pull request by AGulev**
Fixed the issue where neither the editor nor bob reacts when the wrong script type is used, such as a `.script` file instead of a `*.gui_script` in `*.gui` etc.

Fix https://github.com/defold/defold/issues/8005
## PR checklist

* [ ] Code
	* [x] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: editor/src/clj/editor/gui.clj [hunk 1]
```diff
@@ -501,9 +501,13 @@
...
 ;; SDK api
-(defn prop-resource-error [node-id prop-kw prop-value prop-name]
-  (or (validation/prop-error :fatal node-id prop-kw validation/prop-nil? prop-value prop-name)
+(defn prop-resource-error
+  ([node-id prop-kw prop-value prop-name]
+    (or (validation/prop-error :fatal node-id prop-kw validation/prop-nil? prop-value prop-name)
       (validation/prop-error :fatal node-id prop-kw validation/prop-resource-not-exists? prop-value prop-name)))
+  ([node-id prop-kw prop-value prop-name resource-ext]
+    (or (prop-resource-error node-id prop-kw prop-value prop-name)
+      (validation/prop-error :fatal node-id prop-kw validation/prop-resource-ext? prop-value resource-ext prop-name))))
```
Comment (AGulev) [inline editor/src/clj/editor/gui.clj:510]: It's public API + we don't need it in all the cases, so I do this new checking optional.

File: com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/messages.properties [hunk 2]
```diff
@@ -1,6 +1,7 @@
 BuilderUtil_EMPTY_RESOURCE=you must specify a {0}
 BuilderUtil_MISSING_RESOURCE=the {0} ''{1}'' can't be found
 BuilderUtil_DUPLICATE_RESOURCE=the resource ''{0}'' is duplicated
+BuilderUtil_WRONG_RESOURCE_TYPE= Wrong resource ''{0}''. It has resource type ''{1}'', but expected type is ''{2}''
```
Comment (AGulev) [inline com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/messages.properties:4]: I didn't even know we have this file 🤔

File: com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GuiBuilder.java [hunk 3]
```diff
@@ -405,7 +405,14 @@ public static SceneDesc.Builder transformScene(GuiBuilder builder, String input,
 
         if(builder != null) {
             // transform and register scene external resources (if compiling)
-            sceneBuilder.setScript(BuilderUtil.replaceExt(sceneBuilder.getScript(), ".gui_script", ".gui_scriptc"));
+            String scriptPath = sceneBuilder.getScript();
+            String suffix = BuilderUtil.getSuffix(scriptPath);
+            if (!suffix.isEmpty() && !suffix.equals("gui_script"))
```
Comment (JCash) [inline com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GuiBuilder.java:410]: No need to check if it's empty too.

**Review by JCash — DISMISSED** [review]
lgtm.
Do we need this for the vice versa case? (When setting a gui_script instead of a script)

File: com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GuiBuilder.java (hunk 3 above)
Comment (AGulev) [reply com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GuiBuilder.java:410]: no, we need to check if it's empty. Because not all the GUIs use scripts.

**Comment by AGulev** [comment]
Converted to draft: I'll take a look the opposite situation when setting a gui_script instead of a script

File: com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GameObjectBuilder.java [hunk 4]
```diff
@@ -237,6 +238,11 @@ private PrototypeDesc.Builder transformGo(IResource resource,
             compStorage.add(ext);
             String inExt = "." + ext;
             String outExt = project.replaceExt(inExt);
+            if (ext.equals("gui_script") || ext.equals("render_script"))
+            {
+                throw new CompileExceptionError(resource, 0, BobNLS.bind(Messages.BuilderUtil_WRONG_RESOURCE_TYPE,
+                        new String[] { c, ext, "script" } ));
+            }
```
Comment (AGulev) [inline com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GameObjectBuilder.java:245]: Make sure game objects produce an error if the wrong types used

File: com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ProtoBuilders.java [hunk 5]
```diff
@@ -290,6 +290,14 @@ private boolean hasDuplicateNames(List<RenderPrototypeDesc.RenderResourceDesc> r
         protected RenderPrototypeDesc.Builder transform(Task<Void> task, IResource resource, RenderPrototypeDesc.Builder messageBuilder)
                 throws IOException, CompileExceptionError {
 
+            String scriptPath = messageBuilder.getScript();
+            String suffix = BuilderUtil.getSuffix(scriptPath);
+            if (!suffix.isEmpty() && !suffix.equals("render_script"))
+            {
+                throw new CompileExceptionError(resource, 0, BobNLS.bind(Messages.BuilderUtil_WRONG_RESOURCE_TYPE,
+                        new String[] { scriptPath, suffix, "render_script" } ));
```
Comment (AGulev) [inline com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ProtoBuilders.java:298]: The same check for render_scripts

File: editor/src/clj/editor/game_object.clj [hunk 6]
```diff
@@ -140,6 +140,13 @@
       (update :display-order (fn [display-order]
                                (vec (distinct (concat display-order (:display-order source-properties))))))))
 
+(defn resource-path-error [_node-id source-resource]
+  (let [node-type (some-> source-resource resource/resource-type :node-type)]
+    (or (validation/prop-error :fatal _node-id :path validation/prop-nil? source-resource "Path")
```
Comment (AGulev) [inline editor/src/clj/editor/game_object.clj:145]: `:fatal` fits better in this case than `:info` (if user ignores this info and build - it will be an exception in another place).

File: editor/src/clj/editor/game_object.clj [hunk 7]
```diff
@@ -140,6 +140,13 @@
...
+        (validation/prop-error :fatal _node-id :path validation/prop-resource-not-exists? source-resource "Path")
+        (and (= node-type editor.code.script/ScriptNode)
```
Comment (AGulev) [inline editor/src/clj/editor/game_object.clj:147]: If a node is ScriptNode, we should make sure it it the only allowed `script` file here, nor `render_script` or `gui_script`

File: editor/src/clj/editor/render_pb.clj [hunk 8]
```diff
@@ -118,7 +118,8 @@
 
 (defn- build-errors
   [_node-id script named-render-resources]
-  (when-let [errors (->> (into [(validation/prop-error :fatal _node-id :script validation/prop-resource-missing? script "Script")]
+  (when-let [errors (->> (into [(or (validation/prop-error :fatal _node-id :script validation/prop-resource-missing? script "Script")
+                                    (validation/prop-error :fatal _node-id :script validation/prop-resource-ext? script "render_script" "Script"))]
```
Comment (AGulev) [inline editor/src/clj/editor/render_pb.clj:122]: There is no property for that field, only a form view. But it's rarely used thing, so I thing preventing it from building is good enough.

File: editor/src/clj/editor/game_object.clj [hunk 9]
```diff
@@ -254,18 +260,29 @@
...
-                                       :ext (some-> source-resource resource/resource-type :ext)
-                                       :to-type (fn [v] (:resource v))
-                                       :from-type (fn [r] {:resource r :overrides []})}))
+            (dynamic edit-type (g/fnk [source-resource _node-id]
+                                 (let [resource-type (some-> source-resource resource/resource-type)
+                                       tags (:tags resource-type)]
+                                   {:type resource/Resource
+                                    :ext (or (and (or (contains? tags :component) (contains? tags :embeddable))
+                                                  (some-> resource-type :ext))
+                                             (get-all-comp-exts (project/workspace (project/get-project _node-id))))
```
Comment (AGulev) [inline editor/src/clj/editor/game_object.clj:280]: This is strange if we show an error "this is not a component" but right after that suggest picking another one "non-component".  This fix adds a filter to "only components and embeddables" in cases when non-component was picked.

File: editor/src/clj/editor/validation.clj [hunk 10]
```diff
@@ -74,6 +74,13 @@
       (when-not (= (resource/type-ext v) ext)
         (format "%s '%s' is not of type %s" name (resource/resource->proj-path v) (format-ext ext)))))
 
+(defn prop-resource-comp? [v name]
```
Comment (matgis) [inline editor/src/clj/editor/validation.clj:77]: Weirdly, the convention for the validation function name is to reflect what would be considered an error. So for example, the validation function that will emit an error if a resource does not exist is called `prop-resource-not-exists?`, and the function that produces an error for a `nil` value is named `prop-nil?`, etc.

So I think we should rename this `prop-resource-not-component?` to follow the convention. 🤔

File: editor/src/clj/editor/gui.clj (hunk 1 above)
Comment (matgis) [inline editor/src/clj/editor/gui.clj:510]: Style: Indentation is off for this function. **Code > Auto-Indent Lines** should sort it out!

File: editor/src/clj/editor/game_object.clj [hunk 11]
```diff
@@ -161,7 +167,7 @@
                             (let [proj-path->resource-property-build-target (bt/make-proj-path->build-target resource-property-build-targets)]
                               (game-object-common/referenced-component-instance-data build-resource ddf-message pose proj-path->resource-property-build-target)))
             build-target (assoc build-target :instance-data instance-data)]
-        [(bt/with-content-hash build-target)]))))
+        [(bt/with-content-hash build-target)])))))
```
Comment (matgis) [inline editor/src/clj/editor/game_object.clj:170]: Style: Indentation is off for this function. **Code > Auto-Indent Lines** should sort it out!

**Review by matgis — DISMISSED** [review]
Very nice! Love that the weird behaviour where you could pick non-component files when editing the component path got fixed as part of this too! ❤️ 

I only had some naming and indentation niggles to report, but I'll approve the PR anyway so you don't have to ask for a re-review if you decide to fix them.

File: editor/src/clj/editor/validation.clj (hunk 10 above)
Comment (AGulev) [reply editor/src/clj/editor/validation.clj:77]: yes, your option is much better. thx

File: editor/src/clj/editor/gui.clj (hunk 1 above)
Comment (AGulev) [reply editor/src/clj/editor/gui.clj]: I missed that, thx (I usually use `Format Code`, I hope it's fine as well)

**Review by matgis — APPROVED** [review]
I'm happy with the editor-side changes! Nice work! ❤️

**Review by JCash — APPROVED** [review]
