### PR TITLE
Fixed issue of crashing on an uninitialized sound system

### LINKED ISSUE #5774: Crash when the sound system is uninitialized during pause and finalize
**Describe the bug (REQUIRED)**
We have reports of crashes in the sound system when the sound system isn't initialized and Pause() or Finalize() is called.

**Expected behavior (REQUIRED)**
No crash

**Defold version (REQUIRED):**
  - Version 1.2.182

**Platforms (REQUIRED):**
 - Seen on iOS but it likely applies to all platforms

### PR DESCRIPTION
**Pull request by JCash**
Fixes #5774

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -857,6 +857,8 @@ namespace dmEngine
         dmSound::Result soundInit = dmSound::Initialize(engine->m_Config, &sound_params);
         if (dmSound::RESULT_OK == soundInit) {
             dmLogInfo("Initialised sound device '%s'", sound_params.m_OutputDevice);
+        } else {
+            dmLogWarning("Failed to initialize sound system.");
```
Comment (JCash) [inline engine/engine/src/engine.cpp:861]: We could ofc exit the engine.
But, if it's still possible to run the game without sound, it's probably better to try that instead.

**Review by Jhonnyg — APPROVED** [review]
Looks good 🥇
