### PR TITLE
Fix selection context on outline label double click, and no selection npe

### LINKED ISSUE #11074: Double clicking on an outline label might open the last opened tab
> When I double click Gui/Nodes/Textures text to expand it, the previously open tab opens instead. 

Reported [here](https://forum.defold.com/t/defold-1-10-4-has-been-released/81160/11?u=sprocketc).

### PR DESCRIPTION
**Pull request by sprocketc**
Fixes #11074
Fixes #11076

### CODE REVIEW

File: editor/src/clj/editor/outline_view.clj [hunk 1]
```diff
@@ -541,7 +541,7 @@
         (< time-diff db-click-threshold)
         (do
           (cancel-rename! tree-view)
-          (ui/run-command (.getSource event) :file.open-selected))
+          (ui/run-command (.getSource event) :file.open-selected {} false (fn [] (.consume event))))
```
Comment (sprocketc) [inline editor/src/clj/editor/outline_view.clj:544]: We previously used `ui/bind-double-click!` to trigger `:file.open-selected`. That handles this is a similar way, but we now also have to cancel the future event. Maybe it's possible to restructure this in order to use existing ui functions, but I am worried that it would introduce new issues.

File: editor/src/clj/editor/outline_view.clj [hunk 2]
```diff
@@ -517,9 +517,9 @@
 (defn- get-selected-node-id
   [^TreeView tree-view]
   (let [selection-model (.getSelectionModel tree-view)
-        selected-items (.getSelectedItems selection-model)
-        ^TreeItem selected-item (first selected-items)]
-    (item->node-id selected-item)))
+        selected-items (.getSelectedItems selection-model)]
+    (when-let [^TreeItem selected-item (first selected-items)]
+      (item->node-id selected-item))))
```
Comment (sprocketc) [inline editor/src/clj/editor/outline_view.clj:522]: To reproduce #11076, select the root node, and then use `Option+Click` to remove it from the current selection. Then click on the caret icon to collapse or expand a node that can be renamed (avoid selecting the node), and then click on its label.

**Comment by vlaaad** [comment]
Ship it!

**Review by vlaaad — APPROVED** [review]
