### PR TITLE
Issue-6816 Fix issue when engine can't play more than 32 sounds simultaneously 

### LINKED ISSUE #6816: Can't play more than 32 sounds simultaneously
**Describe the bug (REQUIRED)**
Can't play more than 32 sounds simultaneously

**To Reproduce (REQUIRED)**
Just try to play more than 32 sounds

**Expected behavior (REQUIRED)**
Play as many sounds as pointed in project settings

**Defold version (REQUIRED):**
  - Version [1.3.4]

**Platforms (REQUIRED):**
 - All

**Screenshots (OPTIONAL):**
image

### PR DESCRIPTION
**Pull request by AGulev**
Use `sound.max_sound_instances` as maximum count of simultaneously played sounds.

Fix https://github.com/defold/defold/issues/6816

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sound.cpp [hunk 1]
```diff
@@ -74,11 +74,11 @@ namespace dmGameSystem
...
         uint32_t comp_count = dmMath::Min(params.m_MaxComponentInstances, sound_context->m_MaxComponentCount);
-        const uint32_t MAX_INSTANCE_COUNT = 32;
-        world->m_Entries.SetCapacity(MAX_INSTANCE_COUNT);
-        world->m_Entries.SetSize(MAX_INSTANCE_COUNT);
-        world->m_EntryIndices.SetCapacity(MAX_INSTANCE_COUNT);
-        memset(&world->m_Entries.Front(), 0, MAX_INSTANCE_COUNT * sizeof(PlayEntry));
+        const uint32_t max_instances = sound_context->m_MaxSoundInstances;
+        world->m_Entries.SetCapacity(max_instances);
+        world->m_Entries.SetSize(max_instances);
+        world->m_EntryIndices.SetCapacity(max_instances);
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/components/comp_sound.cpp:80]: One `entry` uses one sound `instance` from sound system.
We use `sound.max_sound_instances` as count of `instances` so we should use the same number for `entries`

**Review by britzl — APPROVED** [review]
Seems reasonable! Do we have a test for this?

**Comment by AGulev** [comment]
> Seems reasonable! Do we have a test for this?

no, 
hmmm, I'm not sure what exactly should be tested here

**Comment by britzl** [comment]
> hmmm, I'm not sure what exactly should be tested here

You're right. Me neither :-)
