### PR TITLE
Show notification instead of exception when the editor can't be connected to debugger

### LINKED ISSUE #8885: Unable to build due to debugger exception
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-02T15:10:02.194956</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>acf09db558d18f7ccbbaa02c09333932f7cc8d4a</td></tr>
<tr><td>Defold engine sha</td><td>9141d9d3605e3f5d51c71293116d769da2613d39</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a753ca32306e49a9b2aca4acdac93236"'>a753ca32306e49a9b2aca4acdac93236</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>3.1.0 - Build 9.17.10.4459</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Inability to connect to the debugger is not the issue itself, so it shouldn't be reported as an reportable exception. Now it's a notification.

Fix https://github.com/defold/defold/issues/8885

## PR checklist

* [x] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: editor/src/clj/editor/debugging/mobdebug.clj [hunk 1]
```diff
@@ -149,17 +149,20 @@
...
+        (if-some [socket (try-connect! address port)]
+          (let [debug-session (make-debug-session socket on-closed)]
+            (on-connected debug-session))
+          (if (< retries 50)
+            (do (Thread/sleep 200) (recur (inc retries)))
+            (throw (ex-info (format "Failed to connect to debugger on %s:%d" address port)
+                            {:address address
+                             :port port})))))
+      (catch Exception e
+        (on-error e)))))
```
Comment (AGulev) [inline editor/src/clj/editor/debugging/mobdebug.clj:165]: this is the main fix. 
because of the thread, we don't catch the exception in `start-debugger!`, so I use `on-error` callback instead

File: editor/src/clj/editor/debug_view.clj [hunk 2]
```diff
@@ -473,38 +474,39 @@
...
+                         (mobdebug/run! debug-session (make-debugger-callbacks debug-view))
+                         (state-changed! debug-view true)))
+                     (fn [_debug-session]
+                       (ui/run-now
+                         (g/set-property! debug-view
+                                          :debug-session nil
+                                          :suspension-state nil)
+                         (state-changed! debug-view false)))
+                     (fn [e]
+                       (show-connect-failed-info! target-address (+ mobdebug-port instance-index) e workspace))))
```
Comment (AGulev) [inline editor/src/clj/editor/debug_view.clj:509]: I catch the error in this callback and represent it for the user

File: editor/src/clj/editor/debug_view.clj [hunk 3]
```diff
@@ -473,38 +474,39 @@
...
-       :icon :icon/triangle-error
-       :header msg
-       :content (.getMessage exception)})))
+(defn- show-connect-failed-info! [target-address port ^Exception exception workspace]
+  (ui/run-later
+    (let [msg (str "Failed to attach debugger to " target-address ":" port ".\n"
+                   "Check that the game is running and is reachable over the network.\n"
+                   "Error message:\n" (.getMessage exception))]
+      (log/error :msg msg :exception exception)
+      (notifications/show!
```
Comment (AGulev) [inline editor/src/clj/editor/debug_view.clj:483]: notification instead of dialog . it looks like this: 
CleanShot 2024-08-07 at 09 12 11@2x

**Comment by AGulev** [comment]
This PR for `dev` because it in the same place where I worked on multi-instance changes. These changes are in `beta` but not in the `editor-dev` because of the changes in the engine. 
I'll cherry-pick changes into beta when we are done

File: editor/src/clj/editor/debug_view.clj [hunk 4]
```diff
@@ -473,38 +474,39 @@
...
-                           (state-changed! debug-view true)))
-                       (fn [_debug-session]
-                         (ui/run-now
-                           (g/set-property! debug-view
-                                            :debug-session nil
-                                            :suspension-state nil)
-                           (state-changed! debug-view false))))
-    (catch Exception exception
-      (show-connect-failed-dialog! target-address (+ mobdebug-port instance-index) exception))))
+  [debug-view project target-address instance-index workspace]
```
Comment (matgis) [inline editor/src/clj/editor/debug_view.clj:490]: We could get the `workspace` using `(project/workspace project)`, so we don't need to add it as an argument here.

File: editor/src/clj/editor/debug_view.clj [hunk 5]
```diff
@@ -473,38 +474,39 @@
...
+                         (update-breakpoints! debug-session (g/node-value project :breakpoints))
+                         (mobdebug/run! debug-session (make-debugger-callbacks debug-view))
+                         (state-changed! debug-view true)))
+                     (fn [_debug-session]
+                       (ui/run-now
+                         (g/set-property! debug-view
+                                          :debug-session nil
+                                          :suspension-state nil)
+                         (state-changed! debug-view false)))
+                     (fn [e]
```
Comment (matgis) [inline editor/src/clj/editor/debug_view.clj:508]: Rename `e` -> `exception`?

File: editor/src/clj/editor/debug_view.clj (hunk 3 above)
Comment (matgis) [reply editor/src/clj/editor/debug_view.clj:483]: The double error messages seem a bit reduntant. Maybe we should just show the text from the error instead of "Failed to attach to debugger ...", followed by a newline and the helpful info text?

So it would become:
```
Failed to connect to debugger on localhost:812

Check that the game is running and is reachable over
the network.
```

File: editor/src/clj/editor/debug_view.clj [hunk 6]
```diff
@@ -546,7 +548,7 @@
              (protobuf/bytes->map-with-defaults Lua$LuaModule))))
 
 (defn attach!
-  [debug-view project target build-artifacts]
+  [debug-view project target build-artifacts workspace]
```
Comment (matgis) [inline editor/src/clj/editor/debug_view.clj:551]: We could get the `workspace` using `(project/workspace project)`, so we don't need to add it as an argument here.

File: editor/src/clj/editor/debugging/mobdebug.clj [hunk 7]
```diff
@@ -149,17 +149,20 @@
...
-                          {:address address
-                           :port port})))))))
+    (try
+      (loop [retries 0]
+        (if-some [socket (try-connect! address port)]
+          (let [debug-session (make-debug-session socket on-closed)]
+            (on-connected debug-session))
+          (if (< retries 50)
+            (do (Thread/sleep 200) (recur (inc retries)))
+            (throw (ex-info (format "Failed to connect to debugger on %s:%d" address port)
```
Comment (matgis) [inline editor/src/clj/editor/debugging/mobdebug.clj:161]: Should we add a period `.` after the error message here?

**Review by matgis — DISMISSED** [review]
Looks very nice!

I wonder if we should try to shorten the message a bit by removing one of the very similar error messages in the popup?

File: editor/src/clj/editor/debug_view.clj (hunk 3 above)
Comment (AGulev) [reply editor/src/clj/editor/debug_view.clj:482]: Here is fixed version
CleanShot 2024-08-07 at 10 54 30@2x

File: editor/src/clj/editor/debug_view.clj (hunk 4 above)
Comment (AGulev) [reply editor/src/clj/editor/debug_view.clj]: fixed

File: editor/src/clj/editor/debug_view.clj (hunk 6 above)
Comment (AGulev) [reply editor/src/clj/editor/debug_view.clj]: thx! fixed

File: editor/src/clj/editor/debugging/mobdebug.clj (hunk 7 above)
Comment (AGulev) [reply editor/src/clj/editor/debugging/mobdebug.clj]: added

**Review by matgis — APPROVED** [review]
Ship it! ❤️
