### PR TITLE
issue-4934: Use correct box size when creating 3d physics with non unit scale

### LINKED ISSUE #4934: 3D physics shapes scale wrong with lower physics unit scale (1.2.169)
**Describe the bug**
With 3D physics enabled and the physics unit scale set lower than 1, on a game object with uniform scale other than (1, 1, 1), the physics shape gets incorrectly scaled (it's scaled down).

* The effect is worse the smaller the physics unit scale is set.
    * It's not really noticeable until the physics unit scale is 0.1 or less.
* Smaller shapes will be scaled down more, relatively.
* It appears to be a uniform down scaling on objects with any scale other than 1
    * i.e. A shape on an object with scale 1.01 or 0.99 is scaled down about as much as the one on an object with scale 10.

**To Reproduce:**
1. Set physics.type to "3D" in game.project.
2. Enable physics.debug in game.project.
3. Set physics.scale to 0.01 (or other small number) in game.project.
4. Make a game object with a uniform scale other than (1, 1, 1)
5. Add a box shape and a matching sprite or model so you can compare their sizes.
6. Run.
7. Switch the physics.scale to 1 and run again to see the difference.

**Expected behavior:**
3D physics shapes on objects with uniform scale should scale at the same rate.

**Defold version:**
1.2.169 - editor-alpha
Editor SHA1: e5389d28eab7bfdc5b8edccad637aadcd2832a29
Engine SHA1: 4ebe7a1d548eae2398717ed46f9d7d1b103d5503

**Platforms:**
Windows 7, build and run from editor.

**Minimal repro case project:**
[test model physics scaling.zip](https://github.com/defold/defold/files/4804773/test.model.physics.scaling.zip)

**Screenshots:**
physics_scale_small
physics_scale_1

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/physics/src/physics/physics_3d.cpp [hunk 1]
```diff
@@ -635,7 +635,7 @@ namespace dmPhysics
         switch(shape->getShapeType())
         {
             case SPHERE_SHAPE_PROXYTYPE:        return new btSphereShape(((btSphereShape*)shape)->getRadius()); break;
-            case BOX_SHAPE_PROXYTYPE:           return new btBoxShape(((btBoxShape*)shape)->getHalfExtentsWithoutMargin()); break;
+            case BOX_SHAPE_PROXYTYPE:           return new btBoxShape(((btBoxShape*)shape)->getHalfExtentsWithMargin()); break;
```
Comment (JCash) [inline engine/physics/src/physics/physics_3d.cpp:638]: Since the margin is removed within the constructor, we need the size including the margin.

**Review by britzl — APPROVED** [review]
Very simple fix!
