### PR TITLE
Display tile attributes error on scene

### LINKED ISSUE #10832: [Bug] Error creating animation with tilesource
### Expected behaviour
Nothing should happen

### Actual behaviour
Black Screen in viewport. Red fields in (Image, Tile Height, Tile Margin and Collision).

### Steps to reproduce

1. Create a tilesource file;
2. Add a spritesheet image file to Image field;
3. Add Tile Width;
4. Add Tile Height;
5. Press Enter while type Tile Height.

https://github.com/user-attachments/assets/653c97e4-3a66-461b-b70c-da16148c0b7a

<hr/>

<table>
<tr><td>Build time</td><td>2025-06-10T15:16:24.119609</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f56fcca509a9fa5350bf55f18d8c6087295a8cef</td></tr>
<tr><td>Defold engine sha</td><td>f56fcca509a9fa5350bf55f18d8c6087295a8cef</td></tr>
<tr><td>Defold version</td><td>1.10.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b7c9d58911974ffba3d22d65f9fe89ad"'>b7c9d58911974ffba3d22d65f9fe89ad</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) RX Vega 10 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 24.9.1.240813</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by sprocketc**
Display tile attributes error on the scene view, instead of throwing an exception.

Fixes #10832

### CODE REVIEW

File: editor/src/clj/editor/tile_source.clj [hunk 1]
```diff
@@ -540,7 +540,7 @@
             metrics (texture-set-gen/calculate-tile-metrics image-size properties collision-size)]
         (when metrics
           (merge properties metrics)))
-      (g/error-fatal "tile data could not be generated due to invalid values")))
+      (g/->error _node-id :image :fatal image-resource "tile data could not be generated due to invalid values")))
```
Comment (sprocketc) [inline editor/src/clj/editor/tile_source.clj:543]: When `calculateMetrics` returns null, we don't really know what the problem is. This would render the message to the scene, and would also stop the propagation of invalid tile-source-attributes. A more detailed validation message will probably be available on the properties pane.

**Comment by sprocketc** [comment]
See https://github.com/defold/defold/issues/10832#issuecomment-2974473482 to reproduce the issue.

**Review by matgis — APPROVED** [review]
LGTM!
