### PR TITLE
Fix pivot point related issues

### LINKED ISSUE #9699: The view bounding box frame in the editor when the pivot of the sprite is shifted.
### Expected behaviour
The sprite and bounding box frame visuals match.

### Actual behaviour
The only issue I found was a small bug in displaying the bounding box frame in the editor when the pivot of the sprite is shifted. I.e. frames are still shown as if the pivot remained in the centre of the sprite. Clicking on sprites and selecting objects works correctly.

### Steps to reproduce
Set pivot point for sprite in atlas and switch to scene with guides enabled.
<hr/>

<table>
<tr><td>Build time</td><td>2024-11-04T16:57:17.567609</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>8bf5994c5a1e0991b3627df3168a46831662cded</td></tr>
<tr><td>Defold engine sha</td><td>8bf5994c5a1e0991b3627df3168a46831662cded</td></tr>
<tr><td>Defold version</td><td>1.9.5</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.85</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Fixed issues related to pivot points:
	•	AABB for sprites with non-default pivots.
	•	Sprite position in the editor when using manual size and a custom pivot point.
	•	Fixed bounding boxes for sprites with custom pivot points.

Fix https://github.com/defold/defold/issues/9699

## PR checklist

* [x] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: editor/src/clj/editor/sprite.clj [hunk 1]
```diff
@@ -592,13 +592,24 @@
 
   (input copied-nodes g/Any :array :cascade-delete)
 
-  (output aabb AABB (g/fnk [size]
+  (output aabb AABB (g/fnk [size ^:try scene-infos]
```
Comment (AGulev) [inline editor/src/clj/editor/sprite.clj:595]: is it ok to have such connection?

File: editor/src/clj/editor/sprite.clj [hunk 2]
```diff
@@ -592,13 +592,24 @@
...
+                                                anim-pivot
+                                                [0.0 0.0])
                             half-width (* 0.5 width)
                             half-height (* 0.5 height)
-                            half-depth (* 0.5 depth)]
-                        (geom/make-aabb (Point3d. (- half-width) (- half-height) (- half-depth))
-                                        (Point3d. half-width half-height half-depth)))))
+                            half-depth (* 0.5 depth)
+
+                            ; Adjusted calculations for min-x and min-y
```
Comment (AGulev) [inline editor/src/clj/editor/sprite.clj:608]: Pivot should be taken into account when calculate AABB otherwise when you open scene with one sprite and custom pivot point, you don't see sprite on the scene

File: editor/src/clj/editor/texture_set.clj [hunk 3]
```diff
@@ -250,12 +250,15 @@
 
         ; Pivot point comes from the SpriteGeometry, where (0,0) is center of the image and +Y is up.
         [^double image-pivot-x ^double image-pivot-y] (or (:pivot animation-frame) [0.0 0.0])
-        image-pivot-x (* (or (:width animation-frame) 0.0) image-pivot-x)
-        image-pivot-y (* (or (:height animation-frame) 0.0) image-pivot-y)
+        [width height] (if (or (and (= :size-mode-manual size-mode)) (nil? animation-frame)) size [(:width animation-frame) (:height animation-frame)])
```
Comment (AGulev) [inline editor/src/clj/editor/texture_set.clj:253]: For manual size or if `animation-frame` doesn't exist, it's important to take `width` and `height` from size so position of the sprite to show sprite in the same position runtime shows

File: editor/src/clj/editor/texture_set.clj [hunk 4]
```diff
@@ -250,12 +250,15 @@
...
+        image-pivot-x (* width image-pivot-x)
+        image-pivot-y (* height image-pivot-y)
 
         position-data (:position-data out)
-        offset-positions (offset-vertices image-pivot-x image-pivot-y position-data)]
-    (assoc out :position-data offset-positions)))
+        line-data (:line-data out)
+        offset-positions (offset-vertices image-pivot-x image-pivot-y position-data)
+        offset-lines (offset-vertices image-pivot-x image-pivot-y line-data)]
```
Comment (AGulev) [inline editor/src/clj/editor/texture_set.clj:260]: Lines needed for bounding boxes representation, so we have to offset them too

File: editor/src/clj/editor/sprite.clj (hunk 1 above)
Comment (vlaaad) [reply editor/src/clj/editor/sprite.clj:595]: Yes! It's like a try-catch, but within the graph.

**Review by vlaaad — APPROVED** [review]
LGTM!
