### PR TITLE
Throw away any return values from the gui script

### LINKED ISSUE #5268: return in gui_script crashes engine
If you place a return statement in the main scope of a gui script and return any value, the engine crashes upon execution of the script. However, a return statement in a script, or module, does not have the same behavior. I stumbled into this while transpiling typescript to lua, as the transpiler will add a `return {}` for the exports in the module / script.

### Expected behaviour
No Operation / Silent Continue

### Actual behaviour
Engine crashes with:
`Assertion failed: top == lua_gettop(L), file ..\src\gui.cpp, line 4447`

### Steps to reproduce
- Create a new Gui
- Attach a Gui Script
- Put a `return` statement in the .gui_script within the script scope.
```lua
return {}
```
<hr/>

<table>
<tr><td>Build time</td><td>2020-10-07T09:43:17.766716</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18e7da2c4eea5d37a154d3bde088e161fc49186e</td></tr>
<tr><td>Defold engine sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold version</td><td>1.2.174</td></tr>
<tr><td>GPU</td><td>GeForce RTX 2070 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.38</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

> Minimal repro project
[gui-script-return-crash.zip](https://github.com/defold/defold/files/5358404/gui-script-return-crash.zip)

### PR DESCRIPTION
**Pull request by britzl**
We do not care about them. They are ignored in normal scripts and in the render script.

Fixes #5268

### CODE REVIEW

File: engine/gui/src/gui.cpp [hunk 1]
```diff
@@ -4409,7 +4409,7 @@ Result DeleteDynamicTexture(HScene scene, const dmhash_t texture_hash)
         lua_rawgeti(L, LUA_REGISTRYINDEX, script->m_InstanceReference);
         dmScript::SetInstance(L);
 
-        ret = dmScript::PCall(L, 0, LUA_MULTRET);
+        ret = dmScript::PCall(L, 0, 0);
```
Comment (JCash) [inline engine/gui/src/gui.cpp:4412]: Looks good.
Are there any other places we have the similar code in?
E.g. script_module.cpp:216 ?

**Review by JCash — APPROVED** [review]

File: engine/gui/src/gui.cpp (hunk 1 above)
Comment (britzl) [reply engine/gui/src/gui.cpp:4412]: That's true, in ReloadModule. But at least we're throwing away the values there.
