### PR TITLE
Fixed crash on Android when rebooting the engine

### LINKED ISSUE #10677: `sys.reboot()` crashing when building through bob.jar
**Describe the bug (REQUIRED)**
When restarting the application by using `sys.reboot()` crashes the application on specific device

**To Reproduce (REQUIRED)**
1. Call `sys.reboot()` function on any screen
2. Build using bob.jar

**Expected behavior (REQUIRED)**
Game to restart without crashing

**Defold version (REQUIRED):**
  - Version 1.10.1

**Platforms (REQUIRED):**
 - Platforms: Android 10
 - OS: MIUI version 12.5.1
 - Device: Xiaomi Redmi Note 7 pro

 - Platforms: Android 15
 - OS: 2.0.11.0.VMTMIXM
 - Device: Redmi Note 2

 - Platforms: Android 14
 - OS: Hyper OS
 - Device: Redmi 11

The game crashes in these devices

```
ERROR:CRASH: CALL STACK:

#00 pc 0x0000348ad0 ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#01 pc 0x0000004dd8 /system/bin/app_process64 <unknown>+0
#02 pc 0x000000063c [vdso] __kernel_rt_sigreturn+0
#03 pc 0x0000295244 ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#04 pc 0x0000294d08 ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#05 pc 0x00001285e4 ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#06 pc 0x0000128ee4 ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#07 pc 0x0000129a2c ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#08 pc 0x0000124b10 ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#09 pc 0x00002d32d8 ...BxBjeA==/lib/arm64/librestart.so <unknown>+0
#10 pc 0x00000e6894 ...oid.runtime/lib64/bionic/libc.so <unknown>+0
#11 pc 0x0000084b70 ...oid.runtime/lib64/bionic/libc.so <unknown>+0
````

**Build Script**
```
#!/bin/bash

title=$(less game.project | grep "^title = " | cut -d "=" -f2 | sed -e 's/^[[:space:]]*//')
title_no_space=$(echo -e "${title}" | tr -d '[[:space:]]')

echo "Building Project: ${title}"

bob() {
  java -jar ../bob.jar $@
}

echo "\n[:::::::::::::Cleaning:::::::::::::]"
rm -rf build
bob clean resolve distclean

# ANDROID
echo "\n[:::::::::::::Bundling Android:::::::::::::]"
bob \
  --settings=prod.settings\
  --strip-executable \
  --variant debug \
  --verbose \
  --bundle-format apk,aab \
  --bundle-output build/android \
  --platform armv7-android \
  --keystore ./debug.keystore \
  --keystore-pass ./debug.keystore.pass.txt \
  --archive build bundle
```

### PR DESCRIPTION
**Pull request by AGulev**
Fixed issue where `sys.reboot()` of the engine on Android may crash the game.

Fix https://github.com/defold/defold/issues/10677

### CODE REVIEW

**Comment by AGulev** [comment]
Should we cherry pick it into Beta?

File: external/glfw/lib/android/android_joystick.c [hunk 1]
```diff
@@ -68,7 +69,7 @@ static void glfwAndroidDisconnectJoystick(const int joystickIndex)
     if (_glfwJoy[joystickIndex].State != GLFW_ANDROID_GAMEPAD_DISCONNECTED)
     {
         _glfwJoy[joystickIndex].State = GLFW_ANDROID_GAMEPAD_DISCONNECTED;
-        _glfwJoy[joystickIndex].DeviceId = 0;
+        _glfwJoy[joystickIndex].DeviceId = DEVICE_ID_NONE;
```
Comment (AGulev) [inline external/glfw/lib/android/android_joystick.c:72]: Some devices may have ID 0 - in these cases, the logic breaks.

File: external/glfw/lib/android/android_window.c [hunk 2]
```diff
@@ -178,6 +178,8 @@ int _glfwPlatformOpenWindow( int width__, int height__,
         update_width_height_info(&_glfwWin, &_glfwWinAndroid, 1);
         computeIconifiedState();
     }
+    
+    _glfwTerminateJoysticks();
```
Comment (AGulev) [inline external/glfw/lib/android/android_window.c:182]: It's important to clean up the new static structure between restarts to make sure `DeviceId` isn't 0.

File: external/glfw/lib/android/android_joystick.c [hunk 3]
```diff
@@ -451,3 +452,19 @@ int _glfwPlatformGetJoystickDeviceId( int joy, char** device_id )
         return GL_TRUE;
     }
 }
+
+void _glfwTerminateJoysticks( void )
```
Comment (britzl) [inline external/glfw/lib/android/android_joystick.c:456]: Not sure about the name. `Terminate` doesn't feel quite right. `Reset` is maybe more appropriate?

File: external/glfw/lib/android/android_window.c (hunk 2 above)
Comment (britzl) [reply external/glfw/lib/android/android_window.c:182]: Why did it start crashing btw? The code hasn't changed in a long time?

**Comment by britzl** [comment]
> Should we cherry pick it into Beta?

Yes I think so

**Review by britzl — CHANGES_REQUESTED** [review]
See question about naming.

File: external/glfw/lib/android/android_joystick.c (hunk 3 above)
Comment (AGulev) [reply external/glfw/lib/android/android_joystick.c:456]: this name is from `internal.h` we already use for linux.
Ofc. I can rename it, but it feels like extra work without a reason

File: external/glfw/lib/android/android_window.c (hunk 2 above)
Comment (AGulev) [reply external/glfw/lib/android/android_window.c:182]: It's a good question, I'm not entirely sure.
Maybe this one https://github.com/defold/defold/pull/10541
or maybe this one https://github.com/defold/defold/pull/10229
not sure

File: external/glfw/lib/android/android_joystick.c (hunk 3 above)
Comment (AGulev) [reply external/glfw/lib/android/android_joystick.c:456]: I mean, this isn't something I introduce: https://github.com/defold/defold/blob/3e5846cf3ee9577d3ba37a10b2bb4d526fbf5d3f/external/glfw/lib/internal.h#L293-L295

Comment (britzl) [reply external/glfw/lib/android/android_joystick.c:456]: Ah, that settles it then. I thought it was something new. 👍

**Review by britzl — APPROVED** [review]
