### PR TITLE
Issue 5567: Fixed Android and HTML5 window creation on older devices

### LINKED ISSUE #5567: OpenGLES 3 alpha issues
https://forum.defold.com/t/opengles-3-alpha-testing/67495/4?u=mathias_westerdahl

* Android version parsing issue (on devices that don't support `GL_MAJOR_VERSION`)

* HTML5 WebGL 1 fallback issue
  * Repro: run latest chrome with `chrome.exe --disable-webgl2`

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/glfw/js/library_glfw.js [hunk 1]
```diff
@@ -658,7 +658,13 @@ var LibraryGLFW = {
       depth: (GLFW.params[0x00020009] > 0), // GLFW_DEPTH_BITS
       stencil: (GLFW.params[0x0002000A] > 0) // GLFW_STENCIL_BITS
     };
+
+    // Browser.createContext: https://github.com/emscripten-core/emscripten/blob/master/src/library_browser.js#L312
     Module.ctx = Browser.createContext(Module['canvas'], true, true, contextAttributes);
+    if (Module.ctx == null) {
+      contextAttributes.majorVersion = 1; // Try WebGL 1
+      Module.ctx = Browser.createContext(Module['canvas'], true, true, contextAttributes);
+    }
```
Comment (JCash) [inline engine/glfw/js/library_glfw.js:667]: Also added an issue with Emscripten here:
https://github.com/emscripten-core/emscripten/issues/13501

**Review by britzl — APPROVED** [review]
