### PR TITLE
Fixed issue for DirectInput gamepads with multiple POV's

### LINKED ISSUE #8585: vJoy causes engine crash
vJoy is a virtual joystick software. See more details here:
https://www.vjoy.org/

Report from user:
"I have vJoy installed and activated, and the game (demo) does not start (i.e., it starts and quits immediately).
Problem solved when disabling the vJoy driver."

Crash log:
[engine_crash_log.txt](https://github.com/defold/defold/files/14383917/engine_crash_log.txt)

Symbols:
[dmengine.zip](https://github.com/defold/defold/files/14383925/dmengine.zip)

This happens in 1.6.4 4d724 and the user is on Windows 10.

### LINKED ISSUE #8621: Game crash on sartup, depending on input device
### Summary
Game crashes on startup if some non-standart input devices pluged in to PC.

It happens in Debug build and on Release build either.
According to our crash reporter, I can conclude, that about 1-3% of players have variations of this issue using different devices (physical, or virtual) plugged into PC.

### Steps to reproduce
Way I use to reproduce:
Configure VJoy as shown here: https://www.youtube.com/watch?v=Mf8e4GnZCS4
Then any Defold game will failed to run.
Message I on empty progect:
```
WARNING:INPUT: No gamepad map found for gamepad 0 (vJoy Device). The raw gamepad map will be used.
Assertion failed: button_index == 0, file ..\src\native\hid_gamepad_driver_dinput.cpp, line 491
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\ivanv\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF7FC5CEB60 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144

ERROR:CRASH:  1 0x7FF7FC6A7BD0 raise minkernel\crts\ucrt\src\appcrt\misc\signal.cpp:547

ERROR:CRASH:  2 0x7FF7FC68D1E8 abort minkernel\crts\ucrt\src\appcrt\startup\abort.cpp:71

ERROR:CRASH:  3 0x7FF7FC64D510 common_assert_to_stderr<wchar_t> minkernel\crts\ucrt\src\appcrt\startup\assert.cpp:186

ERROR:CRASH:  4 0x7FF7FC64DC94 _wassert minkernel\crts\ucrt\src\appcrt\startup\assert.cpp:443

ERROR:CRASH:  5 0x7FF7FC4BED50 dmHID::DInputUpdate D:\a\defold\defold\engine\hid\src\native\hid_gamepad_driver_dinput.cpp:491

ERROR:CRASH:  6 0x7FF7FC4BDA20 dmHID::Update D:\a\defold\defold\engine\hid\src\native\hid_native.cpp:297

ERROR:CRASH:  7 0x7FF7FC2360B0 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1500

ERROR:CRASH:  8 0x7FF7FC236D70 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2110

ERROR:CRASH:  9 0x7FF7FC236FA0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83

ERROR:CRASH: 10 0x7FF7FC22F600 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148

ERROR:CRASH: 11 0x7FF7FC637B44 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

ERROR:CRASH: 12 0x7FFE54CA2560 BaseThreadInitThunk <unknown>:0

ERROR:CRASH: 13 0x7FFE5548AA30 RtlUserThreadStart <unknown>:0
```

### P.S.
When Vjoy is configured, every game on Defold will failed to start (tested on Craftomation 101, Warnament, BORE BLASTERS and empty progect)

Allso happen with **VKBsim Gunfighter MCG Ultimate Twist** device and some others.
<hr/>

<table>
<tr><td>Build time</td><td>2023-09-19T14:37:53.306910</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bb52dfb7281ef2b03c3462e9a4205abd69fb11b1</td></tr>
<tr><td>Defold engine sha</td><td>00352cc02f24c12e6081245c0d5fb2e0b263d05e</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 551.61</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/8621
Fixes https://github.com/defold/defold/issues/8585

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/hid/src/native/hid_gamepad_driver_dinput.cpp [hunk 1]
```diff
@@ -490,8 +490,6 @@ namespace dmHID
                     packet.m_Hat[hat_index] = hat_state;
                     hat_index++;
 
-                    assert(button_index == 0);
```
Comment (JCash) [inline engine/hid/src/native/hid_gamepad_driver_dinput.cpp:493]: It seems we were previously lucky that we had 1 POV, and that it came first in the list.

**Review by Jhonnyg — APPROVED** [review]
