### PR TITLE
Fixed an issue where the `sys.open_url()` function did not work

### LINKED ISSUE #10164: sys.open_url() do not work in Defold version 1.9.7 (iOS build)
**Describe the bug (REQUIRED)**
sys.open_url() do not work in Defold version 1.9.7

**To Reproduce (REQUIRED)**
Build any project for iOS with exec of
sys.open_url("https://www.googlr.com")

**Expected behavior (REQUIRED)**
Nothing to happens

**Defold version (REQUIRED):**
  - Version 1.9.7

**Platforms (REQUIRED):**
 iOS

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

### PR DESCRIPTION
**Pull request by AGulev**
Fixed an issue on iOS where a deprecated function was used for URL opening, causing it to not work on iOS and iPadOS.

Fix https://github.com/defold/defold/issues/10164

### CODE REVIEW

File: engine/dlib/src/dlib/sys_cocoa.mm [hunk 1]
```diff
@@ -163,16 +163,11 @@ Result GetLogPath(char* path, uint32_t path_len)
...
-        }
-        else
-        {
-            return RESULT_UNKNOWN;
-        }
+        NSString* ns_str = [NSString stringWithUTF8String:url];
+        NSURL* ns_url = [NSURL URLWithString:ns_str];
+        UIApplication *app = [UIApplication sharedApplication];
+        [app openURL:ns_url options:@{} completionHandler:nil];
+        return [app canOpenURL:ns_url] ? RESULT_OK : RESULT_UNKNOWN;
```
Comment (AGulev) [inline engine/dlib/src/dlib/sys_cocoa.mm:170]: The new `openURL` function is asynchronous, so we can't get a result the same way we did before, but we can use another function to check if URL can be opened or not, and return this info instead.

**Review by britzl — APPROVED** [review]
