### PR TITLE
Preserve changes-view on failed "git status"

### LINKED ISSUE #6623: Error when creating or removing any component on Ubuntu
Editor shows error everytime I create or remove any component in Assets pane.

### Expected behaviour
No error pop-ups.

### Actual behaviour
Error pop-ups when creating or removing any component.

### Steps to reproduce

<hr/>

When creating a component (after I select a name and click Create...)

<table>
<tr><td>Build time</td><td>2022-05-19T08:42:50.389319</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0832b77da0244865a81a3d1fc7246006"'>0832b77da0244865a81a3d1fc7246006</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-41-generic</td></tr>
<table>

<hr/>

When removing a component (after I click Delete):

<table>
<tr><td>Build time</td><td>2022-05-19T08:42:50.389319</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0acec0436a6941308a8bb45e10819872"'>0acec0436a6941308a8bb45e10819872</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-41-generic</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
When `git status` fails during project startup, `make-changes-view` will
return `nil`. This makes it throw NPEs on creating and deleting files,
but not during resource sync that checks for changes-view nullability.
I think resource sync only makes it easier to test it since
other places in code expect `changes-view` to exist. With these changes,
exceptions during `git status` execution will be shown to the user on
resource sync, creation, and deletion of files.

I think this behavior will be better than the current one because
the shown exception is more relevant to the user. For example, in the
related issue the exception looks like that:
```
Malformed input or input contains unmappable characters: /home/pjarosz4/Desktop/witchcrafter/assets/images/gui/backpack_bg ��� kopia.png
```
The user can solve this error.

Fixes #6623

### CODE REVIEW

File: editor/src/clj/editor/changes_view.clj [hunk 1]
```diff
@@ -189,30 +189,30 @@
...
+        (log/error :exception e)))
+    (.addListener disk-availability/available-property disk-available-listener)
+    (ui/on-closed! (.. parent getScene getWindow)
+                   (fn [_]
+                     (.removeListener disk-availability/available-property disk-available-listener)))
+    (ui/observe-selection list-view
+                          (fn [_ _]
+                            (ui/refresh-bound-action-enabled! diff-button)
+                            (ui/refresh-bound-action-enabled! revert-button)))
+    view-id))
```
Comment (vlaaad) [inline editor/src/clj/editor/changes_view.clj:218]: It's not super clear by this diff what the change is: I localized the try/catch block only to git-related code.

**Review by matgis — APPROVED** [review]
Nice find. Looks good to me!
