### PR TITLE
Texture resource now owns the loaded memory until it's finished loading

### LINKED ISSUE #10074: Defold 1.9.7 Causing Crash dump with monarch+loading images
**Describe the bug (REQUIRED)**
When using monarch and then loading an image the game instantly crashes. Unsure if monarch has anything related to it as the app will run fine when the images are removed. However once you try to load an image the app will crash on start up.

[Monarch](https://github.com/britzl/monarch)

**To Reproduce (REQUIRED)**
1. Have Monarch extension setup
2. Have a screen with a large image (at least 512x1024)
3. Build app

**Expected behavior (REQUIRED)**
The app builds with no error.

**Defold version (REQUIRED):**
  - Version 1.9.7

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Minimal repro case project (OPTIONAL):**
Repo: [https://github.com/Qwarr/Def1.9.7Break](https://github.com/Qwarr/Def1.9.7Break)

**Logs (OPTIONAL):**
Crash dump logs _crash and _crash.dmp
[_crash.zip](https://github.com/user-attachments/files/18473956/_crash.zip)

ERROR:CRASH: CALL STACK:
ERROR:CRASH:  0 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  1 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  2 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  3 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  4 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  5 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  6 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  7 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  8 0x7FFFE2FFC760 DrvPresentBuffers <unknown>:0
ERROR:CRASH:  9 0x7FFFE2BF7BB5 <unknown symbol> <unknown>:0
ERROR:CRASH: 10 0x7FFFE2D2AFDD <unknown symbol> <unknown>:0
ERROR:CRASH: 11 0x7FFFE2D2F853 <unknown symbol> <unknown>:0
ERROR:CRASH: 12 0x7FFFE2D3071A <unknown symbol> <unknown>:0
ERROR:CRASH: 13 0x7FFFE2D3CCD2 <unknown symbol> <unknown>:0
ERROR:CRASH: 14 0x7FFFE2B926C3 <unknown symbol> <unknown>:0
ERROR:CRASH: 15 0x7FFFE2D595DA <unknown symbol> <unknown>:0
ERROR:CRASH: 16 0x7FFFE2D5918E <unknown symbol> <unknown>:0
ERROR:CRASH: 17 0x7FFFE2FCC1A0 DrvValidateVersion <unknown>:0
ERROR:CRASH: 18 0x7FF84CA37360 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 19 0x7FF84CC3CC70 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

**Additional context (OPTIONAL):**
With larger projects it always crashes, but the Minimal repro case project sometimes will compile correctly but rebuilding will often fail.

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/10074

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/resources/res_texture.cpp [hunk 1]
```diff
@@ -329,10 +330,11 @@ namespace dmGameSystem
         return result;
     }
 
-    static ImageDesc* CreateImage(dmGraphics::HContext context, dmGraphics::TextureImage* texture_image, uint8_t* image_bytes)
+    static ImageDesc* CreateImage(dmGraphics::HContext context, dmGraphics::TextureImage* texture_image, uint8_t* memory, uint8_t* image_bytes)
     {
         ImageDesc* image_desc = new ImageDesc;
         memset(image_desc, 0x0, sizeof(ImageDesc));
+        image_desc->m_Memory = memory;
```
Comment (JCash) [inline engine/gamesys/src/gamesys/resources/res_texture.cpp:337]: Let's hold the memory until we've uploaded it all.

File: engine/resource/src/async/load_queue_sync.cpp [hunk 2]
```diff
@@ -72,6 +72,12 @@ namespace dmLoadQueue
         *buffer_size = request->m_BufferSize;
         *resource_size = request->m_ResourceSize;
         *buf = buffer->Begin();
+
+        if (load_result->m_BufferOwnershipTransferred)
+        {
+            // we reset the dmArray (size = 0, capacity = 0)
+            memset((void*)buffer, 0, sizeof(*buffer));
```
Comment (JCash) [inline engine/resource/src/async/load_queue_sync.cpp:79]: Might introduce a dmArray::Release() later on.

**Review by Jhonnyg — DISMISSED** [review]
Looks good! Maybe we want a test for this? Seeing as the current ones didn't catch the issue
