### PR TITLE
Issue-6307 Fix ANR: `SCREEN_OFF` when `android.app.NativeActivity.unloadNativeCode`

### LINKED ISSUE #6307: ANR: `android.intent.action.SCREEN_OFF` when `android.app.NativeActivity.unloadNativeCode `
**Describe the bug (REQUIRED)**
ANR:

ANR:
```
  #00  pc 000000000004b60c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #00  pc 000000000004f3b8  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144)
  #00  pc 00000000000af610  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+60)
  #00  pc 0000000000234ef4  /data/app/~~PyRd0sEEoYX9pOmEeFXkTQ==/YSAgJUgOHdIWB4azikSanw==/lib/arm64/libGameProject.so (???)
  #00  pc 00000000000b55ec  /system/lib64/libandroid_runtime.so (android::NativeCode::~NativeCode()+48)
  #00  pc 00000000000b4dcc  /system/lib64/libandroid_runtime.so (android::unloadNativeCode_native(_JNIEnv*, _jobject*, long)+24)
  at android.app.NativeActivity.unloadNativeCode (Native method)
  at android.app.NativeActivity.onDestroy (NativeActivity.java:198)
  at android.app.Activity.performDestroy (Activity.java:8468)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1344)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5660)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5720)
  at android.app.ActivityThread.handleRelaunchActivityInner (ActivityThread.java:6023)
  at android.app.ActivityThread.handleRelaunchActivity (ActivityThread.java:5942)
  at android.app.servertransaction.ActivityRelaunchItem.execute (ActivityRelaunchItem.java:69)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2325)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8633)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
  ```

**To Reproduce (REQUIRED)**

**Defold version (REQUIRED):**
  - Version 1.2.191

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Android 6-11
 - Device: Samsung S10

**Logs (OPTIONAL):**

[bad.txt](https://github.com/defold/defold/files/7814759/bad.txt)

### PR DESCRIPTION
**Pull request by AGulev**
Fix https://github.com/defold/defold/issues/6307

### CODE REVIEW

File: engine/engine/src/engine_main.cpp [hunk 1]
```diff
@@ -104,7 +108,12 @@ int engine_main(int argc, char *argv[])
     g_AndroidApp->onInputEvent = glfwAndroidHandleInput;
 
     // Wait for window to become ready (APP_CMD_INIT_WINDOW in handleCommand)
-    WaitForWindow();
+    if (!WaitForWindow())
+    {
+        // When phone lock/unlock app may receive APP_CMD_DESTROY without APP_CMD_INIT_WINDOW
+        // in this case app should exit immidiatly
```
Comment (JCash) [inline engine/engine/src/engine_main.cpp:114]: typo: `immediately`

**Review by JCash — DISMISSED** [review]
Great find! 👏

File: engine/engine/src/engine_main.cpp (hunk 1 above)
Comment (AGulev) [reply engine/engine/src/engine_main.cpp]: thx, fixed!
