### PR TITLE
Fixed missing tracking when doing layout of glyphs

### LINKED ISSUE #11673: GUI Text Tracking works in editor preview but not in runtime
**Describe the bug (REQUIRED)**
The Text Tracking parameter for GUI Text nodes does not affect rendering in runtime.
In the editor (scene view/preview) tracking is displayed correctly, but when running the game the text is rendered with default spacing as if tracking is always 0.

**Expected behavior (REQUIRED)**
GUI Text Text Tracking should affect letter spacing in runtime exactly the same way it appears in the editor.

**Defold version (REQUIRED):**
  - Version 1.12.0 beta
Image

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Win 11
 - Device: PC

**Additional context (OPTIONAL):**
I'm attaching a screen

**editor**
Image

**runtime**
Image

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/11673

### Technical changes

Fixes a regression where the tracking was removed or not scaled properly.
Added test that checks for added dimensions of a layout when using tracking or leading.

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/font/src/test/test_font.cpp [hunk 1]
```diff
@@ -352,6 +352,92 @@ TEST_F(FontTest, LayoutExplicitDoubleLineBreaks)
...
+    // Legacy tracking scales by line height, Skribidi scales by font size.
+    float expected_tracking = 0.0f;
+#if defined(FONT_USE_SKRIBIDI)
+    // Skribidi interprets tracking in pixels based on font size.
+    expected_tracking = tracking_value * settings.m_Size;
+#else
+    // Legacy uses line height (font metrics scaled by size) for tracking.
+    float scale = FontGetScaleFromSize(m_Font, settings.m_Size);
+    expected_tracking = tracking_value * line_height * scale;
+#endif
```
Comment (JCash) [inline engine/font/src/test/test_font.cpp:411]: In the new implementation, we use font size as the scaling factor (seems to be the standard way).
Our old implementation used the line height.

File: engine/font/src/text_layout_legacy.cpp [hunk 2]
```diff
@@ -154,7 +154,7 @@ static float GetLineTextMetrics(TextGlyph* glyphs, uint32_t row_start, uint32_t
 
     float row_start_x = glyphs[0].m_X;
     float extent_last = monospace ? (last.m_Advance + padding) : (last.m_Advance);
-    float width = last.m_X - row_start_x + (n-1) * tracking + extent_last;
+    float width = last.m_X - row_start_x + extent_last;
```
Comment (JCash) [inline engine/font/src/text_layout_legacy.cpp:157]: The tracking should be added to the glyphs themselves.

File: engine/font/src/text_layout_legacy.cpp [hunk 3]
```diff
@@ -198,14 +196,20 @@ TextResult TextLayoutLegacyCreate(HFontCollection collection,
     HFont font = FontCollectionGetFont(collection, 0);
     float scale = FontGetScaleFromSize(font, settings->m_Size);
 
+    uint32_t ascent = (uint32_t)FontGetAscent(font, 1.0f);
+    uint32_t descent = (uint32_t)FontGetDescent(font, 1.0f); // positive value
+    uint32_t line_height = ascent + descent;
+    float line_height_scaled = line_height * scale;
+    float tracking = line_height_scaled * settings->m_Tracking;
```
Comment (JCash) [inline engine/font/src/text_layout_legacy.cpp:203]: Use the tracking value when doing the layout.

File: engine/font/src/text_layout_legacy.cpp [hunk 4]
```diff
@@ -198,14 +196,20 @@ TextResult TextLayoutLegacyCreate(HFontCollection collection,
...
     FontGlyphOptions options;
     options.m_Scale = 1.0f; // Return in points
     options.m_GenerateImage = false;
 
     uint32_t num_whitespaces = 0;
     // Lay them all out in a single line, using points
-    uint32_t x = 0;
-    uint32_t y = 0; // the legacy "shaping" doesn't support Y offsets
+    float x = 0;
+    float y = 0; // the legacy "shaping" doesn't support Y offsets
```
Comment (JCash) [inline engine/font/src/text_layout_legacy.cpp]: Old issue, which popped up when writing the unit test.
The glyphs were clamped to pixel borders.

File: engine/font/src/text_layout_skribidi.cpp [hunk 5]
```diff
@@ -84,11 +84,13 @@ static bool LayoutText(LayoutContext* ctx,
...
     params.flags              = 0;
 
+    float tracking = settings->m_Tracking * settings->m_Size;
+
     // TODO: Allo setting default as italic etc
     const skb_attribute_t attributes[] = {
         skb_attribute_make_font(SKB_FONT_FAMILY_DEFAULT, settings->m_Size, SKB_WEIGHT_NORMAL, SKB_STYLE_NORMAL, SKB_STRETCH_NORMAL),
         skb_attribute_make_line_height(SKB_LINE_HEIGHT_METRICS_RELATIVE, settings->m_Leading),
-        skb_attribute_make_spacing(settings->m_Tracking, 0.0f)
+        skb_attribute_make_spacing(tracking, 0.0f)
```
Comment (JCash) [inline engine/font/src/text_layout_skribidi.cpp:93]: Use the actual pixel size value.

File: engine/font/src/text_layout_skribidi.cpp [hunk 6]
```diff
@@ -205,7 +207,7 @@ static bool LayoutText(LayoutContext* ctx,
         uint32_t glyph_index = layout->m_Glyphs.Size();
 
         TextLine l;
-        l.m_Width   = line->bounds.width;
+        l.m_Width   = line->bounds.width - (tracking > 0 ? tracking : 0);
```
Comment (JCash) [inline engine/font/src/text_layout_skribidi.cpp:210]: To keep the bounds tight, remove the last added tracking

File: engine/font/src/text_layout_skribidi.cpp [hunk 7]
```diff
@@ -215,8 +217,14 @@ static bool LayoutText(LayoutContext* ctx,
...
     skb_rect2_t layout_bounds = skb_layout_get_bounds(skblayout);
-    layout->m_Width = layout_bounds.width;
+    layout->m_Width = layout_bounds.width - (tracking > 0 ? tracking : 0);
     layout->m_Height = layout_bounds.height;
+    if (lines_count > 0 && settings->m_Leading > 0.0f)
+    {
+        // Normalize Skribidi line height so leading affects only inter-line spacing.
+        float base_line_height = layout_bounds.height / ((float)lines_count * settings->m_Leading);
+        layout->m_Height = layout_bounds.height - base_line_height * (settings->m_Leading - 1.0f);
+    }
```
Comment (JCash) [inline engine/font/src/text_layout_skribidi.cpp:227]: Same with bounds height, remove the last added extra leading.

File: engine/font/src/text_layout_legacy.cpp (hunk 4 above)
Comment (AGulev) [reply engine/font/src/text_layout_legacy.cpp]: hmm, shouldn't it be regulated by subpixels checkbox in game.project->labels? https://github.com/defold/defold/issues/8064

**Review by AGulev — DISMISSED** [review]
LGTM!

File: engine/font/src/text_layout_legacy.cpp (hunk 4 above)
Comment (JCash) [reply engine/font/src/text_layout_legacy.cpp]: Or probably with the font itself.
I'll revert this particular change for now as it'll mess with pixel fonts currently.
