### PR TITLE
Show informative error message on cyclic resource dependencies

### LINKED ISSUE #3919: Cycle detected on node type editor.collection/CollectionNode
Exception:

```
{:cause
 "Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets\n(not (contains? (:in-production ctx) [node-id label]))",
 :via
 [{:type java.util.concurrent.ExecutionException,
   :message
   "java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets\n(not (contains? (:in-production ctx) [node-id label]))",
   :at [java.util.concurrent.FutureTask report "FutureTask.java" 122]}
  {:type java.lang.AssertionError,
   :message
   "Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets\n(not (contains? (:in-production ctx) [node-id label]))",
   :at [internal.node$in_production invokeStatic "node.clj" 1280]}],
 :trace
 [[internal.node$in_production invokeStatic "node.clj" 1280]
  [internal.node$in_production invoke "node.clj" 1279]
  [editor.collection$CollectionNode$behavior$build_targets invokeStatic "collection.clj" 419]
  [editor.collection$CollectionNode$behavior$build_targets invoke "collection.clj" 419]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_first_input_value invokeStatic "node.clj" 1093]
  [internal.node$pull_first_input_value invoke "node.clj" 1088]
  [editor.factory$FactoryNode$behavior$build_targets invokeStatic "factory.clj" 86]
  [editor.factory$FactoryNode$behavior$build_targets invoke "factory.clj" 86]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_first_input_value invokeStatic "node.clj" 1093]
  [internal.node$pull_first_input_value invoke "node.clj" 1088]
  [editor.game_object$ReferencedComponent$behavior$build_targets invokeStatic "game_object.clj" 143]
  [editor.game_object$ReferencedComponent$behavior$build_targets invoke "game_object.clj" 143]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_input_values$fn__21050 invoke "node.clj" 1109]
  [clojure.core$mapv$fn__6953 invoke "core.clj" 6627]
  [clojure.lang.PersistentVector reduce "PersistentVector.java" 341]
  [clojure.core$reduce invokeStatic "core.clj" 6544]
  [clojure.core$mapv invokeStatic "core.clj" 6618]
  [clojure.core$mapv invoke "core.clj" 6618]
  [internal.node$pull_input_values invokeStatic "node.clj" 1107]
  [internal.node$pull_input_values invoke "node.clj" 1104]
  [editor.game_object$GameObjectNode$behavior$build_targets invokeStatic "game_object.clj" 278]
  [editor.game_object$GameObjectNode$behavior$build_targets invoke "game_object.clj" 278]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_first_input_value invokeStatic "node.clj" 1093]
  [internal.node$pull_first_input_value invoke "node.clj" 1088]
  [editor.collection$ReferencedGOInstanceNode$behavior$build_targets invokeStatic "collection.clj" 262]
  [editor.collection$ReferencedGOInstanceNode$behavior$build_targets invoke "collection.clj" 262]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_input_values$fn__21050 invoke "node.clj" 1109]
  [clojure.core$mapv$fn__6953 invoke "core.clj" 6627]
  [clojure.lang.PersistentVector reduce "PersistentVector.java" 341]
  [clojure.core$reduce invokeStatic "core.clj" 6544]
  [clojure.core$mapv invokeStatic "core.clj" 6618]
  [clojure.core$mapv invoke "core.clj" 6618]
  [internal.node$pull_input_values invokeStatic "node.clj" 1107]
  [internal.node$pull_input_values invoke "node.clj" 1104]
  [editor.collection$CollectionNode$behavior$build_targets invokeStatic "collection.clj" 419]
  [editor.collection$CollectionNode$behavior$build_targets invoke "collection.clj" 419]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_first_input_value invokeStatic "node.clj" 1093]
  [internal.node$pull_first_input_value invoke "node.clj" 1088]
  [editor.collection$CollectionInstanceNode$behavior$build_targets invokeStatic "collection.clj" 492]
  [editor.collection$CollectionInstanceNode$behavior$build_targets invoke "collection.clj" 492]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_input_values$fn__21050 invoke "node.clj" 1109]
  [clojure.core$mapv$fn__6953 invoke "core.clj" 6627]
  [clojure.lang.PersistentVector reduce "PersistentVector.java" 341]
  [clojure.core$reduce invokeStatic "core.clj" 6544]
  [clojure.core$mapv invokeStatic "core.clj" 6618]
  [clojure.core$mapv invoke "core.clj" 6618]
  [internal.node$pull_input_values invokeStatic "node.clj" 1107]
  [internal.node$pull_input_values invoke "node.clj" 1104]
  [editor.collection$CollectionNode$behavior$build_targets invokeStatic "collection.clj" 419]
  [editor.collection$CollectionNode$behavior$build_targets invoke "collection.clj" 419]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$pull_input_values$fn__21050 invoke "node.clj" 1109]
  [clojure.core$mapv$fn__6953 invoke "core.clj" 6627]
  [clojure.lang.PersistentVector reduce "PersistentVector.java" 341]
  [clojure.core$reduce invokeStatic "core.clj" 6544]
  [clojure.core$mapv invokeStatic "core.clj" 6618]
  [clojure.core$mapv invoke "core.clj" 6618]
  [internal.node$pull_input_values invokeStatic "node.clj" 1107]
  [internal.node$pull_input_values invoke "node.clj" 1104]
  [editor.game_project$GameProjectNode$behavior$build_targets invokeStatic "game_project.clj" 207]
  [editor.game_project$GameProjectNode$behavior$build_targets invoke "game_project.clj" 207]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 268]
  [internal.node$node_value_STAR_ invokeStatic "node.clj" 335]
  [internal.node$node_value_STAR_ invoke "node.clj" 330]
  [internal.node$node_value invokeStatic "node.clj" 357]
  [internal.node$node_value invoke "node.clj" 350]
  [dynamo.graph$node_value invokeStatic "graph.clj" 742]
  [dynamo.graph$node_value invoke "graph.clj" 712]
  [editor.defold_project$build invokeStatic "defold_project.clj" 306]
  [editor.defold_project$build invoke "defold_project.clj" 300]
  [editor.defold_project$build_and_write invokeStatic "defold_project.clj" 368]
  [editor.defold_project$build_and_write invoke "defold_project.clj" 358]
  [editor.defold_project$build_and_save_project$fn__31456 invoke "defold_project.clj" 587]
  [clojure.core$binding_conveyor_fn$fn__4676 invoke "core.clj" 1938]
  [clojure.lang.AFn call "AFn.java" 18]
  [java.util.concurrent.FutureTask run "FutureTask.java" 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
  [java.lang.Thread run "Thread.java" 745]]}
```

This is a cyclic dependency which means that you for instance have a collection containing a collection proxy or factory which directly or indirectly references itself, thus creating a dependency loop.

### LINKED ISSUE #4893: Cycle detected on node type editor.code.script/ScriptNode
### Expected behaviour
The game builds successfully
### Actual behaviour
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.code.script/ScriptNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
### Steps to reproduce
I don't have any particular steps. I am trying to build from the editor (ctrl+ b), At some point, I started to get this error, even though I didn't touch anything apart from my lua modules.
I am able to bundle windows application successfully (if I choose bundle instead of build).

I am aware of issue [ #121](https://github.com/defold/editor2-issues/issues/121) but my problem doesn't seem to be related to collections.
<hr/>

<table>
<tr><td>Build time</td><td>2020-06-09T06:32:34.184948</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>77864a400bc9028a176a63308e7a82507577c351</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f067cde7127d4351af857529055af111"'>f067cde7127d4351af857529055af111</a></td></tr>
<tr><td>GPU</td><td>GeForce RTX 2060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 431.65</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #6724: Cycle detected on node type editor.game-object/GameObjectNode
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-19T08:43:47.250124</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c03a8b1c853c436fbd77bf1f007e015b"'>c03a8b1c853c436fbd77bf1f007e015b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context FireGL 19.50.32.02 26.20.15032.2015</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

The code I was using is this:`function on_input(self, action_id, action)
	if action.x and action.y then
		local pos = vmath.vector3(action.x, action.y, 1)
		go.set_position(vmath.vector3(action.x, action.y, 1))
		house_id = factory.create("#housefactory", pos)
	end
end`

### PR DESCRIPTION
**Pull request by britzl**
Cyclic resource dependencies in the editor did not show a user friendly error message. The message did in fact seem to indicate an error with the editor rather than with the project structure. This change detect cyclic dependencies and shows a popup with an improved error message to clearly indicate the problem to the developer.

Fixes #4893 
Fixes #3919
Fixes #6724

### CODE REVIEW

**Comment by britzl** [comment]
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

File: editor/src/clj/editor/app_view.clj [hunk 1]
```diff
@@ -790,13 +791,40 @@
...
+(defn- owning-resource [basis node-id]
+  (when-some [owning-resource-node-id (core/scope-of-type basis node-id resource-node/ResourceNode)]
+             [owning-resource (resource-node/resource basis owning-resource-node-id)]
+    owning-resource))
+
+(defn- get-cycle-detected-help-message
+  [node-type-name node-id]
+  (let [basis (g/now)
+        proj-path (some-> (owning-resource basis node-id) resource/proj-path)
+        resource-path (some? proj-path) proj-path "'unknown'"]
```
Comment (britzl) [inline editor/src/clj/editor/app_view.clj:803]: I'm always getting "unknown" here. Not sure if I have adapted the initial code snippet from @matgis correctly?

File: editor/src/clj/internal/node.clj [hunk 2]
```diff
@@ -1334,11 +1334,14 @@
...
-  (assert (not (contains? (:in-production evaluation-context) (gt/endpoint node-id label)))
-          (format "Cycle detected on node type %s and output %s"
-                  (node-type-name node-id evaluation-context)
-                  label))
-  (update evaluation-context :in-production conj (gt/endpoint node-id label)))
+  (if (contains? (:in-production evaluation-context) (gt/endpoint node-id label))
+    (throw (ex-info (format "Cycle detected on node type %s and output %s"
+                      (node-type-name node-id evaluation-context)
+                      label)
+                    {:cause "cycle-detected"
```
Comment (matgis) [inline editor/src/clj/internal/node.clj:1341]: These kind of "comparable strings" that are typically used as an enum are preferably expressed as [keywords](https://clojure.org/reference/data_structures#Keywords). Keywords are readable as strings but their strings are interned in a shared storage and comparisons are extremely cheap as a result.
```suggestion
                    {:cause :cycle-detected
```

File: editor/src/clj/internal/node.clj [hunk 3]
```diff
@@ -1334,11 +1334,14 @@
...
+                     :node-type-name (node-type-name node-id evaluation-context)
```
Comment (matgis) [inline editor/src/clj/internal/node.clj:1342]: I don't think we need to add the `:node-type-name` here. We can get the node type from the `node-id` when we generate the error message in `get-cycle-detected-help-message` above.

File: editor/src/clj/editor/app_view.clj [hunk 4]
```diff
@@ -790,13 +791,40 @@
...
+    (case node-type-name
+      "editor.collection/CollectionNode" (format "This is caused by a two or more collections referenced in a loop from either collection proxies or collection factories. One of the involved resources is: %s." resource-path)
+      "editor.game-object/GameObjectNode" (format "This is caused by two or more game objects referenced in a loop from game object factories. One of the involved resources is: %s." resource-path)
+      "editor.code.script/ScriptNode" (format "This is caused by two or more Lua modules required in a loop. One of the involved resources is: %s." resource-path)
+      (format "This is caused by two or more resources referenced in a loop. One of the involved resources is: %s." resource-path))))
+
```
Comment (matgis) [inline editor/src/clj/editor/app_view.clj:809]: We can resolve the node type keyword from the `node-id` and add some whitespace here to make it more readable. This also lets us remove the `node-type-name` argument.

```suggestion
    (case (g/node-type-kw basis node-id)
      :editor.collection/CollectionNode
      (format "This is caused by a two or more collections referenced in a loop from either collection proxies or collection factories. One of the involved resources is: %s." resource-path)

      :editor.game-object/GameObjectNode
      (format "This is caused by two or more game objects referenced in a loop from game object factories. One of the involved resources is: %s." resource-path)

      :editor.code.script/ScriptNode
      (format "This is caused by two or more Lua modules required in a loop. One of the involved resources is: %s." resource-path)

      (format "This is caused by two or more resources referenced in a loop. One of the involved resources is: %s." resource-path))))
```

File: editor/src/clj/editor/app_view.clj [hunk 5]
```diff
@@ -790,13 +791,40 @@
                                 :text "If the engine is already running, shut down the process manually and retry"}]}
            :content (.getMessage e)})))))
 
+(defn- owning-resource [basis node-id]
+  (when-some [owning-resource-node-id (core/scope-of-type basis node-id resource-node/ResourceNode)]
+             [owning-resource (resource-node/resource basis owning-resource-node-id)]
+    owning-resource))
+
+(defn- get-cycle-detected-help-message
+  [node-type-name node-id]
```
Comment (matgis) [inline editor/src/clj/editor/app_view.clj:800]: We don't really need the `node-type-name` as an argument here. See below.

```suggestion
  [node-id]
```

File: editor/src/clj/editor/app_view.clj [hunk 6]
```diff
@@ -790,13 +791,40 @@
...
+      (catch clojure.lang.ExceptionInfo e
+        (if (= "cycle-detected" (-> e ex-data :cause))
+          (ui/run-later
+            (dialogs/make-info-dialog
+              {:title "Build Error"
+               :icon :icon/triangle-error
+               :header "Cyclic resource dependency detected"
+               :content {:fx/type fxui/label
+                         :style-class "dialog-content-padding"
+                         :text (get-cycle-detected-help-message (-> e ex-data :node-type-name) (-> e ex-data :node-id))}}))
```
Comment (matgis) [inline editor/src/clj/editor/app_view.clj:826]: We don't need to supply the `node-type-name` here - we can resolve it from the `node-id`.

```suggestion
                         :text (get-cycle-detected-help-message (-> e ex-data :node-id))}}))
```

**Review by matgis — CHANGES_REQUESTED** [review]
I made some suggestions for changes. You'll need to test if this works, but I think it should resolve some issues at least. 😅

**Comment by britzl** [comment]
Screenshot 2023-01-10 at 22 36 28

**Review by matgis — APPROVED** [review]
Looks good to me!
