### PR TITLE
Tilegrid render entries are now properly submitted

### LINKED ISSUE #6629: Crash when processing invalid render entries
The frustum culling task modified the behavior of the render entries list.
We need to keep that array compact, and in this case the `dmRender::RenderListSubmit()`-logic was a bit flawed.

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_tilegrid.cpp [hunk 1]
```diff
@@ -805,8 +805,8 @@ namespace dmGameSystem
             }
         }
 
-        if (render_list != write_ptr)
-            dmRender::RenderListSubmit(render_context, render_list, write_ptr);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_tilegrid.cpp:809]: The `RenderListAlloc()` must nowadays be matched with a call to `RenderListSubmit()`
