### PR TITLE
Restored old windows library logic, with more exceptions for new libs made with cmake

### LINKED ISSUE #11533: `libs: [*_null]` added to `*-win32` targets when checking `Exclude *` boxes in the `App Manifest` editor
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)
--  No.<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
When checking an `Exclude *` (`Exclude Profiler` `Exclude Sound` etc.) box in the `App Manifest` editing page, a `*_null` will be added into the `context: libs` arrays of `x86-win32` and `x86_64-win32` targets, rather than a `lib*_null.lib`, which will cause a link error when building a project using the generated `*.appmanifest` file.

**To Reproduce (REQUIRED)**
1. Open `Defold Editor`, create an `App Manifest` file and open it
2. Check the box `Exclude Record`
3. `libs: [record_null]` shown on `x86-win32` and `x86_64-win32` target
4. Save the `App Manifest` file, set the `game.project -> Native Extension -> App Manifest` field to this file, and then save the `game.project` file
5. Build the project on a Windows PC
6. See the build error `lld-link: error: could not open 'record_null.lib': No such file or directory`

**Expected behavior (REQUIRED)**
1. `libs: [librecord_null.lib]` shown on `x86-win32` and `x86_64-win32` targets when checking the `Exclude Record` box
2. Project built successfully

**Defold version (REQUIRED):**
<table>
<tr><td>Build time</td><td>2025-11-20T16:56:22.246280</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>758e7b2ea4646d43a37a9387733100bf9ccc6185</td></tr>
<tr><td>Defold engine sha</td><td>758e7b2ea4646d43a37a9387733100bf9ccc6185</td></tr>
<tr><td>Defold version</td><td>1.12.0</td></tr>
</table>

**Platforms (REQUIRED):**
<table>
<tr><td>GPU</td><td>AMD Radeon(TM) 880M Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 25.10.250611</td></tr>
<tr><td>Java version</td><td>25+36-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Minimal repro case project (OPTIONAL):**
[Empty Project.zip](https://github.com/user-attachments/files/23697296/Empty.Project.zip)

**Logs (OPTIONAL):**

**Workaround (OPTIONAL):**
Change `*_null` to `lib*_null.lib` manually

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/11533

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: editor/src/clj/editor/app_manifest.clj [hunk 1]
```diff
@@ -57,15 +57,31 @@
...
 
 (def custom-lib-names
-  {:x86-win32 {"vulkan" "vulkan-1"}
-   :x86_64-win32 {"vulkan" "vulkan-1"}})
+  {:x86-win32 {"hid" "hid"
+               "hid_null" "hid_null"
+               "input" "input"
+               "platform" "platform"
+               "platform_null" "platform_null"
+               "platform_vulkan" "platform_vulkan"
```
Comment (JCash) [inline editor/src/clj/editor/app_manifest.clj:65]: Ofc much more annoying, but quickest fix out of this issue.

**Review by vlaaad — DISMISSED** [review]
LGTM!

**Review by vlaaad — APPROVED** [review]
