### PR TITLE
Crash fix for when overriding a texture on a sprite

### LINKED ISSUE #8343: 1.6.3-beta - Crash when changing sprite atlas
**Describe the bug**
Changing a sprite's atlas via `go.set("#sprite", "image", self.my_image)` causes the following crash:

```
ERROR:CRASH: CALL STACK:

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x2dcf65) [0x564909adff65]

ERROR:CRASH: /lib64/libc.so.6(+0x3dbb0) [0x7f6c9a85fbb0]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x25e352) [0x564909a61352]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0xbfb6b) [0x5649098c2b6b]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x57157) [0x56490985a157]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x3b970) [0x56490983e970]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x3bfa5) [0x56490983efa5]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x3838f) [0x56490983b38f]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x382f5) [0x56490983b2f5]

ERROR:CRASH: /lib64/libc.so.6(+0x27b8a) [0x7f6c9a849b8a]

ERROR:CRASH: /lib64/libc.so.6(__libc_start_main+0x8b) [0x7f6c9a849c4b]

ERROR:CRASH: /home/haath/workspace/icaria/build/x86_64-linux/dmengine(+0x3811e) [0x56490983b11e]

ERROR:CRASH: 
```

This appeared after updating to `1.6.3-beta`, I verified that the issue is not present on `1.6.2`.

**To Reproduce**
Project zip which reproduces the issue is attached.

[repro.zip](https://github.com/defold/defold/files/13737480/repro.zip)

Line `3070` in `main.lua` is the one that changes the sprite's atlas, you can observe that if it is commented out there is no crash.

**Defold version:**
  - Version **1.6.3-beta** `4e42322`

**Platforms:**
 - Platforms: Linux
 - OS: Fedora

 - Device: PC

### PR DESCRIPTION
**Pull request by JCash**
This fixes an issue when the sprite image is overridden at runtime.

FIxes https://github.com/defold/defold/issues/8343

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -292,7 +292,8 @@ namespace dmGameSystem
         if (!overrides)
             return;
 
-        dmHashUpdateBuffer32(state, overrides->m_Material, sizeof(MaterialResource*));
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:295]: When the material is not overridden, but one of the textures are.

File: engine/gamesys/src/gamesys/test/test_gamesys.cpp [hunk 2]
```diff
@@ -992,6 +992,8 @@ TEST_F(SpriteTest, FrameCount)
     dmGameObject::HInstance go = Spawn(m_Factory, m_Collection, "/sprite/frame_count/sprite_frame_count.goc", dmHashString64("/go"), 0, 0, Point3(0, 0, 0), Quat(0, 0, 0, 1), Vector3(1, 1, 1));
     ASSERT_NE((void*)0, go);
 
+    WaitForTestsDone(100, 0);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/test/test_gamesys.cpp:995]: Was missing the update+render test

**Review by Jhonnyg — DISMISSED** [review]
