### PR TITLE
Do not create a DNS channel on iOS

### LINKED ISSUE #5287: iOS: Defold HTTP API usage results in request for permission to connect to local network
**Describe the bug**
When trying to use the internal HTTP API (https://defold.com/ref/http/) in a project on iOS, there's a popup that asks the user for permission to access the local network: "app would like to find and connect to devices on your local network" (example: https://i.redd.it/jqgbfblvwi651.jpg).
This happens, even if the HTTP server I'm trying to access is publicly (as in: not on my local network) available.

Could this have something to do with the way Defold internally handles dns resolution?

**To Reproduce**
- `http.request("https://www.google.com", "GET", function() end)` on an iOS 14 device (not sure about Simulator).

**Expected behavior**
Local network access is not really needed, so there should be no popup.

**Defold version:** 1.2.174

**Platforms:**
I believe this issue is iOS 14 only.

### PR DESCRIPTION
**Pull request by britzl**
Use getaddrinfo() and don't wait for the thread to finish at shutdown.

Fixes #5287

### CODE REVIEW

File: engine/script/src/http_service.cpp [hunk 1]
```diff
@@ -394,14 +394,28 @@ namespace dmHttpService
...
-                worker->m_DNSChannel = 0;
-            }
+// Do not create a c-ares DNS channel on iOS
+// If we have no DNS channel we will fall back to POSIX getaddrinfo
+// c-ares DNS resolution will trigger a Network Security popup on most
+// residential WiFi setups since the WiFi router will act as a DNS and forward
+// DNS queries to the DNS of the ISP.
+// This will trigger the Network Security popup since c-ares communicates with
+// the router over the local network.
+// getaddrinfo on the other hand seems to be whitelisted in iOS.
```
Comment (JCash) [inline engine/script/src/http_service.cpp:407]: 👍

**Review by JCash — DISMISSED** [review]
Looks good!
