### PR TITLE
Issue 5315: Live update now properly uses the updated archive in thsame session

### LINKED ISSUE #5315: Live update (non-zip) archive isn't updated and used after downloading assets.
We found a regression in liveupdate while testing the beta, using the regular liveupdate download code path:

https://forum.defold.com/t/defold-1-2-175-beta/66679/19

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/liveupdate/src/liveupdate.cpp [hunk 1]
```diff
@@ -474,13 +433,18 @@ printf("MAWE: StoreManifest: %p  algorithm: %d\n", manifest, (int)algorithm);
         dmResourceArchive::SetNewArchiveIndex(archive_container, new_index, mem_mapped);
     }
 
-    const dmResource::Manifest* GetCurrentManifest()
+    void SetNewManifest(dmResource::Manifest* manifest)
```
Comment (JCash) [inline engine/liveupdate/src/liveupdate.cpp:430]: Since we're creating a new manifest on the fly at runtime, we also need a new way to hook it up with the resource factory.

File: engine/liveupdate/src/liveupdate.cpp [hunk 2]
```diff
@@ -560,8 +524,17 @@ printf("MAWE: StoreManifest: %p  algorithm: %d\n", manifest, (int)algorithm);
...
+                if (dmResourceArchive::RESULT_NOT_FOUND != result)
+                {
+                    LUCleanup_Regular(archive_name, app_path, app_support_path);
+                    g_LiveUpdate.m_ArchiveType = -1;
+                }
+                else
+                {
+                    // We might download a manifest later, so we shouldn't clean the currently downloaded archive.
+                    // This is the behavior from 1.2.174 and before.
+                    result = dmResourceArchive::RESULT_OK;
```
Comment (JCash) [inline engine/liveupdate/src/liveupdate.cpp:530]: This was a use case I hadn't considered, that it is possible to download new resources, but not a new manifest.

File: engine/liveupdate/src/liveupdate.cpp [hunk 3]
```diff
@@ -634,6 +607,51 @@ printf("MAWE: StoreManifest: %p  algorithm: %d\n", manifest, (int)algorithm);
...
+        }
+
+        dmStrlCpy(manifest->m_ArchiveIndex->m_ArchiveFileIndex->m_Path, lu_data_path, DMPATH_MAX_PATH);
+        dmLogInfo("Live Update archive: %s", manifest->m_ArchiveIndex->m_ArchiveFileIndex->m_Path);
+
+        manifest->m_ArchiveIndex->m_ArchiveFileIndex->m_FileResourceData = f_lu_data;
+
+        manifest->m_ArchiveIndex->m_Loader.m_Unload = LUUnloadArchive_Regular;
+        manifest->m_ArchiveIndex->m_Loader.m_FindEntry = LUFindEntryInArchive_Regular;
+        manifest->m_ArchiveIndex->m_Loader.m_Read = LUReadEntryFromArchive_Regular;
```
Comment (JCash) [inline engine/liveupdate/src/liveupdate.cpp:644]: For it to function, it also needs the functions to traverse its data.

**Review by britzl — DISMISSED** [review]
