### PR TITLE
Fix for calculating size of sprite vertex buffer data

### LINKED ISSUE #8402: Crash if atlas has sprites with trim mode.
**Describe the bug (REQUIRED)**
If I turn-on trim mode for a few sprites in atlas the engine crashes on start

**To Reproduce (REQUIRED)**
Run test project
if it doesn't crash change trim mode for a few spritese in atlas: 
image

**Expected behavior (REQUIRED)**
no crash

**Defold version (REQUIRED):**
  - 1.6.3 (1.6.2 was fine)

**Platforms (REQUIRED):**
 - Platforms: macOS

**Minimal repro case project (OPTIONAL):**
[colorside.zip](https://github.com/defold/defold/files/13929371/colorside.zip)

**Logs (OPTIONAL):**
```
INFO:CRASH: Successfully wrote Crashdump to file: /Users/agulev/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH: 0   dmengine                            0x0000000103239658 _ZN7dmCrash7OnCrashEi + 104

ERROR:CRASH: 1   libsystem_platform.dylib            0x000000018cf7ba24 _sigtramp + 56

ERROR:CRASH: 2   ???                                 0xffff80010d65f388 0x0 + 18446603340740948872

ERROR:CRASH: 3   AppleMetalOpenGLRenderer            0x000000010d65f388 _ZN15GLRResourceList11addResourceEP11GLRResource + 44

ERROR:CRASH: 4   AppleMetalOpenGLRenderer            0x000000010d695dec _ZN13GLDContextRec27prepareResourceForGPUAccessEP11GLRResourcej12PipelineType + 196

ERROR:CRASH: 5   AppleMetalOpenGLRenderer            0x000000010d66ff14 _ZN13GLDContextRec22addRenderPassResourcesEv + 136

ERROR:CRASH: 6   AppleMetalOpenGLRenderer            0x000000010d6701cc _ZN13GLDContextRec15beginRenderPassEv + 628

ERROR:CRASH: 7   AppleMetalOpenGLRenderer            0x000000010d686094 _ZL20gldRenderVertexArrayP13GLDContextRecjjiijPKviS2_ + 480

ERROR:CRASH: 8   GLEngine                            0x00000001f5107b50 glDrawElements_GL3Exec + 288

ERROR:CRASH: 9   dmengine                            0x000000010323da20 _ZN10dmGraphicsL18OpenGLDrawElementsEPvNS_13PrimitiveTypeEjjNS_4TypeEm + 184

ERROR:CRASH: 10  dmengine                            0x00000001030eb978 _ZN8dmRender4DrawEPNS_13RenderContextEPNS_9PredicateEPNS_19NamedConstantBufferE + 952

ERROR:CRASH: 11  dmengine                            0x00000001030eb548 _ZN8dmRender14DrawRenderListEPNS_13RenderContextEPNS_9PredicateEPNS_19NamedConstantBufferEPKNS_14FrustumOptionsE + 2960

ERROR:CRASH: 12  dmengine                            0x00000001030edd8c _ZN8dmRender13ParseCommandsEPNS_13RenderContextEPNS_7CommandEj + 616

ERROR:CRASH: 13  dmengine                            0x00000001030f2a2c _ZN8dmRender26UpdateRenderScriptInstanceEPNS_20RenderScriptInstanceEf + 136

ERROR:CRASH: 14  dmengine                            0x0000000103002120 _ZN8dmEngine4StepEPNS_6EngineE + 948

ERROR:CRASH: 15  dmengine                            0x0000000103002670 _Z14dmEngineUpdatePN8dmEngine6EngineE + 32

ERROR:CRASH: 16  dmengine                            0x0000000103003088 _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE + 104

ERROR:CRASH: 17  dmengine                            0x000000010300300c _Z11engine_mainiPPc + 88

ERROR:CRASH: 18  dyld                                0x000000018cbd10e0 start + 2360

ERROR:CRASH: 
```

**Workaround (OPTIONAL):**
Do not use trim mode

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/8402

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -1582,17 +1582,27 @@ namespace dmGameSystem
...
+            for (uint32_t i = 0; i < textures.m_NumTextures; ++i)
+            {
+                textures.m_Resources[i] = GetTextureSet(component, i);
+                textures.m_TextureSets[i] = textures.m_Resources[i]->m_TextureSet;
+            }
+
+            // Get the correct animation frames, and other meta data
+            ResolveAnimationData(&textures, component->m_CurrentAnimation, component->m_CurrentAnimationFrame);
+
+            if (!CanUseQuads(&textures))
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:1603]: The if statement didn't match the one used at render time, so the buffer was too small, and we made a buffer overrun.

I think eventually, we need to better check the actual end pointer of the buffer to make sure we can avoid this type of issues.

**Review by Jhonnyg — DISMISSED** [review]
