### PR TITLE
Fix issue with window focus on macOS Sonoma (14.0)

### LINKED ISSUE #8066: editor: Game window not automatically focused in 1.6.0 (stable) on Mac OS
**Describe the bug**
When running a game with Cmd+B on Mac, the game window does not focus in 1.6.0
Working as expected in 1.5.0

**To Reproduce**
Download `Defold-arm64-macos.dmg` from 1.6.0 (stable) - https://github.com/defold/defold/releases/tag/1.6.0
Build and run an empty project with Cmd+B.
Observe game window is not focused.

Download `Defold-arm64-macos.dmg` from 1.5.0 (stable) - https://github.com/defold/defold/releases/tag/1.5.0
Build and run an empty project with Cmd+B.
Observe game window is focused as expected.

**Expected behavior**
The game window focuses when run

**Defold version**
1.6.0

**Platforms:**
macOS (arm)

### PR DESCRIPTION
**Pull request by AGulev**
Fixed issue when on macOS Sonoma (14.0) game window started without focus on it.

Fix https://github.com/defold/defold/issues/8066

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/glfw/lib/cocoa/cocoa_init.m [hunk 1]
```diff
@@ -243,6 +243,19 @@ int _glfwPlatformInit( void )
...
+    if (CFURLCopyResourcePropertyForKey(bundleUrl, kCFURLTypeIdentifierKey, &uti, NULL) &&
+        uti && UTTypeConformsTo(uti, kUTTypeApplicationBundle))
+    {
+        _glfwLibrary.Unbundled = GL_FALSE;
+    } 
+    else
+    {
+        _glfwLibrary.Unbundled = GL_TRUE;
+    }
+
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_init.m:258]: This code detects if it's bundled application (app) or not (run executable from terminal for example)

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 2]
```diff
@@ -132,14 +132,39 @@ - (void)applicationDidUpdate:(NSNotification *)notification
     // Wait for the first update to make window inactive and then activate it again
     // It helps to avoid issue when the window opens inactive
     // https://github.com/defold/defold/issues/6709
-    if( !_glfwLibrary.Unbundled ) {
-        ProcessSerialNumber psn = { 0, kCurrentProcess };
-        TransformProcessType( &psn, kProcessTransformToBackgroundApplication );
-        [self performSelector:@selector(activateProcess) withObject:nil afterDelay:0.1];
-        _glfwLibrary.Unbundled = GL_TRUE;
+    if( _glfwLibrary.FirstUpdate )
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:135]: Run only once

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 3]
```diff
@@ -132,14 +132,39 @@ - (void)applicationDidUpdate:(NSNotification *)notification
...
+    {
+        // Starting from macOS Sonoma (14.0) it should be solved in two different ways depends 
+        // if it's bundled app or not
+        // https://github.com/defold/defold/issues/8066
+        NSOperatingSystemVersion version = [[NSProcessInfo processInfo] operatingSystemVersion];
+        if (version.majorVersion < 14)
+        {
+            [self deactivateProcess];
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:143]: for macOS < 14 we keep everything as it was

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 4]
```diff
@@ -132,14 +132,39 @@ - (void)applicationDidUpdate:(NSNotification *)notification
...
+        else
+        {
+            if ( _glfwLibrary.Unbundled )
+            {
+                [self deactivateProcess];
+            }
+            else
+            {
+                [self activateWindow];
+            }
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:154]: on newer macos it should be activated in two different ways depends on if it's bundled or not

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 5]
```diff
@@ -150,9 +175,21 @@ - (void)activateProcess
...
+    }
     [[NSRunningApplication currentApplication] activateWithOptions:(NSApplicationActivateAllWindows | NSApplicationActivateIgnoringOtherApps)];
 }
 
+// macos 12+
+// https://sector7.computest.nl/post/2022-08-process-injection-breaking-all-macos-security-layers-with-a-single-vulnerability/
+- (BOOL)applicationSupportsSecureRestorableState:(NSApplication *)app
+{
+    return YES;
+}
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:191]: another warning in terminal, it's not directly related but it's nice to fix it all together

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 6]
```diff
@@ -646,6 +683,7 @@ int  _glfwPlatformOpenWindow( int width, int height,
     _glfwWin.context = nil;
     _glfwWin.aux_context = nil;
     _glfwWin.delegate = nil;
+    _glfwLibrary.FirstUpdate = GL_TRUE;
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:686]: reset every time we open window

File: engine/glfw/lib/cocoa/cocoa_window.m (hunk 5 above)
Comment (JCash) [reply engine/glfw/lib/cocoa/cocoa_window.m:191]: It mentions macos 12. We support BigSur which is 11, will it work?

**Review by JCash — APPROVED** [review]

File: engine/glfw/lib/cocoa/cocoa_window.m (hunk 5 above)
Comment (AGulev) [reply engine/glfw/lib/cocoa/cocoa_window.m:191]: I think so, because it's just a function in delegate. I can put any function with any name there, so on macos < 12 it should be just a never called function
