### PR TITLE
Additional fixes to root-level game object transforms inside referenced collections when building from the editor

### LINKED ISSUE #7519: object transforms incorrect in windows build
After migrate the project to 1.4.4 I've noticed that one objects has started to look inccorect in windows build (ctrl+B from the Editor), but looks ok in the Editor and in HTML5 build.

This is the wagon placed as collection into the main level collection. (All objects in the game assembled from quad meshes with texture).

How it look in the Editor:

In HTML5:

In Windows build:

I have extracted this object into a small reprocase:
[repocase.zip](https://github.com/defold/defold/files/11103037/repocase.zip)

perhaps this issue depends on this changes: https://github.com/defold/defold/pull/7504 
<hr/>

<table>
<tr><td>Build time</td><td>2023-03-28T13:52:21.403123</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9257a31358dc9a612a8c2b70a6caf3154832a321</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 517.02</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Fixes #7519
(Regression introduced by #7504)

### User-facing changes
* Additional fixes to root-level game object transforms inside referenced collections when building from the editor.

### CODE REVIEW

File: editor/src/clj/editor/pose.clj [hunk 1]
```diff
@@ -223,10 +223,10 @@
     (cond-> child-pose
 
             parent-scaled
-            (assoc :scale (multiply-vector child-scale parent-scale))
+            (assoc :scale (multiply-vector parent-scale child-scale))
```
Comment (matgis) [inline editor/src/clj/editor/pose.clj:226]: Order doesn't matter when multiplying vectors, but it looks better as the function is called `pre-multiply` and it also corresponds to argument order of the `multiply-quaternion` call (where the order *does* matter!) below.

File: editor/test/editor/pose_test.clj [hunk 2]
```diff
@@ -165,10 +169,17 @@
   (is (= (pose/euler-rotation-pose 0.0 -40.0 0.0)
          (pose/pre-multiply (pose/euler-rotation-pose 0.0 -10.0 0.0)
                             (pose/euler-rotation-pose 0.0 -30.0 0.0))))
-  (is (= (pose/euler-rotation-pose 45.0 45.0 45.0)
-         (-> (pose/euler-rotation-pose 0.0 45.0 0.0)
-             (pose/pre-multiply (pose/euler-rotation-pose 0.0 0.0 45.0))
-             (pose/pre-multiply (pose/euler-rotation-pose 45.0 0.0 0.0)))))
+  (is (= (pose/rotation-pose -0.6615634399999999 -0.24966735999999995 -0.2496673599999999 0.6615634400000001)
+         (pose/pre-multiply (pose/rotation-pose -0.5 -0.5 -0.4999999999999999 0.5000000000000001)
+                            (pose/rotation-pose 0.0 0.41189608 0.0 0.9112308))))
```
Comment (matgis) [inline editor/test/editor/pose_test.clj:174]: Actual values from the scene where this issue was discovered.

File: editor/test/editor/pose_test.clj [hunk 3]
```diff
@@ -165,10 +169,17 @@
...
+  (is (= [-90.0 135.0 0.0]
+         (round-euler-rotation
+           (pose/pre-multiply (pose/euler-rotation-pose 0.0 90.0 0.0)
+                              (pose/euler-rotation-pose 45.0 0.0 90.0)))))
+  (is (= [3.342 103.606 68.165]
+         (round-euler-rotation
+           (pose/pre-multiply (pose/euler-rotation-pose 45.0 45.0 45.0)
+                              (pose/euler-rotation-pose 10.0 20.0 30.0)))))
```
Comment (matgis) [inline editor/test/editor/pose_test.clj:182]: Added tests where we pre-multiply poses with rotation around multiple axises at once.

File: editor/src/clj/editor/math.clj [hunk 4]
```diff
@@ -147,6 +147,9 @@
 (defn quat->euler [^Quat4d quat]
   (quat-components->euler (.getX quat) (.getY quat) (.getZ quat) (.getW quat)))
 
+(defn clj-quat->euler [[^double x ^double y ^double z ^double w]]
+  (quat-components->euler x y z w))
+
```
Comment (matgis) [inline editor/src/clj/editor/math.clj:152]: Utility function added for use in tests.

**Review by vlaaad — APPROVED** [review]
Ship it!
