### PR TITLE
Fix rare multipage atlas issue with compressed textures (HTML5).

### LINKED ISSUE #8030: Paged atlas compression issue in web build
**Describe the bug (REQUIRED)**
Similar issue: https://github.com/defold/defold/issues/7628
Enabling texture compression breaks the rendering of a multi-paged atlas sprite in web build (black rectangles/random atlas parts).
When builded without texture compression issue doesn't reproduce.
Looks like issue reproduces on android and windows old intel gpu.

**To Reproduce (REQUIRED)**
1. Open example project
2. Bundle for web with and without texture compression
3. Check build on old intel gpu/android
4. Paged version of sprite will be in some way broken

**Expected behavior (REQUIRED)**
Multi-page atlases with texture compression renders correctly.

**Defold version (REQUIRED):**
  - Version 1.4.8 stable https://github.com/defold/defold/commit/504de7800fa81847bfc2e26a21973899db9dd747

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Android/Windows
 - Device: realme GT Master Edition and other

**Minimal repro case project (OPTIONAL):**
[repo.zip](https://github.com/defold/defold/files/12700418/repo.zip)

**Screenshots (OPTIONAL):**
Repo:
Compressed
compressed
Uncompressed
uncompressed

Windows player:
windows_1

Android player:
android_3

**Additional context (OPTIONAL):**
We collect some data from our players. Looks like broken sprites reproduces on old intel gpu and black sprites reproduces on android devices.
Here some additional info:
[user_info.txt](https://github.com/defold/defold/files/12700501/user_info.txt)

### PR DESCRIPTION
**Pull request by AGulev**
Some old devices don't work with multipage atlases if texture transcoded to ASTC format. For such devices, ASTC will be marked as non-supported format and the next best fits will be used (most of the time it will be ETC2). 

Fix https://github.com/defold/defold/issues/8030

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 1]
```diff
@@ -1087,6 +1089,33 @@ static void LogFrameBufferError(GLenum status)
...
+                DMGRAPHICS_COMPRESSED_TEX_IMAGE_3D(GL_TEXTURE_2D_ARRAY, 0, DMGRAPHICS_TEXTURE_FORMAT_RGBA_ASTC_4x4_KHR, 4, 4, 2, 0, 32, &fakeZeroBuffer);
+                GLint err = glGetError();
+                if (err != 0) 
+                {
+                     compressedTexImageSupported = false;
+                }
+                glDeleteTextures(1, &texture);
+            }
+            if (!compressedTexImageSupported) {
+                context->m_TextureFormatSupport &= ~(1 << TEXTURE_FORMAT_RGBA_ASTC_4x4);
```
Comment (AGulev) [inline engine/graphics/src/opengl/graphics_opengl.cpp:1115]: Remove ASTC support from supported texture compressions

**Review by Jhonnyg — APPROVED** [review]
👍
