### PR TITLE
Refresh Bundle menu on editor script reload

### LINKED ISSUE #10060: Reloading an editor script does not affect menu items
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
If an editor script defines a menu option (at least in the Project->Bundle menu) and this script is changed and reloaded the change does not always take effect immediately.

**To Reproduce (REQUIRED)**
1. Create an editor script which defines a bundle menu option
2. Make a change to the script
3. Reload it
4. Immediately do Project->Bundle->Your Option
5. Notice that the change hasn't taken effect

Note that if the user does some other interaction in the editor before using the menu option it does work as expected.

**Expected behavior (REQUIRED)**
The menu option should immediately take effect on reloading, regardless of user action

**Defold version (REQUIRED):**
  - 1.9.7

### PR DESCRIPTION
**Pull request by vlaaad**
This changeset fixes an editor UI glitch where refreshing the Bundle menu after editor script reload needed an extra click to see the new bundle commands.

Fixes #10060

### CODE REVIEW

File: editor/src/clj/editor/editor_extensions.clj [hunk 1]
```diff
@@ -563,9 +563,9 @@
 (defn- re-create-ext-state [initial-state evaluation-context]
   (let [{:keys [rt display-output!]} initial-state]
     (->> (e/concat
+           [bundle-editor-script-prototype]
            (:library-prototypes initial-state)
-           (:project-prototypes initial-state)
-           [bundle-editor-script-prototype])
+           (:project-prototypes initial-state))
```
Comment (vlaaad) [inline editor/src/clj/editor/editor_extensions.clj:568]: Not related to the issue: loading the built-in editor script first displays the usual bundle menu items before the ones defined by extensions.

**Review by matgis — APPROVED** [review]
LGTM!
