### PR TITLE
Fix issue when backspace holding doesn't work on iOS

### LINKED ISSUE #6613: iOS keyboard repeats only once or twice
**Describe the bug**
Hello, there’s a problem on iOS when entering/deleting text. When I try to add/delete characters using standard iOS keyboard and holding down a key it repeats it only once or twice.

**To Reproduce**
1. Create empty mobile game project
2. Add .gui and .gui_script files
3. In .gui add a font and a text node
4. In .gui_script add this code and assign gui_script to corresponding .gui:
```
function init(self)
  msg.post(".", “acquire_input_focus”)
  self.message = “label”
  self.node = gui.get_node(“text”)
  gui.show_keyboard(gui.KEYBOARD_TYPE_DEFAULT, false)
end

function on_input(self, action_id, action)
  if action_id == hash(“text”) then
    self.message = self.message … action.text
    gui.set_text(self.node, self.message)
  elseif action_id == hash(“backspace”) and action.repeated then
    local l = string.len(self.message)
    self.message = string.sub(self.message, 0, l-1)
    gui.set_text(self.node, self.message)
  end
end
```
5. In game.input_binding add key trigger Backspace: backspace and text trigger Text: text
6. In main.script leave only this:
```
function init(self)
  msg.post("@render:", “use_fixed_fit_projection”, { near = -1, far = 1 })
end
```
7. In main.collection add .gui component file to go
8. Create an iOS bundle
9. Deploy to real device, I use ios-deploy for example

**Expected behavior**
I expect to see characters added/deleted continuously when holding down a key.

**Defold version:**
  - Version 1.3.2

**Platforms:**
 - Platforms: iOS
 - OS: iOS 14.4.1
 - Device: iPhone 7

**Minimal repro case project:**
[prototype.zip](https://github.com/defold/defold/files/8713848/prototype.zip)

Additional info:
I tried some ways to solve it, like increasing/decreasing repeat interval/repeat delay in game.project, or removing action.repeated, the only thing it does is decrease/increase amount of characters added/deleted at one time, then it stops repeating either way

### PR DESCRIPTION
**Pull request by AGulev**
This fix makes it possible to remove multiple symbols if a user holds `backspace` button instead of a single tap - a single character removing.

Fix https://github.com/defold/defold/issues/6613

### CODE REVIEW

**Review by britzl — APPROVED** [review]
What a lovely little hack! If it works it works, but it ain't pretty!

**Comment by AGulev** [comment]
>What a lovely little hack! If it works it works, but it ain't pretty!

I know ( I don't like it either

File: engine/glfw/lib/ios/app/BaseView.m [hunk 1]
```diff
@@ -477,6 +488,7 @@ - (void)deleteBackward
         [markedText setString:@""];
         _glfwSetMarkedText("");
     } else {
+        _glfwInputKey( GLFW_KEY_BACKSPACE, GLFW_RELEASE );
```
Comment (AGulev) [inline engine/glfw/lib/ios/app/BaseView.m:491]: hack out repeat system to make sure we remove a bit faster then currently possible
there is no long press event for virtual keyboard
