### PR TITLE
Correct animation preview speed on high refresh rate screens

### LINKED ISSUE #5075: Animations are played at incorrect speed when Editor is launched and used on a 144Hz monitor.
**Describe the bug (REQUIRED)**

I have 3-monitor setup:
Main one - 144Hz
Secondary 1 - 144Hz
Secondary 2 - 60Hz

When I launch and use Defold editor on my main monitor all animations that I play from atlas are played at much faster rate than they should be.

When I move Defold editor to secondary monitor that is 60Hz animations are playing at expected speed.

**To Reproduce (REQUIRED)**

1. Create new project from "Movement tutorial"
2. Open `assets/sprites.atlas`
3. Click on `spaceship` animation in Outline
4. Click `View -> Play` 
5. Observe animation

**Expected behavior (REQUIRED)**

When I play animation in Defold editor it should play at configured FPS, regardless of what monitor I use.

**Defold version (REQUIRED):**
  - Version 1.2.171

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10
 - Device: N/A

**Minimal repro case project (OPTIONAL):**

"Movement tutorial" project with spaceship animation can be used.

**Logs (OPTIONAL):**

N/A

**Workaround (OPTIONAL):**

N/A

**Screenshots (OPTIONAL):**

Here are video recordings: https://drive.google.com/drive/folders/19oKY_s_Wc-a6H3Zb4d8raSerdfBxUwbU?usp=sharing

**Additional context (OPTIONAL):**

N/A

### LINKED ISSUE #6530: ParticleFX speed is bound to framerate in the editor
**Describe the bug (REQUIRED)**
When editing a ParticleFX component, it plays faster in the editor than in-game when having a monitor with >60 hz refresh rate.

**To Reproduce (REQUIRED)**
https://user-images.githubusercontent.com/102416174/163803087-d2faa315-21c5-4516-95a3-f6de8a656cb3.mp4

**Expected behavior (REQUIRED)**.
Particles speed shouldn't be bound to framerate and be the same in game and editor.

**Defold version (REQUIRED):**
Version 1.3.1 (Newest)

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Workaround (OPTIONAL):**
Set monitor refresh rate to 60 hz, or limit the editor's fps in any other way.

### PR DESCRIPTION
**Pull request by britzl**
The update speed for flipbook animations and particle effects were locked to 60 updates per second even if previewing on a high refresh rate screen (eg 144Hz).

Fix #5075
Fix #6530 

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: editor/src/clj/editor/scene.clj [hunk 1]
```diff
@@ -850,7 +850,7 @@
               (do (ui/text! info-label info-text)
                   (ui/visible! info-label true))))
           (when (and (some? drawable) (some? async-copy-state-atom))
-            (update-image-view! image-view drawable async-copy-state-atom evaluation-context)))))))
+            (update-image-view! image-view drawable async-copy-state-atom evaluation-context dt)))))))
```
Comment (britzl) [inline editor/src/clj/editor/scene.clj:853]: Not sure about function arg order here. Is it ok to put dt last or do you always want the evaluation-context as the last arg?

**Review by matgis — APPROVED** [review]
Nice! The code changes look good to me, but I'd like to download the updated editor to try it out a bit. Unfortunately the train I'm on is not letting me download it at a reasonable speed. 😅

**Review by vlaaad — APPROVED** [review]
LGTM!
