### PR TITLE
Issue 5141 utf8 prefs

### LINKED ISSUE #5141: Project is not displayed in the list (at editor start)
### Expected behaviour

1. Start editor.
2. I see the list of my projects to choose from.

### Actual behaviour

1. Start editor.
2. A projects are not displayed in the project list, because they have unicode symbols in the path (i mean characters with code over 128).

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-08-27T04:44:14.453565</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>96c820fb9fb9c3d6ddec975e5e1dde4762b0228d</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 200 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13431 Compatibility Profile Context 16.150.2211.0</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

### PR DESCRIPTION
**Pull request by otsakir**
This is actually about fixing utf8 support in prefs.  To my understanding, any preference in UTF8 (more than one byte per char) will break the editor. This was the root issue behind #5141.

### Issue internals

There is some back-and-forth regarding encodings, but it allowed for a minimal modification. Let me explain.

After a pref is read and converted from UTF8 (in the file) to java's internal encoding (i think that is called utf16) it is parsed as json. This parsing relies on InputStream interface and uses StringBufferInputStream. This implementation for some weird reason expects a string of UTF8 in the constructor. It doesn't get it and it fails. No wonder why this is depracated :-).

I've replaced StringBufferInputStream with ByteArrayInputStream. The latter is constructed using  a byte[] and the encoding can be specified here. So, i encoded the pref back in UTF8 and handed it to ByteArrayInputStream as such. 

### Tests

I reproduced the issue using unit test and confirmed the test passes after the fix. I also checked the application itself and it works ok. There is a warning displayed though when the patched code is executed (in the test or in the actual app):

    Reflection warning, editor/prefs.clj:40:39 - call to method getBytes can't be resolved (target class is unknown).

I wouldn't consider it alarming but my clojure-fu is not to be trusted :-)

### CODE REVIEW

File: editor/src/clj/editor/prefs.clj [hunk 1]
```diff
@@ -36,7 +37,8 @@
      (.toString out)))
 
 (defn- read-transit [s]
```
Comment (bagucode) [inline editor/src/clj/editor/prefs.clj:39]: Could add a type annotation here to get rid of the reflection warning. 
`^String`

**Review by bagucode — DISMISSED** [review]
Looks good, but please also add the type annotation I commented about. Thanks for the fix!

File: editor/src/clj/editor/prefs.clj (hunk 1 above)
Comment (otsakir) [reply editor/src/clj/editor/prefs.clj:39]: Ok, let my fix it

**Review by britzl — APPROVED** [review]
