### PR TITLE
Fix build error log parse exception

### LINKED ISSUE #9430: <!-- NOTE! The information you specify will be publicly accessible. --> ### Expected behaviour
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-22T07:42:28.305676</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8a536ed1046ca0190e22eb47f78cb59e840a92a7</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7fddc47acf1b485aaf9bde2800f5e5b4"'>7fddc47acf1b485aaf9bde2800f5e5b4</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 546.29</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
Technical notes:
I reproed and fixed it with Codex, using a red/green approach: first commit created failing tests that repro the issue, second one fixed the issue.
Fix #9430

### CODE REVIEW

File: editor/src/clj/editor/engine/build_errors.clj [hunk 1]
```diff
@@ -267,6 +268,14 @@
...
     acc))
 
+(defn- merge-compilation-message-into-previous-entry
+  "Merge current into the previous entry in acc. If there is no previous entry,
+  current is orphaned context and should be discarded."
+  [acc current]
+  (if (coll/empty? acc)
+    nil
+    (merge-compilation-messages (peek acc) current)))
+
```
Comment (matgis) [inline editor/src/clj/editor/engine/build_errors.clj:278]: `peek` will return `nil` for an empty collection, so no need to check `coll/empty?` separately.

File: editor/src/clj/editor/engine/build_errors.clj [hunk 2]
```diff
@@ -277,8 +286,10 @@
       (fn [state action]
         (case action
           :conj-message (assoc state :current (merge-compilation-messages current line))
-          :conj-message-to-previous (merge state {:current (merge-compilation-messages (last acc) (merge-compilation-messages current line))
-                                                  :acc (pop acc)})
+          :conj-message-to-previous (if-let [merged-entry (merge-compilation-message-into-previous-entry acc (merge-compilation-messages current line))]
+                                      (merge state {:current merged-entry
+                                                    :acc (pop acc)})
+                                      state)
```
Comment (matgis) [inline editor/src/clj/editor/engine/build_errors.clj:292]: I bumped against this, since it is not entirely clear from the context that `merge-compilation-message-into-previous-entry` will return `nil` if `acc` is empty. The call to `(pop acc)` would throw an exception if `acc` is empty, so knowing if it is empty or not is relevant.

It might be clearer to have `merge-compilation-message-into-previous-entry` return either a pair of `[popped-acc merged-entry]` or `nil` if there is nothing to do?

**Review by matgis — DISMISSED** [review]

**Comment by vlaaad** [comment]
Good points, Mats!
