### PR TITLE
Report defignored files as non-existent

### LINKED ISSUE #6400: Ignored files in `.defignore` still processed by the editor
**Describe the bug (REQUIRED)**
Even if a resource added in the `.defignore` file, the editor still process it.

**To Reproduce (REQUIRED)**
1. Open the attached test project
2. Make sure `2.atlas` file is in `.defignore`
3. Open the same file in an external editor
4. Remove one image from this atlas
5. Switch back to the editor
6. Changes takes longer than switching back without any changes.

**Expected behavior (REQUIRED)**
Atlas should be ignored.

**Defold version (REQUIRED):**
  - Version 1.2.193 alpha

**Platforms (REQUIRED):**
 - Platforms: macos
 - OS: macos

**Minimal repro case project (OPTIONAL):**
[Uploading ignore-repo.zip…]()

### PR DESCRIPTION
**Pull request by vlaaad**
Additionally, this changeset makes the editor sync resources after save if `.defignore` file was modified.

Fixes #6400

### CODE REVIEW

File: editor/src/clj/editor/resource.clj [hunk 1]
```diff
@@ -95,10 +95,36 @@
...
+  (let [defignore-file (io/file root ".defignore")
+        defignore-path (.getCanonicalPath defignore-file)
+        latest-mtime (.lastModified defignore-file)
+        {:keys [mtime pred]} (get @defignore-cache defignore-path)]
+    (if (= mtime latest-mtime)
+      pred
+      (let [pred (if (.isFile defignore-file)
+                   (let [prefixes (into
+                                    #{}
+                                    (filter #(string/starts-with? % "/"))
```
Comment (matgis) [inline editor/src/clj/editor/resource.clj:113]: Doesn't this mean that only paths starting with `/` in the `.defignore` file will be ignored? This seems to have changed from the original behavior. I think it was using `string/contains?` previously. Was this an intended change?

Comment (matgis) [reply editor/src/clj/editor/resource.clj:113]: Yeah, I think it should work.
