### PR TITLE
Fix Tile Source Collision Group colors in Outline

### LINKED ISSUE #11290: Regresion: "Collision groups" text color in the outline
There are no colors in tile source for  "Collision groups"

Image

This was fixed here, but doesn't work in new version:
https://github.com/defold/defold/pull/9091

### PR DESCRIPTION
**Pull request by matgis**
Fixes #11290

### Technical changes
* Added some more info to the maps returned by the `dev/javafx-tree` function.

### CODE REVIEW

File: editor/src/clj/editor/outline_view.clj [hunk 1]
```diff
@@ -639,7 +639,7 @@
                          (ui/on-click! (partial toggle-visibility! node-outline-key-path)))
                        (proxy-super setGraphic pane)
                        (when-let [[r g b a] color]
-                         (proxy-super setStyle (format "-fx-text-fill: rgba(%d, %d, %d %d);" (int (* 255 r)) (int (* 255 g)) (int (* 255 b)) (int (* 255 a)))))
+                         (.setStyle text-label (format "-fx-text-fill: rgba(%d, %d, %d %d);" (int (* 255 r)) (int (* 255 g)) (int (* 255 b)) (int (* 255 a)))))
```
Comment (matgis) [inline editor/src/clj/editor/outline_view.clj:642]: Now that we have additional controls such as the visibility toggle surrounding each tree item in the Outline View, this style should no longer be applied to the root-level graphic produced for the `TreeItem`. It should be applied to the `Label` itself.

File: editor/src/dev/jfx.clj [hunk 2]
```diff
@@ -234,11 +234,17 @@
...
+   :pseudo-classes (not-empty (into (sorted-set) (map str) (.getPseudoClassStates styleable)))})
 
 (defn- node-props [^Node node]
   (let [layout-bounds (.getLayoutBounds node)]
-    {:layout-size [(.getWidth layout-bounds) (.getHeight layout-bounds)]}))
+    (cond-> {:layout-size [(.getWidth layout-bounds) (.getHeight layout-bounds)]}
+            (.isDisable node) (assoc :disable true)
+            (.isMouseTransparent node) (assoc :mouse-transparent true)
+            (not (.isManaged node)) (assoc :managed false)
+            (not (.isVisible node)) (assoc :visible false))))
```
Comment (matgis) [inline editor/src/dev/jfx.clj:247]: Just some additions I made to the debugging helpers when investigating the issue.

**Review by vlaaad — APPROVED** [review]
LGTM!
