### PR TITLE
Redesign game.project form

### LINKED ISSUE #6740: game.project is too slow to open
**Describe the bug**
The very first opening of `game.project` is very slow. Subsequent opens are faster, but still somewhat slow.

**To Reproduce**
1. Open `game.project` file as a form.
2. Observe delay until the form is shown.

**Expected behavior**
Opening `game.project` should be faster.

**Defold version:**
`1.3.+`

**Platforms:**
 - Platforms: all

### PR DESCRIPTION
**Pull request by vlaaad**
This changeset alters the UI of forms that requested navigation (currently only game.project form) in a following way:
- the form shows sections UI organized in groups;
- the form shows at most one section at a time.

Fixes #6740

### CODE REVIEW

File: editor/project.clj [hunk 1]
```diff
@@ -78,7 +78,7 @@
 
                      [org.luaj/luaj-jse "3.0.1"]
 
-                     [cljfx "1.7.19"]
+                     [cljfx "1.7.20"]
```
Comment (vlaaad) [inline editor/project.clj:81]: The new cljfx version adds [minor performance improvement](https://github.com/cljfx/cljfx/commit/acbe9972e99abdce2d88d4595aa90f4d7c865629#diff-2d1a8a5d95ca40ee6e203dbca4971239ea263507304181cd86fd28a0bf266deaL44-R46): when performing very first render, if render request happened on UI thread, the render will happen immediately instead of "later".

File: editor/src/clj/editor/cljfx_form_view.clj [hunk 2]
```diff
@@ -1430,6 +1535,7 @@
         repaint-timer (ui/->timer 30 "refresh-form-view"
                                   (fn [_timer _elapsed]
                                     (g/node-value view-id :form-view)))]
+    (g/node-value view-id :form-view)
```
Comment (vlaaad) [inline editor/src/clj/editor/cljfx_form_view.clj:1538]: This requests cljfx to render the UI. Since `make-form-view` is called from UI thread, with new cljfx version we get immediate UI render instead of delaying it to `repaint-timer` tick.

File: editor/src/clj/editor/cljfx_form_view.clj [hunk 3]
```diff
@@ -1263,14 +1262,42 @@
...
-   :on-text-changed {:event-type :filter-text-changed}})
+(defmethod handle-event :navigate-sections [{:keys [fx/event ui-state sections selected-section-title]}]
+  (when (instance? KeyEvent event)
+    (let [^KeyEvent event event]
+      (when (= KeyEvent/KEY_PRESSED (.getEventType event))
+        (condp = (.getCode event)
+          KeyCode/DOWN
+          (do (.consume event)
+              (when-let [next-section (->> sections
+                                           (drop-while (complement #{selected-section-title}))
```
Comment (matgis) [inline editor/src/clj/editor/cljfx_form_view.clj:1273]: Niggle: The set-as-a-function equality check is a cute Clojure-ism, but wouldn't `#(not= % selected-section-title)` be both more readable and efficient?

File: editor/src/clj/editor/cljfx_form_view.clj [hunk 4]
```diff
@@ -1298,74 +1325,152 @@
...
+                 (cond
+                   ;; when child view is below viewport, scroll down
+                   (< viewport-bottom (.getMaxY child-bounds))
+                   (.setVvalue pane (/ (- (.getMaxY child-bounds) (.getHeight viewport-bounds))
+                                       (- content-height viewport-height)))
+                   ;; when child view is above viewport, scroll down
+                   (< (.getMinY child-bounds) (- (.getMinY viewport-bounds)))
+                   (.setVvalue pane (/ (.getMinY child-bounds)
+                                       (- content-height viewport-height)))))))))
+       fx.lifecycle/dynamic)}))
```
Comment (matgis) [inline editor/src/clj/editor/cljfx_form_view.clj:1353]: This seems like it could be of general use? Would it make sense to move it to `editor.fxui`?

**Review by matgis — APPROVED** [review]
Looks great & works great! LGTM! 👍

File: editor/src/clj/editor/cljfx_form_view.clj (hunk 4 above)
Comment (vlaaad) [reply editor/src/clj/editor/cljfx_form_view.clj:1353]: Yes!
