### PR TITLE
Issue 6602: Fix for looping out of bounds when generating render batches

### LINKED ISSUE #6602: Game crashes when minimising the window and when using a timer
**Describe the bug**
Game crashes after few seconds from start, sometimes 2, sometimes 15, and always on minimising the window.
On version 1.9.2 everything is OK.

**Defold version :**
  - Version 1.3.1 , 1.3.2 (1.3.3)

**Platforms :**
 - Windows7x64

**Logs:**

[_crash.zip](https://github.com/defold/defold/files/8690011/_crash.zip)

````
Assertion failed: timer->m_Remaining >= 0.f, file ..\src\script_timer.cpp, line 247
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\Sublustris\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x13F8F7EE0 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144

ERROR:CRASH:  1 0x13FCA30F4 raise /tmp/job8102041518656241272/minkernel/crts/ucrt/src/appcrt/misc/signal.cpp:547

ERROR:CRASH:  2 0x13FC9620C abort /tmp/job8102041518656241272/minkernel/crts/ucrt/src/appcrt/startup/abort.cpp:71

ERROR:CRASH:  3 0x13FC95458 common_assert_to_stderr<wchar_t> /tmp/job8102041518656241272/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:186

ERROR:CRASH:  4 0x13FC94F7C _wassert /tmp/job8102041518656241272/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:443

ERROR:CRASH:  5 0x13F9CAD40 dmScript::UpdateTimers D:\a\defold\defold\engine\script\src\script_timer.cpp:204

ERROR:CRASH:  6 0x13F9CACE0 dmScript::TimerUpdateScriptWorld D:\a\defold\defold\engine\script\src\script_timer.cpp:456

ERROR:CRASH:  7 0x13F90AE10 dmScript::UpdateScriptWorld D:\a\defold\defold\engine\script\src\script.cpp:1123

ERROR:CRASH:  8 0x13F9645B0 dmGameObject::CompScriptUpdate D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:249

ERROR:CRASH:  9 0x13F942EA0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2507

ERROR:CRASH: 10 0x13F9A8920 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1552

ERROR:CRASH: 11 0x13F9A3B20 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2060

ERROR:CRASH: 12 0x13F9A94C0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83

ERROR:CRASH: 13 0x13F8DE6F0 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148

ERROR:CRASH: 14 0x13FC59024 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

ERROR:CRASH: 15 0x771459E0 BaseThreadInitThunk <unknown>:0

ERROR:CRASH: 16 0x7727B810 RtlUserThreadStart <unknown>:0

ERROR:CRASH: 
````

### PR DESCRIPTION
**Pull request by JCash**
Fixes a crash when generating render batches.

Fixes #6602

### CODE REVIEW

File: engine/render/src/render/render_private.h [hunk 1]
```diff
@@ -325,11 +325,12 @@ namespace dmRender
...
         while (m_Iterator < m_EntriesEnd)
         {
-            if (!m_TestEqFn(prev, ++m_Iterator))
+            T next = ++m_Iterator;
+            if ((next >= m_EntriesEnd) || !m_TestEqFn(prev, next))
             {
                 break;
             }
-            prev = m_Iterator;
+            prev = next;
```
Comment (JCash) [inline engine/render/src/render/render_private.h:333]: Issue found when debugging issue-6602

**Review by britzl — APPROVED** [review]
