### PR TITLE
Use the WebGL 1.0 specific constant for the half float format.

### LINKED ISSUE #8241: WebGL 1.0 should use the HALF_FLOAT_OES constant for half float formats
**Describe the bug (REQUIRED)**
Ref: https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_half_float

To upload half float textures on WebGL 1.0 the renderer should use the HALF_FLOAT_OES (value is 0x8D61) constant as a texture type. Otherwise we will get an error about the invalid texture format. 

**Expected behavior (REQUIRED)**
We should be able to use half float textures on WebGL 1.0.

**Defold version (REQUIRED):**
  - Version: 1.6.3 `dev` branch

**Platforms (REQUIRED):**
 - Platforms: HTML5

### PR DESCRIPTION
**Pull request by aglitchman**
WebGL 1.0 supports loading half float textures. But it requires the use of HALF_FLOAT_OES constant, which has a different value from the HALF_FLOAT constant from WebGL 2.0 / OpenGL ES 3.0. This fix enables to use half float texture format on WebGL 1.0 devices.

Fixes #8241

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 1]
```diff
@@ -159,6 +159,7 @@
     #if defined GL_ES_VERSION_2_0
         #undef GL_ARRAY_BUFFER_ARB
         #undef GL_ELEMENT_ARRAY_BUFFER_ARB
+        #define GL_HALF_FLOAT_OES 0x8D61
```
Comment (aglitchman) [inline engine/graphics/src/opengl/graphics_opengl.cpp:162]: In fact, for WebGL we should use header files from ES 2.0/3.0, because it is based on it. But someone decided to use files from desktop GL. That's strange. And there is no GL_HALF_FLOAT_OES in desktop GL. So I added this constant manually as #define.

PS If the desktop include above is replaced by include gl2ext.h, for example, the webgl renderer stops working and pulls a huge amount of patching and testing.

**Comment by aglitchman** [comment]
I made a build of the engine myself and tested half float texture on WebGL 1.0 device - works great.

The only thing for WebGL 1.0 is that half float texture must be POT.

File: engine/graphics/src/opengl/graphics_opengl.cpp (hunk 1 above)
Comment (Jhonnyg) [reply engine/graphics/src/opengl/graphics_opengl.cpp:162]: I think you should put this into graphics_opengl_defines.h and follow the style of the other defines

**Review by Jhonnyg — CHANGES_REQUESTED** [review]
If this requires POT textures, we should probably output an error if someone is trying to use a wrong combination, otherwise we might just get a black screen and no info on why it is happening

File: engine/graphics/src/opengl/graphics_opengl.cpp (hunk 1 above)
Comment (aglitchman) [reply engine/graphics/src/opengl/graphics_opengl.cpp]: Okay 🙌🏻 Done.

**Comment by aglitchman** [comment]
> If this requires POT textures, we should probably output an error if someone is trying to use a wrong combination, otherwise we might just get a black screen and no info on why it is happening

Ok 🙌🏻  I think it should be a new issue and a new PR (like "The engine should warn that the texture should be POT").

**Comment by aglitchman** [comment]
Looks to me like everything is ok now and you can do the merge.
