### PR TITLE
Fix Dependencies and Referencing Files popup showing blank entries for some resource types

### LINKED ISSUE #7306: Dependency list contains only blank names
### Expected behaviour

Dependency list has blank names

### Actual behaviour

List of assets

### Steps to reproduce

Collection context menu ->  Dependencies

<hr/>

<table>
<tr><td>Build time</td><td>2023-01-19T14:36:29.442121</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e0ad4769ad5b83c60b185b54ff889f4437b0d128</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 540</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-18.8.5</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.6.2</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Fix Dependencies and Referencing Files popup showing blank entries for some resource types

Fixes #7306

### CODE REVIEW

File: editor/src/clj/editor/core.clj [hunk 1]
```diff
@@ -62,18 +62,43 @@ connected to the Scope's :nodes input.
...
+   {:pre [(g/node-id? node-id)]}
+   (let [outgoing-arcs (g/explicit-arcs-by-source basis node-id)
+         outgoing-arcs-by-target-id (group-by gt/target-id outgoing-arcs)]
+     (some (fn [[target-id outgoing-arcs-to-target]]
+             (let [target-node-type (g/node-type* basis target-id)
+                   cascade-delete-input-label? (g/cascade-deletes target-node-type)
+                   arc-connects-to-cascade-delete-input? (comp cascade-delete-input-label? gt/target-label)]
+               (when (some arc-connects-to-cascade-delete-input? outgoing-arcs-to-target)
+                 target-id)))
+           outgoing-arcs-by-target-id))))
```
Comment (matgis) [inline editor/src/clj/editor/core.clj:101]: I changed the graph topology at one point to not always connect resource sub-nodes to the `Scope` `:nodes` input. This updated implementation will use any `:cascade-delete` input to decide ownership.

File: editor/test/integration/test_util.clj [hunk 2]
```diff
@@ -117,7 +117,7 @@
   ([graph project-path]
    (let [workspace-config (shared-editor-settings/load-project-workspace-config project-path)
          workspace (workspace/make-workspace graph
-                                             (.getAbsolutePath (io/file project-path))
+                                             project-path
```
Comment (matgis) [inline editor/test/integration/test_util.clj:120]: The `project-path` is made canonical inside `make-workspace`.

File: editor/test/integration/test_util.clj [hunk 3]
```diff
@@ -592,9 +592,9 @@
   directory path must be a temp directory."
   ^java.lang.AutoCloseable [directory-path]
   (let [directory (io/file directory-path)]
-    (assert (string/starts-with? (.getAbsolutePath directory)
+    (assert (string/starts-with? (.getCanonicalPath directory)
```
Comment (matgis) [inline editor/test/integration/test_util.clj:595]: This assert would fail for some tests on macOS after I made the project path canonical. Not sure why I didn't notice it before. 😞

**Review by vlaaad — APPROVED** [review]
Works great, ship it!
