### PR TITLE
Issue-3315 Fix label rotation

### LINKED ISSUE #3315: Label transform is wrong when the size property is not zero (DEF-3756)
Description: There's a discrepancy between editor2 behaviour for labels.

Steps to reproduce:

* Add a label component to a gameobject
* Set a size value (or keep default) and set pivot to center (also default)
* Rotate the label.

Expected result:
* It should rotate around the center of the label
* It should look the same as the editor viewport

Actual result:

It rotates around the center of the box of a radius that is dependant on the box size.

### PR DESCRIPTION
**Pull request by BreadSniper**
**Issue**: #3315 
**Before**: label component was not rotating around the pivot point.
**After**: label is rotating correctly.

**Points for discussion**: I don't like code repetition in tests - I will try to refactor them, but suggestions are welcome. It seems that CompLabelLocalTransform function is not quite related to Label, and it should be renamed and moved to some utils place, if you have a good name and place for this function - please suggest. I also don't like how many parameters it takes - we can discuss possible improvements to this.

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_label.cpp [hunk 1]
```diff
@@ -257,6 +257,22 @@ namespace dmGameSystem
...
+        const Quat& rotation,
+        const Vector3& scale,
+        const Vector3& size,
+        uint32_t pivot)
+    {
+        // Move pivot to (0,0). Rotate around (0,0). Move pivot to position.
+        return dmTransform::ToMatrix4(
+            dmTransform::Mul(
+                dmTransform::Transform(Vector3(position), rotation, 1.0f),
+                dmTransform::Transform(CalcPivotDelta(pivot, mulPerElem(scale, size)), Quat::identity(), 1.0f)
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_label.cpp:271]: Note to self: Don't put "using namespace Vectormath::Aos;" at global scope!
We don't want things to unintentionally leak into other translation units.

File: engine/gamesys/src/gamesys/components/comp_label.cpp [hunk 2]
```diff
@@ -257,6 +257,22 @@ namespace dmGameSystem
         return dmGameObject::CREATE_RESULT_OK;
     }
 
+    Matrix4 CompLabelLocalTransform(
+        const Point3& position,
+        const Quat& rotation,
+        const Vector3& scale,
+        const Vector3& size,
+        uint32_t pivot)
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_label.cpp:265]: We don't generally put each argument onto a separate line.
Best is to follow the style of the rest of the file one is editing.

File: engine/gamesys/src/gamesys/components/comp_label.h [hunk 3]
```diff
@@ -53,7 +53,12 @@ namespace dmGameSystem
 
     const char* CompLabelGetText(const LabelComponent* component);
 
-
+    Vectormath::Aos::Matrix4 CompLabelLocalTransform(
+        const Vectormath::Aos::Point3& position,
+        const Vectormath::Aos::Quat& rotation,
+        const Vectormath::Aos::Vector3& scale,
+        const Vectormath::Aos::Vector3& size,
+        uint32_t pivot);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_label.h:61]: Same as above, arguments on same row.

**Review by JCash — CHANGES_REQUESTED** [review]
Looks good! Just some minor style change needed.

**Comment by JCash** [comment]
> I don't like code repetition in tests - I will try to refactor them, but suggestions are welcome. It seems that CompLabelLocalTransform function is not quite related to Label, and it should be renamed and moved to some utils place, if you have a good name and place for this function - please suggest.

Possibly. Let's just make a mental note that it exists. Gui might have a similar function, but that is also in a separate library. I think the gain of merging the two would add unwanted dependencies.

>I also don't like how many parameters it takes - we can discuss possible improvements to this.

Sure, it's on the borderline, but if it's needed, then I'm ok with it.

File: engine/gamesys/src/gamesys/components/comp_label.cpp (hunk 1 above)
Comment (hapass) [reply engine/gamesys/src/gamesys/components/comp_label.cpp:266]: But this using is in cpp file, it shouldn't leak to other translation units... Or maybe I misunderstand something here?

File: engine/gamesys/src/gamesys/components/comp_label.cpp (hunk 2 above)
Comment (hapass) [reply engine/gamesys/src/gamesys/components/comp_label.cpp]: Changed codestyle here. Also I did some tests refactoring (please take a look).

File: engine/gamesys/src/gamesys/components/comp_label.h (hunk 3 above)
Comment (hapass) [reply engine/gamesys/src/gamesys/components/comp_label.h]: Put everything on the same line. Thanks! :)

File: engine/gamesys/src/gamesys/components/comp_label.cpp (hunk 1 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/components/comp_label.cpp:266]: It might if one would do batch (or "unity") compiling to speed things up.
I.e. a "big.cpp", containing:
```
#include <a.cpp>
#include <b.cpp>
...
```

It's not an unreasonable optimization to do in the future.

**Review by JCash — APPROVED** [review]
Looks  good!

File: engine/gamesys/src/gamesys/components/comp_label.cpp (hunk 1 above)
Comment (hapass) [reply engine/gamesys/src/gamesys/components/comp_label.cpp:266]: got it :) yeah, I might have heard of speeding things up this way in some gdc talk
