### PR TITLE
Fix issue when window (on Mac) opens without focus

### LINKED ISSUE #6709: Non-clickable window when debugging on mac os
In most cases, when debugging is started, it will not respond to clicks. To solve the problem, you need to switch to another window and then return to the debug window.

**To Reproduce:**
1. Go to 'Debug>Start/Attach'
2. Click on 'window'
3. Window is not clickable

**Expected behavior:**
Debug version must react to click

**Defold version:**
  - Version 1.3.2

**Platforms:**
 - Platforms:  macOS 12.5.1

### PR DESCRIPTION
**Pull request by AGulev**
Fixed an issue when a window on Mac opens without focus. In such cases, the window doesn't react to most input events, and only double-click works.

Fix https://github.com/defold/defold/issues/6709
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/glfw/lib/cocoa/cocoa_init.m [hunk 1]
```diff
@@ -88,33 +88,6 @@ - (void)setAppleMenu:(NSMenu *)m;
...
-            inMode: NSDefaultRunLoopMode dequeue: NO ];
-
-        // Could do this only if we discover we're unbundled, but it should
-        // do no harm...
-        ProcessSerialNumber psn = { 0, kCurrentProcess };
-        TransformProcessType( &psn, kProcessTransformToForegroundApplication );
-
-        // Having the app in front of the terminal window is also generally
-        // handy.  There is an NSApplication API to do this, but...
-        SetFrontProcess( &psn );
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_init.m:113]: `SetFrontProcess` - deprecated

File: engine/glfw/lib/cocoa/cocoa_init.m [hunk 2]
```diff
@@ -88,33 +88,6 @@ - (void)setAppleMenu:(NSMenu *)m;
...
-        // If we skip this, sometimes the app/window become unresponsive
-        // right after start.
-        //
-        // This also fixes the bug where the correct menu won't show
-        // unless the user switches from the app and back again.
-        //
-        // Eclipse does something similar:
-        // https://bugs.eclipse.org/bugs/attachment.cgi?id=248969
-        [NSApp nextEventMatchingMask: NSAnyEventMask untilDate: nil
-            inMode: NSDefaultRunLoopMode dequeue: NO ];
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_init.m:104]: it seems like this hack doesn't work anymore. I moved part of it to `didupdate` event

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 3]
```diff
@@ -127,9 +127,17 @@ - (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication *)sende
     return NSTerminateCancel;
 }
 
-- (void)applicationDidFinishLaunching:(NSNotification *)notification
-{
-    [[NSRunningApplication currentApplication] activateWithOptions:(NSApplicationActivateAllWindows | NSApplicationActivateIgnoringOtherApps)];
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:132]: this event never called

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 4]
```diff
@@ -127,9 +127,17 @@ - (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication *)sende
...
+- (void)applicationDidUpdate:(NSNotification *)notification
+{
+    // Wait for the first update to make window active
+    // It helps to avoid issue when the window opens inactive
+    // https://github.com/defold/defold/issues/6709
+    if( !_glfwLibrary.Unbundled ) {
+        ProcessSerialNumber psn = { 0, kCurrentProcess };
+        TransformProcessType( &psn, kProcessTransformToForegroundApplication );
+        [[NSApplication sharedApplication] activateIgnoringOtherApps: YES];
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:138]: Recommended function instead of `SetFrontProcess()` even though it's deprecated as well 🤷‍♂️

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 5]
```diff
@@ -127,9 +127,17 @@ - (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication *)sende
...
 
-- (void)applicationDidFinishLaunching:(NSNotification *)notification
-{
-    [[NSRunningApplication currentApplication] activateWithOptions:(NSApplicationActivateAllWindows | NSApplicationActivateIgnoringOtherApps)];
+- (void)applicationDidUpdate:(NSNotification *)notification
+{
+    // Wait for the first update to make window active
+    // It helps to avoid issue when the window opens inactive
+    // https://github.com/defold/defold/issues/6709
+    if( !_glfwLibrary.Unbundled ) {
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:135]: just to make sure we call it once

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 6]
```diff
@@ -810,7 +817,6 @@ int  _glfwPlatformOpenWindow( int width, int height,
         }
         _glfwWin.aux_context = [[NSOpenGLContext alloc] initWithFormat:_glfwWin.pixelFormat shareContext:_glfwWin.context];
 
-        [_glfwWin.window makeKeyAndOrderFront:nil];
```
Comment (AGulev) [inline engine/glfw/lib/cocoa/cocoa_window.m:813]: there is no reason to call it twice

**Review by britzl — APPROVED** [review]
