### PR TITLE
Editor: Consolidate connections from host gui scene to template nodes

### LINKED ISSUE #6356: GUI template with layers is rendered differently inside editor and game
**Describe the bug (REQUIRED)**
There is the bug, where layers inside templates rendering incorrect inside the Editor. In the game all render as excepted.
See the template (_component.gui_) and their layer setup in example project.

**To Reproduce (REQUIRED)**
1. Have template with layer
2. Use this template inside other GUI, add additional layers on their parent.
3. In some cases (like in example) the layers draw in incorrect way

**Expected behavior (REQUIRED)**
The editor and the game should render layers correctly

**Defold version (REQUIRED):**
On actual version (example created on 185)

**Platforms (REQUIRED):**
Example tested on MacOS.

**Minimal repro case project (OPTIONAL):**
[template_layers_bug.zip](https://github.com/defold/defold/files/7958132/template_layers_bug.zip)

**Workaround (OPTIONAL):**
Currently I have to not use layers for make easier make windows inside the editor

**Screenshots (OPTIONAL):**
Inside Editor:
Screenshot 2022-01-28 at 13 01 46

Inside Game:
Screenshot 2022-01-28 at 13 01 51

### PR DESCRIPTION
**Pull request by matgis**
* Simplified the editor graph connections between host gui scenes and gui nodes imported from referenced templates. This saves a bit of memory in projects with a large number of gui nodes.
* Nodes imported from template scenes that are assigned to a layer will now correctly use the layer configuration from the host scene when viewed in the editor.
* Renaming a gui resource in a referenced scene will no longer erroneously update references that have been redeclared as a different resource in referencing scenes. I.e, if `host.gui` references `template.gui`, and they each declare a font named "header", renaming it inside `template.gui` will not change `host.gui`, because there "header" refers to its the "header" font inside `host.gui`.
* Improved sorting of choice box entries with numbers when referencing gui resources in the Properties View.

Fixes #6356

### Technical changes
* Instead of individual connections for various data originating from the host gui scene, the data is consolidated into two connections, `basic-gui-scene-info` and `costly-gui-scene-info`. The latter contains data whose dependencies are more costly to produce, and is typically only needed when the scene is shown in the Scene View.

This change requires users to update `extension-spine`. Corresponding PR: defold/extension-spine#196.

### CODE REVIEW

File: editor/src/clj/editor/gui.clj [hunk 1]
```diff
@@ -1105,14 +1098,15 @@
...
+                      layout-names (:layout-names basic-gui-scene-info)
 
                       prop->value-for-default-layout-in-original
                       (coll/not-empty (get layout->prop->value-for-original ""))
 
                       prop->value-for-default-layout
                       (cond->> (make-prop->value-for-default-layout _this)
                                prop->value-for-default-layout-in-original
-                               (merge prop->value-for-default-layout-in-original))
+                               (coll/merge prop->value-for-default-layout-in-original))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1109]: We now have our own `merge` implementation that is a bit more efficient.

File: editor/src/clj/editor/gui.clj [hunk 2]
```diff
@@ -1209,10 +1205,13 @@
...
-                                        (g/package-errors _node-id
-                                                          (prop-unique-id-error _node-id :id id id-counts "Id")
-                                                          (validate-layer false _node-id layer-names layer))))
+  (output build-errors-gui-node g/Any
+          (g/fnk [_node-id basic-gui-scene-info id id-counts layer]
+            (let [layer-names (:layer-names basic-gui-scene-info)]
+              (g/package-errors
+                _node-id
+                (prop-unique-id-error _node-id :id id id-counts "Id")
+                (validate-layer false _node-id layer-names layer)))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1214]: Get `layer-names` from `basic-gui-scene-info`. Also decreased the indentation for readability.

File: editor/src/clj/editor/gui.clj [hunk 3]
```diff
@@ -1254,10 +1253,11 @@
 
 (defn- validate-material-capabilities [_node-id material-infos material material-shader texture-infos texture]
   (let [is-paged-material (shader/is-using-array-samplers? material-shader)
-        material-info (or (material-infos material)
-                          (material-infos ""))
+        material-info (or (get material-infos material)
+                          (get material-infos ""))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1257]: `material-infos` can't actually be `nil` here, because you will always have the default material. I guess I just wanted to consistently use `get`, since the lookups come from optional keys in `basic-gui-scene-info`.

File: editor/src/clj/editor/gui.clj [hunk 4]
```diff
@@ -1489,40 +1495,49 @@
...
+                                                      (g/property-overridden? basis self :manual-size)
+                                                      (let [effective-new-value
+                                                            (or new-value
+                                                                (let [original-node-id (g/override-original basis self)]
+                                                                  (g/node-value original-node-id :texture evaluation-context)))]
+                                                        (= :texture-size (visible-size-property-label size-mode effective-new-value))))
+                                                 (assoc :manual-size nil))))))))
+            (dynamic error (g/fnk [_node-id basic-gui-scene-info texture]
+                             (let [texture-names (:texture-names basic-gui-scene-info)]
+                               (validate-texture-resource _node-id texture-names texture)))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1540]: Mostly indentation due to added surrounding `let`.

File: editor/src/clj/editor/gui.clj [hunk 5]
```diff
@@ -1783,22 +1809,24 @@
...
+                                    (let [font-datas (:font-datas costly-gui-scene-info)]
+                                      (or (get font-datas font)
+                                          (get font-datas "")))))
 
   ;; Overloaded outputs
   (output node-msg g/Any :cached produce-text-node-msg)
   (output gpu-texture TextureLifecycle (g/fnk [font-data] (:texture font-data)))
   (output scene-renderable-user-data g/Any :cached
-          (g/fnk [manual-size font font-shaders material material-shaders pivot text-data color+alpha]
+          (g/fnk [costly-gui-scene-info manual-size font material material-shader pivot text-data color+alpha]
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1821]: We can use the `material-shader` output from the base node here instead of looking it up ourselves.

File: editor/src/clj/editor/gui.clj [hunk 6]
```diff
@@ -1783,22 +1809,24 @@
...
                  (let [[w h] manual-size
                        offset (pivot-offset pivot manual-size)
                        lines (mapv conj (apply concat (take 4 (partition 2 1 (cycle (geom/transl offset [[0 0] [w 0] [w h] [0 h]]))))) (repeat 0))
                        font-map (get-in text-data [:font-data :font-map])
                        texture-recip-uniform (font/get-texture-recip-uniform font-map)
-                       material-shader (when (not (empty? material)) (material-shaders material))
-                       font-shader (or material-shader (font-shaders font) (font-shaders ""))
+                       material-shader (when (not (empty? material)) material-shader)
+                       font-shaders (:font-shaders costly-gui-scene-info)
+                       font-shader (or material-shader (get font-shaders font) (get font-shaders ""))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1829]: The `material-shader` overrides the shader associated with the font if specified for this node.

File: editor/src/clj/editor/gui.clj [hunk 7]
```diff
@@ -1944,25 +1975,10 @@
...
-
-                                                                  [:particlefx-infos :aux-particlefx-infos]
-                                                                  [:particlefx-resource-names :aux-particlefx-resource-names]
-                                                                  [:resource-names :aux-resource-names]
-                                                                  [:layout-names :aux-layout-names]
+                                                 (for [[from to] [[:template-prefix :id-prefix]
                                                                   [:current-layout :current-layout]
-                                                                  [:template-prefix :id-prefix]]]
+                                                                  [:basic-gui-scene-info :aux-basic-gui-scene-info]
+                                                                  [:costly-gui-scene-info :aux-costly-gui-scene-info]]]
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1981]: Connections between the `TemplateNode` and the `GuiSceneNode` it brings into the host scene.

File: editor/src/clj/editor/gui.clj [hunk 8]
```diff
@@ -2179,7 +2211,7 @@
   (input gpu-texture g/Any :substitute nil)
   (input texture-page-count g/Int :substitute nil)
   (input anim-data g/Any :substitute (constantly nil))
-  (input anim-ids g/Any :substitute (constantly []))
+  (input anim-ids g/Any :substitute nil)
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2214]: It's fine.

File: editor/src/clj/editor/gui.clj [hunk 9]
```diff
@@ -2419,6 +2451,11 @@
   (property id g/Str (default "") ; No protobuf counterpart.
             (dynamic visible (g/constantly false)))
 
+  (input basic-gui-scene-info BasicGuiSceneInfo)
+  (output basic-gui-scene-info BasicGuiSceneInfo (gu/passthrough basic-gui-scene-info))
+  (input costly-gui-scene-info CostlyGuiSceneInfo)
+  (output costly-gui-scene-info CostlyGuiSceneInfo (gu/passthrough costly-gui-scene-info))
+
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2458]: This is on the `NodeTree`, which would pass all this stuff down to the hosted `GuiNodes`.

File: editor/src/clj/editor/gui.clj [hunk 10]
```diff
@@ -2441,45 +2478,11 @@
...
-  (output spine-scene-names GuiResourceNames (gu/passthrough spine-scene-names))
-  (input particlefx-infos ParticleFXInfos)
-  (output particlefx-infos ParticleFXInfos (gu/passthrough particlefx-infos))
-  (input particlefx-resource-names GuiResourceNames)
-  (output particlefx-resource-names GuiResourceNames (gu/passthrough particlefx-resource-names))
-  (input resource-names GuiResourceNames)
-  (output resource-names GuiResourceNames (gu/passthrough resource-names))
+  (input node-ids NameNodeIds :array)
+  (output node-ids NameNodeIds :cached (g/fnk [node-ids] (reduce coll/merge {} node-ids)))
+
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2483]: I didn't add these. They are simply what remains.

File: editor/src/clj/editor/gui.clj [hunk 11]
```diff
@@ -2522,19 +2525,20 @@
...
+       (concat
+         (g/connect texture :texture-names self :texture-names)
+         (g/connect texture :dep-build-targets self :dep-build-targets)
+         (g/connect texture :pb-msg self :texture-msgs)
+         (g/connect texture :build-errors textures-node :build-errors)
+         (g/connect texture :node-outline textures-node :child-outlines)
+         (g/connect texture :name textures-node :names)
+         (g/connect textures-node :name-counts texture :name-counts)
+         (g/connect self :samplers texture :samplers)
+         (g/connect self :default-tex-params texture :default-tex-params))))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2541]: Indentation, but also note I've renamed the `own-` prefix from the `GuiSceneNode` inputs where gui resources attach. Them belonging to the scene is now implied, and instead of having `own-` and `aux-` variants of each, we have `own-basic-gui-scene-info` and `aux-basic-gui-scene-info`, as well as counterparts for `costly-gui-scene-info`.

File: editor/src/clj/editor/gui.clj [hunk 12]
```diff
@@ -2549,6 +2553,7 @@
   (inherits outline/OutlineNode)
   (input names g/Str :array)
   (output name-counts NameCounts :cached (g/fnk [names] (frequencies names)))
+  (output texture-resource-names GuiResourceNames :cached (g/fnk [names] (into (sorted-set) names)))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2556]: Used to check ownership of texture gui resources when renaming such a gui resource in a referenced scene.

File: editor/src/clj/editor/gui.clj [hunk 13]
```diff
@@ -2723,7 +2730,7 @@
 (g/defnode LayoutsNode
   (inherits outline/OutlineNode)
   (input names g/Str :array)
-  (output names g/Any (gu/passthrough names))
+  (output names GuiResourceNames :cached (g/fnk [names] (into (sorted-set) names)))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2733]: We can collect the names into a set directly in the `LayoutsNode`. This connects to the `layout-names` input `GuiSceneNode`.

File: editor/src/clj/editor/gui.clj [hunk 14]
```diff
@@ -3308,16 +3258,18 @@
...
+            (let [material-names
+                  (coll/transfer (:material-infos aux-basic-gui-scene-info) (sorted-set)
+                    (map key)
+                    (remove coll/empty?))]
+              {:font (:font-names aux-basic-gui-scene-info)
+               :layer (:layer-names aux-basic-gui-scene-info)
+               :material material-names
+               :particlefx (:particlefx-resource-names aux-basic-gui-scene-info)
+               :spine-scene (:spine-scene-names aux-basic-gui-scene-info)
+               :texture (:texture-resource-names aux-basic-gui-scene-info)})))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3272]: Used when renaming gui resources to make sure we don't rename anything in referencing gui scenes that is redeclared (or "shadowed") in the referencing scene.

File: editor/src/clj/editor/gui.clj [hunk 15]
```diff
@@ -3351,34 +3303,59 @@
...
+            (coll/merge-entries-with
+              (fn [[key :as aux-entry] own-entry]
+                (case key
+                  (:layer->index :layer-names) aux-entry ; Covered, not merged.
+                  (let [aux-value (val aux-entry)
+                        own-value (val own-entry)
+                        value (coll/merge aux-value own-value)]
+                    (pair key value))))
+              aux-basic-gui-scene-info
+              own-basic-gui-scene-info)))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3337]: The special layer handing was the source of the template layer ordering issue when viewed in the Scene View. We were correctly covering the `layer-names` of the referenced scene by the ones from the referencing scene, but not the `layer->index` map.

File: editor/src/clj/editor/gui.clj [hunk 16]
```diff
@@ -3351,34 +3303,59 @@
...
+            {:font-datas (reduce coll/merge font-datas)
+             :font-shaders (reduce coll/merge font-shaders)
+             :material-shaders (reduce coll/merge {"" material-shader} material-shaders)
+             :particlefx-infos (reduce coll/merge particlefx-infos)
+             :spine-scene-infos (reduce coll/merge spine-scene-infos)
+             :texture-gpu-textures (reduce coll/merge texture-gpu-textures)
+             :texture-infos (reduce coll/merge texture-infos)}))
+  (output costly-gui-scene-info CostlyGuiSceneInfo :cached
+          (g/fnk [aux-costly-gui-scene-info own-costly-gui-scene-info]
+            (coll/merge-with coll/merge aux-costly-gui-scene-info own-costly-gui-scene-info))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3351]: Yes, we also have `coll/merge-with` now. For efficiency! 😅

File: editor/src/clj/editor/gui.clj [hunk 17]
```diff
@@ -3351,34 +3303,59 @@
...
-      (concat
-       (g/connect resource-node :dep-build-targets self :dep-build-targets)
-       (g/connect resource-node :resource-names    self :resource-names)
-       (g/connect resource-node :pb-msg            self :resource-msgs)
-       (g/connect resource-node :build-errors      resources-node :build-errors)
-       (g/connect resource-node :node-outline      resources-node :child-outlines)
-       (g/connect resource-node :name              resources-node :names)
-       (g/connect resource-node :resource-path     resources-node :paths)
-       (g/connect resources-node :name-counts resource-node :name-counts))))))
-
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3381]: Unused. Maybe a remnant from some earlier stage? 🤔

File: editor/src/clj/editor/gui.clj [hunk 18]
```diff
@@ -3615,6 +3592,7 @@
                     (g/connect textures-node :build-errors self :build-errors)
                     (g/connect textures-node :node-outline self :child-outlines)
                     (g/connect textures-node :add-handler-info self :handler-infos)
+                    (g/connect textures-node :texture-resource-names self :texture-resource-names)
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3595]: Used to check ownership when renaming gui resources.

File: editor/src/clj/editor/gui.clj [hunk 19]
```diff
@@ -3683,26 +3661,10 @@
...
-                                     [:particlefx-infos :particlefx-infos]
-                                     [:particlefx-resource-names :particlefx-resource-names]
-                                     [:resource-names :resource-names]
-                                     [:id-prefix :id-prefix]
-                                     [:layout-names :layout-names]
-                                     [:current-layout :current-layout]]]
+                    (for [[from to] [[:id-prefix :id-prefix]
+                                     [:current-layout :current-layout]
+                                     [:basic-gui-scene-info :basic-gui-scene-info]
+                                     [:costly-gui-scene-info :costly-gui-scene-info]]]
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3667]: `GuiScene` to `NodeTree` connections.

File: editor/src/dev/dev.clj [hunk 20]
```diff
@@ -137,6 +138,27 @@
...
+         override-node-ids (g/overrides basis node-id)]
+     (cond-> (into (array-map :node-id node-id)
+                   (gu/node-debug-info node-id evaluation-context))
+
+             (some? original-node-id)
+             (assoc :original-node-id original-node-id)
+
+             (coll/not-empty override-node-ids)
+             (assoc :override-node-ids override-node-ids)))))
+
```
Comment (matgis) [inline editor/src/dev/dev.clj:161]: Added helpful debug function to the `dev` module.

File: editor/test/integration/build_test.clj [hunk 21]
```diff
@@ -294,7 +295,21 @@
...
+            proj-path (resource/proj-path resource)
+            error-message (some :message (tree-seq :causes :causes error-value))]
+        (throw
+          (ex-info
+            (format "Failed to build '%s': %s"
+                    proj-path
+                    error-message)
+            {:resource-node resource-node
+             :resource resource
+             :error-value error-value}))))))
```
Comment (matgis) [inline editor/test/integration/build_test.clj:312]: Added success check, because it was confusing when the build failed.

File: editor/test/integration/gui_test.clj [hunk 22]
```diff
@@ -762,11 +762,17 @@
...
+                imported-pie (:pie shapes)
+                template-layer (g/node-value template-pie :layer)]
+            (is (= template-layer (g/node-value imported-pie :layer))) ; Layer property is inherited from template.
+            (is (nil? (g/node-value template-pie :layer-index)))
+            (is (nil? (g/node-value imported-pie :layer-index)))
+            (add-layer! template-scene template-layer 0)
+            (is (= 0 (g/node-value template-pie :layer-index)))
+            (is (nil? (g/node-value imported-pie :layer-index))) ; Layers are isolated between scenes. The imported pie inherits the layer property, but there is still no matching layer in its scene.
+            (add-layer! scene template-layer 0)
+            (is (= 0 (g/node-value imported-pie :layer-index))))))
```
Comment (matgis) [inline editor/test/integration/gui_test.clj:775]: Updated test to take layer isolation rules into account after the fix to #6356 included in this PR.

File: editor/test/util/coll_test.clj [hunk 23]
```diff
@@ -466,19 +827,17 @@
                             {:m (JustA. 11)}))))
 
   (testing "Returns nil when called with no maps."
-    (is (nil? (coll/deep-merge)))
+    (is (nil? (coll/deep-merge))))
```
Comment (matgis) [inline editor/test/util/coll_test.clj:830]: Fixed paren scope mismatch by moving the closing paren down in the file.

File: editor/src/clj/editor/gui.clj (hunk 15 above)
Comment (vlaaad) [reply editor/src/clj/editor/gui.clj:3337]: I have a suggestion: define `coll/merge-with-kv` and use it instead of `coll/merge-entries-with`. Make the merge fn accept 3 arguments: `k`, `old-v`, `new-v`, and return a merged `v`. This will make the code more efficient since we won't be allocating any entries.

**Review by vlaaad — CHANGES_REQUESTED** [review]
LGTM, though I think `merge-entries-with` should be improved (or replaced).

File: editor/src/clj/editor/gui.clj (hunk 15 above)
Comment (matgis) [reply editor/src/clj/editor/gui.clj:3337]: Good suggestion! I'll change it. It will make it cleaner at the call site as well.

File: editor/src/clj/util/coll.clj [hunk 24]
```diff
@@ -212,6 +212,91 @@
...
+         (reduce (fn [result [b-key :as b-entry]]
+                   (if-let [merged-entry (merged-entry b-key b-entry)]
+                     (assoc result b-key (val merged-entry))
+                     result))
+                 a
+                 b)))))
+  ([f a b & maps]
+   (reduce #(merge-with f %1 %2)
+           (merge-with f a b)
+           maps)))
```
[the remark this answers is not in the document]
Comment (matgis) [reply editor/src/clj/util/coll.clj:298]: Ah, nice catch! I'll fix and make sure it is covered by the tests.

**Review by vlaaad — DISMISSED** [review]
Shipit!

**Comment by matgis** [comment]
I will! Once I get an approval of the corresponding changes in defold/extension-spine#196. 😅

**Comment by vlaaad** [comment]
Woops, missed it :)
