### PR TITLE
Fix profiler 'view peak frame' mode.

### LINKED ISSUE #8027: Setting profiler ui mode to profiler.MODE_SHOW_PEAK_FRAME does not work
Setting profiler ui mode to profiler.MODE_SHOW_PEAK_FRAME does not work. The profiler continues working in profiler.MODE_RUN mode.

Executed code:
```
profiler.enable_ui(true)
profiler.set_ui_mode(profiler.MODE_SHOW_PEAK_FRAME)
```
This brings up the profiler in profiler.MODE_RUN mode, and peak frames are not displayed.

**Defold version:**
  - Version 1.5.0

**Platforms:**
 - Windows 10

### PR DESCRIPTION
**Pull request by ekharkunov**
Fixes #8027 
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/profiler/src/profile_render.cpp [hunk 1]
```diff
@@ -632,6 +635,7 @@ namespace dmProfileRender
             return;
         }
 
+        uint32_t last_thread_name = GetSelectedThread(render_profile, render_profile->m_CurrentFrame)->m_NameHash;
```
Comment (ekharkunov) [inline engine/profiler/src/profile_render.cpp:638]: Initial problem was in clearing `render_profile->m_CurrentFrame` almost every frame. When clear happened `last_thread->m_NameHash` become 0 that led to reset m_MaxFrameTime and reassign peak frame every time.

File: engine/profiler/src/profile_render.cpp [hunk 2]
```diff
@@ -641,35 +645,31 @@ namespace dmProfileRender
...
         }
 
-        //uint64_t last_frame_time = last_thread ? last_thread->m_SamplesTotalTime : 0;
         uint64_t this_frame_time = current_thread->m_SamplesTotalTime;
 
         bool new_peak_frame = render_profile->m_MaxFrameTime < this_frame_time;
         render_profile->m_MaxFrameTime = dmMath::Max(render_profile->m_MaxFrameTime, this_frame_time);
 
-        if (render_profile->m_Mode == PROFILER_MODE_SHOW_PEAK_FRAME)
+        if (new_peak_frame)
```
Comment (ekharkunov) [inline engine/profiler/src/profile_render.cpp:661]: Move those condition outside of `if (render_profile->m_Mode == PROFILER_MODE_SHOW_PEAK_FRAME)` because profiler updates `m_MaxFrameTime` every frame but peak frame stores only when special profiler mode is active. It can lead to situation when peak frame happened in the past before switching to `PROFILER_MODE_SHOW_PEAK_FRAME`. As result peak frame never stored and profiler is continue showing current frame as active.

File: engine/profiler/src/profile_render.cpp [hunk 3]
```diff
@@ -641,35 +645,31 @@ namespace dmProfileRender
...
+            if (render_profile->m_LastPeakFrame)
             {
-                ProfilerFrame* snapshot = DuplicateProfilerFrame(render_profile->m_CurrentFrame);
-
-                FlushRecording(render_profile, 1);
-                render_profile->m_RecordBuffer.SetSize(1);
-                render_profile->m_RecordBuffer[0] = snapshot;
+                DeleteProfilerFrame(render_profile->m_LastPeakFrame);
             }
+            render_profile->m_LastPeakFrame = DuplicateProfilerFrame(render_profile->m_CurrentFrame);
```
Comment (ekharkunov) [inline engine/profiler/src/profile_render.cpp:667]: Add storing peak frame as separate struct field because:
1. it solves problem with display peak frame in case if it appeared before switching to `PROFILER_MODE_SHOW_PEAK_FRAME`
2. it solves problem when peak mode can conflict with record mode because they used the same record buffer. Now it can be safetly switched between recorded frames and peak frame.

**Review by JCash — APPROVED** [review]
