### PR TITLE
Issue-4952: Fix crash when deleting playing particlefx in gui

### LINKED ISSUE #4952: Assertion failed: i < Size() on deleting a particlefx attached to a box in a node
**Describe the bug (REQUIRED)**
I have Created a particlefx and attach it to a GUI node (GUI/Nodes/box/particlefx)

 i used a call to delete the particle 
```lua
gui.delete_node(gui.get_node("particlefx"))
```
i've got a crash with this message 

```
WARNING:GUI: Stencil buffer exceeded, clipping will not work as expected.
Assertion failed: size <= Capacity(), file d:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 456
```

**To Reproduce (REQUIRED)**
1. Create a particlefx
2. create a gui box 
3. attach the particle to a box
4. use `gui.delete_node(gui.get_node("particlefx"))` to delete the particle

**Expected behavior (REQUIRED)**
the game crashes when the particlefx is attached to a box meanwhile it doesn't when it is attached directly to GUI Nodes path

**Defold version (REQUIRED):**
  - 1.2.170

**Platforms (REQUIRED):**
Windows , Android

**Minimal repro case project (OPTIONAL):**
Open The Project Run and click on screen To Call the delete function
[assertion_bug.zip](https://github.com/defold/defold/files/4816467/assertion_bug.zip)

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/gui/src/gui.cpp [hunk 1]
```diff
@@ -2065,8 +2065,8 @@ Result DeleteDynamicTexture(HScene scene, const dmhash_t texture_hash)
                             }
                         }
 
-                        n->m_ParentIndex = INVALID_INDEX;
                         ResetInternalNode(scene, n);
+                        n->m_ParentIndex = INVALID_INDEX;
```
Comment (JCash) [inline engine/gui/src/gui.cpp:2069]: The internals of ResetInternalNode does a RemoveFromList, which requires it to know the parent, in order to remove it from the parent's list of children.

**Review by britzl — APPROVED** [review]
