### PR TITLE
Fix issue where rebuilding the game from the Editor doesn't keep the simulated resolution

### LINKED ISSUE #10670: Rebuild game from Editor and sys.reboot don't keep simulated resolution
**Describe the bug (REQUIRED)**
If I select Debug -> Select Resolution, it will be saved and set each game instance run

If I rebuild the game, while previous build is running, the resolution will be default
If I call sys.reboot, the resolution will be default

**To Reproduce (REQUIRED)**
1. Load example
2. Run App
3. Debug -> Set Resolution -> Any
4. Window size changed
5. If game restart - size keeped
6. If sys.reboot or rebuild game - size not changed

**Expected behavior (REQUIRED)**
Size always changed

**Defold version (REQUIRED):**
1.10.1

**Platforms (REQUIRED):**
Tested on MacOS

**Minimal repro case project (OPTIONAL):**

[reboot_game_issue.zip](https://github.com/user-attachments/files/20232781/reboot_game_issue.zip)

https://github.com/user-attachments/assets/f6cd573f-c459-44f7-b858-cc742874a42a

### PR DESCRIPTION
**Pull request by AGulev**
If the window resolution has been set in the Editor, it will be applied again when the engine is restarted from the Editor using Build To Target.

Fix https://github.com/defold/defold/issues/10670

### CODE REVIEW

File: editor/src/clj/editor/app_view.clj [hunk 1]
```diff
@@ -820,7 +820,10 @@
               ;; running to keep engine process
               ;; from halting because stdout/err is
               ;; not consumed.
-              (reboot-engine! selected-target web-server debug?))
+              (reboot-engine! selected-target web-server debug?)
+              (console/start-one-line-log-pump!
+                (:log-stream selected-target)
+                (fn [_] (on-service-url-found prefs selected-target))))
```
[the remark this answers is not in the document]
Comment (vlaaad) [reply editor/src/clj/editor/app_view.clj]: I'm not quite sure this will work reliably. As I understand from the comments on lines 819-822, there is already a thread that consumes all output from the target and displays it in the console. If that's the case, then launching another thread that will also read input from the same log stream will work only in cases where this one-line thread gets lucky to read a line first.

File: editor/src/clj/editor/console.clj [hunk 2]
```diff
@@ -128,6 +129,22 @@
...
+;; Start a background thread that waits for a single line from the log-stream,
+;; calls sink-fn with it, and then stops.
+(defn start-one-line-log-pump!
+  "Reads a single line from log-stream in a background thread and calls sink-fn with it.
+   Does NOT close the stream."
+  [log-stream sink-fn]
+  (doto (Thread.
+          (fn []
+            (try
+              (let [reader (BufferedReader. (io/reader log-stream :encoding "UTF-8"))]
```
Comment (vlaaad) [inline editor/src/clj/editor/console.clj]: Also, using a buffered reader might read too much, which will lead to log loss. The log line already seems lost in this case, since it is not submitted to the console.

**Review by vlaaad — COMMENTED** [review]
I'm not sure this solution works, can you explain it?

File: editor/src/clj/editor/app_view.clj (hunk 1 above)
[the remark this answers is not in the document]
Comment (AGulev) [reply editor/src/clj/editor/app_view.clj]: what the best way to know the reboot is done?
Ofc I can just thread sleep for 100 ms

[the remark this answers is not in the document]
Comment (vlaaad) [reply editor/src/clj/editor/app_view.clj]: Great question, I'm not sure. In `editor.engine/reboot!`, we send a reboot request and then wait until all output is processed. Not sure how the engine does it, maybe it closes this connection after the reboot is done? In that case, the editor doesn't have to do anything special and could just apply the resolution after the call to reboot...

[the remark this answers is not in the document]
Comment (AGulev) [reply editor/src/clj/editor/app_view.clj]: No, it doesn't work this way, I tried it. 
Maybe then just sleep (we do it when we start the engine)

[the remark this answers is not in the document]
Comment (AGulev) [reply editor/src/clj/editor/app_view.clj]: I have an idea, let me try

**Comment by AGulev** [comment]
I tried new way to implement it, please take a look

File: editor/src/clj/editor/app_view.clj [hunk 3]
```diff
@@ -749,6 +751,10 @@
         (swap! initial-output str line "\n")
         (when-let [target-info (engine/parse-launched-target-info @initial-output)]
           (targets/update-launched-target! launched-target target-info on-service-url-found)))
+      (when @engine-just-rebooted
+        (reset! engine-just-rebooted false)
+        (doseq [l-target (targets/all-launched-targets)]
+          (on-service-url-found l-target)))
```
Comment (vlaaad) [inline editor/src/clj/editor/app_view.clj]: Shouldn't the code call `on-service-url-found` only for the `launched-target` that is an argument to this function?

Comment (vlaaad) [reply editor/src/clj/editor/app_view.clj]: Does it work if the old engine is constantly outputting something into logs? Then this branch might be executed before the engine is actually restarted. There is code above (`engine/parse-launched-target-info`) that parses log output, perhaps we should do something like that instead? maybe even without the global state `engine-just-rebooted` atom...

**Review by vlaaad — COMMENTED** [review]
I'm not a big fan of communicating via shared global state, but perhaps we don't have other options here. Or maybe we do? Maybe it's worth exploring if we could parse the log similarly to what `engine/parse-launched-target-info` does, and call `on-service-url-found` only when we get a particular message indicating that the engine has rebooted? 

Also, as I understand, when we have multiple instances running, we have a separate log sink for each instance (see `launch-new-engine!` fn in `launch-built-project!`). In that case, we should only call `on-service-url-found` for the target that we have as an argument in `make-launched-log-sink`, since this is the engine that got rebooted.

File: editor/src/clj/editor/app_view.clj (hunk 3 above)
Comment (AGulev) [reply editor/src/clj/editor/app_view.clj]: I don't like the idea with parsing, because then we have to parse it every single line which is far way from perfect. For now we parse only 5000 messages (which is too many I think).

> Shouldn't the code call on-service-url-found only for the launched-target that is an argument to this function?

no, because it will be changed in `targets/update-launched-target!` 
but I'll recheck logic with multiple instance again (when I have time)

Comment (vlaaad) [reply editor/src/clj/editor/app_view.clj]: Initially, we could wait for a message in the shape `INFO:ENGINE: Defold Engine $version ($sha)`. Then we could store it inside the function, and then we would only need to compare new lines for equality with the stored string. Then, subsequent "parsing" of every line is going to be fast. I think this approach of gradually gathering information from every log line is more reliable than relying on the next log output line after notifying the engine about a reboot request to indicate that the engine has already rebooted.

Btw, the info parser looks for the first 5000 characters, not 5000 messages.

File: editor/src/clj/editor/app_view.clj [hunk 4]
```diff
@@ -743,12 +743,20 @@
       (throw e))))
 
 (defn- make-launched-log-sink [launched-target on-service-url-found]
-  (let [initial-output (atom "")]
+  (let [initial-output (atom "")
+        version-line (atom nil)
+        updated-target (atom nil)]
```
Comment (AGulev) [inline editor/src/clj/editor/app_view.clj:748]: instead of global state we have these two atoms

File: editor/src/clj/editor/targets.clj [hunk 5]
```diff
@@ -114,27 +114,21 @@
...
-                           ;; Wait for the console stream to be marked as active
-                           (loop []
-                             (if (console/current-stream? (:log-stream result-target))
-                               (on-service-url-found result-target)
-                               (do
-                                 (Thread/sleep 100)
-                                 (recur))))))
-                       result-target)
+                     (let [rt (merge launched-target target-info)]
+                       (vreset! result-target rt)
```
Comment (AGulev) [inline editor/src/clj/editor/targets.clj:124]: we need it to be able to return updated target as result of update-launched-target!. Update target will contain `:url` we need to be able to send resolution change message

File: editor/src/clj/editor/engine.clj [hunk 6]
```diff
@@ -174,6 +174,13 @@
              {:log-port log-port
               :address loopback-address}))))
 
+;; Parse a line from engine output to extract engine version info.
+(defn parse-engine-version-line [output]
+  (some (fn [line]
+          (when-let [[_ version sha] (re-find #"INFO:ENGINE: Defold Engine ([^\s]+) \(([^)]+)\)" line)]
+            line))
+        (split-lines output)))
```
Comment (AGulev) [inline editor/src/clj/editor/engine.clj]: if line has form of `INFO:ENGINE: Defold Engine $version ($sha)` - return it

File: editor/src/clj/editor/app_view.clj [hunk 7]
```diff
@@ -743,12 +743,20 @@
...
         (swap! initial-output str line "\n")
         (when-let [target-info (engine/parse-launched-target-info @initial-output)]
-          (targets/update-launched-target! launched-target target-info on-service-url-found)))
+          (let [result-target (targets/update-launched-target! launched-target target-info)]
+            (reset! updated-target result-target)))
+        (when (not @version-line)
+          (when-let [engine-version-line (engine/parse-engine-version-line @initial-output)]
+            (reset! version-line engine-version-line))))
+      (when (and @updated-target line (= @version-line line))
+        (on-service-url-found @updated-target))
```
Comment (AGulev) [inline editor/src/clj/editor/app_view.clj:759]: (see comments below first)
now we have result of `update-launched-target!` and `version-line` we use to compare every line with it.
if we get such line - then update window size

File: editor/src/clj/editor/targets.clj [hunk 8]
```diff
@@ -114,27 +114,21 @@
...
-                       (when (and (:url target-info) (not (:url launched-target)))
-                         (future
-                           ;; Wait for the console stream to be marked as active
-                           (loop []
-                             (if (console/current-stream? (:log-stream result-target))
-                               (on-service-url-found result-target)
-                               (do
-                                 (Thread/sleep 100)
-                                 (recur))))))
-                       result-target)
```
Comment (AGulev) [inline editor/src/clj/editor/targets.clj:132]: I think we don't need it anymore. New even that waits `INFO:ENGINE: Defold Engine $version ($sha)` should work just fine

**Review by AGulev — COMMENTED** [review]
One more attempt...

File: editor/src/clj/editor/app_view.clj [hunk 9]
```diff
@@ -743,12 +743,20 @@
...
+        updated-target (atom nil)]
     (fn [line]
       (when (< (count @initial-output) 5000)
         (swap! initial-output str line "\n")
         (when-let [target-info (engine/parse-launched-target-info @initial-output)]
-          (targets/update-launched-target! launched-target target-info on-service-url-found)))
+          (let [result-target (targets/update-launched-target! launched-target target-info)]
+            (reset! updated-target result-target)))
+        (when (not @version-line)
+          (when-let [engine-version-line (engine/parse-engine-version-line @initial-output)]
```
Comment (vlaaad) [inline editor/src/clj/editor/app_view.clj]: This code could parse a `line` instead of `@initial-input`, so it checks every new line instead of re-checking a set of initial lines multiple times. This would improve performance a bit.

File: editor/src/clj/editor/app_view.clj [hunk 10]
```diff
@@ -743,12 +743,20 @@
...
+            (reset! version-line engine-version-line))))
+      (when (and @updated-target line (= @version-line line))
```
Comment (vlaaad) [inline editor/src/clj/editor/app_view.clj]: As I understand, `line` is never `nil`, it's always a string, so there is no need to check if it exists.

**Review by vlaaad — DISMISSED** [review]
LGTM!

File: editor/src/clj/editor/app_view.clj (hunk 9 above)
Comment (AGulev) [reply editor/src/clj/editor/app_view.clj]: true!

**Comment by AGulev** [comment]
Thank you @vlaaad ! 
I think this approach is more robust, even for the initial resolution setup (instead of using sleep).  
I like it much more now!

File: editor/src/clj/editor/engine.clj [hunk 11]
```diff
@@ -174,6 +174,13 @@
              {:log-port log-port
               :address loopback-address}))))
 
+;; Parse a line from engine output to extract engine version info.
+(defn parse-engine-version-line [output]
+  (some (fn [line]
+          (when-let [[_ version sha] (re-find #"INFO:ENGINE: Defold Engine ([^\s]+) \(([^)]+)\)" line)]
+            line))
```
Comment (vlaaad) [inline editor/src/clj/editor/engine.clj]: Since you always pass a single line here, there is no need to split it into lines. The whole function body can be simplified to:
```clj
(when (re-find #"INFO:ENGINE: Defold Engine ([^\s]+) \(([^)]+)\)" line)
  line)
```

**Review by vlaaad — APPROVED** [review]
shipit!
