### PR TITLE
Removed game.project maximum field size of 2048 bytes

### LINKED ISSUE #6567: Custom resources (game.project) => limited number/quantity of custom resources
**Describe the bug (REQUIRED)**
Looks like there is a max number/quantity of custom resources (game.project) preventing me from adding some custom resources.

_This is likely a bug or limitation in Bob and the editor. Could you please create a ticket on GitHub? It’s probably a fairly simple fix._ (Britzl)

cf forum
https://forum.defold.com/t/is-there-a-max-number-quantity-of-custom-resources/70807/3

**To Reproduce (REQUIRED)**
cf forum

**Expected behavior (REQUIRED)**
cf forum

**Defold version (REQUIRED):**
  - Version1.3.1

### PR DESCRIPTION
**Pull request by britzl**
The maximum length of a game.project value was previously hardcoded to 2048 characters. This is more than enough for most values, but when it comes to something like the bundle or custom resources which expects a comma separated list of paths it may not be enough and a long list of paths will cause the parser to fail when loading the game.project file. This change dynamically allocates a buffer large enough to hold the value.

Fixes #6567

### CODE REVIEW

File: engine/dlib/src/dlib/configfile.cpp [hunk 1]
```diff
@@ -287,9 +301,9 @@ namespace dmConfigFile
         Expect(context, '=');
         EatBlank(context);
 
-        char value_buf[2048];
-
-        ParseLiteral(context, value_buf, sizeof(value_buf));
+        int value_len = SizeOfLiteral(context) + 1;
+        char* value_buf = new char[value_len];
```
Comment (britzl) [inline engine/dlib/src/dlib/configfile.cpp:305]: One improvement might be to not allocate a new buffer each time ParseEntry is called and instead pass a buffer and length as arguments to ParseEntry and only reallocate the buffer if the value is larger than the buffer.

File: engine/dlib/src/dlib/configfile.cpp [hunk 2]
```diff
@@ -255,6 +255,20 @@ namespace dmConfigFile
...
+        int c = GetChar(context);
+        int i = 0;
+        while (c != '\n' && c != '\r')
+        {
+            c = GetChar(context);
+            ++i;
+        }
+        context->m_BufferPos = pos;
+        return i;
+    }
```
Comment (JCash) [inline engine/dlib/src/dlib/configfile.cpp:270]: A common api (for various C functions) is to use the same function, but not pass in the output buffer:

```
static int ParseLiteral(Context* context, char* buf, int buf_len)
{
    int c = GetChar(context);
    int i = 0;
    while (c != '\n' && c != '\r')
    {
        if (buf != 0)
        {
            buf[i] = c;
            if (i >= (int) buf_len - 1)
                ParseError(context, RESULT_LITERAL_TOO_LONG);
        }
        c = GetChar(context);
        ++i;
    }
    BufferUngetChar(c, context);
    if (buf != 0)
        buf[i] = '\0';
    return i;
}
```

**Review by JCash — CHANGES_REQUESTED** [review]

File: engine/dlib/src/dlib/configfile.cpp (hunk 2 above)
Comment (britzl) [reply engine/dlib/src/dlib/configfile.cpp:270]: I considered this but felt that the ParseLiteral function became a bit too messy:

```
    static int ParseLiteral(Context* context, char* buf, int buf_len)
    {
        int pos = context->m_BufferPos;
        int c = GetChar(context);
        int i = 0;
        while (c != '\n' && c != '\r')
        {
            if (buf != 0)
            {
                buf[i] = c;
                if (i >= (int) buf_len - 1)
                    ParseError(context, RESULT_LITERAL_TOO_LONG);
            }
            c = GetChar(context);
            ++i;
        }
        if (buf != 0)
        {
            BufferUngetChar(c, context);
            buf[i] = '\0';
        }
        else
        {
            context->m_BufferPos = pos;
        }
        return i;
    }
```

File: engine/dlib/src/dlib/configfile.cpp (hunk 1 above)
Comment (JCash) [reply engine/dlib/src/dlib/configfile.cpp:305]: I agree, and I think that is a better approach!

File: engine/dlib/src/dlib/configfile.cpp (hunk 2 above)
Comment (JCash) [reply engine/dlib/src/dlib/configfile.cpp:270]: The downside to having two functions is that the iterator functionality is also split into two functions.
It's easier for the implementations to diverge.

File: engine/dlib/src/dlib/configfile.cpp (hunk 1 above)
Comment (JCash) [reply engine/dlib/src/dlib/configfile.cpp:305]: Also, why not simply use the upper limit `context.m_BufferSize`?
It's not going to be that huge. and if it is huge, it might also be required!

File: engine/dlib/src/dlib/configfile.cpp (hunk 2 above)
Comment (britzl) [reply engine/dlib/src/dlib/configfile.cpp:270]: That is a good point. I'll use the combined function instead.

File: engine/dlib/src/dlib/configfile.cpp (hunk 1 above)
Comment (britzl) [reply engine/dlib/src/dlib/configfile.cpp]: This is a much better approach! One allocation and no need to measure the length of a value!

**Review by JCash — APPROVED** [review]
