### PR TITLE
Issue 6256: Fixed issue where particlefx could get wrong material con…

### LINKED ISSUE #6246: critical rendering issue with 1.2.189
It seems to me that 1.2.189 has various critical rendering issues.

I see it particularly with particles but the same issue is also present for sprites! All the particles disappear at once for many frames and then they are drawn again only for one frame. The game has never shown anything similar before I updated to 1.2.189. No error / warning reported in the console.

I may guess something related to extension-spine that corrupts the data sent to the GPU? A spinemodel is present when I see the rendering issue...

**To Reproduce (REQUIRED)**
NA

**Expected behavior (REQUIRED)**
The particles and the sprites should be rendered in each frame

**Defold version (REQUIRED):**
  - 1.2.189

**Platforms (REQUIRED):**
 - Platforms: Android and macOS

### LINKED ISSUE #6256: Sometimes the particlefx gets the wrong render constant

### PR DESCRIPTION
**Pull request by JCash**
…stants

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_particlefx.cpp [hunk 1]
```diff
@@ -282,6 +282,8 @@ namespace dmGameSystem
             pfx_world->m_ConstantBuffers[ro_index] = dmRender::NewNamedConstantBuffer();
         }
         ro.m_ConstantBuffer = pfx_world->m_ConstantBuffers[ro_index];
+
+        dmRender::ClearNamedConstantBuffer(ro.m_ConstantBuffer);
         SetRenderConstants(ro.m_ConstantBuffer, first->m_RenderConstants, first->m_RenderConstantsSize);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_particlefx.cpp:287]: The named constant buffer (`pfx_world->m_ConstantBuffers[ro_index]`) is reused.
So if the "ro_index" changes, it's possible you get a buffer that already contains constants.
The fix (also used in other components), is to clear the constants from the buffer (/internally a hash table) before adding new constants.

File: engine/render/src/dmsdk/render/render.h [hunk 2]
```diff
@@ -471,10 +471,18 @@ namespace dmRender
...
      */
     bool GetNamedConstant(HNamedConstantBuffer buffer, dmhash_t name_hash, dmVMath::Vector4** values, uint32_t* num_values);
 
+    /*#
+     * Gets number of constants in the buffer
+     * @name GetNamedConstantCount
+     * @param buffer [type: dmRender::HNamedConstantBuffer] the constants buffer
+     * @return ok [type: bool] true if constant existed.
+     */
+    uint32_t GetNamedConstantCount(HNamedConstantBuffer buffer);
```
Comment (JCash) [inline engine/render/src/dmsdk/render/render.h:484]: Not really used anywhere, but I used it for debugging the number of constants in a buffer.

**Review by britzl — APPROVED** [review]
Looks good!
