### PR TITLE
Issue-6060 Allow window size change at initialization phase

### LINKED ISSUE #6060: Engine crashes if change window size (using DefOS) at Initialization stage
**Describe the bug (REQUIRED)**
If window size changed at Initialisation stage (for example in InitializeDefos) then app crashes because can't find gui

**To Reproduce (REQUIRED)**
1. Open Defos example project
2. add the following line after [this line](https://github.com/subsoap/defos/blob/8867999886025170264e518f9ea6751bfae2a2ab/defos/src/defos.cpp#L705)
3. 
>defos_set_window_size(0.0, 0.0, 200.0, 200.0);

**Expected behavior (REQUIRED)**
App shouldn't crash

**Defold version (REQUIRED):**
  - Version 1.2.187 beta

**Platforms (REQUIRED):**
 - Platforms: all

**Minimal repro case project (OPTIONAL):**

[minimal-repo.zip](https://github.com/defold/defold/files/7191262/minimal-repo.zip)

**Logs (OPTIONAL):**
```
ERROR:ENGINE: Could not find '@render' socket.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/agulev/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

# 0 pc     0x30bd7d libxpc.dylib _sigtramp+29
# 1 pc     0x2732f2 dmengine _ZN5dmGui21SetPhysicalResolutionEPNS_7ContextEjj+18
# 2 pc       0x870b dmengine _ZN8dmEngineL14OnWindowResizeEPvjj+251
# 3 pc     0x270f2e dmengine -[GLFWWindowDelegate windowDidResize:]+270
# 4 pc     0x3b521d libxpc.dylib __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__+12
# 5 pc     0x450c7c libxpc.dylib ___CFXRegistrationPost_block_invoke+49
# 6 pc     0x450bfa libxpc.dylib _CFXRegistrationPost+454
# 7 pc     0x38629e libxpc.dylib _CFXNotificationPost+736
# 8 pc     0x3642c8 libSparse.dylib -[NSNotificationCenter postNotificationName:object:userInfo:]+59
# 9 pc    0x1e810e0 libSparse.dylib -[NSWindow _setFrameCommon:display:fromServer:]+3309
#10 pc       0x3d39 dmengine _Z21defos_set_window_sizeffff+265
#11 pc       0x20d7 dmengine _Z15InitializeDefosPN11dmExtension6ParamsE+87
#12 pc     0x1751c7 dmengine _ZN8dmScriptL28InternalInitializeExtensionsEPNS_7ContextE+327
#13 pc     0x170039 dmengine _ZN8dmScript10InitializeEPNS_7ContextE+761
#14 pc       0x6f7c dmengine _ZN8dmEngine4InitEPNS_6EngineEiPPc+3772
#15 pc       0xa0d7 dmengine _Z14dmEngineCreateiPPc+71
#16 pc       0xa3af dmengine _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE+95
#17 pc       0xa322 dmengine _Z11engine_mainiPPc+98
```

### PR DESCRIPTION
**Pull request by AGulev**
fix https://github.com/defold/defold/issues/6060

### CODE REVIEW

**Comment by AGulev** [comment]
In such case I see the following error:

>ERROR:ENGINE: Could not find '@render' socket.

https://github.com/defold/defold/blob/538ae34a0ad81df454b262a5db77992353fa72c7/engine/engine/src/engine.cpp#L127

Maybe it would be better to exit function using `return` when we get such error instead of checking Gui context?

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -935,6 +935,11 @@ namespace dmEngine
         gui_params.m_GetUserDataCallback = dmGameSystem::GuiGetUserDataCallback;
         gui_params.m_ResolvePathCallback = dmGameSystem::GuiResolvePathCallback;
         gui_params.m_GetTextMetricsCallback = dmGameSystem::GuiGetTextMetricsCallback;
+
+        // If window size changed at the initialization phase, size should be actualized
```
Comment (JCash) [inline engine/engine/src/engine.cpp:939]: What "phase" specifically?
I believe that should be put in the code comment

File: engine/gui/src/gui.cpp [hunk 2]
```diff
@@ -267,6 +267,11 @@ namespace dmGui
 
     void SetPhysicalResolution(HContext context, uint32_t width, uint32_t height)
     {
+        // If window size changed at the initialization phase, gui context doesn't exist.
```
Comment (JCash) [inline engine/gui/src/gui.cpp:270]: Not sure this should be here.
What code called this function without a context?

If it's from engine.cpp OnWindowSize() then I think the null ptr check should be there since
1) we don't do defensive programming
2) the rest of the guicpp doesn't check the context pointer

File: engine/engine/src/engine.cpp (hunk 1 above)
Comment (AGulev) [reply engine/engine/src/engine.cpp:939]: true!
```
// If an extension changes window size at extensions initialization phase, engine should read that.
```

File: engine/gui/src/gui.cpp (hunk 2 above)
Comment (AGulev) [reply engine/gui/src/gui.cpp]: Yes, I didn't like that either. Thank you!

File: engine/engine/src/engine.cpp [hunk 3]
```diff
@@ -138,8 +138,11 @@ namespace dmEngine
         Engine* engine = (Engine*)user_data;
         engine->m_InvPhysicalWidth = 1.0f / width;
         engine->m_InvPhysicalHeight = 1.0f / height;
-        // update gui context
-        dmGui::SetPhysicalResolution(engine->m_GuiContext.m_GuiContext, width, height);
+        // update gui context if it exists
+        if (engine->m_GuiContext.m_GuiContext)
+        {
+            dmGui::SetPhysicalResolution(engine->m_GuiContext.m_GuiContext, width, height);
```
Comment (JCash) [inline engine/engine/src/engine.cpp:144]: 👍

File: engine/engine/src/engine.cpp [hunk 4]
```diff
@@ -935,6 +938,11 @@ namespace dmEngine
         gui_params.m_GetUserDataCallback = dmGameSystem::GuiGetUserDataCallback;
         gui_params.m_ResolvePathCallback = dmGameSystem::GuiResolvePathCallback;
         gui_params.m_GetTextMetricsCallback = dmGameSystem::GuiGetTextMetricsCallback;
+
+      // If an extension changes window size at extensions initialization phase, engine should read that.
```
Comment (JCash) [inline engine/engine/src/engine.cpp:942]: 👍

**Review by JCash — APPROVED** [review]
