### PR TITLE
Issue-6788: Reset text context earlier before dispatching the render list

### LINKED ISSUE #6788: GUI text doesn't render, sometimes crashes, if render script has previously early-outed
**Describe the bug**
If the render script early-outs, then GUI text will not render from that point onwards, even when the render script resumes.
In our game, attempting the same causes a crash but I don't yet have a repro case for that.

**To Reproduce**
Sample project attached. Main.collection has a sprite, a GUI box and a GUI text.

Modify update() in default.render_script as so:

```
local frame_count = 0

function update(self)
    frame_count = frame_count + 1
    if (frame_count % 100) > 50 then
        return
    end
```

I'm attempting this while investigating Unity Ads crashing on low-end Android devices, which [some Unity users have worked around by pausing game rendering while an ad is showing](https://forum.unity.com/threads/high-memory-usage-playing-rewarded-ads-on-ios.1198693/#post-7930054).

**Expected behavior**
The GUI text is rendered.

**Defold version:**
  - 1.3.4 80b1b73fd9cdbd4682c2583403fddfbaf0919107

**Platforms:**
 - Platforms: Windows
 - OS: Windows 10
image
image

**Other information**
This is the callstack in game. The attached project is an attempt to recreate it.
```
ERROR:CRASH:  0 0x7FF61B2E20C0 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
ERROR:CRASH:  1 0x7FF61B697354 raise /tmp/job8188771907799980064/minkernel/crts/ucrt/src/appcrt/misc/signal.cpp:547
ERROR:CRASH:  2 0x7FF61B687D34 abort /tmp/job8188771907799980064/minkernel/crts/ucrt/src/appcrt/startup/abort.cpp:71
ERROR:CRASH:  3 0x7FF61B686C48 common_assert_to_stderr<wchar_t> /tmp/job8188771907799980064/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:186
ERROR:CRASH:  4 0x7FF61B68676C _wassert /tmp/job8188771907799980064/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:443
ERROR:CRASH:  5 0x7FF61B30E500 dmArray<dmRender::RenderListEntry>::SetSize D:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk\dlib\array.h:505
ERROR:CRASH:  6 0x7FF61B30C770 dmRender::RenderListAlloc D:\a\defold\defold\engine\render\src\render\render.cpp:214
ERROR:CRASH:  7 0x7FF61B35BAE0 dmRender::FlushTexts D:\a\defold\defold\engine\render\src\render\font_renderer.cpp:1110
ERROR:CRASH:  8 0x7FF61B2C9A40 dmGameSystem::RenderTextNodes D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_gui.cpp:978
ERROR:CRASH:  9 0x7FF61B2CD790 dmGameSystem::RenderNodes D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_gui.cpp:1807
ERROR:CRASH: 10 0x7FF61B341940 dmGui::RenderScene D:\a\defold\defold\engine\gui\src\gui.cpp:1519
ERROR:CRASH: 11 0x7FF61B2CE370 dmGameSystem::CompGuiRender D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_gui.cpp:2130
ERROR:CRASH: 12 0x7FF61B329650 dmGameObject::Render D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2626
ERROR:CRASH: 13 0x7FF61B409980 dmGameSystem::CompCollectionProxyRender D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_collection_proxy.cpp:322
ERROR:CRASH: 14 0x7FF61B329650 dmGameObject::Render D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2626
ERROR:CRASH: 15 0x7FF61B394720 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1586
ERROR:CRASH: 16 0x7FF61B38F9F0 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2094
ERROR:CRASH: 17 0x7FF61B395130 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83
ERROR:CRASH: 18 0x7FF61B2D0120 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148
ERROR:CRASH: 19 0x7FF61B645ED4 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 20 0x7FF8B56F7020 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 21 0x7FF8B76C2630 RtlUserThreadStart <unknown>:0
```
[_crash.zip](https://github.com/defold/defold/files/9084803/_crash.zip)
[DefoldRendererEarlyOut.zip](https://github.com/defold/defold/files/9084804/DefoldRendererEarlyOut.zip)

### PR DESCRIPTION
**Pull request by Jhonnyg**
This fixes an issue with text not always rendering when skipping a frame, for instance during an early out in the render script.

Fixes #6788 

Related: https://github.com/defold/defold/pull/5597

### CODE REVIEW

File: engine/render/src/render/font_renderer.cpp [hunk 1]
```diff
@@ -1129,7 +1130,7 @@ namespace dmRender
         }
 
         // Always update after flushing
-        text_context.m_TextEntriesFlushed = text_context.m_TextEntries.Size();
+        text_context.m_TextEntriesFlushed = count;
```
Comment (Jhonnyg) [inline engine/render/src/render/font_renderer.cpp:1133]: The problem is/was:
We always say that we flushed all the text entries, but the m_TextEntriesFlushed is only reset when we actually do the rendering inside the FontRenderListDispatch function. When we skip a frame (or if no texts are drawn), this value will remain the same between frames, so the m_TextEntriesFlushed will still indicate that we already flushed the texts even though we technically never did.

**Review by JCash — DISMISSED** [review]
