### PR TITLE
Fixed an issue where files larger than 2GB couldn’t be read on windows

### LINKED ISSUE #11060: Crash on Launch When Compress Archive is Disabled (Windows Only)
**Description:**
This is a platform-specific issue that occurs only on Windows.
When the _Compress Archive_ property in the project settings is unchecked (i.e., build archive compression is disabled), the resulting build crashes immediately upon launch.

**Steps to Reproduce:**
1. Open your project settings (file game.project).
2. Locate the _Compress Archive_ property.
3. By default, this checkbox is enabled. Uncheck the _Compress Archive_ property.
4. Build the project for the Windows 64-bit platform.
5. Launch the resulting build executable.

**Expected Behavior:**
The built executable should run and launch without errors, even when _Compress Archive_ is disabled.

**Actual Behavior:**
The executable crashes immediately after launch.

**Environment:**
- Engine version: 1.10.3
- Platform: Windows 10 64-bit
- Architecture: x86 Intel PC

### PR DESCRIPTION
**Pull request by AGulev**
This PR fixes the issue where having an `arcd` archive larger than 2 GB on Windows results in a runtime error:
```
ERROR:RESOURCE: Path to small to fit into buffer: game.arcd
ERROR:RESOURCE: Failed to mount base archive: -1000 for mount archive://game.dmanifest
WARNING:RESOURCE: No resource loaders mounted that could match uri archive:game.dmanifest
```

Fix https://github.com/defold/defold/issues/11060

### CODE REVIEW

File: engine/resource/src/providers/provider_archive.cpp [hunk 1]
```diff
@@ -62,12 +62,12 @@ namespace dmResourceProviderArchive
         char mount_archive_data_path[DMPATH_MAX_PATH];
         if (dmSys::RESULT_OK != dmSys::ResolveMountFileName(mount_archive_index_path, sizeof(mount_archive_index_path), archive_index_path))
         {
-            dmLogError("Path to small to fit into buffer: %s", archive_index_path);
+            dmLogError("File doesn’t exist or can’t be read: %s", archive_index_path);
```
Comment (AGulev) [inline engine/resource/src/providers/provider_archive.cpp:65]: Better error message

File: engine/dlib/src/dlib/sys_posix.cpp [hunk 2]
```diff
@@ -977,8 +977,13 @@ namespace dmSys
             return true;
         }
 #endif
+#ifdef _WIN32
+        struct _stat64 file_stat;
+        return _stat64(path, &file_stat) == 0;
+#else
         struct stat file_stat;
```
Comment (AGulev) [inline engine/dlib/src/dlib/sys_posix.cpp:984]: On windows POSIX compatible function `stat()` limited to 32 bit
CleanShot 2025-08-06 at 22 15 41@2x
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=msvc-170

**Review by britzl — APPROVED** [review]
