### PR TITLE
Issue 5655: Alignment fix for basis structs on Amazon Fire

### LINKED ISSUE #5655: Crash in Basis Universal when transcoding image
https://forum.defold.com/t/blank-project-with-a-single-texture-crashes-on-amazon-fire-v1-2-180/67823

The error is a SIGBUS Illegal Alignment.

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

**Comment by JCash** [comment]
Note: The build fails on formatting errors in files I haven't changed.

**Comment by JCash** [comment]
Also reported in the main repo here:
https://github.com/BinomialLLC/basis_universal/pull/209

File: engine/dlib/src/basis/transcoder/basisu_transcoder_uastc.h [hunk 1]
```diff
@@ -5,8 +5,8 @@
 namespace basist
 {
 	struct color_quad_u8
-	{ 
-		uint8_t m_c[4]; 
+	{
+		uint8_t m_c[4];
```
Comment (JCash) [inline engine/dlib/src/basis/transcoder/basisu_transcoder_uastc.h:9]: Accidental whitespace changes. Sorry.

**Review by britzl — APPROVED** [review]
