### PR TITLE
Forward the timeout from the http request to the DNS lookup

### LINKED ISSUE #5176: Timeout is ignored for DNS lookups
When there is no Internet connection the timeout seconds are ignored, and instead 60 seconds of time is used. Instead the timeout time should be used when there is no Internet connection.

Example

```	
	http.request("https://www.google.com/", "GET", function(self, id, response)
		pprint(response)
	end, nil, nil, {timeout = 1})
```	
Run this with no Internet connection (tested on Windows 10) instead of timing out after 1 second, it takes 60 seconds to time out.
```
ERROR:SCRIPT: Unable to create HTTP connection to 'https://www.google.com/'. No route to host?
WARNING:DLIB: Profiler Message.Dispatch @__http_worker_1 took 60.021 seconds
DEBUG:SCRIPT: 
{ --[[000001CE1F3CA9F0]]
  status = 0,
  response = "",
  headers = { } --[[000001CE1F3CAA80]]
}
```

### PR DESCRIPTION
**Pull request by britzl**
Fixes #5176

### CODE REVIEW

File: engine/dlib/src/dlib/http_client.cpp [hunk 1]
```diff
@@ -237,21 +237,26 @@ namespace dmHttpClient
...
 
     HClient New(const NewParams* params, const char* hostname, uint16_t port, bool secure)
     {
         dmSocket::Address address;
 
+
         if (params->m_DNSChannel)
         {
-            if (dmDNS::GetHostByName(hostname, &address, params->m_DNSChannel) != dmDNS::RESULT_OK)
+            dmLogError("http_client NEW request dmDNS::GetHostByName timeout: %i", params->m_RequestTimeout);
```
Comment (JCash) [inline engine/dlib/src/dlib/http_client.cpp:251]: Debug prints?

**Review by JCash — DISMISSED** [review]
Looks good, but some debug prints should be removed

File: engine/dlib/src/dlib/http_client.cpp (hunk 1 above)
Comment (britzl) [reply engine/dlib/src/dlib/http_client.cpp:251]: Oops, yes
