### PR TITLE
Release pressed keys when regaining focus in HTML5 builds

### LINKED ISSUE #3186: If a key is held down while HTML5 build has focus and then another window gains focus the key continues to say it is held down (DEF-2787)
Description:

Steps to reproduce:

Expected result:

Actual result:

### PR DESCRIPTION
**Pull request by britzl**
If a key is pressed while the game lost focus and that key is released while not in focus the event will not be received for the key release. This will result in the key remaining in the pressed state when the game regains focus. To fix this we set all pressed keys to released before regaining focus.

Fixes #3186

### CODE REVIEW

File: engine/glfw/js/library_glfw.js [hunk 1]
```diff
@@ -158,11 +158,11 @@ var LibraryGLFW = {
           }
       },
 
-      removeEventListenerCanvas:function (type, listener, useCapture) {
-          if (typeof Module['canvas'] !== 'undefined') {
-              Module['canvas'].removeEventListener(type, listener, useCapture);
-          }
-      },
+    removeEventListenerCanvas:function (type, listener, useCapture) {
```
Comment (britzl) [inline engine/glfw/js/library_glfw.js:161]: Fixed indentation

**Review by JCash — APPROVED** [review]
