### PR TITLE
Fix issue where profiler doesn't work after reboot

### LINKED ISSUE #9427: Profiler is not working if build was relaunched by Defold Editor
**Describe the bug (REQUIRED)**
The profiler is not working if the game build was relaunched from Editor. I mean If the game is running, we returning to the Defold Editor and run Build command. The new instance of build can be attached with profiler in this case

**To Reproduce (REQUIRED)**
1. Run game
2. Click Profiler - it's working
3. Relaunch game without close it from Defold Editor
4. Click Profiler - it's not working
5. Close game before start - it's working

**Expected behavior (REQUIRED)**
Profiler is working

**Defold version (REQUIRED):**
Tested on 1.8.0 and 1.9.2, both affected

**Platforms (REQUIRED):**
Tested on MacOS

**Minimal repro case project (OPTIONAL):**
[issue_profiler.zip](https://github.com/user-attachments/files/16993884/issue_profiler.zip)

**Screenshots (OPTIONAL):**

https://github.com/user-attachments/assets/4de0f419-cb8b-49b9-adc1-95f7217cf102

### LINKED ISSUE #10671: Rebuild game from Editor and sys.reboot breaks Profiler
**Describe the bug (REQUIRED)**
If the game was build from editor while previous instance is running (not manually closed)
or used `sys.reboot()` before, profiler will not work

**To Reproduce (REQUIRED)**
1. Run game, press "R"
2. Profiler working
3. Rebuild game or click to `sys.reboot()`
4. Profiler breaks

**Expected behavior (REQUIRED)**
Profiler works

**Defold version (REQUIRED):**
1.10.1

**Platforms (REQUIRED):**
Tested on MacOS

**Minimal repro case project (OPTIONAL):**

[reboot_game_issue.zip](https://github.com/user-attachments/files/20232781/reboot_game_issue.zip)

https://github.com/user-attachments/assets/42f9f434-9e5a-4d97-9054-958ed69c5f8c

### PR DESCRIPTION
**Pull request by AGulev**
Make sure that the profiler shows the correct scope and property names after the engine reboot.

Fix https://github.com/defold/defold/issues/10671
Fix https://github.com/defold/defold/issues/9427

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -1857,7 +1874,7 @@ namespace dmEngine
 
                 if (esc_pressed || !dmGraphics::GetWindowStateParam(engine->m_GraphicsContext, dmPlatform::WINDOW_STATE_OPENED))
                 {
-                    engine->m_Alive = false;
+                    Exit(engine, 0);
```
Comment (AGulev) [inline engine/engine/src/engine.cpp:1877]: we need to use `Exit` here so `engine->m_RunResult.m_Action` updated as well

File: engine/engine/src/engine.h [hunk 2]
```diff
@@ -23,12 +23,12 @@ namespace dmEngine
...
-	    RESULT_REBOOT   =  1,
-	    RESULT_EXIT     = -1,
-	};
+    enum UpdateResult
+    {
+        RESULT_OK       =  0,
+        RESULT_REBOOT   =  1,
+        RESULT_EXIT     = -1,
+    };
 };
```
Comment (AGulev) [inline engine/engine/src/engine.h:32]: Tabs -> spaces

File: engine/extension/src/dmsdk/extension/extension.h [hunk 3]
```diff
@@ -98,11 +98,28 @@ typedef enum ExtensionCallbackType
...
+    EXTENSION_APP_REBOOT   =  1,
+    EXTENSION_APP_EXIT     = -1,
+} AppExitStatus;
 
 typedef struct ExtensionAppParams
 {
-    HConfigFile m_ConfigFile; // Deprecated. Here for backwards compatibility
-
+    HConfigFile     m_ConfigFile; // Deprecated. Here for backwards compatibility
+    AppExitStatus   m_ExitStatus;
```
Comment (AGulev) [inline engine/extension/src/dmsdk/extension/extension.h:122]: If/when I merge this PR I'll run `./scripts/build.py gen_sdk_source` separately in another PR.

File: engine/profiler/src/profiler.cpp [hunk 4]
```diff
@@ -885,7 +888,11 @@ static dmExtension::Result AppFinalizeProfiler(dmExtension::AppParams* params)
     }
 
     dmProfiler::SetEnabled(false);
-    dmProfile::Finalize();
+
+    if (params->m_ExitStatus != EXTENSION_APP_REBOOT)
+    {
+        dmProfile::Finalize();
+    }
```
Comment (AGulev) [inline engine/profiler/src/profiler.cpp:895]: The actual fix. Just avoid finalization on restart

File: engine/extension/src/dmsdk/extension/extension.h (hunk 3 above)
Comment (JCash) [reply engine/extension/src/dmsdk/extension/extension.h:122]: Theoretically, it's nice to also have the actual "exit code", but let's wait with that until someone asks for it.

File: engine/profiler/src/profiler.cpp [hunk 5]
```diff
@@ -885,7 +888,11 @@ static dmExtension::Result AppFinalizeProfiler(dmExtension::AppParams* params)
     }
 
     dmProfiler::SetEnabled(false);
-    dmProfile::Finalize();
+
+    if (params->m_ExitStatus != EXTENSION_APP_REBOOT)
```
[the remark this answers is not in the document]
Comment (JCash) [reply engine/profiler/src/profiler.cpp:892]: I would like to avoid using the structure directly though.
Please add a function like the other sdk functions for accessing this member.

**Review by JCash — CHANGES_REQUESTED** [review]
overall good.
Needs a new sdk function to retrieve the exit status

File: engine/extension/src/dmsdk/extension/extension.hpp [hunk 6]
```diff
@@ -48,6 +48,13 @@ namespace dmExtension {
       return (T)ExtensionParamsGetContext((ExtensionParams*)params, name_hash);
    }
 
+   /*# get the app exit status
+   * @name GetAppExitStatus
+   * @param app_params [type:dmExtension::AppParams*] The app params sent to the extension dmExtension::AppInitialize / dmExtension::AppInitialize
+   * @return status [type:AppExitStatus] engine exit status
+   */
+   dmExtension::AppExitStatus GetAppExitStatus(dmExtension::AppParams* app_params);
```
Comment (JCash) [inline engine/extension/src/dmsdk/extension/extension.hpp]: The `ExtensionAppParamsGetAppExitCode()` is missing from `extension.h` (the C header file).
For these generated apis, we want to treat our C api as the "truth", and only need the ".hpp" files when the generator can't or doesn't do a good job.
(We want minimal maintenance here).

So, move this function to extension.h (and rename accordingly) and regenerate the bindings.
You'll have to implement both:
E.g. in source (here C api calls C++ api):
```
int ExtensionAppParamsSetContext(ExtensionAppParams* params, const char* name, void* context)
{
    return SetContext(&params->m_Impl->m_Contexts, name, context);
}
```

Or vice versa, let C++ api call C api.

**Review by JCash — CHANGES_REQUESTED** [review]
Almost there.
Some rearrangement required for the C api needed.

File: engine/extension/src/dmsdk/extension/extension.hpp (hunk 6 above)
Comment (AGulev) [reply engine/extension/src/dmsdk/extension/extension.hpp]: I hope now I got it right—thank you for your patience.

**Review by JCash — APPROVED** [review]
lgtm
