### PR TITLE
Use AL_BUFFERS_QUEUED to unqueue OpenAL buffers

### LINKED ISSUE #8049: HTML5 sys.reboot() problems with sound Defold 1.6
**Describe the bug (REQUIRED)**
Browser hanging on sys.reboot() 

**To Reproduce (REQUIRED)**
1. Any Sound playing
2. Call sys.reboot() 

**Expected behavior (REQUIRED)**
Application rebooted everything fine

**Defold version (REQUIRED):**
  - 1.6

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - Device: Tested on Chrome and Firefox

**Minimal repro case project (OPTIONAL):**
(https://github.com/Mulderua/defold1.6_bug_with_sys_reboot)

**Screenshots (OPTIONAL):**
[If applicable, add screenshots to help explain your problem.](https://forum.defold.com/uploads/default/original/3X/5/3/530cc77dd5c6bd191345625733a74ce2539d06d4.png)

### PR DESCRIPTION
**Pull request by JCash**
The OpenAL library for HTML5 seems to work a bit differently than the other platforms.
Instead of removing the processed buffers, we remove the queued buffers explicitly.

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/sound/src/devices/device_openal.cpp [hunk 1]
```diff
@@ -118,17 +119,28 @@ namespace dmDeviceOpenAL
...
+
         int iter = 0;
         while (openal->m_Buffers.Size() != openal->m_Buffers.Capacity())
         {
-            int processed;
-            alGetSourcei(openal->m_Source, AL_BUFFERS_PROCESSED, &processed);
-            while (processed > 0) {
+            ALint num_queued = 0;
+            alcProcessContext(openal->m_Context);
+            alGetSourcei(openal->m_Source, AL_BUFFERS_QUEUED, &num_queued);
```
Comment (JCash) [inline engine/sound/src/devices/device_openal.cpp:129]: Use AL_BUFFERS_QUEUED instead.

File: engine/sound/src/devices/device_openal.cpp [hunk 2]
```diff
@@ -139,20 +151,27 @@ namespace dmDeviceOpenAL
 
             if (iter > 1000) {
                 dmLogError("Still buffers in OpenAL. Bailing.");
+                break;
```
Comment (JCash) [inline engine/sound/src/devices/device_openal.cpp:154]: If we've waited so long, we might as well at least try to continue the shutdown sequence.

**Comment by AGulev** [comment]
is it fix for https://github.com/defold/defold/issues/8049

**Review by AGulev — DISMISSED** [review]
