### PR TITLE
Ignore URL query parameters when serving files from the editor

### LINKED ISSUE #6940: Error with Build HTML and URL parameters
### Actual behaviour

When I run a **Build HTML** and start loading a JS script with parameters, I get an error in the **editor**:

    java.nio.file.InvalidPathException: Illegal char <?> at index 17: data/some_file.js?some_param=some_data

Everything works fine without parameters.
Also with the  bundle everything is fine.

### Expected behaviour

Js script with url parameters loaded successfully

### Steps to reproduce

    html5.run([[
        var script = document.createElement('script');
        script.src = './data/some_file.js?some_param=some_data';
        document.body.appendChild(script);
    ]])
    
Run **Build HTML**

[Bug.zip](https://github.com/defold/defold/files/9477343/Bug.zip)

As far as I understand it is related to these issues:
https://github.com/defold/editor2-issues/issues/2220
https://github.com/defold/editor2-issues/issues/2282

<hr/>

<table>
<tr><td>Build time</td><td>2022-08-21T07:05:23.543939</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>28d332c9d67b9c8df35fed1274729322ecfd79f1</td></tr>
<tr><td>Defold engine sha</td><td>c1c0592986a4421f33490422c2af532e533aeca5</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.6.14800 Compatibility Profile Context 22.6.1 30.0.21023.1015</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by britzl**
The webserver in the editor which serves files to a local HTML5 build did not handle URLs containing query parameters. This change removes any query parameters from an URL before looking up a file to serve as response to a GET request.

Fixes #6940

### CODE REVIEW

File: editor/src/clj/editor/pipeline/bob.clj [hunk 1]
```diff
@@ -360,9 +360,10 @@
       {:code 302
        :headers {"Location" (str html5-url-prefix "/index.html")}}
 
-      (let [served-file   (try-resolve-html5-file project url)
+      (let [url-without-query-params  (get (string/split url #"\?") 0)
```
Comment (vlaaad) [inline editor/src/clj/editor/pipeline/bob.clj:363]: It will also fail for URL fragments, right? E.g. `"/foo#some-anchor"`... We could add checking for `#` to the split regex, or we could parse URL and extract the path (assuming `url` here is of the form `/foo/bar?q=1#zoops`):
```clj
(.getPath (java.net.URL. (str "http://" url)))
=> "/foo/bar"

```

**Review by vlaaad — APPROVED** [review]
I think it's good, but can be slightly improved in terms of URL parsing.

File: editor/src/clj/editor/pipeline/bob.clj (hunk 1 above)
Comment (britzl) [reply editor/src/clj/editor/pipeline/bob.clj:363]: Ah, yes, you're right. It might be better to parse it.
