### PR TITLE
Issue 5313: Don't upload font vertex buffer unless it has changed

### LINKED ISSUE #5313: Performance regression when rendering text
**Describe the bug (REQUIRED)**
I noticed that the fix for [this issue](https://github.com/defold/defold/issues/4901) was reverted in [this commit](https://github.com/defold/defold/commit/6fc9dc26fce06c3c85986ed671c134061cd61e73). This severely impacts text rendering performance, especially in Domains of Dusk, which is very text-heavy. I'm curious: Was the fix breaking something else?

This is on an Intel i7 8700, with the built-in iGPU (UHD 630). No other text apart from the one visible on screen is being rendered:
Screenshot 2020-11-05 at 12 02 01

**To Reproduce (REQUIRED)**
1. Render text nodes

**Expected behavior (REQUIRED)**
Text shouldn't be so resource-intensive.

**Defold version (REQUIRED):**
  - 1.2.174

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: 10.15.7

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/render/src/render/font_renderer.cpp [hunk 1]
```diff
@@ -1047,15 +1048,23 @@ namespace dmRender
             case dmRender::RENDER_LIST_OPERATION_END:
                 {
                     uint32_t buffer_size = sizeof(GlyphVertex) * text_context.m_VertexIndex;
-                    dmGraphics::SetVertexBufferData(text_context.m_VertexBuffer, 0, 0, dmGraphics::BUFFER_USAGE_STREAM_DRAW);
-                    dmGraphics::SetVertexBufferData(text_context.m_VertexBuffer, buffer_size, text_context.m_ClientBuffer, dmGraphics::BUFFER_USAGE_STREAM_DRAW);
-                    text_context.m_VerticesFlushed = text_context.m_VertexIndex;
+                    dmhash_t hash = dmHashBuffer64(text_context.m_ClientBuffer, buffer_size);
+                    if (hash != text_context.m_PreviousHash)
```
Comment (JCash) [inline engine/render/src/render/font_renderer.cpp:1052]: Create a hash of the vertex data we want to upload.
If it differs from the previously uploaded data, then we upload again.

Comment (JCash) [reply engine/render/src/render/font_renderer.cpp:1052]: The way it differs from the previous attempt is that this always checks the entire buffer whilst the last "fix" only checked if the number of vertices were the same (! which of cours was very silly of me).

File: engine/render/src/render/font_renderer.cpp [hunk 2]
```diff
@@ -1047,15 +1048,23 @@ namespace dmRender
...
+                        dmGraphics::SetVertexBufferData(text_context.m_VertexBuffer, buffer_size, text_context.m_ClientBuffer, dmGraphics::BUFFER_USAGE_STREAM_DRAW);
+                        text_context.m_VerticesFlushed = text_context.m_VertexIndex;
+                        text_context.m_PreviousHash = hash;
+                    }
                     DM_COUNTER("FontVertexBuffer", buffer_size);
                 }
                 break;
-            default:
-                assert(params.m_Operation == dmRender::RENDER_LIST_OPERATION_BATCH);
+            case dmRender::RENDER_LIST_OPERATION_BATCH:
```
Comment (JCash) [inline engine/render/src/render/font_renderer.cpp:1063]: No need to assert if we handle the case in it's correct switch case.

File: engine/render/src/render/font_renderer.cpp [hunk 3]
```diff
@@ -1047,15 +1048,23 @@ namespace dmRender
...
                 CreateFontRenderBatch(render_context, params.m_Buf, params.m_Begin, params.m_End);
```
Comment (JCash) [inline engine/render/src/render/font_renderer.cpp:1064]: Another (more complicated) optimization would be to avoid regenerating the local vertex buffer if a text entry has the same position and nothing in it has changed. See the "CreateFontRenderBatch" in the issue.

**Review by britzl — APPROVED** [review]
Nice!
