### PR TITLE
Fix profiler step blinking

### LINKED ISSUE #7017: Profiler step blinking
### Expected behaviour
Can see step info every frame.

### Actual behaviour
No step details
Sometimes step info blinking.

### Steps to reproduce
1)toggle profiler by button click
```lua
profiler.enable_ui(self.views.btn_profiler.show_profiler)
```
2)No step details

2.1)If i resize window i see blinking
<hr/>

<table>
<tr><td>Build time</td><td>2022-09-14T09:14:36.712371</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>905234d8da2e642f1075c73aaa1bfb72e49199e3</td></tr>
<tr><td>Defold engine sha</td><td>905234d8da2e642f1075c73aaa1bfb72e49199e3</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14756 Compatibility Profile Context 20.40.64 27.20.14064.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

https://user-images.githubusercontent.com/2655263/192838746-cb0e7451-e7ba-4b1a-ad4b-fdc3c4058bfc.mp4

### PR DESCRIPTION
**Pull request by AGulev**
Fix the issue where the profiler blinks when the property Update Frequency other than 0.

Fix https://github.com/defold/defold/issues/7017
## PR checklist

* [x] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -1755,6 +1754,7 @@ namespace dmEngine
 
         for (uint32_t i = 0; i < num_steps; ++i)
         {
+            DM_PROFILE("Step");
             // We currently cannot separate the update from the render,
             // since some of the update is done in the render updates (e.g. sprite transforms)
```
Comment (AGulev) [inline engine/engine/src/engine.cpp:1759]: When Update Frequency isn’t 0 we don’t do a step. We just calculate time step calling `CalcTimeStep` (see 1754) and `num_steps` depends on it. If `num_steps` is 0 - we don’t really do a step.

**Review by britzl — APPROVED** [review]

File: engine/engine/src/engine.cpp [hunk 2]
```diff
@@ -1755,6 +1754,7 @@ namespace dmEngine
 
         for (uint32_t i = 0; i < num_steps; ++i)
         {
+            DM_PROFILE("Step");
```
Comment (JCash) [inline engine/engine/src/engine.cpp:1757]: I would have suggested to move it to StepFrame instead
