### PR TITLE
Fix for out of bounds assert when rendering uninitialized render entries

### LINKED ISSUE #6518: Crash after sending a disable message to a sprite
**Describe the bug (REQUIRED)**
The project crashes after a disable message is sent to a specific sprite component, with this message:
Assertion failed: i < Size(), file D:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 478

**To Reproduce (REQUIRED)**
I was only able to produce this crash in this specific project. The version in crashing_project.zip should crash automatically as soon as the collection main/main_menu.collection is loaded and the script scanner.script is initialised, sending the disable message.

A minimal version in crash_mimimal.zip crashes less often. It can be reliably triggered by clicking away from the project window as it is loading. Removing more things from the project made me unable to reproduce it, but I haven't found a spečcific trigger.

**Expected behavior (REQUIRED)**
The sprite component is disabled as normal.

**Defold version (REQUIRED):**
  - Version 1.3.1

**Platforms (REQUIRED):**
Windows 10 (tested on two different machines)

**Minimal repro case project:**
Full project: [crashing_project.zip](https://github.com/defold/defold/files/8472444/crashing_project.zip)
Minimal version: [crash_mimimal.zip](https://github.com/defold/defold/files/8472447/crash_mimimal.zip)

**Logs (OPTIONAL):**
[_crash.zip](https://github.com/defold/defold/files/8472446/_crash.zip)

**Workaround (OPTIONAL):**
Sending the disable message after a set time stops the project from crashing. So does adding another sprite component or removing the disable message (perhaps I could hide the sprite by setting its Z-level).
I have tried bundling the project for Android and saw no crash there.

**Additional context (OPTIONAL):**
Slightly more detailed info is here:
https://forum.defold.com/t/crash-after-sending-a-disable-message-to-a-sprite/70703

### PR DESCRIPTION
**Pull request by JCash**
This fixes a render related crash which may happen if sprites are disabled in the `init()` lifecycle function.

Fixes #6518

### CODE REVIEW

File: engine/render/src/render/render.cpp [hunk 1]
```diff
@@ -228,6 +225,10 @@ namespace dmRender
             render_context->m_RenderList.SetSize(list_size);
         }
```
Comment (JCash) [inline engine/render/src/render/render.cpp:226]: We return the unused entries here.

File: engine/render/src/render/render.cpp [hunk 2]
```diff
@@ -228,6 +225,10 @@ namespace dmRender
...
 
+        if (end == begin) {
+            return;
+        }
```
Comment (JCash) [inline engine/render/src/render/render.cpp:230]: We need an opportunity to return the unused entries to the list before we early out.

**Review by britzl — APPROVED** [review]
