### PR TITLE
Remove partially cached HTTP response on timeout

### LINKED ISSUE #7034: HTTP cache corruption
**Describe the bug (REQUIRED)**
If a timeout occurs while receiving a response during a call to http.request() the engine will write a partial file to the HTTP cache.

**To Reproduce (REQUIRED)**
1. Make a http.request() call with a timeout option that is short enough that a timeout will happen while receiving the response
2. Check the http cache (on macOS: ~/Library/Application Support/Defold/http-cache)
4. See that file is only partially downloaded

**Expected behavior (REQUIRED)**
If a timeout occurs while receiving a response no file should be written to the cache

**Defold version (REQUIRED):**
  - Version 1.3.6

**Platforms (REQUIRED):**
 - Platforms: All (except html5?)

**Minimal repro case project (OPTIONAL):**

**Workaround (OPTIONAL):**
Chose a long enough timeout. Or request file again with the `ignore_cache` option.

### PR DESCRIPTION
**Pull request by britzl**
This fixes an issue where a network request is interrupted due to a network error or timeout still left a partial response stored in the HTTP cache. Subsequent requests for the same resource would in such a case return the partial and most likely corrupted response stored in the cache. The cache will now remove any partial response on error.

Fixes #7034

### CODE REVIEW

**Comment by britzl** [comment]
## PR checklist (remove before merging)

* [X] Prepared the PR for release notes
	* [X] Proper description of feature or fix (see example x?)
	* [x] Added a #fixes ### if it fixes an issue
	* [x] Assigned issue to a project
* [ ] Added engine and/or editor unit tests
* [ ] ~Added documentation for public API changes~
* [ ] ~Is this a new feature?~
	* [ ] ~Added or updated manual entry~

File: engine/dlib/src/test/test_httpcache.cpp [hunk 1]
```diff
@@ -155,6 +155,37 @@ TEST_F(dmHttpCacheTest, Simple)
...
+    // Check that there is no stored etag
+    char tag_buffer[16];
+    r = dmHttpCache::GetETag(cache, "uri", tag_buffer, sizeof(tag_buffer));
+    ASSERT_EQ(dmHttpCache::RESULT_NO_ENTRY, r);
+
+    // Free
+    r = dmHttpCache::Close(cache);
+    ASSERT_EQ(dmHttpCache::RESULT_OK, r);
+}
+
```
Comment (JCash) [inline engine/dlib/src/test/test_httpcache.cpp:188]: 👍

**Review by JCash — APPROVED** [review]
