### PR TITLE
Fixed broken gizmo manipulations for Model component

### LINKED ISSUE #8756: Wrong axis translation after model rotation
[Запись экрана от 04.04.2024 11:37:22.webm](https://github.com/defold/defold/assets/21050233/524359d2-fd53-4d42-944e-8dd7a4048754)

**To Reproduce (REQUIRED)**
1. Open Basic 3d Project
2. Rotate cube to Y=90
3. Translate cube to X or Z coordinates

**Expected behavior (REQUIRED)**
Object need translated to where arrow is look

**Defold version (REQUIRED):**
  - Version 1.7.0
  - 
**Platforms (REQUIRED):**
 - OS: Ubuntu, Mac OS

### PR DESCRIPTION
**Pull request by matgis**
* Fixed a regression where the move gizmo would translate rotated Models along the wrong axis.
* Fixed a regression where the manipulator gizmo would not be properly aligned to Model pivot points.

Fixes #8756

### CODE REVIEW

**Comment by AGulev** [comment]
Does the fix work for both modes? 
CleanShot 2024-04-08 at 18 03 25@2x

File: editor/src/clj/editor/model_scene.clj [hunk 1]
```diff
@@ -236,12 +236,11 @@
...
-        renderable (first renderables)
-        node-id (:node-id renderable)
-        request-id [::outline node-id]]
-    (assert (= pass/outline pass))
-    (render/render-aabb-outline gl render-args request-id renderables rcount)))
+  (when (= pass/outline (:pass render-args))
+    (let [renderable (first renderables)
+          node-id (:node-id renderable)
+          request-id [::outline node-id]]
+      (render/render-aabb-outline gl render-args request-id renderables rcount))))
```
Comment (matgis) [inline editor/src/clj/editor/model_scene.clj:243]: Mostly indentation. Wrapped in `(when (= pass/outline (:pass render-args)) ...)` instead of asserting on the pass. We needed to add the renderable to `pass/selection` or `pass/opaque-selection` for it to be considered selectable.

File: editor/src/clj/editor/model_scene.clj [hunk 2]
```diff
@@ -355,8 +352,8 @@
      :renderable {:render-fn render-outline
                   :tags #{:model :outline}
                   :batch-key nil ; Batching is disabled in the editor for simplicity.
-                  :select-batch-key model-scene-resource-node-id
-                  :passes [pass/outline]}
+                  :select-batch-key :not-rendered ; The render-fn only does anything during the outline pass.
+                  :passes [pass/outline pass/opaque-selection]} ; Include in a selection pass to ensure it can be selected and manipulated.
```
Comment (matgis) [inline editor/src/clj/editor/model_scene.clj:356]: It seems the correct way to do this is to have the root `scene` include the `:node-id` of the `ResourceNode` (i.e. the `ModelSceneNode` in our case), and include a `:renderable` that is assigned to either `pass/selection` or `pass/opaque-selection`. It doesn't have to render anything, but this ensures it can be included in the `:selected-renderables` output of the `SceneRenderer`.

None of the `:children` scenes should specify a `:node-id`, unless they are actually from different nodes in the graph that can be transformed independently using the gizmo.

**Review by Jhonnyg — APPROVED** [review]

File: editor/src/clj/editor/model_scene.clj [hunk 3]
```diff
@@ -355,8 +352,8 @@
      :renderable {:render-fn render-outline
                   :tags #{:model :outline}
                   :batch-key nil ; Batching is disabled in the editor for simplicity.
-                  :select-batch-key model-scene-resource-node-id
-                  :passes [pass/outline]}
+                  :select-batch-key :not-rendered ; The render-fn only does anything during the outline pass.
```
Comment (vlaaad) [inline editor/src/clj/editor/model_scene.clj:355]: A bit confusing, at first I thought this is a specially recognized key, but it's not :)

**Review by vlaaad — APPROVED** [review]
LGTM!
