### PR TITLE
Make sure ASTC used in maximum possible cases in HTML5 bundle

### LINKED ISSUE #11416: Low texture quality on Android Chrome due to ETC2_RGBA fallback (BasisU compression)
**Describe the bug**
Textures appear **pixelated and jagged on Android (Chromium-based browsers)** when using **BasisU compression** in Defold HTML5 builds.
The issue occurs because Defold’s WebGL runtime falls back to **ETC2_RGBA** transcoding on Android Chrome, which produces noticeably lower visual quality compared to **BC7** (desktop/iOS) or **ASTC** (on some devices).

On the same build:

* Textures look perfect on **desktop browsers (BC7)** and **iOS Safari**.
* Textures also look correct on **Android Firefox** (not Chromium-based).

This confirms the problem is specific to Chromium’s WebGL renderer on Android, which currently prevents Defold from using ASTC ([due to a Chromium-side issue](https://issues.chromium.org/issues/434983812)) and forces a fallback to ETC2_RGBA.

**To Reproduce**

1. Clone the test repository:
   👉 [https://github.com/NANAMINER/Texture-Conpression-Text-Defold-/tree/main](https://github.com/NANAMINER/Texture-Conpression-Text-Defold-/tree/main)
2. Build and run the project as **HTML5**.
3. Open the resulting build on **Android Chrome**:

   * Observe visible compression artifacts, pixelated edges, and jagged details.
4. Open the same build in **Android Firefox** or **desktop Chrome/macOS Safari**:

   * Textures look smooth and correct.

You can also test directly here:
👉 [https://nanaminer.itch.io/texture-compression-test](https://nanaminer.itch.io/texture-compression-test)

**Expected behavior**
Textures should look visually consistent across platforms.
Ideally, Defold should allow transcoding to **ASTC** when supported on Android devices, or provide an option to force ASTC when stable, instead of always falling back to ETC2_RGBA.

**Defold version:**

* Version: **1.11.1 (stable)**

**Platforms:**

* Platform: **HTML5 (Web build)**
* OS: **Android 16**
* Device: **Google Pixel 8 Pro** (also reproducible on other Android devices)
* Browser: **Google Chrome 141.0.7390.122 (Chromium-based)**
* Works fine on: **Firefox for Android**, **macOS Safari**, **Windows Chrome**

**Minimal repro case project:**
[https://github.com/NANAMINER/Texture-Conpression-Text-Defold-/tree/main](https://github.com/NANAMINER/Texture-Conpression-Text-Defold-/tree/main)

**Online demo:**
[https://nanaminer.itch.io/texture-compression-test](https://nanaminer.itch.io/texture-compression-test)

**Display device info logs:**
Logs captured from `display.get_info()` for comparison:

**Chrome on macOS:**

```
Running...
dmloader.js:911 
dmloader.js:908 INFO:DLIB: Log server started on port 0

dmloader.js:908 INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'

dmloader.js:908 INFO:ENGINE: Defold Engine 1.11.1 (1ba9e1a)

TextureCompression_wasm.js:1         Made with Defold            https://www.defold.com
dmloader.js:908 INFO:PROFILER: Skipped ProfilerJS profiler due to setting profiler.performance_timeline_enabled

dmloader.js:908 INFO:GRAPHICS: Device: OpenGL

dmloader.js:908 INFO:GRAPHICS: Renderer: WebKit WebGL

dmloader.js:908 INFO:GRAPHICS: Version: OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))

dmloader.js:908 INFO:GRAPHICS: Vendor: WebKit

dmloader.js:908 INFO:GRAPHICS: Extensions:

dmloader.js:908 INFO:GRAPHICS:   EXT_clip_control

dmloader.js:908 INFO:GRAPHICS:   EXT_color_buffer_float

dmloader.js:908 INFO:GRAPHICS:   EXT_color_buffer_half_float

dmloader.js:908 INFO:GRAPHICS:   EXT_conservative_depth

dmloader.js:908 INFO:GRAPHICS:   EXT_depth_clamp

dmloader.js:908 INFO:GRAPHICS:   EXT_disjoint_timer_query_webgl2

dmloader.js:908 INFO:GRAPHICS:   EXT_float_blend

dmloader.js:908 INFO:GRAPHICS:   EXT_polygon_offset_clamp

dmloader.js:908 INFO:GRAPHICS:   EXT_texture_compression_bptc

dmloader.js:908 INFO:GRAPHICS:   EXT_texture_compression_rgtc

dmloader.js:908 INFO:GRAPHICS:   EXT_texture_filter_anisotropic

dmloader.js:908 INFO:GRAPHICS:   EXT_texture_norm16

dmloader.js:908 INFO:GRAPHICS:   KHR_parallel_shader_compile

dmloader.js:908 INFO:GRAPHICS:   NV_shader_noperspective_interpolation

dmloader.js:908 INFO:GRAPHICS:   OES_texture_float_linear

dmloader.js:908 INFO:GRAPHICS:   WEBGL_blend_func_extended

dmloader.js:908 INFO:GRAPHICS:   WEBGL_clip_cull_distance

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_astc

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_etc

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_etc1

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_s3tc

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_s3tc_srgb

dmloader.js:908 INFO:GRAPHICS:   WEBGL_debug_renderer_info

dmloader.js:908 INFO:GRAPHICS:   WEBGL_debug_shaders

dmloader.js:908 INFO:GRAPHICS:   WEBGL_lose_context

dmloader.js:908 INFO:GRAPHICS:   WEBGL_multi_draw

dmloader.js:908 INFO:GRAPHICS:   WEBGL_polygon_mode

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_clip_control

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_color_buffer_float

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_color_buffer_half_float

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_conservative_depth

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_depth_clamp

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_disjoint_timer_query_webgl2

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_float_blend

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_polygon_offset_clamp

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_texture_compression_bptc

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_texture_compression_rgtc

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_texture_filter_anisotropic

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_texture_norm16

dmloader.js:908 INFO:GRAPHICS:   GL_KHR_parallel_shader_compile

dmloader.js:908 INFO:GRAPHICS:   GL_NV_shader_noperspective_interpolation

dmloader.js:908 INFO:GRAPHICS:   GL_OES_texture_float_linear

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_blend_func_extended

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_clip_cull_distance

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_astc

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_etc

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_etc1

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_s3tc

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_s3tc_srgb

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_debug_renderer_info

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_debug_shaders

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_lose_context

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_multi_draw

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_polygon_mode

dmloader.js:908 INFO:GRAPHICS: Context features:

dmloader.js:908 INFO:GRAPHICS:   CONTEXT_FEATURE_MULTI_TARGET_RENDERING

dmloader.js:908 INFO:GRAPHICS:   CONTEXT_FEATURE_TEXTURE_ARRAY

dmloader.js:908 INFO:ENGINE: Loading data from: archive:game.dmanifest

dmloader.js:908 INFO:LIVEUPDATE: Found no legacy liveupdate zip file references

dmloader.js:908 INFO:LIVEUPDATE: Found no legacy liveupdate index paths

dmloader.js:908 INFO:SOUND: Info

dmloader.js:908 INFO:SOUND:   nSamplesPerSec:   48000

dmloader.js:908 INFO:SOUND:   DSP backend: Fallback

dmloader.js:908 INFO:SOUND: Sound

dmloader.js:908 INFO:SOUND:   nSamplesPerSec:   48000

dmloader.js:908 INFO:SOUND:        useThread:   0

dmloader.js:908 INFO:ENGINE: Initialised sound device 'default'

dmloader.js:908 INFO:GRAPHICS: Transcoding: /main/atlas.texturec from 21 to 6 (TEXTURE_FORMAT_RGBA_BC7 -> cTFBC7_RGBA)
```

**Chrome on Android:**

```
Running...
dmloader.js:908 WARNING:DLIB: No territory detected in language string: "ru"

dmloader.js:908 INFO:DLIB: Log server started on port 0

dmloader.js:908 INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'

dmloader.js:908 INFO:ENGINE: Defold Engine 1.11.1 (1ba9e1a)

TextureCompression_wasm.js:1         Made with Defold            https://www.defold.com
dmloader.js:908 WARNING:DLIB: No territory detected in language string: "ru"

dmloader.js:908 INFO:PROFILER: Skipped ProfilerJS profiler due to setting profiler.performance_timeline_enabled

dmloader.js:908 INFO:GRAPHICS: Device: OpenGL

dmloader.js:908 INFO:GRAPHICS: Renderer: WebKit WebGL

dmloader.js:908 INFO:GRAPHICS: Version: OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))

dmloader.js:908 INFO:GRAPHICS: Vendor: WebKit

dmloader.js:908 INFO:GRAPHICS: Extensions:

dmloader.js:908 INFO:GRAPHICS:   EXT_color_buffer_float

dmloader.js:908 INFO:GRAPHICS:   EXT_float_blend

dmloader.js:908 INFO:GRAPHICS:   EXT_texture_filter_anisotropic

dmloader.js:908 INFO:GRAPHICS:   EXT_texture_norm16

dmloader.js:908 INFO:GRAPHICS:   OES_texture_float_linear

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_astc

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_etc

dmloader.js:908 INFO:GRAPHICS:   WEBGL_compressed_texture_etc1

dmloader.js:908 INFO:GRAPHICS:   WEBGL_debug_renderer_info

dmloader.js:908 INFO:GRAPHICS:   WEBGL_debug_shaders

dmloader.js:908 INFO:GRAPHICS:   WEBGL_lose_context

dmloader.js:908 INFO:GRAPHICS:   WEBGL_multi_draw

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_color_buffer_float

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_float_blend

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_texture_filter_anisotropic

dmloader.js:908 INFO:GRAPHICS:   GL_EXT_texture_norm16

dmloader.js:908 INFO:GRAPHICS:   GL_OES_texture_float_linear

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_astc

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_etc

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_compressed_texture_etc1

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_debug_renderer_info

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_debug_shaders

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_lose_context

dmloader.js:908 INFO:GRAPHICS:   GL_WEBGL_multi_draw

dmloader.js:908 INFO:GRAPHICS: Context features:

dmloader.js:908 INFO:GRAPHICS:   CONTEXT_FEATURE_MULTI_TARGET_RENDERING

dmloader.js:908 INFO:GRAPHICS:   CONTEXT_FEATURE_TEXTURE_ARRAY

dmloader.js:908 INFO:ENGINE: Loading data from: archive:game.dmanifest

dmloader.js:908 INFO:LIVEUPDATE: Found no legacy liveupdate zip file references

dmloader.js:908 INFO:LIVEUPDATE: Found no legacy liveupdate index paths

dmloader.js:908 INFO:SOUND: Info

dmloader.js:908 INFO:SOUND:   nSamplesPerSec:   48000

dmloader.js:908 INFO:SOUND:   DSP backend: Fallback

dmloader.js:908 INFO:SOUND: Sound

dmloader.js:908 INFO:SOUND:   nSamplesPerSec:   48000

dmloader.js:908 INFO:SOUND:        useThread:   0

dmloader.js:908 INFO:ENGINE: Initialised sound device 'default'

dmloader.js:908 INFO:GRAPHICS: Transcoding: /main/atlas.texturec from 15 to 1 (TEXTURE_FORMAT_RGBA_ETC2 -> cTFETC2_RGBA)

index.html:1 [.WebGL-0x6c00580a00]GL ERROR :GL_INVALID_VALUE : glCompressedTexImage3D: size is not correct for dimensions
```

These logs should show the difference in texture format handling and GPU extensions between desktop and Android Chrome.

**Screenshots:**

**Android – Chrome (problem):**

Image

(an example from my personal project)

Image

**Android – Firefox (correct):**

Image

(an example from my personal project)

Image

### PR DESCRIPTION
**Pull request by AGulev**
[Because of a Chromium-side issue](https://issues.chromium.org/issues/434983812), Defold uses a workaround that disables ASTC compression when the issue is detected, falling back to ETC2 - which offers lower visual quality.  

This update narrows the fallback to ETC2 so it only applies to **paged atlases** in affected cases.  
As a result, single-paged atlases now use ASTC for maximum texture quality, while multi-paged atlases remain visible even on devices impacted by the Chromium problem.  

Fix https://github.com/defold/defold/issues/11416

### CODE REVIEW

File: engine/graphics/src/graphics.cpp [hunk 1]
```diff
@@ -674,6 +674,16 @@ namespace dmGraphics
                format == TEXTURE_FORMAT_RGBA_ASTC_12X12;
     }
 
+    bool IsTextureFormatSupportedForType(HContext context, TextureType type, TextureFormat format)
+    {
+        if (type == TEXTURE_TYPE_2D_ARRAY && IsTextureFormatASTC(format))
```
Comment (ekharkunov) [inline engine/graphics/src/graphics.cpp]: I think we can add here `TEXTURE_TYPE_3D` also because from OpenGL perspective we use the same `glCompressedTexImage3D` for texture array for texture 3d.

**Review by ekharkunov — DISMISSED** [review]

File: engine/graphics/src/graphics.cpp (hunk 1 above)
Comment (AGulev) [reply engine/graphics/src/graphics.cpp]: 👍 thanks! Fixed!

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 2]
```diff
@@ -1353,7 +1355,8 @@ static void LogFrameBufferError(GLenum status)
                 GLint err = glGetError();
                 if (err != 0)
                 {
-                    context->m_ASTCSupport = 0;
+                    // Only disable ASTC for array textures; keep 2D ASTC enabled
+                    context->m_ASTCArrayTextureSupport = 0;
```
Comment (JCash) [inline engine/graphics/src/opengl/graphics_opengl.cpp:1359]: Can we check what actual graphics backend we're running on? (e.g. Chromium)
Or, do we want to disable it for _all_ browsers?

**Review by JCash — APPROVED** [review]
Looks good. Question about compatibility for other browsers.

File: engine/graphics/src/opengl/graphics_opengl.cpp (hunk 2 above)
Comment (AGulev) [reply engine/graphics/src/opengl/graphics_opengl.cpp:1359]: For now, I do it by uploading to GPU a fake 2 paged ASTC atlas, if it fails I turned it off, so it's not needed to detect backend, if it works - it works if it doesn't we turn this off:
```cpp
 #if defined (__EMSCRIPTEN__)
            // Workaround for some old phones which don't work with ASTC in glCompressedTexImage3D
            // see https://github.com/defold/defold/issues/8030
            // and https://github.com/defold/defold/issues/11009
            if (context->m_IsGles3Version && OpenGLIsTextureFormatSupported(context, TEXTURE_FORMAT_RGBA_ASTC_4X4)) {
                unsigned char fakeZeroBuffer[] = {
                    0xFC, 0xFD, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
                    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
                    
                    0xFC, 0xFD, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
                    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
                };
                GLuint texture;
                glGenTextures(1, &texture);
                glBindTexture(GL_TEXTURE_2D_ARRAY, texture);
                DMGRAPHICS_COMPRESSED_TEX_IMAGE_3D(GL_TEXTURE_2D_ARRAY, 0, DMGRAPHICS_TEXTURE_FORMAT_RGBA_ASTC_4x4_KHR, 4, 4, 2, 0, 32, &fakeZeroBuffer);
                 GLint err = glGetError();
                  if (err != 0)
                {
                    // Only disable ASTC for array textures; keep 2D ASTC enabled
                    context->m_ASTCArrayTextureSupport = 0;
                    ...
```

**Review by ekharkunov — APPROVED** [review]
