### PR TITLE
Fix editor exception during build if a referenced collection overrides a resource script property

### LINKED ISSUE #7048: Exception during build with script property override in collection
### Expected behaviour
The project should build without issues.

### Actual behaviour
An exception is thrown when you attempt to build the project.

### Steps to reproduce
1. Crate a script with a resource property declaration.
2. Create a game object and add a reference to the script.
3. Create a collection and add a reference to the game object.
4. Override the script property from the collection.
5. Create another collection and add a reference to the first collection.
6. Build the project.

An exception is thrown. If I override the script property from the second collection, the project builds fine again.

<hr/>

<table>
<tr><td>Build time</td><td>2022-10-03T14:10:33.459020</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18bcb391eb01d8d4f627df7a53c4cb0302acf403</td></tr>
<tr><td>Defold engine sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"aebe2a6b47e84347818020346da5a2c3"'>aebe2a6b47e84347818020346da5a2c3</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.6</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Fixed an editor exception during build if a referenced collection overrides a resource script property.

Fixes #7048

### CODE REVIEW

File: editor/src/clj/editor/collection.clj [hunk 1]
```diff
@@ -525,6 +528,7 @@
         {:keys [id children component-properties]} instance-msg
         is-child? (contains? all-child-ids id)
         build-target-go-props (partial properties/build-target-go-props resource-property-build-targets)
+        component-properties (map source-resource-component-property-desc component-properties)
```
Comment (matgis) [inline editor/src/clj/editor/collection.clj:531]: The `:clj-value` entries for resources in the properties we get from the build-targets of referenced collections have been converted into build resources. In order for the referenced-resource-to-build-target-mapping to work in `properties/build-target-go-props`, these need to be source resources, not build resources. Here, we map the build resources produced by the call to `properties/build-target-go-props` for the referenced collections build targets back into source resources so we can repeat the process with our own overrides applied.

File: editor/src/clj/editor/collection.clj [hunk 2]
```diff
@@ -556,7 +560,9 @@
     (let [ddf-properties (into {} (map (juxt :id :properties)) ddf-properties)
           base-id (str id path-sep)
           instance-data (get-in build-targets [0 :user-data :instance-data])
-          child-ids (reduce (fn [child-ids data] (into child-ids (:children (:instance-msg data)))) #{} instance-data)]
+          child-ids (into #{}
+                          (mapcat (comp :children :instance-msg))
+                          instance-data)]
```
Comment (matgis) [inline editor/src/clj/editor/collection.clj:565]: Same result, just clearer.

File: editor/test/integration/script_properties_test.clj [hunk 3]
```diff
@@ -1540,7 +1540,13 @@
...
           edit-property! (fn [node-id proj-path] (edit-property! node-id :__atlas (tu/resource workspace proj-path)))
           assigned-property? (fn [node-id proj-path] (atlas-resource-property? (get (properties node-id) :__atlas) (tu/resource workspace proj-path)))
-          overridden-property? (fn [node-id] (overridden? node-id "atlas"))]
+          overridden-property? (fn [node-id] (overridden? node-id "atlas"))
+          build-target-source-path (comp resource/proj-path :resource :resource)
+          built-source-paths (fn [resource-node]
+                               (into #{}
+                                     (keep build-target-source-path)
+                                     (pipeline/flatten-build-targets
+                                       (g/node-value resource-node :build-targets))))]
```
Comment (matgis) [inline editor/test/integration/script_properties_test.clj:1549]: Added tests. Some of these tests would cause exceptions before the fix.

File: editor/src/clj/editor/properties.clj [hunk 4]
```diff
@@ -746,6 +746,25 @@
 
     go-props-with-fused-build-resources))
 
+(defn- source-resource-go-prop [property-desc]
+  (if (not= :property-type-hash (:type property-desc))
+    property-desc
+    (let [build-resource (:clj-value property-desc)]
+      (if (not (workspace/build-resource? build-resource))
```
Comment (vlaaad) [inline editor/src/clj/editor/properties.clj:753]: `if-not` 😛

**Review by vlaaad — APPROVED** [review]
Ship it!
