### PR TITLE
Fix exception when pasting named resources inside Gui scenes

### LINKED ISSUE #10145: Resource copy/pasting in GU/I scene
### Expected behaviour
new resource created

### Actual behaviour
exception appear when trying to copy/paste resource in gui scene

### Steps to reproduce
1. select a font resource in a gui scene
2. cmd+c
3. cmd+v
4. java exception

<hr/>

<table>
<tr><td>Build time</td><td>2024-12-19T10:48:06.505774</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>83536c65275c04366b704b2fd3f3d681c88b8267</td></tr>
<tr><td>Defold engine sha</td><td>11d2cd3a9be17b2fc5a2cb5cea59bbfb4af1ca96</td></tr>
<tr><td>Defold version</td><td>1.9.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5b4b767889cf4f6ab287a8b65d01df2f"'>5b4b767889cf4f6ab287a8b65d01df2f</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 89.3</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>15.2</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Fixed an issue where pasting a named resource inside a Gui scene would throw an exception.

Fixes #10145.

### Technical changes
* Added functions for Outline-related clipboard actions to the `test-util` module.
* Added tests for pasting all resource types. This uncovered that we do not support copy-pasting of Spine Scene resources in GUI. The tests added here depend on merging https://github.com/defold/extension-spine/pull/198.

### CODE REVIEW

File: editor/project.clj [hunk 1]
```diff
@@ -281,7 +281,7 @@
                                 :jvm-opts          ["-Ddefold.extension.lua-preprocessor.url=https://github.com/defold/extension-lua-preprocessor/archive/main.zip"
                                                     "-Ddefold.extension.rive.url=https://github.com/defold/extension-rive/archive/refs/tags/2.4.0.zip"
                                                     "-Ddefold.extension.simpledata.url=https://github.com/defold/extension-simpledata/archive/refs/tags/v1.1.0.zip"
-                                                    "-Ddefold.extension.spine.url=https://github.com/defold/extension-spine/archive/refs/tags/3.6.4.zip"
+                                                    "-Ddefold.extension.spine.url=https://github.com/defold/extension-spine/archive/refs/heads/editor-paste-spine-scene-gui-resource.zip"
```
Comment (matgis) [inline editor/project.clj:284]: I'll revert this once https://github.com/defold/extension-spine/pull/198 has been merged and released.

File: editor/test/integration/gui_test.clj [hunk 2]
```diff
@@ -158,7 +158,7 @@
       (test-util/with-prop [pie :perimeter-vertices 1001]
         (is (g/error-fatal? (test-util/prop-error pie :perimeter-vertices)))))))
 
-(deftest gui-textures
+(deftest gui-textures-test
```
Comment (matgis) [inline editor/test/integration/gui_test.clj:161]: Renamed some tests, as they were conflicting with function names in the same scope. Let's make sure to always suffix test names with `-test` going forward!

File: editor/test/integration/test_util.clj [hunk 3]
```diff
@@ -675,6 +676,56 @@
...
+
+(defn outline-duplicate!
+  "Simulate a copy-paste operation of the specified node in-place, typically how
+  a user might duplicate an element in the edited scene."
+  ([project root-node-id outline-path]
+   (outline-duplicate! project root-node-id outline-path nil))
+  ([project root-node-id outline-path select-fn]
+   (let [copied-data (outline-copy project root-node-id outline-path)]
+     (outline-paste! project root-node-id outline-path copied-data select-fn))))
+
```
Comment (matgis) [inline editor/test/integration/test_util.clj:728]: Curiously we did not have helper functions for simulating copy-paste operations in `test-util`. So named Gui resources are the only clipboard operations covered by tests at the moment. 😬

There are some general tests of this for the outline view, but nothing really exercises the various `:tx-attach-fns` of various node types. 😞

**Review by vlaaad — APPROVED** [review]
Shipit!
