### PR TITLE
Send correct Content-Length HTTP headers in responses to engine HEAD resource requests

### LINKED ISSUE #7944: Building a project when the project is running causes build to fail
**Describe the bug (REQUIRED)**
When building a game project through Ctrl+B or Project menu, if the game project is already running, the Game window closes but the build does not complete, and various errors appear depending on the project.

**To Reproduce (REQUIRED)**
Precondition: A Defold game project is running
1. Set focus to Defold IDE
2. Press CTRL + B

**Expected behavior (REQUIRED)**
The project builds at its current state, the existing instance of the game closes, and a new window appears

**Defold version (REQUIRED):**
  Version 1.5 (b55f345)

**Platforms (REQUIRED):**
 Platforms: Windows
OS: Windows 10
Device: Desktop PC

**Minimal repro case project (OPTIONAL):**
This can be done on any project. Open Defold > New Project > Empty Project > Ctrl+B > Ctrl+B again 

**Screenshots (OPTIONAL):**
Error running from my current project:
image

Error Running from a new project:
image

**Additional context (OPTIONAL):**
If the game instance is closed before another build attempt, the build completes fine, it seems to just be when a build instance is running that this issue occurs.

### PR DESCRIPTION
**Pull request by matgis**
Fixes #7944.

### User-facing changes
* Fixed an issue where rebuilding the game project with the game already running would shut down the game with an error message.

### CODE REVIEW

File: editor/src/clj/editor/hot_reload.clj [hunk 1]
```diff
@@ -29,29 +29,38 @@
...
+
+                        (or (= method "GET")
+                            (= method "HEAD"))
+                        (assoc "Content-Length" (str content-length)))]
+            (cond-> {:code (if is-cached 304 200)
+                     :headers response-headers}
+
+                    (and content
+                         (= method "GET"))
+                    (assoc :body content))))))))
```
Comment (matgis) [inline editor/src/clj/editor/hot_reload.clj:63]: A lot of corrected indentation and some restructuring going on here, but in short:
* We now include the `Content-Length` header when responding to both `GET` and `HEAD` requests.
* We get the `Content-Length` from the file size on disk so we don't have to read the file for the `HEAD` request.

File: editor/src/clj/editor/hot_reload.clj [hunk 2]
```diff
@@ -85,7 +94,7 @@
     (let [body-str (string/join "\n" (body->valid-entries workspace body))
           body (.getBytes body-str "UTF-8")]
       {:code 200
-       :headers {"Content-Length" (str (count body))}
+       :headers {"Content-Length" (str (alength ^bytes body))}
```
Comment (matgis) [inline editor/src/clj/editor/hot_reload.clj:97]: Tiny efficiency tweak since we know this will be an array.

**Review by vlaaad — APPROVED** [review]
Shipit!
