### PR TITLE
Fix in shutdown when gui type context was destroyed before the gui collections

### LINKED ISSUE #6521: Component types are deleted before the collections
This issue was detected when the comp_gui crashes due to the type context was already deleted when the call came to delete a gui world.

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -275,6 +275,8 @@ namespace dmEngine
             dmResource::Release(engine->m_Factory, engine->m_MainCollection);
         dmGameObject::PostUpdate(engine->m_Register);
 
+        dmGameObject::DeleteRegister(engine->m_Register); // Delete all collections and game objects
```
Comment (JCash) [inline engine/engine/src/engine.cpp:278]: Not sure why this wasn't noticed before.
I think it seems like a good idea to destroy the collections/game objects before moving on to destroy the other engine systems.
