### PR TITLE
Fix for lua panic when connecting a gamepad

### LINKED ISSUE #7782: Crash when plugging in gamepad
### Expected behaviour
Gamepad to be recognised by engine

### Actual behaviour
Crash. Console outputs:
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\Lenovo\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:
ERROR:CRASH:  0 0x7FFDBEC7CEB0 RaiseException <unknown>:0
ERROR:CRASH:  1 0x7FF7B670A2C0 lj_err_unwind_win <unknown>:0
ERROR:CRASH:  2 0x7FF7B67098D0 lj_err_throw <unknown>:0
ERROR:CRASH:  3 0x7FF7B6709970 lj_err_run <unknown>:0
ERROR:CRASH:  4 0x7FF7B670A2C0 lj_err_unwind_win <unknown>:0
ERROR:CRASH:  5 0x7FF7B6709C10 lj_err_optype <unknown>:0
ERROR:CRASH:  6 0x7FF7B67CC280 lj_meta_tset <unknown>:0
ERROR:CRASH:  7 0x7FF7B6702BB0 lua_settable <unknown>:0
ERROR:CRASH:  8 0x7FF7B6774FB0 dmGameObject::CompScriptOnInput D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:512
ERROR:CRASH:  9 0x7FF7B674B850 dmGameObject::DispatchInput D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2859
ERROR:CRASH: 10 0x7FF7B67C0C90 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1581
ERROR:CRASH: 11 0x7FF7B67BBE80 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2117
ERROR:CRASH: 12 0x7FF7B67C16C0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83
ERROR:CRASH: 13 0x7FF7B66F9280 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148
ERROR:CRASH: 14 0x7FF7B6969B14 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 15 0x7FFDC0EE7600 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 16 0x7FFDC10826D0 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 
INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\Lenovo\AppData\Roaming\Defold/_crash.dmp

<<dump file attached>>

### Steps to reproduce
Run game then insert a gamepad. Have tried Xbox, PS2 and generic RAW USB gamepad, same result.

<hr/>

<table>
<tr><td>Build time</td><td>2023-07-05T10:31:36.474656</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>5ab36f5e2658cd3c0e1cac4e257121083f12d34f</td></tr>
<tr><td>Defold engine sha</td><td>5ab36f5e2658cd3c0e1cac4e257121083f12d34f</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>GPU</td><td>AMD Radeon R7 M370</td></tr>
<tr><td>GPU Driver</td><td>4.6.14822 Compatibility Profile Context 20.50.30 27.20.15030.19</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>
[_crash.dmp.txt](https://github.com/defold/defold/files/11985771/_crash.dmp.txt)

### PR DESCRIPTION
**Pull request by JCash**
Fixes #7782 

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/gui/src/gui.cpp [hunk 1]
```diff
@@ -1805,17 +1805,14 @@ Result DeleteDynamicTexture(HScene scene, const dmhash_t texture_hash)
                     lua_newtable(L);
 
                     if (ia->m_IsGamepad) {
-                        lua_pushliteral(L, "gamepad");
                         lua_pushnumber(L, ia->m_GamepadIndex);
-                        lua_settable(L, -3);
+                        lua_setfield(L, -2, "gamepad");
```
Comment (JCash) [inline engine/gui/src/gui.cpp:1809]: The missing "lu_settable" messed up the lua stack, and caused a panic that shut the application down.

I prefer "lua_setfield" for readability and it helps keep the "key-value" approach simpler.

Comment (JCash) [reply engine/gui/src/gui.cpp:1809]: (I'm suspecting a bad merge somewhere)

**Review by britzl — APPROVED** [review]
