### PR TITLE
Fix slow loading of sprite data in the editor

### LINKED ISSUE #7061: Dramatic increase in project load times
Testers saw a dramatic increase in project load times in the editor with the 1.3.8 beta.

### PR DESCRIPTION
**Pull request by matgis**
Fixed slow project load times introduced by the addition of slice-9 support for sprites.

Fixes #7061

### CODE REVIEW

File: editor/src/clj/editor/sprite.clj [hunk 1]
```diff
@@ -389,13 +389,21 @@
...
+      (g/set-property self :slice9 (:slice9 sprite))
+
+      ;; The size property value clause is dependent on size metadata from the
+      ;; image, and the old value is evaluated whenever the property is set (for
+      ;; use in the property setter function). Assigning the image property
+      ;; after the size property ensures the dependent property value clause
+      ;; does not perform the expensive image size metadata computation for the
+      ;; ignored old-value of the size property. This saves immensely on load
+      ;; times for projects with a lot of sprites.
+      (g/set-property self :image image))))
```
Comment (vlaaad) [inline editor/src/clj/editor/sprite.clj:406]: A bit scary that the order of txs has such a tremendous influence on load times, it's good that you made this comment!

**Review by vlaaad — APPROVED** [review]
Ship it!

File: editor/src/clj/editor/sprite.clj (hunk 1 above)
Comment (matgis) [reply editor/src/clj/editor/sprite.clj:406]: Yeah, I wonder there might be similar situations elsewhere. Most property-setters don't need the old-value either. There might be further gains to be made in this area.
