### PR TITLE
Fix `ComponentRenderConstants` allocations

### LINKED ISSUE #10436: Progressively worse performance in scene with many skinned meshes
**Describe the bug (REQUIRED)**
Immediately after launch, the animation is smooth, but the frame rate seems to worsen the longer the scene is being rendered.

**To Reproduce (REQUIRED)**
Build and run the attached project.

**Expected behavior (REQUIRED)**
The frame rate remains relatively constant over time.

**Defold version (REQUIRED):**
  - 1.10.0-alpha

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: 15.4 (24E248)
 - Device: MacBook Air M3

**Minimal repro case project (OPTIONAL):**
[dev-model-perf-test.zip](https://github.com/user-attachments/files/19587799/dev-model-perf-test.zip)

### PR DESCRIPTION
**Pull request by AGulev**
Fix https://github.com/defold/defold/issues/10436

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 1]
```diff
@@ -1341,7 +1342,7 @@ namespace dmGameSystem
 
     static inline HComponentRenderConstants GetScratchConstantBuffer(ModelWorld* world)
     {
-        if (world->m_ScratchConstantBuffers.Full())
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:1344]: It's always full (see a line 3 lines below)

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 2]
```diff
@@ -1141,6 +1141,7 @@ namespace dmGameSystem
         dmRender::HMaterial render_context_material, uint32_t material_index,
         ModelComponent* component, dmRender::RenderListEntry *buf, uint32_t* begin, uint32_t* end, dmGraphics::HVertexDeclaration inst_decl)
     {
+        DM_PROFILE("VSInstanced");
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:1144]: just a sub-scope to make profiling easier

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 3]
```diff
@@ -1364,6 +1365,7 @@ namespace dmGameSystem
         dmRender::HMaterial render_context_material, uint32_t material_index,
         ModelComponent* component, dmRender::RenderListEntry *buf, uint32_t* begin, uint32_t* end)
     {
+        DM_PROFILE("VSUninstanced");
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:1368]: Usually "Non" (as opposed to "Un")

**Review by JCash — APPROVED** [review]
