### PR TITLE
Fixed Crash when using raycasts under certain conditions

### LINKED ISSUE #10312: Crash when using raycasts under certain conditions
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
Using physics.raycast() sometimes causes a crash.

**To Reproduce (REQUIRED)**
This code:

```
	local from = vmath.vector3(0, -13200000, 0)
	local to = from + vmath.vector3(0, -1, 0)
	local groups = {hash("test")}
	physics.raycast(from, to, groups)
```

Together with the game.project setting:

```
[physics]
scale = 0.01
```

Causes a crash with this message:

`Assertion failed: (r.LengthSquared() > 0.0f), function RayCast, file b2DynamicTree.h, line 232.`

**Expected behavior (REQUIRED)**
Usually when a ray’s vector has 0 length, this warning is displayed instead:

`WARNING:PHYSICS: Ray had 0 length when ray casting, ignoring request.`

It could have something to do with floating point precision, because of the extreme numbers, coupled with a short ray.

The crash can be avoided, but it may be better to catch it and display the above message instead?

**Defold version (REQUIRED):**
1.9.7

**Platforms (REQUIRED):**
macOS Sonoma (14.6.1)

**Minimal repro case project (OPTIONAL):**
[RaycastCrash.zip](https://github.com/user-attachments/files/19144151/RaycastCrash.zip)

**Workaround (OPTIONAL):**
Avoid using raycasts for extreme numbers.

**Additional context (OPTIONAL):**
[Add any other context about the problem here.](https://forum.defold.com/t/raycast-crash/79990)

### PR DESCRIPTION
**Pull request by DarkRavenStar**
This fixes a crash when the length of a 2D or 3D raycast is zero.
This fix specifically takes into account the case when the ray length becomes zero after applying the `physics.scale` setting in game.project.

Fixes #10312

### Technical notes
Added extra dmLogWarning if ray had 0 length after applying physics scale
Added Unit Test to test for zero length raycast before and oafter applying scale

### CODE REVIEW

File: engine/physics/src/physics/box2d/box2d_physics.cpp [hunk 1]
```diff
@@ -2105,6 +2105,12 @@ namespace dmPhysics
         ToB2(from2d, from, scale);
         b2Vec2 to;
         ToB2(to2d, to, scale);
+        
+        if (b2LengthSquared((to - from)) <= 0.0f)
+        {
+            dmLogWarning("Ray had 0 length when ray casting after applying physics scale, ignoring request.");
+            return;
+        }
```
Comment (JCash) [inline engine/physics/src/physics/box2d/box2d_physics.cpp:2108]: Do we really need two checks?
I suggest we remove the first check, and keep this one.

File: engine/physics/src/physics/box2d_defold/box2d_defold_physics.cpp [hunk 2]
```diff
@@ -1396,18 +1396,26 @@ namespace dmPhysics
...
+        b2Vec2 from;
+        ToB2(from2d, from, scale);
+        b2Vec2 to;
+        ToB2(to2d, to, scale);
+        
+        if ((to - from).LengthSquared() <= 0.0f)
+        {
+            dmLogWarning("Ray had 0 length when ray casting after applying physics scale, ignoring request.");
+            return;
+        }
```
Comment (JCash) [inline engine/physics/src/physics/box2d_defold/box2d_defold_physics.cpp:1404]: Same here

File: engine/physics/src/physics/physics_3d.cpp [hunk 3]
```diff
@@ -1213,6 +1213,12 @@ namespace dmPhysics
         ToBt(request.m_From, from, scale);
         btVector3 to;
         ToBt(request.m_To, to, scale);
+        
+        if ((to - from).length2() <= 0.0f)
+        {
+            dmLogWarning("Ray had 0 length when ray casting after applying physics scale, ignoring request.");
+            return;
+        }
```
Comment (JCash) [inline engine/physics/src/physics/physics_3d.cpp:1215]: and here

**Review by JCash — CHANGES_REQUESTED** [review]

File: engine/physics/src/physics/box2d/box2d_physics.cpp (hunk 1 above)
Comment (britzl) [reply engine/physics/src/physics/box2d/box2d_physics.cpp:2108]: What do you mean by two checks? Where is the first one?

Comment (DarkRavenStar) [reply engine/physics/src/physics/box2d/box2d_physics.cpp:2108]: @britzl, I think @JCash is refering(few lines above my newly added warning message), same with other 2 files
[L2096](https://github.com/defold/defold/blob/8be1bf350159f8fe755602528237b8c400f7389d/engine/physics/src/physics/box2d/box2d_physics.cpp#L2096)

@JCash I agree with you. I will make it into 1 check only

File: engine/physics/src/physics/box2d_defold/box2d_defold_physics.cpp (hunk 2 above)
Comment (DarkRavenStar) [reply engine/physics/src/physics/box2d_defold/box2d_defold_physics.cpp:1404]: Fixed

File: engine/physics/src/physics/physics_3d.cpp (hunk 3 above)
Comment (DarkRavenStar) [reply engine/physics/src/physics/physics_3d.cpp:1215]: Fixed

**Review by JCash — CHANGES_REQUESTED** [review]
lgtm. Only thing missing is a small addition to our unit tests.

File: engine/physics/src/physics/test/test_physics.cpp [hunk 4]
```diff
@@ -1034,6 +1035,34 @@ TYPED_TEST(PhysicsTest, EmptyRayCasting)
...
+    // A zero length raycast after applying scale
+    hits.SetSize(0);
+    request.m_From = Point3(0.0f, -13200000.0f, 0.0f);
+    request.m_To = Point3(0.0f, -13200001.0f, 0.0f);
+    request.m_ReturnAllResults = 0;
+    (*TestFixture::m_Test.m_RayCastFunc)(TestFixture::m_World, request, hits);
+
+    ASSERT_EQ(0u, hits.Size());
+}
+
```
Comment (JCash) [inline engine/physics/src/physics/test/test_physics.cpp:1065]: 👍

**Review by JCash — DISMISSED** [review]

**Review by JCash — APPROVED** [review]
