### PR TITLE
Fix various issues with slice9 and gui pivots

### LINKED ISSUE #8826: Does not apply size property to node in manual size mode. (rotated sprite in atlas)
The issue is that in some cases the manual size mode is not applied to gui node in the editor.  But it works absolutely correctly in runtime. I caught the issue by chance, in version 1.7.0. In beta 1.8.0 it is still there.

In the video I apply to node in the first case atlas with rotated atlas packing picture, in the second case with normal position. The picture is the same. The node is the same. The difference, as far as I can see, is how the editor packed the resource into the atlas.

https://github.com/defold/defold/assets/842807/4bf8c139-2932-40a2-bb2f-93beeaa4ec0a

The first atlas (rotated sprite):

The second.

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-22T08:34:17.916817</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>bf9b9ff94ee975a4f0301c1f870bf5e328a90334</td></tr>
<tr><td>Defold engine sha</td><td>bf9b9ff94ee975a4f0301c1f870bf5e328a90334</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 551.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #9192: Changing the size of a GUI node doesn't affect the Editor's viewport
Changing the size of a GUI node doesn't affect the editor's viewport, but it works in the build. 
As you can see in the video, I change the size of the box node from 20 to 40 and vice versa, but the editor view of the node stays the same size(always 20). The project is newly opened and didn't have any editor errors before this video. 
Also, if I close and re-open the project, the editor shows the correct size until I change it again.

I don't have a repo case yet; this is a complex project, so if needed, I can try to prepare one. 
Additionally, after recent editor/engine updates, my GUI pivots seem to have changed (I need to investigate this).

https://github.com/defold/defold/assets/1324635/25d868dc-67a2-4bc4-b650-f4832fa6e3f1

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-09T11:49:37.921972</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>2a0915824143eccfea015e28c2421e3d69fbef16</td></tr>
<tr><td>Defold engine sha</td><td>2a0915824143eccfea015e28c2421e3d69fbef16</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
* The slice-9 setting will now be correctly visualized in the editor viewport in all scenarios.
* Gui pivot offsets are now correctly visualized in the editor viewport in all scenarios.
* You can no longer select "Polygons" as a Sprite Trim Mode for an atlas image, which would previously throw an exception.

Fixes #8826.
Fixes #9192.

---

Test Project: 
[dev-texture-vertex-data.zip](https://github.com/user-attachments/files/16565114/dev-texture-vertex-data.zip)

### CODE REVIEW

File: editor/src/clj/editor/atlas.clj [hunk 1]
```diff
@@ -150,19 +150,6 @@
...
-    (let [user-data (-> renderable :user-data)
-          page-offset-x (get-rect-page-offset (:layout-width user-data) (:page-index user-data))
-          color (colors/renderable-outline-color renderable)]
-      (render-rect gl (:rect user-data) color page-offset-x)))
-  (doseq [renderable renderables]
-    (let [user-data (-> renderable :user-data)
-          page-offset-x (get-rect-page-offset (:layout-width user-data) (:page-index user-data))]
-      (when (= (-> renderable :updatable :state :frame) (:order user-data))
-        (render-rect gl (:rect user-data) colors/defold-pink page-offset-x)))))
-
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj:165]: Unrelated: Removed unused code.

File: editor/src/clj/editor/slice9.clj [hunk 2]
```diff
@@ -41,21 +41,9 @@
...
-    (:pivot-e :pivot-ne :pivot-se) :right
-    (:pivot-center :pivot-n :pivot-s) :center
-    (:pivot-w :pivot-nw :pivot-sw) :left))
-
-(defn- pivot->v-align [pivot]
-  (case pivot
-    (:pivot-ne :pivot-n :pivot-nw) :top
-    (:pivot-e :pivot-center :pivot-w) :middle
-    (:pivot-se :pivot-s :pivot-sw) :bottom))
-
```
Comment (matgis) [inline editor/src/clj/editor/slice9.clj:55]: Moved to `geom` module.

File: editor/src/clj/editor/slice9.clj [hunk 3]
```diff
@@ -108,9 +99,10 @@
   (map box box-triangles-vertex-order))
 
 (defn vertex-data
-  [{:keys [width height tex-coords] :as _frame} size slice9 pivot]
-  (let [texture-width (max 1.0 (double (or width (first size) 0.0)))
-        texture-height (max 1.0 (double (or height (second size) 0.0)))
+  [{:keys [width height tex-coords] :as _animation-frame} size slice9 pivot]
+  (let [[^double box-width ^double box-height] size
+        texture-width (max 1.0 (double (or width box-width)))
+        texture-height (max 1.0 (double (or height box-height)))
```
Comment (matgis) [inline editor/src/clj/editor/slice9.clj:105]: Now works if `width` or `height` are specified, but zero.

File: editor/src/clj/editor/sprite.clj [hunk 4]
```diff
@@ -108,29 +102,10 @@
...
-    (doto buf
-      (vtx/buf-push-floats! v0)
-      (vtx/buf-push-floats! v1)
-      (vtx/buf-push-floats! v1)
-      (vtx/buf-push-floats! v2)
-      (vtx/buf-push-floats! v2)
-      (vtx/buf-push-floats! v3)
-      (vtx/buf-push-floats! v3)
-      (vtx/buf-push-floats! v0))))
-
```
Comment (matgis) [inline editor/src/clj/editor/sprite.clj:133]: Removed unused code.

File: editor/src/clj/editor/texture_set.clj [hunk 5]
```diff
@@ -15,25 +15,29 @@
...
+            [editor.slice9 :as slice9]
+            [util.coll :as coll])
   (:import [com.google.protobuf ByteString]
            [com.jogamp.opengl GL2]
            [editor.gl.vertex2 VertexBuffer]
            [java.nio ByteOrder FloatBuffer]
            [javax.vecmath Matrix4d Point3d Vector3d]))
 
 (set! *warn-on-reflection* true)
+(set! *unchecked-math* :warn-on-boxed)
```
Comment (matgis) [inline editor/src/clj/editor/texture_set.clj:31]: Quite a lot of small changes in this file to fix the boxed math warnings.

File: editor/src/clj/editor/texture_set.clj [hunk 6]
```diff
@@ -67,28 +73,34 @@
...
         flat-array))
 
 (defn- ->anim-frame-from-geometry
-  [page-index frame-geometry]
+  [frame-index page-index tex-coords tex-coord-order frame-geometry]
   {:page-index page-index
-   :tex-coords (flat-array->2d-points (:uvs frame-geometry))
+   :tex-coords (->uv-quad frame-index tex-coords tex-coord-order)
    :vertex-coords (flat-array->2d-points (:vertices frame-geometry))
+   :vertex-tex-coords (flat-array->2d-points (:uvs frame-geometry))
```
Comment (matgis) [inline editor/src/clj/editor/texture_set.clj:84]: We need both the `:tex-coords` for the entire quad and the `:vertex-tex-coords` for the trimmed geometry. We need the untrimmed quad if an image is rendered in slice-9 mode.

**Review by vlaaad — APPROVED** [review]
LGTM!
