### PR TITLE
Get and set node materials from gui scripts

### LINKED ISSUE #7838: gui.get_material(node) and gui.set_material(node, material) not implemented
**Describe the bug (REQUIRED)**
#7455 is marked as closed, but gui.get_material(node) and gui.set_material(node, material) are not implemented in #7606 

**To Reproduce (REQUIRED)**
1. Call gui.get_material or gui.set_material on any gui nodes 
2. Error:  attempt to call field 'get_material' (a nil value),  attempt to call field 'set_material' (a nil value)
3. gui.get_material(node) and gui.set_material(node, material) are missing on https://defold.com/ref/gui/

**Expected behavior (REQUIRED)**
The functions should get or set the gui node material

**Defold version (REQUIRED):**
  - Version 1.4.8

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 11
 - Device: Windows

### PR DESCRIPTION
**Pull request by Jhonnyg**
GUI scripts have three new functions:

`gui.get_material(node)` - Gets the node material assigned in the editor (or an empty hash of "" if none assigned)
`gui.gui.set_material(node, material)` - Sets a material for a gui node from either material string or hash as specified in the list of materials in the GUI file
`gui.reset_material(node)` - Reset the material for a node to the default node specified in the GUI the node belongs to.

In addition to the GUI functions, you can also get and set materials in the gui via `go.get` and `go.set`:

```lua
go.get("#my_gui", "materials", { key = "my_custom_material_1" })
-- returns the hash of the resource, e.g hash("/path/to/material.materialc")
```

```lua
go.property("material_property", resource.material("/other_material.material"))
function init(self)
     -- this changes the material with key "my_custom_material1" to use a different material ("/other_material.material")
     go.set("#my_gui", "materials", self.material_property, { key = "my_custom_material_1" })
end
```

Fixes #7838 

## PR checklist

* [x] Code
	* [x] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [ ] Documentation
	* [x] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [x] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_label.cpp [hunk 1]
```diff
@@ -556,7 +556,6 @@ namespace dmGameSystem
     void CompLabelGetTextMetrics(const LabelComponent* component, struct dmRender::TextMetrics& metrics)
     {
         LabelResource* resource = component->m_Resource;
-        dmGameSystemDDF::LabelDesc* ddf = resource->m_DDF;
```
Comment (Jhonnyg) [inline engine/gamesys/src/gamesys/components/comp_label.cpp:559]: unused

**Review by britzl — APPROVED** [review]
