### PR TITLE
Added support for specifying fixed physics time steps

### LINKED ISSUE #3168: Physics fixed timestep (DEF-3646)
Description: The only real simulation running in Defold is the 2D/3D physics. Simulations are stable under fixed timesteps which is why the entire engine defaults to using fixed time steps. This is great for physics, but is a real pain when it comes to supporting a wide array or monitor settings and configurations. If we want to keep a fixed timestep in the engine we need to detect all these hardware configs and set correct fixed timestep. It gets even more painful when Sync or FreeSync monitors are used, which has variable refresh rates.

It would be really great to decouple the physics timestep from engine timestep. With a separate fixed physics timestep, we could measure actual frame time in the rest of the engine and automagically resolve all the corner cases described above by measuring actual time.

Use case:

Decoupling the physics timestep from the global game timestep lets us be more flexible in using actual frame duration timestep in the rest of the engine, which should work well for most cases that are otherwise hard to cater for using a global fixed timestep (variable refreshrate monitors, phone battery saving modes, missing desktop drivers etc.).

Business need:

In the long run, support for a multitude of monitors/displays and devices regardless of refresh rates while still keeping physics stable.

### LINKED ISSUE #3169: Decouple physics timestep from engine timestep (DEF-3769)
Decoupling the physics timestep from the global game timestep lets us be more flexible in using actual frame duration timestep in the rest of the engine, which should work well for most cases that are otherwise hard to cater for using a global fixed timestep (variable refreshrate monitors, phone battery saving modes, missing desktop drivers etc.).

Design doc (ongoing):(LINK REMOVED)

### LINKED ISSUE #6346: Physics and vsync option
Describe the bug
If I turn off "vsync" option in game.project then physics works wrong while tab changing in HTML-5 build.

To Reproduce
1. Create static floor and a dynamic box above it.
2. Set ​gravity to -1000 and scale to 0.01
3. Turn off vsync option
4. Build HTML5
5. Tap on any other tabs in your browser
6. Return to the tab with your game

Screenshot 2022-01-24 at 14 08 11
Screenshot 2022-01-24 at 14 08 18

Minimal repro case project
Here is the minimal project to reproduce.
[min_repo.zip](https://github.com/defold/defold/files/7925117/min_repo.zip)
Video (https://youtu.be/f25yfMygA4w)

Expected behavior
Physics works identically with vsync turned on or off.

Defold version
1.2.179 -- 1.2.190

Platforms
HTML5 (in browsers on macOS, iOS, Android)

Workaround
If I set framecap to 60, physics works fine with vsync turned on and off.

### LINKED ISSUE #6459: Add fixed time step support for physics
As a step towards making the game updates respect the vsync, we need to make sure the physics component can update in a fixed time step, separate from the game objects.

Design:
https://docs.google.com/document/d/14pAZG1612rXfMsrcR26jQNRpKtE0oX3H9VUSAQc6sXs/edit?usp=sharing

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 1]
```diff
@@ -895,18 +898,71 @@ namespace dmGameSystem
         return dispatch_context.m_Success;
     }
 
+    static void Step(CollisionWorld* world, PhysicsContext* physics_context, dmGameObject::HCollection collection, const dmPhysics::StepWorldContext* step_ctx)
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:901]: The actual step function, with dispatching messages before/after and also updating the gameobject transforms.

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 2]
```diff
@@ -956,50 +1011,40 @@ namespace dmGameSystem
...
-        }
-        if (contact_user_data.m_Count >= physics_context->m_MaxContactPointCount)
-        {
-            if (!g_ContactOverflowWarning)
-            {
-                dmLogWarning("Maximum number of contacts (%d) reached, messages have been lost. Tweak \"%s\" in the config file.", physics_context->m_MaxContactPointCount, PHYSICS_MAX_CONTACTS_KEY);
-                g_ContactOverflowWarning = true;
-            }
+            float num_steps_f = time / physics_dt;
+            num_steps_i = (uint32_t)num_steps_f;
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:1028]: Calculate the number of steps to take, given the currently accumulated time.

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 3]
```diff
@@ -119,9 +121,10 @@ namespace dmGameSystem
             dmPhysics::HWorld2D m_World2D;
             dmPhysics::HWorld3D m_World3D;
         };
-        float m_LastDT; // Used to calculate joint reaction force and torque.
-        uint8_t m_ComponentIndex;
-        uint8_t m_3D : 1;
+        float       m_CurrentDT;    // Used to calculate joint reaction force and torque.
+        float       m_AccumTime;    // Time saved from last component type update
+        uint8_t     m_ComponentTypeIndex;
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:126]: Renamed it to better reflect what it is and how it's used.

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 4]
```diff
@@ -119,9 +121,10 @@ namespace dmGameSystem
             dmPhysics::HWorld2D m_World2D;
             dmPhysics::HWorld3D m_World3D;
         };
-        float m_LastDT; // Used to calculate joint reaction force and torque.
-        uint8_t m_ComponentIndex;
-        uint8_t m_3D : 1;
+        float       m_CurrentDT;    // Used to calculate joint reaction force and torque.
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:124]: Since the variable was always set _before_ the physics update, it seemed better to name it _current_ dt.

**Comment by JCash** [comment]
Fixes: https://github.com/defold/defold/issues/3168

File: com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties [hunk 5]
```diff
@@ -95,6 +95,10 @@ type.type = string
 type.help = which type of physics to use, 2D (default) or 3D
 type.default = 2D
 
+update_frequency.type = integer
+update_frequency.help = Number of physics updates per second. 0 means one update per game frame, using the dt passed in.
+update_frequency.default = 0
```
Comment (JCash) [inline com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties:100]: Note that it's disabled by default, so we need to update our templates to set this to e.g. `60`

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 6]
```diff
@@ -956,50 +1011,40 @@ namespace dmGameSystem
         step_world_context.m_RayCastCallback = RayCastCallback;
         step_world_context.m_RayCastUserData = world;
 
-        world->m_LastDT = params.m_UpdateContext->m_DT;
+        float physics_dt = params.m_UpdateContext->m_DT;
+        uint32_t num_steps_i = 1;
 
-        g_NumPhysicsTransformsUpdated = 0;
+        static int frame = 0;
```
Comment (britzl) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:1017]: What is this used for?

**Review by britzl — DISMISSED** [review]
Looks good! I had a question about `static int frame = 0`

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp (hunk 6 above)
Comment (JCash) [reply engine/gamesys/src/gamesys/components/comp_collision_object.cpp:1017]: It's a remnant of a debug print. will remove
