### PR TITLE
Make Lua chunknames standardized across platforms and formats

### LINKED ISSUE #6485: Editor > Links are no longer clickable in the console (when an error occurs)
**Describe the bug (REQUIRED)**

In the editor, until very recently, when I had an error displayed in the console, some links were sending me to the scripts (and the exact lines) in question, which was very convenient.

After a recent update, it looks like some links are not available (displayed but not clickable) so I have to open the scripts manually and scroll down until I find the line in question.

From Defold forum:
https://forum.defold.com/t/solved-defold-editor-links-not-available-in-the-console-bug/70585

**To Reproduce (REQUIRED)**
Cf above

**Expected behavior (REQUIRED)**
Any link should be clickable in the console.

**Defold version (REQUIRED):**
Version 1.3.0 => but not 100% sure the bug was introduced in this version

**Platforms (REQUIRED):**
Windows 10

### PR DESCRIPTION
**Pull request by britzl**
### Engine
The chunk/filename set at runtime is not consistent between Lua modules and script components. The same is true for bytecode when compared to source code.

Examples:

The file `game/foo.lua` was either given `=game.foo` or `@game/foo.lua` depending on wether it was compiled to bytecode or not. The same kind of differences could be observed for script components.

With this change *all* Lua scripts and modules will use the same naming convention which is `@path/to/file.lua` or `@path/to/file.script`. The @ is used so that Lua will show the last 60 of long filenames.

### Editor User-facing changes
* Fixed an issue where certain file paths printed to the Console upon a Lua error were not clickable.
* Fixed an issue where the Lua debugger Current Line indicator would not show up inside `.lua` modules.
* When multiple project resources match a partial file path in the Console, we now present a choice of resources to open.

### Editor Technical changes
* The `on-click!` callback for a `code.view` region is now called with an additional `MouseEvent` argument.

Fixes #6485

### CODE REVIEW

File: engine/engine/content/builtins/scripts/mobdebug.lua [hunk 1]
```diff
@@ -330,7 +330,7 @@ local function stack(start)
     if not source then break end
 
     local src = source.source
-    if src:find("[@=]") == 1 then
+    if src:find("@") == 1 then
```
Comment (britzl) [inline engine/engine/content/builtins/scripts/mobdebug.lua:333]: We can now safely revert this patch since we no longer provide filenames starting with = (see script_module.cpp)

File: engine/engine/content/builtins/scripts/mobdebug.lua [hunk 2]
```diff
@@ -633,8 +633,8 @@ local function debug_hook(event, line)
       -- Unfortunately, there is no reliable/quick way to figure out
       -- what is the filename and what is the source code.
       -- If the name doesn't start with `@`, assume it's a file name if it's all on one line.
-      if find(file, "^[@=]") or not find(file, "[\r\n]") then
-        file = gsub(gsub(file, "^[@=]", ""), "\\", "/")
+      if find(file, "^@") or not find(file, "[\r\n]") then
```
Comment (britzl) [inline engine/engine/content/builtins/scripts/mobdebug.lua:636]: Same as above

File: engine/script/src/script_module.cpp [hunk 3]
```diff
@@ -55,60 +55,20 @@ namespace dmScript
...
-    }
-
     int LuaLoad(lua_State *L, dmLuaDDF::LuaSource *source)
     {
         const char *buf;
         uint32_t size;
         GetLuaSource(source, &buf, &size);
-        char tmp[DMPATH_MAX_PATH];
-        return luaL_loadbuffer(L, buf, size, PrefixFilename(FindSuitableChunkname(source->m_Filename), '=', tmp, sizeof(tmp)));
+        return luaL_loadbuffer(L, buf, size, source->m_Filename);
```
Comment (britzl) [inline engine/script/src/script_module.cpp:63]: Always use the filename provided by LuaBuilder

File: engine/script/src/script_module.cpp [hunk 4]
```diff
@@ -142,7 +102,7 @@ namespace dmScript
             return 1;
         }
 
-        if (!LuaLoadModule(L, module->m_Script, module->m_ScriptSize, name))
+        if (!LuaLoadModule(L, module->m_Script, module->m_ScriptSize, module->m_Filename))
```
Comment (britzl) [inline engine/script/src/script_module.cpp:105]: We do the same for Lua modules. Always use what LuaBuilder.java has provided as filename.

File: com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java [hunk 5]
```diff
@@ -191,6 +191,15 @@ public byte[] constructBytecode(Task<Void> task, String source, File inputFile,
         }
     }
 
+    // we use the same chunk name across the board
+    // we always use @ + full path
+    // if the path is shorter than 60 characters the runtime will show the full path
+    // if the path is longer than 60 characrers the runtime will show ... and the last portion of the path
```
Comment (JCash) [inline com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java:197]: characters

File: engine/script/src/script_module.cpp [hunk 6]
```diff
@@ -55,60 +55,20 @@ namespace dmScript
...
-    const char* PrefixFilename(const char *input, char prefix, char *buf, uint32_t size)
-    {
-        if (!input)
-            return 0;
-
-        buf[0] = prefix;
-        dmStrlCpy(&buf[1], input, size-1);
-        return buf;
-    }
-
```
Comment (JCash) [inline engine/script/src/script_module.cpp:95]: 👏

File: engine/script/src/script_module.cpp [hunk 7]
```diff
@@ -231,6 +192,7 @@ namespace dmScript
         }
         free(value->m_Script);
         free(value->m_Name);
```
Comment (JCash) [inline engine/script/src/script_module.cpp:194]: Do we still need m_Name?

**Review by JCash — DISMISSED** [review]

File: engine/script/src/script_module.cpp (hunk 7 above)
Comment (britzl) [reply engine/script/src/script_module.cpp:194]: Module.m_Name is if I understand correctly the name used in require("game.foo") and we use this for lookups each time a module is loaded. I'm not sure of the implications if we ditch m_Name in favor of m_Filename

**Review by JCash — DISMISSED** [review]

**Comment by britzl** [comment]
@matgis discovered issues with hotreload of Lua modules (scripts work fine). We need to look into this first.

**Review by matgis — APPROVED** [review]
Works great! The editor parts have been reviewed by Vlad already.
