### PR TITLE
Fix broken handling of shader compiler warnings in the editor

### LINKED ISSUE #11976: Shaders Errors no longer shown
## Describe the bug:
Errors while compiling shaders are not longer shown to the user. This is only feedback I get:
Image
<details>
```
clojure.lang.ExceptionInfo: Failed to compile resource '/rendering/materials/post/shadows.material'.
clojure.lang.ExceptionInfo: Failed to digest content for resource: /_generated_0.spc
clojure.lang.ExceptionInfo: Digest process ran into an error.
clojure.lang.ExceptionInfo: Encountered undigestable value: [Ljava.lang.String;@22013649
```
</details>

## To Reproduce:
1. Make a syntax error in a shader
1. Build the project (ctrl+b)
1. See the build fail, with a generic "can't compile shader" error, and it doesn't show the error

## Expected behavior:
I would like to see the actual error, so I can fix it.

## Defold version:
  - Version 1.12.2

## Platforms:
 - Platforms: ALL
 - OS: Windows 10
 - Device: Editor

# Logs:
<table>
<tr><td>Build time</td><td>2026-03-02T12:18:10.508245</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e43be333aa7a4fc319ab62adc8d405c8e98bf92f</td></tr>
<tr><td>Defold engine sha</td><td>e43be333aa7a4fc319ab62adc8d405c8e98bf92f</td></tr>
<tr><td>Defold version</td><td>1.12.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b3ffdbeec58947b8884b432c652671e4"'>b3ffdbeec58947b8884b432c652671e4</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.99</td></tr>
<tr><td>Java version</td><td>25+36-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

## Workaround:
I just look for the errors manually. 😇 

## Additional context:
- I migratedfrom Defold 1.11.0 to 1.12.2
- Using `#version 330` shaders

### PR DESCRIPTION
**Pull request by matgis**
Fix unhelpful error during editor builds when the GLSL shader compiler emits warnings.

Fixes #11976

### Technical changes
* Arrays are now digestable. Before this, GLSL shader compilation would throw an exception when attempting to digest the `build-target` produced from a shader that emitted warnings.

### CODE REVIEW

File: editor/src/clj/util/digestable.clj [hunk 1]
```diff
@@ -171,6 +171,12 @@
   (let [sorted-set (to-sorted-set coll)]
     (digest-sequence! "#{" sorted-set "}" writer opts)))
 
+(defn- digest-array! [^Class component-class coll writer opts]
+  (digest-raw! "#dg/" writer)
+  (digest-raw! (.getName component-class) writer)
+  (digest-raw! "_ARRAY " writer)
```
Comment (vlaaad) [inline editor/src/clj/util/digestable.clj:177]: Is there an intention to keep it a readable edn? If not, it could be `"[] "` instead.

File: editor/test/util/digestable_test.clj [hunk 2]
```diff
@@ -60,6 +60,36 @@
...
+             (digestable/sha1-hash (long-array [1]))))
+      (is (= "19155570fcf1725d7a1fd0ef2ed25632cb002e59"
+             (digestable/sha1-hash (long-array [1 2])))))
+
+    (testing "Type information is included in the hash."
+      (is (not= (digestable/sha1-hash (long-array 0))
+                (digestable/sha1-hash (int-array 0))))
+      (is (not= (digestable/sha1-hash (long-array 0))
+                (digestable/sha1-hash (make-array Long 0))))))
+
```
Comment (vlaaad) [inline editor/test/util/digestable_test.clj:92]: Should we also test arrays of arrays?

**Review by vlaaad — DISMISSED** [review]
LGTM! Feel free to ignore the comments :D

**Comment by vlaaad** [comment]
Now that I'm thinking about it, it's probable that empty `String[][]` and empty `String[]` will have the same hash, which is probably invalid...

**Comment by matgis** [comment]
> Now that I'm thinking about it, it's probable that empty `String[][]` and empty `String[]` will have the same hash, which is probably invalid...

Do you mean an empty array of string arrays will hash the same as an empty array of strings? The class of the array itself is included in the hash, so it shouldn't be a problem. But maybe I don't understand you correctly?

File: editor/src/clj/util/digestable.clj (hunk 1 above)
Comment (matgis) [reply editor/src/clj/util/digestable.clj:177]: Yeah, that's the idea. Not really important, though.

File: editor/test/util/digestable_test.clj (hunk 2 above)
Comment (matgis) [reply editor/test/util/digestable_test.clj:92]: Good idea! I've added some more tests for this.

**Comment by vlaaad** [comment]
Ah, my bad, I thought `.getComponentType` returns a "final" class, but it's not:
```clj
(.getComponentType String/1)
=> java.lang.String
(.getComponentType String/2)
=> [Ljava.lang.String;
```
Ship it!
