### PR TITLE
Log error when vertex declaration doesn't match the vertex data in Vulkan

### LINKED ISSUE #10481: glTF model cause crash using Vulkan
[Popular](https://kaylousberg.itch.io/kaykit-adventurers) 3D gltf models with animation (skinned) cause a crash when using Vulkan. They work fine with OpenGL.

According to the latest [glTF validator ](https://github.com/KhronosGroup/glTF-Validator/releases)(v2.0.0), the file does not contain any errors:
`Errors: 0, Warnings: 6, Infos: 0, Hints: 59`
Report:
[Rogue_Hooded.glb.report.json.zip](https://github.com/user-attachments/files/19707282/Rogue_Hooded.glb.report.json.zip)

Repro:
[gltf_model_crash.zip](https://github.com/user-attachments/files/19707220/gltf_model_crash.zip)

Error:

```

[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
Vertex attribute bone_weights(3) is missing from the vertex descriptor.
ERROR:GRAPHICS: Vulkan Error (../src/vulkan/graphics_vulkan.cpp:1631) VK_ERROR_INITIALIZATION_FAILED
Assertion failed: (0), function GetOrCreatePipeline, file graphics_vulkan.cpp, line 1631.

...


5   dmengine                      	       0x100b8d470 dmGraphics::GetOrCreatePipeline(VkDevice_T*, VkSampleCountFlagBits, dmGraphics::PipelineState, dmHashTable64<VkPipeline_T*>&, dmGraphics::VulkanProgram*, dmGraphics::RenderTarget*, dmGraphics::VertexDeclaration**, unsigned int) + 76 (graphics_vulkan.cpp:1631) [inlined]
6   dmengine                      	       0x100b8d470 dmGraphics::DrawSetup(dmGraphics::VulkanContext*, VkCommandBuffer_T*, dmGraphics::ScratchBuffer*, dmGraphics::DeviceBuffer*, dmGraphics::Type) (.cold.3) + 88 (graphics_vulkan.cpp:2331)
7   dmengine                      	       0x10095e7a4 dmGraphics::GetOrCreatePipeline(VkDevice_T*, VkSampleCountFlagBits, dmGraphics::PipelineState, dmHashTable64<VkPipeline_T*>&, dmGraphics::VulkanProgram*, dmGraphics::RenderTarget*, dmGraphics::VertexDeclaration**, unsigned int) + 4 (graphics_vulkan.cpp:1631) [inlined]
8   dmengine                      	       0x10095e7a4 dmGraphics::DrawSetup(dmGraphics::VulkanContext*, VkCommandBuffer_T*, dmGraphics::ScratchBuffer*, dmGraphics::DeviceBuffer*, dmGraphics::Type) + 1536 (graphics_vulkan.cpp:2331)
9   dmengine                      	       0x10095ac30 dmGraphics::VulkanDrawElements(void*, dmGraphics::PrimitiveType, unsigned int, unsigned int, dmGraphics::Type, unsigned long, unsigned int) + 236 (graphics_vulkan.cpp:2369)
10  dmengine                      	       0x1009e3340 dmRender::Draw(dmRender::RenderContext*, dmRender::Predicate*, dmRender::NamedConstantBuffer*) + 1152 (render.cpp:1156)
11  dmengine                      	       0x1009e2df8 dmRender::DrawRenderList(dmRender::RenderContext*, dmRender::Predicate*, dmRender::NamedConstantBuffer*, dmRender::FrustumOptions const*) + 3144 (render.cpp:992)
12  dmengine                      	       0x1009e59fc dmRender::ParseCommands(dmRender::RenderContext*, dmRender::Command*, unsigned int) + 632 (render_command.cpp:180)
```

Crash:
[_crash.zip](https://github.com/user-attachments/files/19706871/_crash.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2025-04-11T09:28:09.969069</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>5a4223f63e8b7c17422825014eb4ae8be8c03ad1</td></tr>
<tr><td>Defold engine sha</td><td>5a4223f63e8b7c17422825014eb4ae8be8c03ad1</td></tr>
<tr><td>Defold version</td><td>1.10.0</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 89.3</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>15.3.2</td></tr>
<table>

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/10481

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/graphics/src/vulkan/graphics_vulkan.cpp [hunk 1]
```diff
@@ -1628,6 +1628,11 @@ namespace dmGraphics
             vk_scissor.offset.y = 0;
 
             VkResult res = CreateGraphicsPipeline(vk_device, vk_scissor, vk_sample_count, pipelineState, program, vertexDeclaration, vertexDeclarationCount, rt, &new_pipeline);
+            if (res == VK_ERROR_INITIALIZATION_FAILED)
+            {
+                dmLogError("Failed to create VkPipeline");
+                return 0;
```
Comment (JCash) [inline engine/graphics/src/vulkan/graphics_vulkan.cpp:1634]: We do wish to catch this earlier (build time) as the error isn't really helpful (See https://github.com/defold/defold/issues/10410)
But the main thing for now is to prevent an unnecessary assert.

**Review by britzl — APPROVED** [review]
