### PR TITLE
Fixed crash when the invalid tilemap cell index wasn't checked

### LINKED ISSUE #10426: tilemap.set_tile causes crash in 1.10.0
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
The game crashes when using tilemap.set_tile to remove a wall. In the case I'm experiencing calling tilemap.set_tile("#map", "walls", 21, y, 0) causes the crash. This works without issue in 1.9.8

**To Reproduce (REQUIRED)**
Create a map with a walls layer and then call set_tile to set it to 0. This should disable the wall and its collision but instead it crashes.

**Expected behavior (REQUIRED)**
The walls set to 0 should disappear and no longer collide with the player

**Defold version (REQUIRED):**
  - Version 1.10.0

**Platforms (REQUIRED):**
 Windows, Android, HTML5

**Logs (OPTIONAL):**
ERROR:CRASH:  0 0x7FF7E4CF4C90 dmPhysics::CreateGridCellShape D:\a\defold\defold\engine\physics\src\physics\box2d\box2d_physics.cpp:1086

I can provide the full crash dmp if it will help

**Workaround (OPTIONAL):**
None I know of yet

### LINKED ISSUE #10431: Tilemap set shape regression
The setting of a tile shape currently crashes:
https://forum.defold.com/t/defold-1-10-0-beta/80108/53?u=mathias_westerdahl

```C++
ERROR:CRASH: 0   dmengine                            0x0000000104853038 _ZN7dmCrash7OnCrashEi + 100
ERROR:CRASH: 1   dmengine                            0x0000000104853318 _ZN7dmCrashL7HandlerEiP9__siginfoPv + 60
ERROR:CRASH: 2   libsystem_platform.dylib            0x000000018adfede4 _sigtramp + 56
ERROR:CRASH: 3   dmengine                            0x00000001045a9ce8 _ZN9dmPhysics19CreateGridCellShapeEPvjj + 96
ERROR:CRASH: 4   dmengine                            0x00000001045aa8a8 _ZN9dmPhysics24SetCollisionObjectFilterEPvjjtt + 216
ERROR:CRASH: 5   dmengine                            0x00000001044f893c _ZN12dmGameSystem33CompCollisionObjectBox2DOnMessageERKN12dmGameObject24ComponentOnMessageParamsE + 1428
ERROR:CRASH: 6   dmengine                            0x0000000104505488 _ZN12dmGameSystem28CompCollisionObjectOnMessageERKN12dmGameObject24ComponentOnMessageParamsE + 56
ERROR:CRASH: 7   dmengine                            0x00000001044aca9c _ZN12dmGameObject24DispatchMessagesFunctionEPN9dmMessage7MessageEPv + 2496
ERROR:CRASH: 8   dmengine                            0x0000000104738c78 _ZN9dmMessage16InternalDispatchEyPFvPNS_7MessageEPvES2_b + 332
ERROR:CRASH: 9   dmengine                            0x0000000104738e44 _ZN9dmMessage8DispatchEyPFvPNS_7MessageEPvES2_ + 48
ERROR:CRASH: 10  dmengine                            0x00000001044ae06c _ZN12dmGameObjectL16DispatchMessagesEPNS_10CollectionEPyj + 260
ERROR:CRASH: 11  dmengine                            0x00000001044ab3a0 _ZN12dmGameObjectL14InitCollectionEPNS_10CollectionE + 428
ERROR:CRASH: 12  dmengine                            0x00000001044ab1e8 _ZN12dmGameObject4InitEPNS_16CollectionHandleE + 28
ERROR:CRASH: 13  dmengine                            0x00000001044893fc _ZN8dmEngine4InitEPNS_6EngineEiPPc + 11796
ERROR:CRASH: 14  dmengine                            0x000000010448b9b8 _Z14dmEngineCreateiPPc + 104
ERROR:CRASH: 15  dmengine                            0x000000010448e434 _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE + 140
ERROR:CRASH: 16  dmengine                            0x000000010448e144 _ZL10EngineMainiPPc + 124
ERROR:CRASH: 17  dmengine                            0x000000010448e0bc _Z11engine_mainiPPc + 32
ERROR:CRASH: 18  dmengine                            0x0000000104485384 main + 36
ERROR:CRASH: 19  dyld                                0x000000018aa48274 start + 2840
```

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/10431
Fixes https://github.com/defold/defold/issues/10426

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/physics/src/physics/box2d/box2d_physics.cpp [hunk 1]
```diff
@@ -1082,7 +1082,11 @@ namespace dmPhysics
             return;
         }
 
-        HullSet::Hull& hull = shape_data->m_HullSet->m_Hulls[shape_data->m_Cells[child].m_Index];
+        const GridShapeData::Cell& cell = shape_data->m_Cells[child];
+        if (cell.m_Index == B2GRIDSHAPE_EMPTY_CELL)
+            return;
```
Comment (JCash) [inline engine/physics/src/physics/box2d/box2d_physics.cpp:1087]: When the user sets tile "0", it means "clear the cell", and the index is set to B2GRIDSHAPE_EMPTY_CELL.
After this has happened, we didn't check it before trying to iterate over the hull vertices (cannot get a hull is it's an empty cell)

**Review by AGulev — APPROVED** [review]
