### PR TITLE
Set data correctly when recreating dynamic texture in gui

### LINKED ISSUE #8356: Dynamic GUI texture is not set if is created, deleted and created again in the same frame
**Describe the bug (REQUIRED)**
When creating, deleting and creating again texture with the same id in the same frame causes texture to not be used by gui node.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior (note: everything has to happen in the same frame):
1. Create buffer `buffer` with valid image
2. Assign image to `tex_id`
3. Delete `tex_id`
4. Assign image again to `tex_id`
5. Assign `tex_id` to node

Please see code below:
```lua
gui.new_texture(tex_id, img.width, img.height, img.type, img.buffer) -- DynamicTexture::m_Buffer is allocated and img.buffer copied
gui.delete_texture(tex_id)                                           -- free(m_Buffer); m_Buffer = 0
gui.new_texture(tex_id, img.width, img.height, img.type, img.buffer) -- m_Buffer is reused but m_Buffer == 0
gui.set_texture(node, tex_id)                                        -- node renders as it does not have tex_id assigned (white box by default)
```

**Expected behavior (REQUIRED)**
Assigned image is rendered on doubly assigned node.

**Defold version (REQUIRED):**
  - Version: tested on 1.5.0, but probably all versions are affected

**Platforms (REQUIRED):**
 - Platforms: All
 - OS: All
 - Device: All

**Minimal repro case project (OPTIONAL):**
[mre.zip](https://github.com/defold/defold/files/13809328/mre.zip)

**Workaround (OPTIONAL):**
Don't reuse the same texture id in the same frame.

**Additional context (OPTIONAL):**
Root cause

`gui.new_texture` call hierarchy:
```
gui.new_texture (lua)
  LuaNewTexture (gui_script.cpp)
    NewDynamicTexture (gui.cpp)
```
```cpp
// gui_script.cpp
Result NewDynamicTexture(HScene scene, const dmhash_t texture_hash, uint32_t width, uint32_t height, dmImage::Type type, bool flip, const void* buffer, uint32_t buffer_size)
{
    // ...
    if (DynamicTexture* t = scene->m_DynamicTextures.Get(texture_hash)) {
        if (t->m_Deleted) {
            t->m_Deleted = 0; // Bad assumption here. t->m_Buffer == 0 here need to reassign
            return RESULT_OK;
        } else {
            return RESULT_TEXTURE_ALREADY_EXISTS;
        }
    }

    // ...
    DynamicTexture t(0);
    t.m_Buffer = malloc(buffer_size);

    // ...
    memcpy(t.m_Buffer, buffer, buffer_size);
  
    // ...
    scene->m_DynamicTextures.Put(texture_hash, t);
    
    // ...
}
```

`gui.delete_texture` call hierarchy:
```
gui.delete_texture (lua)
  LuaDeleteTexture (gui_script.cpp)
    DeleteDynamicTexture (gui.cpp)
```
```cpp
Result DeleteDynamicTexture(HScene scene, const dmhash_t texture_hash)
{
    // ...
    DynamicTexture* t = scene->m_DynamicTextures.Get(texture_hash);

    // ...
    t->m_Deleted = 1U;

    if (t->m_Buffer) {
        free(t->m_Buffer);
        t->m_Buffer = 0;
    }

    return RESULT_OK;
}
```
`scene->m_DynamicTextures` items Erase is called by
```
RenderScene (gui.cpp)
  DeferredDeleteDynamicTextures (gui.cpp)
```

### PR DESCRIPTION
**Pull request by Jhonnyg**
Bugfix for when recreating a deleted texture within the same frame in GUI:

``` lua
gui.new_texture(tex_id, img.width, img.height, img.type, img.buffer)
gui.delete_texture(tex_id)
gui.new_texture(tex_id, img.width, img.height, img.type, img.buffer)
gui.set_texture(node, tex_id)
```

Fixes #8356 

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gui/src/gui.cpp [hunk 1]
```diff
@@ -532,6 +532,31 @@ namespace dmGui
         return true;
     }
 
+    static Result MakeDynamicTextureData(DynamicTexture* dynamic_texture, uint32_t width, uint32_t height, dmImage::Type type, bool flip, const void* buffer, uint32_t buffer_size)
```
Comment (Jhonnyg) [inline engine/gui/src/gui.cpp:535]: All the dynamic texture functions did the same thing, so I just merged the code paths.

File: engine/gui/src/gui.cpp [hunk 2]
```diff
@@ -540,11 +565,15 @@ namespace dmGui
...
+        {
+            if (t->m_Deleted)
+            {
                 t->m_Deleted = 0;
-                return RESULT_OK;
-            } else {
+                return MakeDynamicTextureData(t, width, height, type, flip, buffer, buffer_size);
+            }
+            else
+            {
```
Comment (Jhonnyg) [inline engine/gui/src/gui.cpp:576]: This is the actual bug:
When a texture exists we un-mark it for deletion here so we can reuse it within the frame, but the buffer with the data has already been deleted. The new data is never put into the buffer, and the old buffer is already deleted by this point so the existing texture will essentially be blank.

**Review by JCash — APPROVED** [review]
