### PR TITLE
Fixed radius calculation of sprites

### LINKED ISSUE #7217: Issue with sprite frustum culling
Not sure if it's a problem with precision or what.
The camera is at position `11852.794921875, 564.09362792969, 0` (or at least the game object is)

User `truv`sent be a project, and I'll try to create a minimal repro case for it.

### PR DESCRIPTION
**Pull request by JCash**
Fixed an issue where the culling radius of a sprite wasn't calculated correctly.
The issue caused some (rotated) sprites to cull prematurely.

## PR checklist (remove before merging)

* [x] Prepared the PR for release notes
	* [x] Proper description of feature or fix (see example x?)
	* [x] Added a #fixes ### if it fixes an issue
	* [x] Assigned issue to a project
* [-] Added documentation for public API changes
* [-] Is this a new feature?
	* [-] Added engine and/or editor unit tests
	* [-] Added or updated manual entry

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -975,27 +976,6 @@ namespace dmGameSystem
...
-        // Thus, we can use the same "physical" indices used between the culling and the render items.
-        for (uint32_t i = 0; i < n; ++i)
-        {
-            SpriteComponent* component = &components[i];
-
-            float sx = Vectormath::Aos::length(component->m_World.getCol(0).getXYZ());
-            float sy = Vectormath::Aos::length(component->m_World.getCol(1).getXYZ());
-            float radius = dmMath::Max(sx, sy) * 0.5f;
-
-            sprite_world->m_BoundingVolumes[i] = radius;
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:995]: That's not the proper way to calculate a radius of a rectangle...

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 2]
```diff
@@ -830,6 +829,10 @@ namespace dmGameSystem
                 Matrix4 world = dmGameObject::GetWorldMatrix(c->m_Instance);
                 Vector3 size( c->m_Size.getX() * c->m_Scale.getX(), c->m_Size.getY() * c->m_Scale.getY(), 1);
                 c->m_World = appendScale(world * local, size);
+                // we need to consider the full scale here
+                // I.e. we want the length of the diagonal C, where C = X + Y
+                float radius_sq = Vectormath::Aos::lengthSqr((c->m_World.getCol(0).getXYZ() + c->m_World.getCol(1).getXYZ()) * 0.5f);
+                sprite_world->m_BoundingVolumes[i] = radius_sq;
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:835]: One benefit of doing the calculation here is that it's only done once per frame, and not once per draw call.

Also, removed some extra calculations by taking the length from the diagonal, as opposed to doing it individually per axis.

**Review by Jhonnyg — DISMISSED** [review]
Seems straight forward 👍

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp (hunk 2 above)
Comment (Jhonnyg) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp:835]: 👍

File: engine/dlib/src/dmsdk/dlib/intersection.h [hunk 3]
```diff
@@ -40,9 +40,12 @@ namespace dmIntersection
 
     void CreateFrustumFromMatrix(const dmVMath::Matrix4& m, bool normalize, Frustum& frustum);
 
+    // Returns true if the objects intersect
     bool TestFrustumPoint(const Frustum& frustum, const dmVMath::Point3& pos, bool skip_near_far);
     bool TestFrustumSphere(const Frustum& frustum, const dmVMath::Point3& pos, float radius, bool skip_near_far);
     bool TestFrustumSphere(const Frustum& frustum, const dmVMath::Vector4& pos, float radius, bool skip_near_far);
+    bool TestFrustumSphereSq(const Frustum& frustum, const dmVMath::Point3& pos, float radius_sq, bool skip_near_far);
+    bool TestFrustumSphereSq(const Frustum& frustum, const dmVMath::Vector4& pos, float radius_sq, bool skip_near_far);
     bool TestFrustumOBB(const Frustum& frustum, const dmVMath::Matrix4& world, dmVMath::Vector3& aabb_min, dmVMath::Vector3& aabb_max, bool skip_near_far);
```
Comment (Jhonnyg) [inline engine/dlib/src/dmsdk/dlib/intersection.h:49]: There's no documentation for these, but maybe not necessary?

Comment (JCash) [reply engine/dlib/src/dmsdk/dlib/intersection.h:49]: Good point. I think I postponed it until I knew it was we wanted going forward.
But now that we're using it for many components, it's time for us to add docs.

**Review by Jhonnyg — APPROVED** [review]
