### PR TITLE
Fix texture page count validation

### LINKED ISSUE #11923: Error building project after version upgrade - "unable to resolve build target from value {:FileResource ...}"
### Actual behaviour
Error building my project from Defold editor 1.12.2 beta
This appears to also reproduce in 1.12.1, but not in 1.12.0. The screenshot/bugreport were produced by 1.12.2 beta.

Image

### Steps to reproduce
Load my project in Defold 1.12.1 or 1.12.2 beta
Build
Get error

<hr/>

<table>
<tr><td>Build time</td><td>2026-02-18T09:22:48.667685</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>31e1a6b7a7b1d217e277a5a2956c18dfacff1618</td></tr>
<tr><td>Defold engine sha</td><td>31e1a6b7a7b1d217e277a5a2956c18dfacff1618</td></tr>
<tr><td>Defold version</td><td>1.12.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d2c7cb1dcb5b4fab97dce011b1672fe8"'>d2c7cb1dcb5b4fab97dce011b1672fe8</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 770</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 32.0.101.6987</td></tr>
<tr><td>Java version</td><td>25+36-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by JosephFerano**
Add a check for when validating atlas page count > 8. Should allow atlases to have as many pages Validation is improved for exceeding the 8 atlas page count and can now be ignored by checking "Exclude GLES 2.0" in game.project Shader section.

Fixes #11923

### CODE REVIEW

**Comment by JosephFerano** [comment]
This is the minimum needed to allow users to exceed 8 pages on their atlases at their discretion.

File: editor/src/clj/editor/atlas.clj [hunk 1]
```diff
@@ -789,13 +791,14 @@
...
-                                                                  page-count)
-                                           page-count))))
+  (output texture-page-count g/Int (g/fnk [_node-id layout-data max-page-size exclude-gles-sm100]
+                                     (when (not exclude-gles-sm100)
+                                       (let [page-count (calculate-texture-page-count layout-data max-page-size)]
+                                         (or (validation/prop-error :fatal _node-id
+                                                                    :validate-texture-page-count
+                                                                    texture-page-count-error-message
+                                                                    page-count)
+                                             page-count)))))
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj]: I don't think `nil` is a valid value for this output looking at how it is used.   We just want to skip the validation. I think it should work if we move the `when` to surround the `validation/prop-error` call instead?

**Review by matgis — CHANGES_REQUESTED** [review]

File: editor/src/clj/editor/atlas.clj (hunk 1 above)
Comment (JosephFerano) [reply editor/src/clj/editor/atlas.clj]: Ah shoot, you're right. Fixed.

**Review by matgis — APPROVED** [review]
