### PR TITLE
Fixed the issue where transformation gizmos for models disappeared when "Component Guides" was turned off

### LINKED ISSUE #9571: Model component gizmo is available only if components guides is on [Editor]
### Expected behaviour
Selelect and moving gizmo should  be always available.
### Actual behaviour
The gizmo is available only if guides is enabled (Ctrl, cmd+H).
See screencast:

https://github.com/user-attachments/assets/c4f11b3f-0f65-45e2-a545-06907d17e85c

Also. In collection preview gizmo for a model component appears only for one object of the selected type on the screen (probably the first one added to the collection), not the object that is currently selected.

Repropduced in 1.9.3 and the actual beta 1.9.4.

<hr/>

<table>
<tr><td>Build time</td><td>2024-10-07T13:30:37.534326</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>c1f033b7800366d04a0b015c9ba51d1e42934a5c</td></tr>
<tr><td>Defold engine sha</td><td>c1f033b7800366d04a0b015c9ba51d1e42934a5c</td></tr>
<tr><td>Defold version</td><td>1.9.4</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.85</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #10498: Transformation gizmos disappeared when "Component guides" is turn off
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
No

**Describe the bug (REQUIRED)**
For model component transformation gizmos is disappeared when turn off "Component guides" toggle in "Visibility filters" menu.

**To Reproduce (REQUIRED)**
1. Create new game object
2. Add any model component
3. Add sprite component
4. Open "Visibility filters" and turn off Component guides toggle
5. See error

**Expected behavior (REQUIRED)**
Gizmos are still available for interaction.

**Defold version (REQUIRED):**
  - Editor: 1.9.8, f68db9583283029bd2c2425839119f34c253143b

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**

**Workaround (OPTIONAL):**
Keep "Component guides" toggle is on

**Screenshots (OPTIONAL):**
https://github.com/user-attachments/assets/c5a1c9ef-9209-4e27-a019-3aec56ea239e

**Additional context (OPTIONAL):**

### PR DESCRIPTION
**Pull request by AGulev**
Fix https://github.com/defold/defold/issues/9571
Fix https://github.com/defold/defold/issues/10498

### CODE REVIEW

File: editor/src/clj/editor/model_scene.clj [hunk 1]
```diff
@@ -372,15 +372,23 @@
...
+                              model-scenes)]
     {:node-id model-scene-resource-node-id
      :aabb aabb
      :renderable {:render-fn render-outline
-                  :tags #{:model :outline}
+                  :tags #{:model}
                   :batch-key nil ; Batching is disabled in the editor for simplicity.
                   :select-batch-key :not-rendered ; The render-fn only does anything during the outline pass.
-                  :passes [pass/outline pass/opaque-selection]} ; Include in a selection pass to ensure it can be selected and manipulated.
-     :children model-scenes}))
```
Comment (AGulev) [inline editor/src/clj/editor/model_scene.clj:383]: We use the same tags for both passes: `pass/outline` and `pass/opaque-selection`, but `:outline` is off by `:toggle-component-guides`, so we should use different tags for these passes

Comment (matgis) [reply editor/src/clj/editor/model_scene.clj:383]: You should probably remove the `:render-fn` and `:select-batch-key` entries from the `:renderable` here too, based on the comments? 🤔

**Review by matgis — DISMISSED** [review]
It works, but it looks like calling the `:render-fn` is now unnecessary for the outline pass?

File: editor/src/clj/editor/model_scene.clj (hunk 1 above)
Comment (AGulev) [reply editor/src/clj/editor/model_scene.clj:383]: done!

Comment (matgis) [reply editor/src/clj/editor/model_scene.clj:383]: No, no! You didn't do what I asked! You broke it now.

**Review by matgis — CHANGES_REQUESTED** [review]

File: editor/src/clj/editor/model_scene.clj (hunk 1 above)
Comment (AGulev) [reply editor/src/clj/editor/model_scene.clj:383]: ah, yeah
sorry
done now

Comment (matgis) [reply editor/src/clj/editor/model_scene.clj:383]: Dammit, I got it wrong when I wrote my "clarifying explanation". 😞 The entries should be removed from the `opaque-selection` pass, not the `outline` pass, because `;; The render-fn only does anything during the outline pass.`

It's still broken. Sorry about that.

**Review by matgis — CHANGES_REQUESTED** [review]
I messed up my explanation, so unfortunately it's still broken. Sorry! 😬

File: editor/src/clj/editor/model_scene.clj (hunk 1 above)
Comment (AGulev) [reply editor/src/clj/editor/model_scene.clj:383]: It's not your fault that I don't use my own brain here. Pros and Cons of code reviews.

Comment (AGulev) [reply editor/src/clj/editor/model_scene.clj:383]: I carefully re-read everything. Removed 2 lines and fixed one comment.
Tested it again to make sure it works.
I think now it's fine

**Review by matgis — APPROVED** [review]
LGTM! ❤️
