### PR TITLE
Removed the `skeleton` property from the `.animationset` resource.

### LINKED ISSUE #7712: Model animation broken in 1.4.6
### Expected behaviour
All model animation worked.
### Actual behaviour
Some of model animations broken.
In 145 all worked. In 146 some models and some animations not worked
### Steps to reproduce

https://github.com/defold/defold/assets/2655263/3b1fdb7e-9014-4ccd-95e7-e7ccc4902fdd

Repro case
[ModelAnimation146.zip](https://github.com/defold/defold/files/11624459/ModelAnimation146.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2023-05-22T08:46:22.602206</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c846a0013bf8606ea55e8fea4f6b3df809e2a1fa</td></tr>
<tr><td>Defold engine sha</td><td>cb8b34230bd42a5e0b68c12441657f06485562a6</td></tr>
<tr><td>Defold version</td><td>1.4.6</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14756 Compatibility Profile Context 20.40.64 27.20.14064.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by JCash**
We've removed the `skeleton` property from the `.animationset` resource.
This allows us to better match animation names with bone names at runtime.

The root bone of a skeleton is now also always renamed to `root`, making it easier to use similar code in engine/scripting.

Fixes https://github.com/defold/defold/issues/7712

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

**Review by matgis — DISMISSED** [review]
Editor and `.proto` changes look good to me.

File: editor/src/clj/editor/animation_set.clj [hunk 1]
```diff
@@ -185,12 +185,16 @@
...
+(defn- sanitize-animation-set [animation-set-desc]
+  (dissoc animation-set-desc :skeleton)) ; Deprecated field.
+
 (defn register-resource-types [workspace]
   (resource-node/register-ddf-resource-type workspace
     :ext "animationset"
     :icon animation-set-icon
     :label "Animation Set"
     :load-fn load-animation-set
+    :sanitize-fn sanitize-animation-set
```
Comment (JCash) [inline editor/src/clj/editor/animation_set.clj:197]: +1
