### PR TITLE
Issue 3775 collision sticking

### LINKED ISSUE #3775: Slow moving collision objects get stuck on collision (DEF-2488)
Description:

If a dynamic collision object has a very low velocity and collides with another object it is likely to get stuck to the object while still retaining some velocity and move along the collision shape. This is caused by a Box2D configurable valueb2_velocityThreshold that by default is set to 1.0f. We should expose this value in game.project.

Steps to reproduce:

Let a dynamic collision object move slowly and collide with another collision object

Expected result:

If Box2D is configured properly the colliding object should still bounce

Actual result:

The colliding object sticks to the other collision object while retaining speed and following the shape.

Reported on the forum:(LINK REMOVED)

### PR DESCRIPTION
**Pull request by otsakir**
Allows flexible update for box2d `velocityThreshold` through game.project configuration options. Implemented in issue #3775 .

### Scope of changes

* Changes has been introduced to box2D bundled code so that it relies on a variable rather than a #define. 
* The core engine will load custom `velocityThreshold` and update the respective variable in Box2D when creating the Context2D.
* The new property has been added to the editor. No code changes there. A new number property under 'physics' section.

### Automated testing

* Since `velocityThreshold` is set to 1.0 by default and we need to change it in order to test, a new _customizable_ property was added to test_gamesys.h:ProjectOptions. A `VelocityThreshold2DTest` class was also added to initialized to a different value.
* You'll notice some renaming in two resources under `gamesys/.../test/collision_object` directory. It seems to me that having a static base and two dynamic objects moving on it seems a generic scenario deserving fewer resource files. So, the body.* and base.* files serve that purpose. They are also used by the older test with sleep/wakeup object. All tests are green in gamesys module.
* The idea of the test implemented is described in https://github.com/defold/defold/issues/3775#issuecomment-928973501

### Manual testing

A tried various tests with marginal velocities for colliding objects while tweaking velocityThreshold in game.project from within the new editor. I also loaded an old project in the new editor to make sure nothing breaks and defaults work properly. I didn't try to load a new project in the old editor.

### CODE REVIEW

File: engine/physics/src/physics/physics_2d.cpp [hunk 1]
```diff
@@ -215,7 +216,9 @@ namespace dmPhysics
         context->m_TriggerEnterLimit = params.m_TriggerEnterLimit * params.m_Scale;
         context->m_RayCastLimit = params.m_RayCastLimit2D;
         context->m_TriggerOverlapCapacity = params.m_TriggerOverlapCapacity;
+        context->m_VelocityThreshold = params.m_VelocityThreshold;
         context->m_AllowDynamicTransforms = params.m_AllowDynamicTransforms;
+        b2ContactSolver::setVelocityThreshold(params.m_VelocityThreshold * params.m_Scale); // overrides fixed b2_velocityThreshold in b2Settings.h. Includes compensation for the scale factor so that velocityThreshold corresponds to the velocity values used in the game.
```
Comment (JCash) [inline engine/physics/src/physics/physics_2d.cpp:221]: 👍

File: engine/physics/src/box2d/Box2D/Dynamics/Contacts/b2ContactSolver.h [hunk 2]
```diff
@@ -88,7 +88,12 @@ class b2ContactSolver
 	b2ContactVelocityConstraint* m_velocityConstraints;
 	b2Contact** m_contacts;
 	int m_count;
+
+	static void setVelocityThreshold(float value); // defold: overrides #define b2_velocityThreshold in b2Settings.h
```
Comment (JCash) [inline engine/physics/src/box2d/Box2D/Dynamics/Contacts/b2ContactSolver.h:92]: 👍

**Review by JCash — APPROVED** [review]
Looks good!
