### PR TITLE
Fix exceptions caused by changing file extensions during renames

### LINKED ISSUE #8549: Renaming no extension "File"s containing plaintext to .MD webview arrow
### Expected behaviour
-making a "File" and naming it any version of "readme.md" then trying to open (which defaults to web-view)

### Actual behaviour
- opening a markdown file made from renaming a "File" containing some text within Defold produces an error message
- right-click > Open As > Text still works correctly

### Steps to reproduce

I'm making a "collection of brain teaser games" game (think Lumosity, Peak, Elevate specifically, or Warioware / Mario Party for real examples of collections of games.

- Make a folder for each game and associated bits and pieces, e.g.
BrainTrain
>DirectionLook
>>DirectionLook.collection, 
>>Arrow.go
>>Arrow.script
>>readme
- inside each minigame's folder, create a New File or New > File, name it readme
- put some text into it
- rename it readme.md
- try and open
- unexpected result

<hr/>

<table>
<tr><td>Build time</td><td>2024-02-15T08:54:48.112358</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7bafadda047312e68a7094c2928e5a403ebf90d8</td></tr>
<tr><td>Defold engine sha</td><td>fcec9500fd438e365d4e4f6cec24b99afb907247</td></tr>
<tr><td>Defold version</td><td>1.6.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b0c6a27aacee4579adb901e5b464e850"'>b0c6a27aacee4579adb901e5b464e850</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 26.20.100.7584</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #8626: Adding a `.lua` suffix to file created with "New File" that is imported somewhere results in error
Not like a lot of people will bump into this one, but may as well report it.

### Steps to reproduce
* Create a gui_script. In it write `local game = main.game`
* Create a file within the `main` folder with the `New File` menu option, name it `game` without a suffix.
* Rename the new file, add `.lua` as the suffix.

<hr/>

<table>
<tr><td>Build time</td><td>2024-02-28T08:46:35.883246</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fde3b9ca14f2629b143173ba41b580c6191317f4</td></tr>
<tr><td>Defold engine sha</td><td>fcec9500fd438e365d4e4f6cec24b99afb907247</td></tr>
<tr><td>Defold version</td><td>1.6.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b314374879784c5d95e07fa65601c932"'>b314374879784c5d95e07fa65601c932</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.9.1.230821</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #10634: Autocompletion fails with error
### Actual behaviour
When trying to autocomplete an import file name, it fails with the error
```
java.lang.AssertionError: Assert failed: Attempting to connect 72057594037932324 (a editor.placeholder-resource/PlaceholderResourceNode) :completion-info to 72057594037928096 (a editor.code.script/ScriptNode) :module-completion-infos, but editor.placeholder-resource/PlaceholderResourceNode does not have an output or property named :completion-info
output-valtype
```

### Steps to reproduce
1. Create foo.lua
3. In main.script write `local Foo = require("f")`, put your cursor after `"f`
4. Press Ctrl + Spacebar to prompt the autocompletion suggesting `foo`
5. Press Tab to confirm
6. Get the error above

<hr/>

<table>
<tr><td>Build time</td><td>2025-04-14T17:21:55.276940</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>591eb496d52f4140bc2c7de547131f1b9408b9b4</td></tr>
<tr><td>Defold engine sha</td><td>591eb496d52f4140bc2c7de547131f1b9408b9b4</td></tr>
<tr><td>Defold version</td><td>1.10.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a7ca9b1390c042cdbb93990e48721125"'>a7ca9b1390c042cdbb93990e48721125</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Iris(R) Xe Graphics (ADL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 25.0.4</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.14.5-300.fc42.x86_64</td></tr>
<table>

### LINKED ISSUE #10932: Trying to use auto complete on a "require" statements string
<hr/>

<table>
<tr><td>Build time</td><td>2025-06-11T16:47:35.104826</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5944eddf7392f6735768b5dfc495695b63ef3c76</td></tr>
<tr><td>Defold engine sha</td><td>7a0e23b3fcab4c5db82f2b32f5d8ac5df9467c9d</td></tr>
<tr><td>Defold version</td><td>1.10.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5c7d1084dbda403a8f9d6aae10ae86cc"'>5c7d1084dbda403a8f9d6aae10ae86cc</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 24.12.1.241127</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #10932 
Fixes #10634
Fixes #10835
Fixes #8549
Fixes #8626
Fixes #10835

### CODE REVIEW

File: editor/src/clj/editor/resource_update.clj [hunk 1]
```diff
@@ -271,8 +271,17 @@
...
                 move-cases))))
 
-(defn resource-change-plan [old-nodes-by-path old-node->old-disk-sha256 {:keys [added removed changed moved] :as changes}]
-  (let [basis (g/now)
+(defn- exclude-extension-changes [moved]
+  ;; It's possible to add an extension to file when renaming it, e.g.,
+  ;; /foo -> /foo.lua
+  ;; We should not redirect such nodes, because different resource extensions
+  ;; might imply different resource node types
+  (filterv #(= (resource/ext (first %)) (resource/ext (second %))) moved))
```
Comment (matgis) [inline editor/src/clj/editor/resource_update.clj]: Should it use `resource/type-ext` to compare extensions? 🤔

**Review by matgis — DISMISSED** [review]

File: editor/src/clj/editor/resource_update.clj (hunk 1 above)
Comment (vlaaad) [reply editor/src/clj/editor/resource_update.clj]: Ah, good point, I forgot about case sensitivity.
