### PR TITLE
[DEFEDIT-6401] Faster resource-sync after external changes

### LINKED ISSUE #6401: The editor takes a very long time to process new assets added using external tools
**Describe the bug (REQUIRED)**
Adding the ready for use assets into the project folder in a big project takes too long. Up to a few minutes to read all the changes.

(ready for use assets means a collection with many images which was generated in an external editor, for example)

**To Reproduce (REQUIRED)**
1. Open a big project
2. Switch to an external text editor
3. Paste content into the collection file
4. Return to the editor window
Editor hangs for a few minustes

**Expected behavior (REQUIRED)**
Editor should read changes faster

**Defold version (REQUIRED):**
1.2.188

### PR DESCRIPTION
**Pull request by matgis**
### User-facing changes
* Reloading large collections or game objects that have been modified externally is now a lot faster.
* The editor will now skip reloading externally touched files if they already match the in-memory state.

### Technical changes
* Added metrics for time spent in project loading, resource-sync, and graph transactions during development. To enable, add the `metrics` profile to the Leiningen command line, or start `java` with `-Ddefold.metrics=true` when running the editor.
* Optimized graph traversal when applying overrides.
* We now calculate the hash of externally touched files and compare them to our in-memory state to check if they have meaningful changes. If they do not, we skip reload and keep the existing nodes in the graph.
* The `g/override` function now takes a `:traverse-fn` instead of a `:traverse?` predicate in the `opts` map. You can create a `traverse-fn` from a `traverse?` predicate using `(g/make-override-traverse-fn traverse?)`. Like before, the `traverse?` function takes a `Basis` and an `Arc`, and is expected to return `true` if the Arc should be followed.
* Added `g/node-instance-of-any?` for when you want to efficiently determine if the type of a Node adheres to any of several node types.
* We now use `Arcs` and `pair` in some hot-spots where we used to use multi-element Clojure vectors.

Fixes #6401

### CODE REVIEW

File: editor/src/clj/internal/graph/types.clj [hunk 1]
```diff
@@ -12,15 +12,18 @@
...
-(ns internal.graph.types
-  (:require [internal.util :as util]
-            [schema.core :as s]))
+(ns internal.graph.types)
 
 (set! *warn-on-reflection* true)
+(set! *unchecked-math* :warn-on-boxed)
 
-(defrecord Arc [source-id source-label target-id target-label])
+(defrecord Arc [^long source-id source-label ^long target-id target-label])
```
[the remark this answers is not in the document]
Comment (vlaaad) [reply editor/src/clj/internal/graph/types.clj:20]: Wouldn't it result in a lot of boxing in the places where source-id/target-id are used?

File: editor/src/clj/editor/defold_project.clj [hunk 2]
```diff
@@ -142,40 +146,64 @@
...
+        resource-metrics-load-timer (du/when-metrics
+                                      (volatile! 0))
+        start-resource-metrics-load-timer! (du/when-metrics
+                                             (fn []
+                                               (vreset! resource-metrics-load-timer (System/nanoTime))))
+        stop-resource-metrics-load-timer! (du/when-metrics
+                                            (fn [resource-path]
+                                              (let [end-time (System/nanoTime)
+                                                    ^long start-time @resource-metrics-load-timer]
+                                                (du/update-metrics resource-metrics resource-path :process-load-tx-data (- end-time start-time)))))
```
Comment (vlaaad) [inline editor/src/clj/editor/defold_project.clj:178]: I think the abstraction for metrics could be a bit cleaner? I like how it's done in `util.profiler`, where you provide a keyword id to the profile block. We could have something similar instead? E.g.
```clj
(du/begin ::load) ;; compiles to nothing if metrics are disabled, 
                  ;; otherwise starts measuring in a global metrics atom
```

Also, I think `(System/nanoTime)` should and `end-start` stuff should be fully encapsulated in this measure util

File: editor/src/clj/util/debug_util.clj [hunk 3]
```diff
@@ -0,0 +1,118 @@
+(ns util.debug-util)
```
Comment (vlaaad) [inline editor/src/clj/util/debug_util.clj:1]: Maybe pick a more descriptive name than `util.debug-util`? Like `util.measure`, perhaps?

File: editor/src/clj/editor/resource_update.clj [hunk 4]
```diff
@@ -61,33 +66,95 @@
...
+                           nil))
+            new-sha256 (try
+                         (if (and read-fn write-fn)
+                           (let [source-value (read-fn new-resource)
+                                 sanitized-content (write-fn source-value)]
+                             (DigestUtils/sha256Hex ^String sanitized-content))
+                           (with-open [input-stream (io/input-stream new-resource)]
+                             (DigestUtils/sha256Hex ^InputStream input-stream)))
+                         (catch Exception _
+                           nil))]
```
Comment (vlaaad) [inline editor/src/clj/editor/resource_update.clj:101]: Is it safe to assume that for every unchanged resource node its `:sha265` output is `(sha (write (read resource)))`?

File: editor/src/clj/editor/resource_update.clj [hunk 5]
```diff
@@ -221,12 +296,18 @@
...
+        old-resource-by-old-node (g/with-auto-evaluation-context evaluation-context
+                                   (into {}
+                                         (map (fn [[_ old-node]]
+                                                (let [old-resource (g/node-value old-node :resource evaluation-context)]
+                                                  [old-node old-resource])))
+                                         old-nodes-by-path))
+        resource->old-resource (comp old-resource-by-old-node resource->old-node)
         resource-swapped? (fn [r] (not= r (resource->old-resource r)))
-        changed-map (into {} (map (juxt resource/proj-path identity) changed))
+        changed-map (into {} (map (juxt resource/proj-path identity)) changed)
```
[the remark this answers is not in the document]
Comment (vlaaad) [reply editor/src/clj/editor/resource_update.clj:311]: If you care about GC pressure here, you can also avoid creating temporary vectors with `juxt` and use `reduce`+`assoc!`

File: editor/src/clj/internal/graph/types.clj [hunk 6]
```diff
@@ -12,15 +12,18 @@
...
 
+(defn source-id ^long [^Arc arc] (.source-id arc))
+(defn source-label [^Arc arc] (.source-label arc))
 (defn source [^Arc arc] [(.source-id arc) (.source-label arc)])
+(defn target-id ^long [^Arc arc] (.target-id arc))
```
Comment (vlaaad) [inline editor/src/clj/internal/graph/types.clj:25]: The same concern about hurting the performance here: usages of `source-id`/`target-id` will have to box anyway to do lookups in the graph.

**Review by vlaaad — CHANGES_REQUESTED** [review]
I think the measuring system is too invasive into graph internals for a dev-only helper and could be backed a bit more. Perhaps we could move it to another PR and take the opportunity to unify it with `util.profiler` and `*tps-debug*`? 

Great improvements on the resource sync time!

**Review by matgis — COMMENTED** [review]
I think I've addressed most of your concerns, but I don't really see how we the changes made to `internal.transaction` can be made less intrusive. We need to instrument the individual transaction steps plus the overhead of the finalizing functions somehow, and all of the metrics stuff is compiled out unless you enable metrics. As far as I understand, `*tx-debug*` can be toggled at runtime via a REPL, so I don't see how that applies. Do you have any suggestions how we could make it less intrusive?

**Comment by vlaaad** [comment]
I was thinking about instrumenting all `g/transact` calls and then using a sliding buffer (like in `util.profiler`) in the global metrics collector so it doesn't eat all the memory in development.

**Review by vlaaad — APPROVED** [review]
LGTM!
