### PR TITLE
API documentation fixes

### LINKED ISSUE #9915: API reference issues (collectionfactory.create() scale)
**Describe the bug (REQUIRED)**
API reference issues 

Scale also can be number, vector3
but in doc it only number
https://defold.com/ref/collectionfactory/#collectionfactory.create:url-%5Bposition%5D-%5Brotation%5D-%5Bproperties%5D-%5Bscale%5D
https://defold.com/ref/stable/collectionfactory/?q=factory#collectionfactory.create:url-%5Bposition%5D-%5Brotation%5D-%5Bproperties%5D-%5Bscale%5D

[scale] number

### PR DESCRIPTION
**Pull request by d954mas**
Fixed two issues in api documentation:

1) scale can be number or vector3 in `collectionfactory.create`
2) text can be string or number in `label.set_text`

Fixes #9915

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### CODE REVIEW

File: engine/gamesys/src/gamesys/scripts/script_label.cpp [hunk 1]
```diff
@@ -264,7 +264,7 @@ static const char* LABEL_EXT = "labelc";
  *
  * @name label.set_text
  * @param url [type:string|hash|url] the label that should have a constant set
- * @param text [type:string] the text
+ * @param text [type:string|number] the text
```
Comment (JCash) [inline engine/gamesys/src/gamesys/scripts/script_label.cpp:267]: I think it's perhaps more correct to say anything that supports "tostring()".
Perhaps `object` is the way to go here?

Comment (britzl) [reply engine/gamesys/src/gamesys/scripts/script_label.cpp:267]: > I think it's perhaps more correct to say anything that supports "tostring()".
> Perhaps `object` is the way to go here?

I don't think we are documenting it like this anywhere else?

Comment (d954mas) [reply engine/gamesys/src/gamesys/scripts/script_label.cpp:267]: bad argument #2 to 'set_text' (string expected, got boolean)
bad argument #2 to 'set_text' (string expected, got table)

number and string worked

**Comment by d954mas** [comment]
Hi) Please look)

File: engine/gamesys/src/gamesys/scripts/script_label.cpp (hunk 1 above)
Comment (britzl) [reply engine/gamesys/src/gamesys/scripts/script_label.cpp:267]: We document gui.set_text() the same way with string|number accepted

**Review by britzl — APPROVED** [review]
