### PR TITLE
Do not render mesh if it was deleted in the same frame as it was created

### LINKED ISSUE #10957: Crash when trying delete go with mesh
**Describe the bug (REQUIRED)**
Crash when trying deleting game object with mesh

**To Reproduce (REQUIRED)**

1. open attachment
2. run

**Expected behavior (REQUIRED)**
no crash

**Defold version (REQUIRED):**
  - Version 1.10.3

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Fedora Linux 42 (Workstation Edition), 6.15.4-200.fc42.x86_64

**Minimal repro case project (OPTIONAL):**
[My Project.zip](https://github.com/user-attachments/files/21178126/My.Project.zip)

### PR DESCRIPTION
**Pull request by britzl**
If a mesh component is created and then deleted in the same frame (for instance by calling `go.delete()` in `init()`) it should not be rendered.

Fixes #10957

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_mesh.cpp [hunk 1]
```diff
@@ -490,7 +490,9 @@ namespace dmGameSystem
             MeshComponent& component = *components[i];
 
             if (!component.m_Enabled || !component.m_AddedToUpdate)
+            {
```
Comment (britzl) [inline engine/gamesys/src/gamesys/components/comp_mesh.cpp:493]: Some code hygiene in a few places

File: engine/gamesys/src/gamesys/components/comp_mesh.cpp [hunk 2]
```diff
@@ -900,8 +902,10 @@ namespace dmGameSystem
         for (uint32_t i = 0; i < count; ++i)
         {
             MeshComponent& component = *components[i];
-            if (!component.m_Enabled)
+            if (!component.m_Enabled || !component.m_AddedToUpdate)
```
Comment (britzl) [inline engine/gamesys/src/gamesys/components/comp_mesh.cpp:905]: The fix. If the mesh wasn't added to update the CompMeshUpdate() function wasn't called which means that the buffer wasn't copied to the vertex buffer and we should not try to render it.

We do the same check in comp_sprite, comp_particlefx etc.

**Review by AGulev — APPROVED** [review]
