### PR TITLE
Fix crash when changing sprite atlas and sprite has an invalid animation

### LINKED ISSUE #7445: Crash when changing sprite atlas and sprite has an invalid animation
**Describe the bug (REQUIRED)**
The engine crashes if the atlas/tilesource of a sprite is changed and the sprite uses an animation which doesn't exist in the new atlas/tilesource.

**To Reproduce (REQUIRED)**
See example project for steps to repro.

```
Assertion failed: (i < m_Count), function operator[], file texture_set_ddf.h, line 88.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/bjornritzl/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

# 0 pc     0x2839c4 dmengine _ZN7dmCrashL7HandlerEiP9__siginfoPv+36
# 1 pc      0x69dfd libc++abi.dylib _sigtramp+29
# 2 pc      0x1e00f libc++abi.dylib __pthread_kill+11
# 3 pc      0x541ff libc++abi.dylib pthread_kill+263
# 4 pc     0x218d24 libxpc.dylib abort+123
# 5 pc     0x2180cb libxpc.dylib err+0
# 6 pc     0x2d6cf1 dmengine _ZN12dmGameSystemL27UpdateCurrentAnimationFrameEPNS_15SpriteComponentE.cold.1+33
# 7 pc      0x6088b dmengine _ZN12dmGameSystemL27UpdateCurrentAnimationFrameEPNS_15SpriteComponentE+299
# 8 pc      0x5d3cd dmengine _ZN12dmGameSystem16CompSpriteUpdateERKN12dmGameObject22ComponentsUpdateParamsERNS0_22ComponentsUpdateResultE+397
# 9 pc      0x1d307 dmengine _ZN12dmGameObject6UpdateEPNS_16CollectionHandleEPKNS_13UpdateContextE+503
#10 pc       0x74e9 dmengine _ZN8dmEngine4StepEPNS_6EngineE+1065
#11 pc       0x7b7a dmengine _Z14dmEngineUpdatePN8dmEngine6EngineE+26
#12 pc       0x868d dmengine _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE+109
#13 pc       0x85f2 dmengine _Z11engine_mainiPPc+98
```
**Expected behavior (REQUIRED)**
It should not crash

**Defold version (REQUIRED):**
  - 1.4.4

**Platforms (REQUIRED):**
 - All platforms

**Minimal repro case project (OPTIONAL):**
See attached project

### PR DESCRIPTION
**Pull request by AGulev**
Fix crash when set new atlas which has more animations than the old one but without animation with the same name which currently playing.

Fix https://github.com/defold/defold/issues/7445

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -1400,16 +1400,20 @@ namespace dmGameSystem
...
-                uint32_t* anim_id =  GetTextureSet(component, component->m_Resource)->m_AnimationIds.Get(component->m_CurrentAnimation);
+                TextureSetResource* texture_set = GetTextureSet(component, component->m_Resource);
+                uint32_t* anim_id =  texture_set->m_AnimationIds.Get(component->m_CurrentAnimation);
                 if (anim_id)
                 {
                     PlayAnimation(component, component->m_CurrentAnimation, GetCursor(component), component->m_PlaybackRate);
                 }
                 else
                 {
-                    component->m_Playing = 0;
```
Comment (britzl) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:1410]: Why are we no longer setting m_Playing to 0?

Comment (AGulev) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp:1410]: because it is typo ( good catch!

Comment (AGulev) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp:1410]: Fixed

**Review by britzl — APPROVED** [review]
