### PR TITLE
Issue 5844: Fixed animated render constant crash

### LINKED ISSUE #5844: Render-related engine crash on macOS
**Describe the bug (REQUIRED)**
The engine crashes when loading a scene.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior: Unsure, but crashes reliably in one of our projects (https://github.com/critique-gaming/gmai). Can give you Github access if you want to.

**Expected behavior (REQUIRED)**
Not a crash

**Defold version (REQUIRED):**
  - 1.2.183 (7e52cad)

**Platforms (REQUIRED):**
 - Platforms: macOS 11.3.1
 - OS: macOS 11.3.1
 - Device: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports), Intel Iris Plus Graphics 650

**Logs (OPTIONAL):**
[_crash.zip](https://github.com/defold/defold/files/6584151/_crash.zip)

```
Process:               dmengine [88033]
Path:                  /Applications/Defold.app/Contents/MacOS/Defold
Identifier:            com.defold.editor
Version:               2.0 (2.0)
Code Type:             X86-64 (Native)
Parent Process:        java [58694]
User ID:               501

Date/Time:             2021-06-02 14:32:43.574 +0300
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        CE833B60-AF6D-31BB-F0FD-7F824FFC1EF2

Sleep/Wake UUID:       CEC8C46E-BBE5-4D80-A8E4-D6809C43B44E

Time Awake Since Boot: 180000 seconds
Time Since Wake:       2300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  engine_main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [88033]

Thread 0 Crashed:: engine_main  Dispatch queue: com.apple.main-thread
0   com.apple.driver.AppleIntelKBLGraphicsGLDriver	0x00007fff5ef1e0d0 void ILAdapter::DeleteCompilerOutputPixelShaderOpenGL_impl_IGC<USC::SCompilerOutputPixelShaderOpenGL_Gen9>(USC::SCompilerOutputPixelShaderOpenGL_Gen9*&) + 16
1   com.apple.driver.AppleIntelKBLGraphicsGLDriver	0x00007fff5ef1de21 USC::IM_Shader::~IM_Shader() + 49
2   com.apple.driver.AppleIntelKBLGraphicsGLDriver	0x00007fff5ef1dd0f freeShader(ShaderInfoRec*) + 188
3   com.apple.driver.AppleIntelKBLGraphicsGLDriver	0x00007fff5ef1dbc5 clearShaderCache(GLDContextRec*, ShaderInfoCacheRec*) + 282
4   com.apple.driver.AppleIntelKBLGraphicsGLDriver	0x00007fff5edefc1c intelUpdateCtxSysProgramCommon(GLDContextRec*, GLDProgramRec*, GLDPipelineProgramRec*, void*, ShaderInfoCacheRec*, unsigned int) + 257
5   com.apple.driver.AppleIntelKBLGraphicsGLDriver	0x00007fff5edef2a8 gpusLoadCurrentPipelinePrograms + 3511
6   com.apple.driver.AppleIntelKBLGraphicsGLDriver	0x00007fff5eded17d updateDispatch + 1590
7   GLEngine                      	0x00007fff6bce22ec gleDoDrawDispatchCoreGL3 + 674
8   GLEngine                      	0x00007fff6bcb2d69 glDrawArrays_ACC_GL3Exec + 236
9   dmengine                      	0x000000010fd9bf0f dmGraphics::OpenGLDraw(dmGraphics::Context*, dmGraphics::PrimitiveType, unsigned int, unsigned int) + 159 (graphics_opengl.cpp:1609)
10  dmengine                      	0x000000010fdde5e1 dmRender::Draw(dmRender::RenderContext*, dmRender::Predicate*, dmRender::NamedConstantBuffer*) + 1377 (render.cpp:682)
11  dmengine                      	0x000000010fdddd36 dmRender::DrawRenderList(dmRender::RenderContext*, dmRender::Predicate*, dmRender::NamedConstantBuffer*) + 2790 (render.cpp:608)
12  dmengine                      	0x000000010fde2c1b dmRender::ParseCommands(dmRender::RenderContext*, dmRender::Command*, unsigned int) + 731 (render_command.cpp:168)
13  dmengine                      	0x000000010fde75ea dmRender::UpdateRenderScriptInstance(dmRender::RenderScriptInstance*, float) + 170 (render_script.cpp:2930)
14  dmengine                      	0x000000010fce777c dmEngine::Step(dmEngine::Engine*) + 1164 (engine.cpp:1526)
15  dmengine                      	0x000000010fce897a dmEngineUpdate(dmEngine::Engine*) + 26 (engine.cpp:1955)
16  dmengine                      	0x000000010fce8bad dmEngine::RunLoop(dmEngine::RunLoopParams const*) + 109 (engine_loop.cpp:69)
17  dmengine                      	0x000000010fce8b12 EngineMain(int, char**) + 90 (engine_main.cpp:49) [inlined]
18  dmengine                      	0x000000010fce8b12 engine_main(int, char**) + 98 (engine_main.cpp:126)
19  dmengine                      	0x000000010fc9f394 start + 52

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff20463484 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff20463484 start_wqthread + 0

Thread 3:: log
0   libsystem_kernel.dylib        	0x00007fff20434c22 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff203b4c2a nanosleep + 196
2   libsystem_c.dylib             	0x00007fff203b4b24 usleep + 53
3   dmengine                      	0x000000010feb6499 dmLogThread(void*) + 121 (log.cpp:279)
4   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
5   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
6   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff20463484 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff20463484 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff20463484 start_wqthread + 0

Thread 7:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ed7 _pthread_cond_wait + 1352
2   com.apple.CoreVideo           	0x00007fff27393fe3 CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff273934ec CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 8:: graphicsworker
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ea1 _pthread_cond_wait + 1298
2   dmengine                      	0x000000010fedfd7e dmConditionVariable::Wait(dmConditionVariable::ConditionVariable*, dmMutex::Mutex*) + 14 (condition_variable.cpp:58)
3   dmengine                      	0x000000010fd9fb66 dmGraphics::AsyncThread(void*) + 102 (job_queue_threaded.cpp:58)
4   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
5   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
6   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 9:: http
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ea1 _pthread_cond_wait + 1298
2   dmengine                      	0x000000010fedfd7e dmConditionVariable::Wait(dmConditionVariable::ConditionVariable*, dmMutex::Mutex*) + 14 (condition_variable.cpp:58)
3   dmengine                      	0x000000010feb7efb dmMessage::InternalDispatch(unsigned long long, void (*)(dmMessage::Message*, void*), void*, bool) + 267 (message.cpp:510)
4   dmengine                      	0x000000010fde8b48 dmHttpService::Loop(void*) + 72 (http_service.cpp:330)
5   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
6   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 10:: http
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ea1 _pthread_cond_wait + 1298
2   dmengine                      	0x000000010fedfd7e dmConditionVariable::Wait(dmConditionVariable::ConditionVariable*, dmMutex::Mutex*) + 14 (condition_variable.cpp:58)
3   dmengine                      	0x000000010feb7efb dmMessage::InternalDispatch(unsigned long long, void (*)(dmMessage::Message*, void*), void*, bool) + 267 (message.cpp:510)
4   dmengine                      	0x000000010fde8b48 dmHttpService::Loop(void*) + 72 (http_service.cpp:330)
5   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
6   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 11:: http
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ea1 _pthread_cond_wait + 1298
2   dmengine                      	0x000000010fedfd7e dmConditionVariable::Wait(dmConditionVariable::ConditionVariable*, dmMutex::Mutex*) + 14 (condition_variable.cpp:58)
3   dmengine                      	0x000000010feb7efb dmMessage::InternalDispatch(unsigned long long, void (*)(dmMessage::Message*, void*), void*, bool) + 267 (message.cpp:510)
4   dmengine                      	0x000000010fde8b48 dmHttpService::Loop(void*) + 72 (http_service.cpp:330)
5   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
6   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 12:: http
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ea1 _pthread_cond_wait + 1298
2   dmengine                      	0x000000010fedfd7e dmConditionVariable::Wait(dmConditionVariable::ConditionVariable*, dmMutex::Mutex*) + 14 (condition_variable.cpp:58)
3   dmengine                      	0x000000010feb7efb dmMessage::InternalDispatch(unsigned long long, void (*)(dmMessage::Message*, void*), void*, bool) + 267 (message.cpp:510)
4   dmengine                      	0x000000010fde8b48 dmHttpService::Loop(void*) + 72 (http_service.cpp:330)
5   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
6   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 13:: http_balance
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ea1 _pthread_cond_wait + 1298
2   dmengine                      	0x000000010fedfd7e dmConditionVariable::Wait(dmConditionVariable::ConditionVariable*, dmMutex::Mutex*) + 14 (condition_variable.cpp:58)
3   dmengine                      	0x000000010feb7efb dmMessage::InternalDispatch(unsigned long long, void (*)(dmMessage::Message*, void*), void*, bool) + 267 (message.cpp:510)
4   dmengine                      	0x000000010fde8bbf dmHttpService::LoadBalancer(void*) + 47 (http_service.cpp:345)
5   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
6   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 14:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff20432366 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff284ff8da caulk::mach::semaphore::wait_or_error() + 16
2   com.apple.audio.caulk         	0x00007fff284ec836 caulk::semaphore::timed_wait(double) + 110
3   com.apple.audio.caulk         	0x00007fff284ec784 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff284ec502 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
6   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 15:
0   libsystem_kernel.dylib        	0x00007fff2043237e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff202bdcf5 _dispatch_sema4_timedwait + 72
2   libdispatch.dylib             	0x00007fff202be125 _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff202cc636 _dispatch_worker_thread + 284
4   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 16:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff2043232a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff2043269c mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff21f37f19 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 111
3   com.apple.audio.CoreAudio     	0x00007fff21ddab37 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 3365
4   com.apple.audio.CoreAudio     	0x00007fff21f766e8 HALB_IOThread::Entry(void*) + 72
5   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
6   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 17:
0   libsystem_kernel.dylib        	0x00007fff2043237e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff202bdcf5 _dispatch_sema4_timedwait + 72
2   libdispatch.dylib             	0x00007fff202be125 _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff202cc636 _dispatch_worker_thread + 284
4   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 18:: sound
0   libsystem_kernel.dylib        	0x00007fff20434c22 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff203b4c2a nanosleep + 196
2   libsystem_c.dylib             	0x00007fff203b4b24 usleep + 53
3   dmengine                      	0x000000010ff026aa dmSound::SoundThread(dmSound::SoundSystem*) + 42 (sound.cpp:1456)
4   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
5   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
6   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 19:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff2043232a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff2043269c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff20560c6f __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff2055f34f __CFRunLoopRun + 1328
4   com.apple.CoreFoundation      	0x00007fff2055e75c CFRunLoopRunSpecific + 563
5   com.apple.AppKit              	0x00007fff22ee0baa _NSEventThread + 124
6   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 20:: liveupdate
0   libsystem_kernel.dylib        	0x00007fff20434d4e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20467ea1 _pthread_cond_wait + 1298
2   dmengine                      	0x000000010fedfd7e dmConditionVariable::Wait(dmConditionVariable::ConditionVariable*, dmMutex::Mutex*) + 14 (condition_variable.cpp:58)
3   dmengine                      	0x000000010ff2ab0a dmLiveUpdate::AsyncThread(void*) + 394 (liveupdate_async.cpp:97)
4   dmengine                      	0x000000010fec58ac dmThread::ThreadStartProxy(void*) + 28 (thread.cpp:42)
5   libsystem_pthread.dylib       	0x00007fff20467954 _pthread_start + 224
6   libsystem_pthread.dylib       	0x00007fff204634a7 thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x3d4ccccd3f3ebebf  rbx: 0x00007fefc742c880  rcx: 0x0000000000000000  rdx: 0x00000000000e22a0
  rdi: 0x00007fefc742c8a8  rsi: 0x000007fefc751986  rbp: 0x00007ffedff607b0  rsp: 0x00007ffedff60790
   r8: 0x000000000000157f   r9: 0x0000000000000003  r10: 0x00007fefc7500000  r11: 0x00007fefc7530450
  r12: 0x00007fefc7447c40  r13: 0x00007fefba7e8350  r14: 0x00007fefc742c880  r15: 0x00007fefbb6b6800
  rip: 0x00007fff5ef1e0d0  rfl: 0x0000000000010206  cr2: 0x000000c00047b000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     13

Thread 0 instruction stream:
  83 c3 18 48 89 df 48 83-c4 08 5b 5d e9 df 66 3f  ...H..H...[]..f?
  00 48 83 c3 28 48 89 df-48 83 c4 08 5b 5d e9 0d  .H..(H..H...[]..
  67 3f 00 e8 09 88 cb 00-f2 fd ff ff ac fe ff ff  g?..............
  5e fe ff ff de fe ff ff-28 fe ff ff 0f 1f 40 00  ^.......(.....@.
  55 48 89 e5 5d e9 06 00-00 00 66 0f 1f 44 00 00  UH..].....f..D..
  55 48 89 e5 53 48 83 e4-f0 48 83 ec 10 48 8b 07  UH..SH...H...H..
 [48]8b 00 48 85 c0 0f 84-9f 00 00 00 48 89 fb 48  H..H........H..H	<==
  8b b8 d8 02 00 00 48 85-ff 74 14 83 b8 f0 02 00  ......H..t......
  00 00 74 0b e8 b1 97 cb-00 48 8b 03 48 8b 00 48  ..t......H..H..H
  8b b8 e0 02 00 00 48 85-ff 74 0e 83 b8 f4 02 00  ......H..t......
  00 00 74 05 e8 91 97 cb-00 48 8b 03 48 8b 08 48  ..t......H..H..H
  8b b9 e8 02 00 00 48 85-ff 74 14 83 b9 f8 02 00  ......H..t......
  
Thread 0 last branch register state not available.


Binary Images:
       0x10fc9e000 -        0x110026fff +dmengine (???) <AD49CAC0-D2BD-36D1-B108-B4116E309D1D> /Users/USER/*/dmengine
       0x110736000 -        0x110745fff  libobjc-trampolines.dylib (824) <443A76FC-45AB-380A-98BF-EF0466708A33> /usr/lib/libobjc-trampolines.dylib
       0x113176000 -        0x11317dfff  com.apple.audio.AppleHDAHALPlugIn (283.15 - 283.15) <FDEE29C6-56E7-3E0F-A77C-BAF341F90F34> /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn
       0x113191000 -        0x11322cfff  dyld (851.27) <7EAA668B-F906-3BAA-A980-139BBE6E8766> /usr/lib/dyld
       0x117121000 -        0x117284fff  com.apple.audio.units.Components (1.14 - 1.14) <1584243B-9F90-3A29-84CA-7CC028CE741F> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x1172bd000 -        0x117878fff  com.apple.audio.AudioDSPComponents (1.0 - 1) <E56B3314-6552-3DE4-8299-67F4DDCD5A87> /System/Library/Components/AudioDSP.component/Contents/MacOS/AudioDSP
    0x7fff2019f000 -     0x7fff201a0fff  libsystem_blocks.dylib (79) <1C8538C3-F2BE-3F02-89AE-E7052DE66D51> /usr/lib/system/libsystem_blocks.dylib
    0x7fff201a1000 -     0x7fff201d6fff  libxpc.dylib (2038.100.48) <CFB56DA8-7462-3E8F-9CFB-20926C6A2BB5> /usr/lib/system/libxpc.dylib
    0x7fff201d7000 -     0x7fff201eefff  libsystem_trace.dylib (1277.100.21) <1AAE1F8F-9F9D-3327-8A95-3A6887CED713> /usr/lib/system/libsystem_trace.dylib
    0x7fff201ef000 -     0x7fff2028cfff  libcorecrypto.dylib (1000.100.38) <96A88875-7771-394E-A88E-389DCD02A935> /usr/lib/system/libcorecrypto.dylib
    0x7fff2028d000 -     0x7fff202b9fff  libsystem_malloc.dylib (317.100.9) <029B5632-62B4-39F6-981C-BCA99C1FBF1D> /usr/lib/system/libsystem_malloc.dylib
    0x7fff202ba000 -     0x7fff202fefff  libdispatch.dylib (1271.100.5) <6B7B23E3-2FD4-3EA2-8A89-CE06244CCA98> /usr/lib/system/libdispatch.dylib
    0x7fff202ff000 -     0x7fff20338fff  libobjc.A.dylib (824) <929E3040-4605-3C14-885B-D742EF02F2CB> /usr/lib/libobjc.A.dylib
    0x7fff20339000 -     0x7fff2033bfff  libsystem_featureflags.dylib (28.60.1) <FEA91919-A5BB-3606-9445-F2077D90BF87> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff2033c000 -     0x7fff203c4fff  libsystem_c.dylib (1439.100.3) <DF45CDEC-6B7E-3586-94B4-F3679A762661> /usr/lib/system/libsystem_c.dylib
    0x7fff203c5000 -     0x7fff2041afff  libc++.1.dylib (905.6) <B027735F-B398-381C-84A7-606D7BBE4997> /usr/lib/libc++.1.dylib
    0x7fff2041b000 -     0x7fff20430fff  libc++abi.dylib (905.6) <22AFC7FC-2DB6-3EF0-9CC0-EFFB9B65D5E2> /usr/lib/libc++abi.dylib
    0x7fff20431000 -     0x7fff20460fff  libsystem_kernel.dylib (7195.101.2) <62A19DE4-50C5-3866-B5B2-43220E379C3B> /usr/lib/system/libsystem_kernel.dylib
    0x7fff20461000 -     0x7fff2046cfff  libsystem_pthread.dylib (454.100.8) <52F807B1-41A0-3D1E-AE89-115CA570863F> /usr/lib/system/libsystem_pthread.dylib
    0x7fff2046d000 -     0x7fff204a8fff  libdyld.dylib (851.27) <9F95C644-D1BD-38D9-9612-6188FE9EA53C> /usr/lib/system/libdyld.dylib
    0x7fff204a9000 -     0x7fff204b2fff  libsystem_platform.dylib (254.80.2) <03429519-EBEA-3549-84A6-0FD426CB7373> /usr/lib/system/libsystem_platform.dylib
    0x7fff204b3000 -     0x7fff204defff  libsystem_info.dylib (542.40.3) <C189F0D7-A430-328D-BD7F-7EB0FA023736> /usr/lib/system/libsystem_info.dylib
    0x7fff204df000 -     0x7fff2097cfff  com.apple.CoreFoundation (6.9 - 1775.118.101) <895AFD1C-0307-32B3-81CB-BA33DA368DE1> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2097d000 -     0x7fff20baffff  com.apple.LaunchServices (1122.33 - 1122.33) <CBFF2714-646C-3DDB-906D-672E420683E6> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff20bb0000 -     0x7fff20c83fff  com.apple.gpusw.MetalTools (1.0 - 1) <CD0A257C-70F9-3C42-A13E-76FD54BEFD96> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff20c84000 -     0x7fff20ee0fff  libBLAS.dylib (1336.101.1) <28ABAD61-A323-33C6-8674-8A14118D4C20> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff20ee1000 -     0x7fff20f2dfff  com.apple.Lexicon-framework (1.0 - 86.1) <27959773-C4F4-33BC-9A68-39EF2037F1E5> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff20f2e000 -     0x7fff20f9cfff  libSparse.dylib (106) <A666D9B0-8979-3C9C-83D6-1C0B535B8B0F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff20f9d000 -     0x7fff2101afff  com.apple.SystemConfiguration (1.20 - 1.20) <BEDC3BFB-D680-3E56-9A3A-2FAB181C52A9> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff2101b000 -     0x7fff2104ffff  libCRFSuite.dylib (50) <E49A8F87-3F3A-3A0F-853E-65FA6FB33E77> /usr/lib/libCRFSuite.dylib
    0x7fff21050000 -     0x7fff21288fff  libmecabra.dylib (929.9) <87ACCBB5-FD09-3044-B6FF-1A94A7129DDF> /usr/lib/libmecabra.dylib
    0x7fff21289000 -     0x7fff215e6fff  com.apple.Foundation (6.9 - 1775.118.101) <5B112EDB-35C1-31A7-BFDA-E185D1B49D93> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff215e7000 -     0x7fff216cffff  com.apple.LanguageModeling (1.0 - 247.3) <81DEF845-C1A0-3BD0-9820-D1C308AFBE09> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff216d0000 -     0x7fff21806fff  com.apple.CoreDisplay (236.4 - 236.4) <C1F98CC6-5C02-372D-BFC8-420DEF159C9D> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff21807000 -     0x7fff21a77fff  com.apple.audio.AudioToolboxCore (1.0 - 1180.90) <EB4DE2B5-7947-3422-8151-9E1BDA2B3183> /System/Library/PrivateFrameworks/AudioToolboxCore.framework/Versions/A/AudioToolboxCore
    0x7fff21a78000 -     0x7fff21c5cfff  com.apple.CoreText (677.4.0.4 - 677.4.0.4) <F65330BD-9D48-3DE5-9E6B-1232B5BDB656> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff21c5d000 -     0x7fff222edfff  com.apple.audio.CoreAudio (5.0 - 5.0) <68667A4E-B4BC-3DF4-9D34-1E3ECECF7E0F> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff222ee000 -     0x7fff22642fff  com.apple.security (7.0 - 59754.100.106) <E9261CB0-E729-3F58-98B7-172F243D4427> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff22643000 -     0x7fff228a2fff  libicucore.A.dylib (66112) <478D57C3-FFF8-35E1-A64F-8490A616AB37> /usr/lib/libicucore.A.dylib
    0x7fff228a3000 -     0x7fff228acfff  libsystem_darwin.dylib (1439.100.3) <28AB0CBC-61F6-3A01-BCE2-A53DA1AECB0F> /usr/lib/system/libsystem_darwin.dylib
    0x7fff228ad000 -     0x7fff22b98fff  com.apple.CoreServices.CarbonCore (1307.2 - 1307.2) <C43BE82A-9E75-39C3-807F-2E87B97B7A78> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff22b99000 -     0x7fff22bd7fff  com.apple.CoreServicesInternal (476.1 - 476.1) <65BD8E8C-2F23-3790-B9CB-C04671BE34EE> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff22bd8000 -     0x7fff22c12fff  com.apple.CSStore (1122.33 - 1122.33) <209D2E9A-FC95-3E51-A0DC-4F32C21B2266> /System/Library/PrivateFrameworks/CoreServicesStore.framework/Versions/A/CoreServicesStore
    0x7fff22c13000 -     0x7fff22cc1fff  com.apple.framework.IOKit (2.0.2 - 1845.100.19) <99034CC2-EC1B-38C0-A8DE-CE37672DF139> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22cc2000 -     0x7fff22ccdfff  libsystem_notify.dylib (279.40.4) <1AA89769-E07F-37CD-BBCF-6DBD345862EB> /usr/lib/system/libsystem_notify.dylib
    0x7fff22cce000 -     0x7fff22d1bfff  libsandbox.1.dylib (1441.101.1) <EC86BFE6-4909-356F-BBEF-DDB1C886D38E> /usr/lib/libsandbox.1.dylib
    0x7fff22d1c000 -     0x7fff23a63fff  com.apple.AppKit (6.9 - 2022.44.151) <10AFBC3A-E9A4-3E62-B9F5-97DF579B7A84> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff23a64000 -     0x7fff23cb2fff  com.apple.UIFoundation (1.0 - 728.6) <C815FD3F-C0F0-31F6-B60D-C544D807384F> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff23cb3000 -     0x7fff23cc5fff  com.apple.UniformTypeIdentifiers (636.9 - 636.9) <5F110054-A401-34EA-B789-F62B6B152DC4> /System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/UniformTypeIdentifiers
    0x7fff23cc6000 -     0x7fff23e50fff  com.apple.desktopservices (1.19 - 1346.4.7) <A3CAC396-18DC-3B13-9505-54BE001014CE> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff24130000 -     0x7fff247affff  libnetwork.dylib (2288.100.111) <8D567D13-AE70-34BF-834D-9A65C702A8EA> /usr/lib/libnetwork.dylib
    0x7fff247b0000 -     0x7fff24c4efff  com.apple.CFNetwork (1237 - 1237) <347078F9-34AC-3AD5-AA02-B7E5E1D11FB6> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff24c4f000 -     0x7fff24c5dfff  libsystem_networkextension.dylib (1295.101.1) <33F45B5A-D346-3E7F-AB34-DFC4387E5A3C> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff24c5e000 -     0x7fff24c5efff  libenergytrace.dylib (22.100.1) <C6283CA4-26A1-352B-B678-C81D0E5E02D6> /usr/lib/libenergytrace.dylib
    0x7fff24c5f000 -     0x7fff24cbbfff  libMobileGestalt.dylib (978.100.37) <1B957D3E-C0F7-36AF-98E4-8897F8633BEA> /usr/lib/libMobileGestalt.dylib
    0x7fff24cbc000 -     0x7fff24cd2fff  libsystem_asl.dylib (385) <4D4E0D4F-8B40-3ACC-85E1-16375966D6CC> /usr/lib/system/libsystem_asl.dylib
    0x7fff24cd3000 -     0x7fff24ceafff  com.apple.TCC (1.0 - 1) <10E022E6-5939-32DF-80E7-11BEA294F987> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff24ceb000 -     0x7fff2504efff  com.apple.SkyLight (1.600.0 - 585) <5DB42D5D-CF51-3433-96E6-B2987E0C33C8> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff2504f000 -     0x7fff256d8fff  com.apple.CoreGraphics (2.0 - 1463.14.2) <E16063AD-03D6-3DC7-A1D4-7103D3721A5A> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff256d9000 -     0x7fff257cffff  com.apple.ColorSync (4.13.0 - 3473.4.3) <69831124-C7EE-3E6E-AC2E-6DCF8A96DB02> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff257d0000 -     0x7fff2582bfff  com.apple.HIServices (1.22 - 715) <7F4A58B2-2A3A-321D-BD82-536D0E37A759> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff25bd2000 -     0x7fff25ff1fff  com.apple.CoreData (120 - 1048) <E44CC602-AE8E-3AC0-A3D4-37E9A5AA949F> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff25ff2000 -     0x7fff26007fff  com.apple.ProtocolBuffer (1 - 285.24.10.20.1) <B83422A6-FA4A-3E24-891F-15851A8D8265> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff26008000 -     0x7fff261bbfff  libsqlite3.dylib (321.3) <39129A81-0E78-3130-85AD-5FA0BFBCC6FA> /usr/lib/libsqlite3.dylib
    0x7fff261bc000 -     0x7fff26238fff  com.apple.Accounts (113 - 113) <928FC136-F5E1-3865-8384-AB5B7A626C7C> /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts
    0x7fff26239000 -     0x7fff26250fff  com.apple.commonutilities (8.0 - 900) <951F55FB-F13F-30E6-AB97-1CEEBE0E78DE> /System/Library/PrivateFrameworks/CommonUtilities.framework/Versions/A/CommonUtilities
    0x7fff26251000 -     0x7fff262d0fff  com.apple.BaseBoard (526 - 526) <E88C7B2A-5372-3E8C-B719-AAC35B0F4E91> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff262d1000 -     0x7fff26319fff  com.apple.RunningBoardServices (1.0 - 505.100.7.0.1) <2E2672F5-C9F1-36E4-B3BA-D3561D7D8BEC> /System/Library/PrivateFrameworks/RunningBoardServices.framework/Versions/A/RunningBoardServices
    0x7fff2631a000 -     0x7fff2638efff  com.apple.AE (918.4 - 918.4) <5377134F-CCA8-3610-8888-8598115A8E8F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff2638f000 -     0x7fff26395fff  libdns_services.dylib (1310.100.10) <CCC9994C-9A07-3740-98AE-908617A67CA5> /usr/lib/libdns_services.dylib
    0x7fff26396000 -     0x7fff2639dfff  libsystem_symptoms.dylib (1431.100.22) <226C631F-5380-395A-AA20-D686AEA05B9B> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff2639e000 -     0x7fff26522fff  com.apple.Network (1.0 - 1) <E70D5387-9843-34AB-B8C4-F468EB7EB1EF> /System/Library/Frameworks/Network.framework/Versions/A/Network
    0x7fff26523000 -     0x7fff26552fff  com.apple.analyticsd (1.0 - 1) <356D0732-7AC4-3579-A96E-640FD4C9AB56> /System/Library/PrivateFrameworks/CoreAnalytics.framework/Versions/A/CoreAnalytics
    0x7fff26553000 -     0x7fff26555fff  libDiagnosticMessagesClient.dylib (112) <04F0E364-262E-3826-B0AF-1076FBAF304A> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff26556000 -     0x7fff265a2fff  com.apple.spotlight.metadata.utilities (1.0 - 2150.16) <AF41D884-70D2-393B-8DB7-C023C4105D0A> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff265a3000 -     0x7fff2663dfff  com.apple.Metadata (10.7.0 - 2150.16) <FCCD84AD-EDFA-310E-B607-FFC464419716> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff2663e000 -     0x7fff26644fff  com.apple.DiskArbitration (2.7 - 2.7) <B6CB4430-35B5-3DD1-BA02-666426F87971> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff26645000 -     0x7fff26cacfff  com.apple.vImage (8.1 - 544.4) <427DE83B-D133-3DCB-A5EA-BC4A644B9283> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff26cad000 -     0x7fff26f89fff  com.apple.QuartzCore (1.11 - 927.17) <23171B27-B274-3E1D-A6D5-AF6A390B2BAE> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff26f8a000 -     0x7fff26fcbfff  libFontRegistry.dylib (309) <89B235B9-DDA9-3E22-8A30-ED98437F0334> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff26fcc000 -     0x7fff2710cfff  com.apple.coreui (2.1 - 691.3) <EA97A98F-C829-3A70-9698-68AFBE6773D9> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff2710d000 -     0x7fff271f8fff  com.apple.ViewBridge (553.1 - 553.1) <2068B3BC-FE88-3129-8828-9A2BBD40BF67> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff271f9000 -     0x7fff27204fff  com.apple.PerformanceAnalysis (1.278.3 - 278.3) <679E8ED4-3577-3F47-801E-8169467E44AC> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff27205000 -     0x7fff27214fff  com.apple.OpenDirectory (11.3 - 230.40.1) <6A59F2E7-1E42-3894-8F40-2D174D5A7938> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff27215000 -     0x7fff27234fff  com.apple.CFOpenDirectory (11.3 - 230.40.1) <1084A655-1A23-309D-8C74-B8B0135ABAC7> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff27235000 -     0x7fff2723dfff  com.apple.CoreServices.FSEvents (1290.101.1 - 1290.101.1) <43164A51-72ED-30E1-8F28-40B3598BCF5C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff2723e000 -     0x7fff27262fff  com.apple.coreservices.SharedFileList (144 - 144) <D8521DF0-1AA2-3157-AE32-7C88AB78C803> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff27263000 -     0x7fff27265fff  libapp_launch_measurement.dylib (14.1) <99F97E05-95A4-3E88-8723-6F92C63F875D> /usr/lib/libapp_launch_measurement.dylib
    0x7fff27266000 -     0x7fff272adfff  com.apple.CoreAutoLayout (1.0 - 21.10.1) <9CBC3DB1-FE97-311D-A19F-1A09B4F2CEFA> /System/Library/PrivateFrameworks/CoreAutoLayout.framework/Versions/A/CoreAutoLayout
    0x7fff272ae000 -     0x7fff27390fff  libxml2.2.dylib (34.9) <B3F9E655-AB90-3375-8262-EC76550929D2> /usr/lib/libxml2.2.dylib
    0x7fff27391000 -     0x7fff273defff  com.apple.CoreVideo (1.8 - 414.7) <2CF6A7EC-9AD1-316B-A59E-E6C2FC56E3A7> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff273df000 -     0x7fff273e1fff  com.apple.loginsupport (1.0 - 1) <E58B3D65-277B-392B-BD98-71FC9A6ED89C> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff2740a000 -     0x7fff27425fff  com.apple.UserManagement (1.0 - 1) <7921CB5B-BC73-300A-9A0F-F9C35F121A4A> /System/Library/PrivateFrameworks/UserManagement.framework/Versions/A/UserManagement
    0x7fff28399000 -     0x7fff283a9fff  libsystem_containermanager.dylib (318.100.4) <3BAF45DD-75D2-3D8A-845E-83A7058CBA08> /usr/lib/system/libsystem_containermanager.dylib
    0x7fff283aa000 -     0x7fff283bbfff  com.apple.IOSurface (290.7 - 290.7) <1A0AD030-00A3-330D-A821-16C0BBA88A82> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff283bc000 -     0x7fff283c5fff  com.apple.IOAccelerator (442.9 - 442.9) <9D9FC91B-2544-3D53-A7AC-DD2E2961DE16> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff283c6000 -     0x7fff284e9fff  com.apple.Metal (244.119 - 244.119) <99A6E326-7BCC-33C5-B0C8-D80C29059592> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff284ea000 -     0x7fff28506fff  com.apple.audio.caulk (1.0 - 70) <8F72B5EE-6E11-3019-8ADC-96D4BFC6BB1F> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7fff28507000 -     0x7fff285f1fff  com.apple.CoreMedia (1.0 - 2770.32.4.7) <DA4F8C7D-060F-36AA-BF83-2EA9FDF5E2D4> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff285f2000 -     0x7fff2874efff  libFontParser.dylib (305.4.0.2) <746AD8C6-F112-336E-B96D-C2EB48072E8E> /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
    0x7fff2874f000 -     0x7fff28a4afff  com.apple.HIToolbox (2.1.1 - 1061.9) <65D66FF8-F361-31FD-9970-1798B9D43DBB> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff28a4b000 -     0x7fff28a5efff  com.apple.framework.DFRFoundation (1.0 - 265) <B37981D4-5230-38EC-8DBF-65E6FFBBEF5D> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff28a5f000 -     0x7fff28a62fff  com.apple.dt.XCTTargetBootstrap (1.0 - 18119.1) <A713CFF0-172C-33D8-834A-129B906DA035> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff28a63000 -     0x7fff28a8cfff  com.apple.CoreSVG (1.0 - 149) <56BD9FF2-197B-3B70-9FDF-86DE68F6F2B1> /System/Library/PrivateFrameworks/CoreSVG.framework/Versions/A/CoreSVG
    0x7fff28a8d000 -     0x7fff28cc8fff  com.apple.ImageIO (3.3.0 - 2130.4.7) <002DE84A-6CDB-30D7-8489-37D3859D3C81> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff28cc9000 -     0x7fff29044fff  com.apple.CoreImage (16.3.0 - 1140.2) <A4D35B12-738E-365E-94F8-5D4751557883> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff29045000 -     0x7fff290abfff  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <55937FF4-F2FA-3671-84DE-88950DD81A88> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff290ac000 -     0x7fff290affff  libsystem_configuration.dylib (1109.101.1) <49050F1E-3143-31B9-8B5C-FCCE4C6F23E5> /usr/lib/system/libsystem_configuration.dylib
    0x7fff290b0000 -     0x7fff290b4fff  libsystem_sandbox.dylib (1441.101.1) <24C8DF94-E258-3E24-AC96-2D1FB85F076A> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff290b5000 -     0x7fff290b6fff  com.apple.AggregateDictionary (1.0 - 1) <652D4FC1-1335-3E5C-86F4-A92D2413AF81> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff290b7000 -     0x7fff290bafff  com.apple.AppleSystemInfo (3.1.5 - 3.1.5) <DB748E0C-9C29-347B-A732-26558E860547> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
    0x7fff290bb000 -     0x7fff290bcfff  liblangid.dylib (136) <F93CA738-D5A4-311E-B130-081B8F1ED6CB> /usr/lib/liblangid.dylib
    0x7fff290bd000 -     0x7fff29161fff  com.apple.CoreNLP (1.0 - 245.2) <FA304330-6361-34DE-B6D6-70BE28E14517> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff29162000 -     0x7fff29168fff  com.apple.LinguisticData (1.0 - 399) <53F0DCFF-114F-3954-9EA2-820C3CB598E1> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff29169000 -     0x7fff29811fff  libBNNS.dylib (288.100.5) <A7B566D9-19BA-357A-BAB5-0DDD4DA85E69> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff29812000 -     0x7fff299e4fff  libvDSP.dylib (760.100.3) <8AC1F990-C583-3354-B5D2-00EF0B696C51> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff299e5000 -     0x7fff299f6fff  com.apple.CoreEmoji (1.0 - 128.4) <1E5E625B-1B19-37E6-BAD2-05301D7BB0FC> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff299f7000 -     0x7fff29a01fff  com.apple.IOMobileFramebuffer (343.0.0 - 343.0.0) <86325AA4-4D75-36AC-800B-3E5574A65F02> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/Versions/A/IOMobileFramebuffer
    0x7fff29a02000 -     0x7fff29ad4fff  com.apple.framework.CoreWLAN (16.0 - 1657) <38CEA388-609B-38A4-82F7-9E61EBE900FF> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff29ad5000 -     0x7fff29cd6fff  com.apple.CoreUtils (6.6 - 660.36) <63015F07-99D3-3396-8675-C7E43E391C0F> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff29cd7000 -     0x7fff29cf9fff  com.apple.MobileKeyBag (2.0 - 1.0) <D70E25E5-40F8-3C41-B1C5-7D6838E032F6> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff29cfa000 -     0x7fff29d0afff  com.apple.AssertionServices (1.0 - 505.100.7.0.1) <5E01DE2E-60AE-342E-9DD2-A4B01B295183> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff29d0b000 -     0x7fff29d96fff  com.apple.securityfoundation (6.0 - 55240.40.4) <0B2C0366-0C1A-3A48-BC0E-02F95EDCC259> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff29d97000 -     0x7fff29da0fff  com.apple.coreservices.BackgroundTaskManagement (1.0 - 104) <59A88CF5-6FD6-3801-AAB9-D0B358ABECD2> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff29da1000 -     0x7fff29da5fff  com.apple.xpc.ServiceManagement (1.0 - 1) <309EC085-9520-3D62-BBCE-6D44117308B7> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff29da6000 -     0x7fff29da8fff  libquarantine.dylib (119.40.2) <FABCD375-2FD7-3FF5-9A28-452D8A323D3E> /usr/lib/system/libquarantine.dylib
    0x7fff29da9000 -     0x7fff29db4fff  libCheckFix.dylib (31) <439FF8FA-1F07-31BC-A578-06CBA45B4E43> /usr/lib/libCheckFix.dylib
    0x7fff29db5000 -     0x7fff29dccfff  libcoretls.dylib (169.100.1) <F477FCDE-2E64-3162-9C4B-670CFBF5A2DF> /usr/lib/libcoretls.dylib
    0x7fff29dcd000 -     0x7fff29dddfff  libbsm.0.dylib (68.40.1) <8817CFED-17DD-3E83-9F48-1028E4D8B97D> /usr/lib/libbsm.0.dylib
    0x7fff29dde000 -     0x7fff29e27fff  libmecab.dylib (929.9) <4558AEA4-814E-3EFE-8976-BA7BECCAB27E> /usr/lib/libmecab.dylib
    0x7fff29e28000 -     0x7fff29e2dfff  libgermantok.dylib (24) <82F85FB5-9D23-3BFD-9CA7-43F0F76752BD> /usr/lib/libgermantok.dylib
    0x7fff29e2e000 -     0x7fff29e43fff  libLinearAlgebra.dylib (1336.101.1) <25376663-3EF4-32D9-A567-A57B719E5E5F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff29e44000 -     0x7fff2a062fff  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <0C639E2D-0C0E-3FF4-8194-782EE0824C3B> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff2a063000 -     0x7fff2a0b2fff  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <3527EC40-E19E-3400-9A6A-1A5457947C94> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff2a0b3000 -     0x7fff2a214fff  com.apple.MLCompute (1.0 - 1) <7A1CD731-D17D-3394-93D8-612C0C47C12D> /System/Library/Frameworks/MLCompute.framework/Versions/A/MLCompute
    0x7fff2a215000 -     0x7fff2a24bfff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <DCE514B8-AC5F-3BB0-AEF3-41C9ECC0D31F> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff2a24c000 -     0x7fff2a2a2fff  com.apple.MetalPerformanceShaders.MPSNDArray (1.0 - 1) <58BD130C-DC37-3CC0-8DD5-4B783EFBE467> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray
    0x7fff2a2a3000 -     0x7fff2a333fff  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <860DA94F-2106-380A-A90A-CA4979A06777> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff2a334000 -     0x7fff2a343fff  com.apple.AppleFSCompression (125 - 1.0) <935B76EE-49A3-3FC6-99BB-994D83B3FA26> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff2a344000 -     0x7fff2a350fff  libbz2.1.0.dylib (44) <111C16DD-70F2-3BFF-A3E1-928C7F64B0C1> /usr/lib/libbz2.1.0.dylib
    0x7fff2a351000 -     0x7fff2a355fff  libsystem_coreservices.dylib (127) <A1451528-AD1D-3E86-93A9-1340535FAF46> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff2a356000 -     0x7fff2a383fff  com.apple.CoreServices.OSServices (1122.33 - 1122.33) <4B4148C5-9CFB-3AA1-89B0-0EB988C0BCD2> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff2a384000 -     0x7fff2a4b3fff  com.apple.AuthKit (1.0 - 1) <822709F3-FAA6-3E0F-81B2-7F0445F894BF> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff2a552000 -     0x7fff2a564fff  libz.1.dylib (76) <45B3DDDD-FCA5-3387-98B8-38D9BFF68588> /usr/lib/libz.1.dylib
    0x7fff2a565000 -     0x7fff2a5acfff  libsystem_m.dylib (3186.100.3) <2F75F75F-DB36-3841-988F-48A7237ED6E9> /usr/lib/system/libsystem_m.dylib
    0x7fff2a5ad000 -     0x7fff2a5adfff  libcharset.1.dylib (59) <5B967C5A-B6AC-322F-B731-4D653B8462B8> /usr/lib/libcharset.1.dylib
    0x7fff2a5ae000 -     0x7fff2a5b3fff  libmacho.dylib (980) <D503EC4A-6B6A-39C4-8218-9F4B6147A5BF> /usr/lib/system/libmacho.dylib
    0x7fff2a5b4000 -     0x7fff2a5cffff  libkxld.dylib (7195.101.2) <ED65FA35-CCE2-3999-902D-6696512B674F> /usr/lib/system/libkxld.dylib
    0x7fff2a5d0000 -     0x7fff2a5dbfff  libcommonCrypto.dylib (60178.100.1) <EA0C1728-C905-3A58-A285-C32ECF903BB4> /usr/lib/system/libcommonCrypto.dylib
    0x7fff2a5dc000 -     0x7fff2a5e6fff  libunwind.dylib (201) <32F74246-BEB8-3249-8C51-CAD863EF158E> /usr/lib/system/libunwind.dylib
    0x7fff2a5e7000 -     0x7fff2a5eefff  liboah.dylib (203.42) <E3126D8C-F1F5-3E30-B7A2-0EB1AB0AF12D> /usr/lib/liboah.dylib
    0x7fff2a5ef000 -     0x7fff2a5f9fff  libcopyfile.dylib (173.40.2) <DDE4BE71-76BA-3CDC-B3B0-F5E0BADF8FF2> /usr/lib/system/libcopyfile.dylib
    0x7fff2a5fa000 -     0x7fff2a601fff  libcompiler_rt.dylib (102.2) <AD12DBB0-8D0B-3D71-800D-E591A3CBE0D8> /usr/lib/system/libcompiler_rt.dylib
    0x7fff2a602000 -     0x7fff2a604fff  libsystem_collections.dylib (1439.100.3) <8B0EA86C-AFA8-3B51-916F-7ED9A42669A4> /usr/lib/system/libsystem_collections.dylib
    0x7fff2a605000 -     0x7fff2a607fff  libsystem_secinit.dylib (87.60.1) <18494A83-796C-33D5-A6D0-BD4E0C2BBFC4> /usr/lib/system/libsystem_secinit.dylib
    0x7fff2a608000 -     0x7fff2a60afff  libremovefile.dylib (49.101.1) <DC4523F8-F5FF-3837-BD58-0AA8763F8FDE> /usr/lib/system/libremovefile.dylib
    0x7fff2a60b000 -     0x7fff2a60bfff  libkeymgr.dylib (31) <1A66B854-350D-3064-A606-2D9BFE71C400> /usr/lib/system/libkeymgr.dylib
    0x7fff2a60c000 -     0x7fff2a613fff  libsystem_dnssd.dylib (1310.100.10) <600B1851-C1D4-3ACF-BE2A-99E7E40E6FC0> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff2a614000 -     0x7fff2a619fff  libcache.dylib (83) <ED7D7EB4-B248-33A9-9E6A-58F45EAB7602> /usr/lib/system/libcache.dylib
    0x7fff2a61a000 -     0x7fff2a61bfff  libSystem.B.dylib (1292.100.5) <EADFB1D1-E113-35B4-BD2D-C1E4C38010D4> /usr/lib/libSystem.B.dylib
    0x7fff2a61c000 -     0x7fff2a61ffff  libfakelink.dylib (3) <3EDDC5DA-6FAD-3031-91C1-E3465C34E643> /usr/lib/libfakelink.dylib
    0x7fff2a620000 -     0x7fff2a620fff  com.apple.SoftLinking (1.0 - 1) <82988A53-B066-3D39-A314-CE3C5C3868DE> /System/Library/PrivateFrameworks/SoftLinking.framework/Versions/A/SoftLinking
    0x7fff2a621000 -     0x7fff2a658fff  libpcap.A.dylib (98.100.3) <4D1E2F3F-484D-3FDC-B764-EB1DB10AFCFB> /usr/lib/libpcap.A.dylib
    0x7fff2a659000 -     0x7fff2a749fff  libiconv.2.dylib (59) <FFC919B8-AA34-3C59-9927-DD1345EF3F32> /usr/lib/libiconv.2.dylib
    0x7fff2a74a000 -     0x7fff2a75bfff  libcmph.dylib (8) <7603021E-45F7-31A8-9449-A356A81712DD> /usr/lib/libcmph.dylib
    0x7fff2a75c000 -     0x7fff2a7cdfff  libarchive.2.dylib (83.100.2) <7896CEB5-AE27-3E35-8C0D-DF3771C3EDF7> /usr/lib/libarchive.2.dylib
    0x7fff2a7ce000 -     0x7fff2a835fff  com.apple.SearchKit (1.4.1 - 1.4.1) <F54991CF-B1D9-338F-97D7-25E0675E24CA> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff2a836000 -     0x7fff2a837fff  libThaiTokenizer.dylib (3) <3B0B24A3-94AA-3876-803D-7E849EF7F5FF> /usr/lib/libThaiTokenizer.dylib
    0x7fff2a838000 -     0x7fff2a85afff  com.apple.applesauce (1.0 - 16.28) <6451578D-F1BF-3476-838D-D45ED05CF78F> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff2a85b000 -     0x7fff2a872fff  libapple_nghttp2.dylib (1.41) <11629AC3-024A-3972-AAD8-A875AEAEBB30> /usr/lib/libapple_nghttp2.dylib
    0x7fff2a873000 -     0x7fff2a889fff  libSparseBLAS.dylib (1336.101.1) <1C78861A-2B74-3172-9EB0-A13275785517> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff2a88a000 -     0x7fff2a88bfff  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <25F9308E-312C-3C30-B7B4-27E98EED7E4A> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff2a88c000 -     0x7fff2a890fff  libpam.2.dylib (28.40.1) <0386A3AB-7134-34FB-A456-3B84D52DFAB1> /usr/lib/libpam.2.dylib
    0x7fff2a891000 -     0x7fff2a8a9fff  libcompression.dylib (96.100.7) <C737D8BA-BD97-3BBF-A2B6-7C63D5144C4B> /usr/lib/libcompression.dylib
    0x7fff2a8aa000 -     0x7fff2a8affff  libQuadrature.dylib (7) <5D8EB379-1B51-3B80-AF16-B3B05F04A182> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff2a8b0000 -     0x7fff2ac4dfff  libLAPACK.dylib (1336.101.1) <1AC818CD-DB01-3F84-91E4-71D14DB47E41> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff2ac4e000 -     0x7fff2ac9dfff  com.apple.DictionaryServices (1.2 - 341) <FFC38615-B3CC-395B-8658-4B159A9A0AC2> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff2ac9e000 -     0x7fff2acb6fff  liblzma.5.dylib (16) <3FC910D3-F9C8-323F-8373-4CF8D3702396> /usr/lib/liblzma.5.dylib
    0x7fff2acb7000 -     0x7fff2acb8fff  libcoretls_cfhelpers.dylib (169.100.1) <6784E023-906B-3FDF-8953-089BEE9E0973> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff2acb9000 -     0x7fff2adb3fff  com.apple.APFS (1677.100.114 - 1677.100.114) <949210B0-BE79-3BB4-A0D2-22C8EDE6E8BA> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff2adb4000 -     0x7fff2adc1fff  libxar.1.dylib (452) <19D3ABA0-D327-37AB-92F7-BB87FC58AB2B> /usr/lib/libxar.1.dylib
    0x7fff2adc2000 -     0x7fff2adc5fff  libutil.dylib (58.40.2) <E3FE02FF-2812-3A42-8AAC-248A20F5414B> /usr/lib/libutil.dylib
    0x7fff2adc6000 -     0x7fff2adeefff  libxslt.1.dylib (17.4) <70C9C559-98AB-3FAB-BFDB-5022E00058D5> /usr/lib/libxslt.1.dylib
    0x7fff2adef000 -     0x7fff2adf9fff  libChineseTokenizer.dylib (37) <C45BF85D-864C-3089-90A6-17ECD67FA469> /usr/lib/libChineseTokenizer.dylib
    0x7fff2adfa000 -     0x7fff2aeb7fff  libvMisc.dylib (760.100.3) <D6E786AE-7BEB-3096-88F1-00F08C69BA4B> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff2aeb8000 -     0x7fff2af4ffff  libate.dylib (3.0.6) <E9B61D7A-CCD5-3610-B5B1-5A3B20502811> /usr/lib/libate.dylib
    0x7fff2af50000 -     0x7fff2af57fff  libIOReport.dylib (64.100.1) <40887C81-C6AF-32EA-8A31-311D7796DBFA> /usr/lib/libIOReport.dylib
    0x7fff2af58000 -     0x7fff2af6bfff  com.apple.CrashReporterSupport (10.13 - 15053) <357061C3-F26E-3F53-89AA-C9049309CC94> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff2b059000 -     0x7fff2b060fff  libMatch.1.dylib (38) <F0B2CCB0-353D-3BD6-A5DD-53F7087ED9FE> /usr/lib/libMatch.1.dylib
    0x7fff2b061000 -     0x7fff2b0ecfff  libCoreStorage.dylib (554) <18EEEA50-E308-35D0-B82B-F81634F1BC80> /usr/lib/libCoreStorage.dylib
    0x7fff2b0ed000 -     0x7fff2b140fff  com.apple.AppleVAFramework (6.1.3 - 6.1.3) <8A2F6F2F-DAF5-3458-BBFB-C359A68870B9> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff2b141000 -     0x7fff2b159fff  libexpat.1.dylib (26) <065A9ADC-2A69-3205-8D58-2E578524883A> /usr/lib/libexpat.1.dylib
    0x7fff2b15a000 -     0x7fff2b163fff  libheimdal-asn1.dylib (597.100.6) <2B948917-490A-30A8-B5DE-D1BB77648D9E> /usr/lib/libheimdal-asn1.dylib
    0x7fff2b164000 -     0x7fff2b178fff  com.apple.IconFoundation (479.4 - 479.4) <61411CF3-1684-3C4E-B726-A317BCCC61A3> /System/Library/PrivateFrameworks/IconFoundation.framework/Versions/A/IconFoundation
    0x7fff2b179000 -     0x7fff2b1e5fff  com.apple.IconServices (479.4 - 479.4) <F70746DB-0DAB-3F36-8613-26270312469C> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff2b1e6000 -     0x7fff2b283fff  com.apple.MediaExperience (1.0 - 1) <1794EDC2-D838-31A5-A85B-16348853D385> /System/Library/PrivateFrameworks/MediaExperience.framework/Versions/A/MediaExperience
    0x7fff2b284000 -     0x7fff2b2acfff  com.apple.persistentconnection (1.0 - 1.0) <205078F8-8420-3F12-A4C8-C9A9B1A670FB> /System/Library/PrivateFrameworks/PersistentConnection.framework/Versions/A/PersistentConnection
    0x7fff2b2ad000 -     0x7fff2b2bbfff  com.apple.GraphVisualizer (1.0 - 100.1) <9D341EA0-A478-3F9F-AC34-80D854DA3B64> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff2b2bc000 -     0x7fff2b6d7fff  com.apple.vision.FaceCore (4.3.2 - 4.3.2) <F7EE5B8C-9809-391A-BDA2-5EADED37B5B5> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff2b6d8000 -     0x7fff2b71ffff  com.apple.OTSVG (1.0 - 677.4.0.4) <565D79AE-4303-346F-960D-AECDA5CA2690> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff2b720000 -     0x7fff2b726fff  com.apple.xpc.AppServerSupport (1.0 - 2038.100.48) <51D2FD7B-4D6B-3BF5-859B-6E551DC9B0AB> /System/Library/PrivateFrameworks/AppServerSupport.framework/Versions/A/AppServerSupport
    0x7fff2b727000 -     0x7fff2b739fff  libhvf.dylib (1.0 - $[CURRENT_PROJECT_VERSION]) <E7B0CA22-7546-3680-A4E6-4A8E98EAE7D2> /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib
    0x7fff2b73a000 -     0x7fff2b73cfff  libspindump.dylib (295.2) <5CAAFF2C-1565-3916-9349-937C3C7F9BBA> /usr/lib/libspindump.dylib
    0x7fff2b73d000 -     0x7fff2b7fdfff  com.apple.Heimdal (4.0 - 2.0) <C4F4A987-6AB0-393C-ADAB-AA74975ADEB7> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff2b7fe000 -     0x7fff2b818fff  com.apple.login (3.0 - 3.0) <B055F669-D189-3CA2-8592-284A154D1C14> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff2b99d000 -     0x7fff2b9d9fff  com.apple.bom (14.0 - 235) <C50B4F1C-013E-3EE6-9B4F-A3E063C9B801> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
    0x7fff2b9da000 -     0x7fff2ba23fff  com.apple.AppleJPEG (1.0 - 1) <6D1195AD-6EB2-3387-B775-9CD6DB981C9B> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff2ba24000 -     0x7fff2bb03fff  libJP2.dylib (2130.4.7) <C8AB059F-C825-3E5D-B98F-7812A953FA9E> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff2bb04000 -     0x7fff2bb07fff  com.apple.WatchdogClient.framework (1.0 - 98.100.3) <7E02DDAB-F57C-3A7F-95FE-F152A6E9D3B9> /System/Library/PrivateFrameworks/WatchdogClient.framework/Versions/A/WatchdogClient
    0x7fff2bb08000 -     0x7fff2bb3efff  com.apple.MultitouchSupport.framework (4440.3 - 4440.3) <37EA4D87-0469-3801-A04C-65BBB468E2F0> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff2bb3f000 -     0x7fff2bc9dfff  com.apple.VideoToolbox (1.0 - 2770.32.4.7) <73AF0B10-EA9F-3718-9729-E80F9E4F5EBF> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff2bc9e000 -     0x7fff2bcd1fff  libAudioToolboxUtility.dylib (1180.90) <10D0F0C5-A6F3-349F-BDE2-A3A13A155F3E> /usr/lib/libAudioToolboxUtility.dylib
    0x7fff2bcd2000 -     0x7fff2bcf8fff  libPng.dylib (2130.4.7) <6AE95141-FEE9-3FB9-B3D0-F0D72EF47840> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff2bcf9000 -     0x7fff2bd58fff  libTIFF.dylib (2130.4.7) <FFB0BE8E-71CF-366C-A8A4-DD117CA5E3C6> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff2bd59000 -     0x7fff2bd75fff  com.apple.IOPresentment (58 - 37) <9450168E-31AB-3451-8D4A-04C1CCE03AB8> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff2bd76000 -     0x7fff2bd7dfff  com.apple.GPUWrangler (6.2.9 - 6.2.9) <25F69C6F-6B3D-3672-9F0D-0F7680BD5CB7> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff2bd7e000 -     0x7fff2bd81fff  libRadiance.dylib (2130.4.7) <BFBB5F8E-3D7A-3F01-B1B5-A8A024B3F6C5> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff2bd82000 -     0x7fff2bd87fff  com.apple.DSExternalDisplay (3.1 - 380) <326D8975-72ED-3114-8153-F290DD68EE94> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff2bd88000 -     0x7fff2bdacfff  libJPEG.dylib (2130.4.7) <8C0412B2-8A87-358D-9FC4-99FB4D38A900> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff2bdad000 -     0x7fff2bddcfff  com.apple.ATSUI (1.0 - 1) <A949815B-B138-3D25-B38A-37EE958A317F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/A/ATSUI
    0x7fff2bddd000 -     0x7fff2bde1fff  libGIF.dylib (2130.4.7) <2FA2F911-EF4C-34C7-9DDA-8C5D6C5CE682> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff2bde2000 -     0x7fff2bdebfff  com.apple.CMCaptureCore (1.0 - 81.37) <4F0C01D1-732D-32B6-9AD9-97BB65B102CE> /System/Library/PrivateFrameworks/CMCaptureCore.framework/Versions/A/CMCaptureCore
    0x7fff2bdec000 -     0x7fff2be33fff  com.apple.print.framework.PrintCore (16.1 - 531.1) <9299D57A-FA79-30B6-ADA6-580A55EFE95C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff2be34000 -     0x7fff2bf01fff  com.apple.TextureIO (3.10.9 - 3.10.9) <CC060BC3-7164-3B07-92BC-885FECB8E004> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff2bf02000 -     0x7fff2bf0afff  com.apple.InternationalSupport (1.0 - 61.1) <5B4614EE-88CF-33D2-89D4-02D1845017C0> /System/Library/PrivateFrameworks/InternationalSupport.framework/Versions/A/InternationalSupport
    0x7fff2bf0b000 -     0x7fff2bf85fff  com.apple.datadetectorscore (8.0 - 674) <B29D5034-5AAD-3037-828B-B237C87835A2> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff2bf86000 -     0x7fff2bfe3fff  com.apple.UserActivity (438 - 438) <3D4BBAA6-516C-31A2-A2D0-1AB91AAD7E85> /System/Library/PrivateFrameworks/UserActivity.framework/Versions/A/UserActivity
    0x7fff2cc47000 -     0x7fff2cc78fff  libSessionUtility.dylib (76.69) <00784F09-BC27-30FE-8F9B-83C052EEA40C> /System/Library/PrivateFrameworks/AudioSession.framework/libSessionUtility.dylib
    0x7fff2cc79000 -     0x7fff2cdadfff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <9E029A41-7E6D-384E-8E13-0C97DCCF34BE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2cdae000 -     0x7fff2ce13fff  com.apple.audio.AudioSession (1.0 - 76.69) <6EC6A5C5-0FAC-39EB-8429-71D9BA1E637F> /System/Library/PrivateFrameworks/AudioSession.framework/Versions/A/AudioSession
    0x7fff2ce14000 -     0x7fff2ce26fff  libAudioStatistics.dylib (27.64) <A1439C1D-8014-3911-825B-40685FDCDEE9> /usr/lib/libAudioStatistics.dylib
    0x7fff2ce27000 -     0x7fff2ce36fff  com.apple.speech.synthesis.framework (9.0.64 - 9.0.64) <19106DFB-75CF-3160-B7E5-D529D18D2F28> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff2ce37000 -     0x7fff2cea3fff  com.apple.ApplicationServices.ATS (377 - 516) <0EC3E4C1-5879-3DB6-8E62-3D734C6C1424> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff2cea4000 -     0x7fff2cebcfff  libresolv.9.dylib (68) <7EA918BC-50B3-3ABB-9021-88CB852FF4D6> /usr/lib/libresolv.9.dylib
    0x7fff2cfef000 -     0x7fff2d0cefff  libSMC.dylib (20) <AE6A0A4D-329B-3830-9A36-CF1A9DE21367> /usr/lib/libSMC.dylib
    0x7fff2d0cf000 -     0x7fff2d12efff  libcups.2.dylib (494.1) <D0767916-ADAF-3D25-BDC4-AB4FF0D48AAD> /usr/lib/libcups.2.dylib
    0x7fff2d12f000 -     0x7fff2d13efff  com.apple.LangAnalysis (1.7.0 - 254) <27988FBF-93AC-375C-B4B3-3179C3BD6715> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff2d13f000 -     0x7fff2d149fff  com.apple.NetAuth (6.2 - 6.2) <05871A6B-81B4-3D86-B9C6-BA444171C4C6> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff2d14a000 -     0x7fff2d151fff  com.apple.ColorSyncLegacy (4.13.0 - 1) <6E55FF8B-35AD-3436-9A1B-98E2E8794911> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff2d152000 -     0x7fff2d15dfff  com.apple.QD (4.0 - 416) <01C30E15-D0D3-3C60-ADCD-6645EE728649> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff2d15e000 -     0x7fff2d7b2fff  com.apple.audio.AudioResourceArbitration (1.0 - 1) <58BB87A3-54AC-31DA-A465-DDAAEA19861A> /System/Library/PrivateFrameworks/AudioResourceArbitration.framework/Versions/A/AudioResourceArbitration
    0x7fff2d7b3000 -     0x7fff2d7befff  com.apple.perfdata (1.0 - 67.40.1) <37CC6E78-27F8-3D0F-8C98-6674500FAF54> /System/Library/PrivateFrameworks/perfdata.framework/Versions/A/perfdata
    0x7fff2d7bf000 -     0x7fff2d7cdfff  libperfcheck.dylib (41) <2DD22E33-80EB-389F-9970-C35C38C21E01> /usr/lib/libperfcheck.dylib
    0x7fff2d7ce000 -     0x7fff2d7ddfff  com.apple.Kerberos (3.0 - 1) <2544BA7A-BBEE-3A87-A270-263F5ECA0034> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff2d7de000 -     0x7fff2d82efff  com.apple.GSS (4.0 - 2.0) <04B974A2-93FC-333A-8FF3-51B0226B1686> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff2d82f000 -     0x7fff2d83ffff  com.apple.CommonAuth (4.0 - 2.0) <EFA67DFF-0B70-361F-88C9-DEEEFE080EA9> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff2d895000 -     0x7fff2d8b4fff  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <C80F47B6-A1FD-33C3-948D-915F3C1BC059> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff2d8b5000 -     0x7fff2d8bdfff  com.apple.CorePhoneNumbers (1.0 - 1) <43716B80-9EF9-336A-B736-19E9425A7BFA> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff2da10000 -     0x7fff2da10fff  liblaunch.dylib (2038.100.48) <3C5E58AF-F753-378B-8E0C-F3C9BB82E04D> /usr/lib/system/liblaunch.dylib
    0x7fff2e1f1000 -     0x7fff2e33cfff  com.apple.Sharing (1618.1 - 1618.1) <AEF64DAC-78C8-30D4-856A-EB3F91961E56> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff2e33d000 -     0x7fff2e45efff  com.apple.Bluetooth (8.0.4 - 8.0.4d18) <4D05FFA8-B735-32F6-AF88-D922157601B3> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff2e478000 -     0x7fff2e4d1fff  com.apple.ProtectedCloudStorage (1.0 - 1) <6ED489AF-BBD1-326F-91BE-4BD8585255A4> /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Versions/A/ProtectedCloudStorage
    0x7fff2fc27000 -     0x7fff2fc4efff  com.apple.RemoteViewServices (2.0 - 163) <265D46D9-B000-3052-AE06-0879C43F88BB> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff2fc4f000 -     0x7fff2fc5efff  com.apple.SpeechRecognitionCore (6.1.23 - 6.1.23) <E427C8FB-4A03-38F4-BEA9-42C60327FB5E> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff2fc5f000 -     0x7fff2fc66fff  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <43B82E77-CB0C-3A20-A9D8-6F6F6C0D5A2E> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff2fe94000 -     0x7fff2fe94fff  libsystem_product_info_filter.dylib (8.40.1) <4CCFBF85-6483-364F-A8D6-A5D2956BEC52> /usr/lib/system/libsystem_product_info_filter.dylib
    0x7fff2ff6c000 -     0x7fff2ff6cfff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <533CA6C2-D07A-35F6-A711-4A55A4319C52> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff2ff92000 -     0x7fff2ff92fff  com.apple.CoreServices (1122.33 - 1122.33) <A1E63C1B-E06B-3DE1-9C96-77E1A412D6DA> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff30149000 -     0x7fff30149fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <D8A3E393-A247-34BC-BE43-E3EA399B491D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff3098b000 -     0x7fff309effff  com.apple.CoreBluetooth (1.0 - 1) <2921520B-0980-33C1-9DB9-8C3723607813> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff309f0000 -     0x7fff309f9fff  com.apple.SymptomDiagnosticReporter (1.0 - 79.100.10) <ACE8AE50-3B88-3BD5-9C4C-F89FB901CEC0> /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/Versions/A/SymptomDiagnosticReporter
    0x7fff30a0d000 -     0x7fff30a19fff  com.apple.AppleIDAuthSupport (1.0 - 1) <5971013E-8435-354D-8EBB-ADD05261DE2C> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff30a1a000 -     0x7fff30ac2fff  com.apple.DiscRecording (9.0.3 - 9030.4.5) <9CE5FB86-C856-3D07-931E-3300B18CE6B3> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fff30ac3000 -     0x7fff30af6fff  com.apple.MediaKit (16 - 927.40.2) <8C737C08-4A97-3347-8B07-8C20AC8529C5> /System/Library/PrivateFrameworks/MediaKit.framework/Versions/A/MediaKit
    0x7fff30af7000 -     0x7fff30be2fff  com.apple.DiskManagement (14.0 - 1733.100.4) <87F5A9DB-3FEC-3054-A530-256C785F1191> /System/Library/PrivateFrameworks/DiskManagement.framework/Versions/A/DiskManagement
    0x7fff30fd0000 -     0x7fff3111efff  com.apple.FileProvider (347.7 - 347.7) <DDDD0816-EFBF-3B02-B35B-0ECEDF4CFBE3> /System/Library/Frameworks/FileProvider.framework/Versions/A/FileProvider
    0x7fff3111f000 -     0x7fff31141fff  com.apple.GenerationalStorage (2.0 - 323) <E1F484FE-24E1-3078-AB57-C6E431FE57CB> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fff31a77000 -     0x7fff31ab2fff  com.apple.DebugSymbols (195.1 - 195.1) <4BAE7472-2131-3398-9BAE-DC78E7FAA973> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff31ab3000 -     0x7fff31b68fff  com.apple.CoreSymbolication (12.5 - 64544.69.1) <CC7DFC41-3C2A-3D11-93B1-0E5109E94C5F> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff32a5d000 -     0x7fff32ac0fff  com.apple.framework.Apple80211 (17.0 - 1728) <54926C8E-EB3B-3760-ADBA-4FA0CFC47C18> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff32ac1000 -     0x7fff32c12fff  com.apple.CoreWiFi (3.0 - 341) <97EEC578-04C8-3632-AE33-071D2048326F> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff32e83000 -     0x7fff32e92fff  com.apple.RemoteServiceDiscovery (1.0 - 1.100.7) <907B1E36-8D22-3278-ADF6-1EB4E0C934C5> /System/Library/PrivateFrameworks/RemoteServiceDiscovery.framework/Versions/A/RemoteServiceDiscovery
    0x7fff32ef0000 -     0x7fff32ef3fff  com.apple.help (1.3.8 - 71) <5DED5EBF-2525-3F7E-87F7-4EC4B0A3185A> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff32ef4000 -     0x7fff32efbfff  com.apple.EFILogin (2.0 - 2) <FB6D52FA-9378-3E69-99F7-055DEAB03DE5> /System/Library/PrivateFrameworks/EFILogin.framework/Versions/A/EFILogin
    0x7fff32efc000 -     0x7fff32f07fff  libcsfde.dylib (554) <C1155B9E-AB39-39DC-B5A4-CF8A88EAE063> /usr/lib/libcsfde.dylib
    0x7fff33145000 -     0x7fff33145fff  com.apple.ApplicationServices (48 - 50) <706E69DF-06C7-3C8E-B0A5-BDD96635CAE4> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3345a000 -     0x7fff3345afff  libHeimdalProxy.dylib (79) <FFDE97B6-A777-33A7-A335-6A42D94CE670> /System/Library/Frameworks/Kerberos.framework/Versions/A/Libraries/libHeimdalProxy.dylib
    0x7fff3350d000 -     0x7fff3350dfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <31CB1996-369E-3ADF-9C6E-1ADD89BD273D> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff33620000 -     0x7fff33e21fff  com.apple.vision.EspressoFramework (1.0 - 256.4.4) <43537944-447C-3DBF-A0A4-9A6C8B7F4776> /System/Library/PrivateFrameworks/Espresso.framework/Versions/A/Espresso
    0x7fff33e22000 -     0x7fff33e39fff  com.apple.ANEServices (4.75 - 4.75) <095A88EA-C73B-36AB-BF73-667EF03DACAE> /System/Library/PrivateFrameworks/ANEServices.framework/Versions/A/ANEServices
    0x7fff344d4000 -     0x7fff34524fff  com.apple.ChunkingLibrary (334.1 - 334.1) <E1E752DB-828E-32B9-B6CE-7EFC31757311> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fff34d98000 -     0x7fff34dadfff  com.apple.CoreML.AppleNeuralEngine (1.0 - 1) <B91D6C1C-19C2-3705-A11F-3A0009D91D3E> /System/Library/PrivateFrameworks/AppleNeuralEngine.framework/Versions/A/AppleNeuralEngine
    0x7fff34f22000 -     0x7fff34f25fff  com.apple.Cocoa (6.11 - 23) <ACA14CB3-6C24-31BE-9C2B-EF3AC3754C1F> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff36376000 -     0x7fff36399fff  com.apple.openscripting (1.7 - 190) <B4718F88-6569-3653-81F9-F0256EE89C48> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff3639a000 -     0x7fff3639dfff  com.apple.securityhi (9.0 - 55008) <66DBED22-5951-3EC2-90CD-0610104B4816> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff3639e000 -     0x7fff363a1fff  com.apple.ink.framework (10.15 - 227) <36446EAF-E2F5-38BD-849A-D489DC7700A8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff363a2000 -     0x7fff363a5fff  com.apple.CommonPanels (1.2.6 - 101) <34455FFB-0A75-366C-BBFB-046D2CAD9EE1> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff363a6000 -     0x7fff363adfff  com.apple.ImageCapture (1711.4.2 - 1711.4.2) <07AB6E67-1DD8-3642-823A-E91AECDBBA3A> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff3c8ee000 -     0x7fff3c8f1fff  com.apple.print.framework.Print (15 - 271) <BED0F662-C9C3-3F4A-8FB3-97BB0ADE2DC8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff3c8f2000 -     0x7fff3c8f5fff  com.apple.Carbon (160 - 164) <6E0D7D9A-2C50-3FBD-A4CF-1D1285F086F1> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3cba8000 -     0x7fff3cbc7fff  com.apple.private.SystemPolicy (1.0 - 1) <05976F26-8C1E-3F7A-8CD6-91F2F3340DD8> /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy
    0x7fff3d4e3000 -     0x7fff3d4eefff  com.apple.MallocStackLogging (1.0 - 1) <07ECDF56-3710-3DEC-8B1D-56C01BD0ED4B> /System/Library/PrivateFrameworks/MallocStackLogging.framework/Versions/A/MallocStackLogging
    0x7fff3d503000 -     0x7fff3d515fff  libmis.dylib (274.100.13) <B863AF9A-44A2-3FBF-BFB1-77AD47302FED> /usr/lib/libmis.dylib
    0x7fff411ad000 -     0x7fff411cbfff  libCGInterfaces.dylib (544.4) <65AABCAF-99FB-327C-B7B7-BDA8940D6EA5> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff462ba000 -     0x7fff462c5fff  libGPUSupportMercury.dylib (18.5.8) <064DABD9-F4F9-33E1-9AB3-092CCBCBB22C> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fff478f1000 -     0x7fff47930fff  com.apple.osanalytics.OSAnalytics (1.0 - 1) <B58A2E5E-83C9-3DB4-98F6-0B0151DB18E4> /System/Library/PrivateFrameworks/OSAnalytics.framework/Versions/A/OSAnalytics
    0x7fff51569000 -     0x7fff51608fff  com.apple.Symbolication (12.5 - 64544.66.1) <3B7F54FE-B5F8-303B-9489-13B178247286> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff5ede0000 -     0x7fff5fdc7fff  com.apple.driver.AppleIntelKBLGraphicsGLDriver (16.2.16 - 16.0.2) <14A94EA6-E240-386D-A4EF-088EEEFC38FE> /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver
    0x7fff6b9c2000 -     0x7fff6b9c8fff  libCoreFSCache.dylib (200.8) <5917BFDD-5553-3258-A468-C86A5BF62FD5> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff6b9c9000 -     0x7fff6b9cdfff  libCoreVMClient.dylib (200.8) <F0654F63-27BA-3700-AC46-E86B29F0111D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff6b9ce000 -     0x7fff6b9ddfff  com.apple.opengl (18.5.8 - 18.5.8) <DFFCB9A8-90D3-3189-B3ED-DBEED6B3695D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6b9de000 -     0x7fff6b9e0fff  libCVMSPluginSupport.dylib (18.5.8) <AC02C127-850C-34A7-978E-46FD7ED26D81> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff6b9e1000 -     0x7fff6b9e9fff  libGFXShared.dylib (18.5.8) <9B136CD9-7268-3B00-8F31-01440986C220> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff6b9ea000 -     0x7fff6ba1dfff  libGLImage.dylib (18.5.8) <9DC644AA-9670-3F66-AC1F-5099ADDFC004> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff6ba1e000 -     0x7fff6ba5afff  libGLU.dylib (18.5.8) <54EEB307-0C17-3890-A969-1633F68291AB> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff6ba5b000 -     0x7fff6bbeefff  libGLProgrammability.dylib (18.5.8) <C21102B6-8549-3E60-BBA0-A4AD6E4A6B2B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fff6bbef000 -     0x7fff6bbf9fff  libGL.dylib (18.5.8) <806D0B08-2CEC-3C98-A9F0-8BD72ACFFB05> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff6bbfa000 -     0x7fff6bd77fff  GLEngine (18.5.8) <D926830E-3CAA-32C1-BD10-B6BFDB4E4E15> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7fff6bd78000 -     0x7fff6bda0fff  GLRendererFloat (18.5.8) <64485F3C-B024-3DA0-8C62-7E03BBE9C846> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
    0x7fff6d039000 -     0x7fff6d091fff  com.apple.opencl (4.5 - 4.5) <4EE9CF1A-E2F1-376B-B387-36DAEBE290E6> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff6e137000 -     0x7fff6e13efff  com.apple.agl (3.3.4 - AGL-3.3.3) <D8CBB8CC-42C0-395A-9EF9-EBB009007838> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff6ea22000 -     0x7fff6ea44fff  com.apple.audio.OpenAL (1.8 - 1.8) <2DC8F853-2AAE-39AB-8492-4791DDC7B507> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff6f3b6000 -     0x7fff6f3c0fff  com.apple.AccessibilityBundles (1.0 - 174) <473A7B60-A56B-344C-9088-5969DFEA71EE> /System/Library/PrivateFrameworks/AccessibilityBundles.framework/Versions/A/AccessibilityBundles
    0x7fff777e3000 -     0x7fff777eafff  libRosetta.dylib (203.42) <E3126D8C-F1F5-3E30-B7A2-0EB1AB0AF12D> /usr/lib/libRosetta.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=733.3M resident=0K(0%) swapped_out_or_unallocated=733.3M(100%)
Writable regions: Total=280.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=280.0M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 3240K        6 
CG image                            72K        5 
CoreAnimation                       84K        9 
CoreGraphics                        12K        2 
CoreUI image data                  940K        8 
Dispatch continuations            32.0M        1 
Foundation                          16K        1 
IOKit                             7940K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           129.6M      154 
MALLOC guard page                   32K        8 
MALLOC_LARGE (reserved)           80.8M       19         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
STACK GUARD                       56.1M       21 
Stack                             16.3M       21 
VM_ALLOCATE                       16.6M      117 
__DATA                            13.8M      309 
__DATA_CONST                      14.6M      181 
__DATA_DIRTY                       557K      103 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       505.9M       12 
__OBJC_RO                         70.1M        1 
__OBJC_RW                         2480K        2 
__TEXT                           227.4M      314 
__UNICODE                          588K        1 
mapped file                       77.5M       19 
shared memory                      756K       15 
===========                     =======  ======= 
TOTAL                              1.2G     1340 
TOTAL, minus reserved VM space     1.2G     1340 

Model: MacBookPro14,2, BootROM 429.100.7.0.0, 2 processors, Dual-Core Intel Core i5, 3,1 GHz, 8 GB, SMC 2.44f6
Graphics: kHW_IntelIrisGraphics650Item, Intel Iris Plus Graphics 650, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x171), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.7)
Bluetooth: Version 8.0.4d18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: tom, VPN (com.wireguard.macos), utun2
USB Device: USB 3.0 Bus
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4
```

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/gamesys/src/gamesys/test/test_gamesys.cpp [hunk 1]
```diff
@@ -2840,6 +2842,60 @@ TEST_F(ScriptBufferTest, RefCount)
...
+    result = dmGameSystem::GetRenderConstant(constants, name_hash1, &constant);
+    ASSERT_TRUE(result);
+    ASSERT_NE((void*)0, constant);
+    ASSERT_EQ(name_hash1, constant->m_NameHash);
+
+    // Issue in 1.2.183: We reallocated the array, thus invalidating the previous pointer
+    dmGameObject::PropertyVar var2(dmVMath::Vector4(5,6,7,8));
+    dmGameSystem::SetRenderConstant(constants, material, name_hash2, 0, var2);
+    // Make sure it's still valid and doesn't trigger an ASAN issue
+    ASSERT_EQ(name_hash1, constant->m_NameHash);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/test/test_gamesys.cpp:2886]: WIthout the fix, this test will fail when using ASAN (which we do on nightly builds)

File: engine/gamesys/src/gamesys/components/comp_private.cpp [hunk 2]
```diff
@@ -350,11 +352,6 @@ void SetRenderConstant(HComponentRenderConstants constants, dmRender::HMaterial
             return;
         }
 
-        if (constants->m_RenderConstants.Full())
-        {
-            constants->m_RenderConstants.OffsetCapacity(1);
-            constants->m_PrevRenderConstants.OffsetCapacity(1);
-        }
         constants->m_RenderConstants.SetSize(count+1);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_private.cpp:355]: A reallocation might make the buffer point to somewhere else, thus leaving any existing pointers into this area, as new dangling pointers.

**Review by britzl — APPROVED** [review]
Looks good
