### PR TITLE
issue-6531: Don't automatically enable all extensions on WebGL

### LINKED ISSUE #6531: Black screen on Samsung TV
**Describe the bug (REQUIRED)**
Yandex.Games has added the "TV" platform recently. So, I decided to test our games on my home TV, SAMSUNG UE50NU7400 with Tizen OS.

As expected, the TV's browser is based on an outdated version of WebKit, and it supports WebGL 1.0 only. And it doesn't support WASM.

Samsung Smart TV PowerVR WebGL Report

Sad to say that Defold games didn't run on it and the TV displayed only black screen immediately after the loading of the Defold game. Other WebGL games/demos ran well.

Okay, I decided to investigate the problem. At first, I added Sentry.io SDK to check errors but there wasn't any errors at all. Step by step, I found that WebGL canvas turns immediately "black" if Defold requests the `OES_EGL_image_external` extension.

**To Reproduce (REQUIRED)**
Run any Defold game on SAMSUNG UE50NU7400.

**Expected behavior (REQUIRED)**
Defold games should run well on that TV as any WebGL games actually do.

**Defold version (REQUIRED):**
  - Version: 1.2.188 ... 1.3.1
  - It's important to mention that some time ago Defold games were able to run on that TV.

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Tizen 4
 - Device: Samsung TV

**Workaround (OPTIONAL):**
Add the following code to the head of `engine_template.html`:
```html
<script>
// Fix for Samsung Tizen Smart-TV
// User-Agent is "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/56.0.2924.0 TV Safari/537.36"
if (navigator.userAgent.indexOf("SMART-TV") > -1) {
    [window.WebGLRenderingContext, window.WebGL2RenderingContext].forEach(function(context) {
        if (!context) return;
        var getSupportedExtensionsOld = context.prototype.getSupportedExtensions;
        context.prototype.getSupportedExtensions = function() {
            var arr = getSupportedExtensionsOld.call(this);
            var index = arr.indexOf("OES_EGL_image_external");
            if (index > -1) {
                arr.splice(index, 1);
            }
            return arr;
        };
    });
}
</script>
```

### PR DESCRIPTION
**Pull request by Jhonnyg**
Fixes #6531

### CODE REVIEW

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 1]
```diff
@@ -911,6 +911,48 @@ static uintptr_t GetExtProcAddress(const char* name, const char* extension_name,
...
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_compressed_texture_etc1");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_compressed_texture_pvrtc");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_compressed_texture_s3tc");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_compressed_texture_s3tc_srgb");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_debug_renderer_info");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_debug_shaders");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_depth_texture");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_draw_buffers");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_lose_context");
+        emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_multi_draw");
```
Comment (Jhonnyg) [inline engine/graphics/src/opengl/graphics_opengl.cpp:953]: These are taken from this list:
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Using_Extensions

Comment (JCash) [reply engine/graphics/src/opengl/graphics_opengl.cpp:953]: Seems like a good code comment :)

Comment (Jhonnyg) [reply engine/graphics/src/opengl/graphics_opengl.cpp:953]: Yeah, that's true :) I'll add it

**Review by JCash — DISMISSED** [review]
