### PR TITLE
Fix the issue where the window becomes invisible after a restart.

### LINKED ISSUE #9128: New build from Editor can't close previous started build
**Describe the bug (REQUIRED)**
In Defold 1.9.0 on MacOS if game build from editor is started, the new build can't close previous started build. In Defold 1.8.1 this works correctly

**To Reproduce (REQUIRED)**
1. Make Empty Project
2. Run Build
3. Switch to the Editor
4. Run Build again

**Expected behavior (REQUIRED)**
New Build will start correctly

**Defold version (REQUIRED):**
Bug on 1.9.0
Ok on 1.8.1

**Platforms (REQUIRED):**
- MacOS

**Minimal repro case project (OPTIONAL):**
Empty Project from templates is ok

**Workaround (OPTIONAL):**
Manually close started build every time

**Screenshots (OPTIONAL):**
https://github.com/defold/defold/assets/3294627/412d7936-89b8-4564-a52a-54fa426cd3e4

### PR DESCRIPTION
**Pull request by AGulev**
Fixed the issue where the window becomes invisible after a restart or when building from the editor multiple times without closing the window.

Fix https://github.com/defold/defold/issues/9128

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/platform/src/platform_window_glfw3.cpp [hunk 1]
```diff
@@ -186,14 +192,10 @@ namespace dmPlatform
...
-        if (params.m_Fullscreen)
-        {
-            fullscreen_monitor = glfwGetPrimaryMonitor();
-        }
-
         // Note: We can't create a 0x0 window
-        wnd->m_AuxWindow = glfwCreateWindow(1, 1, "aux_window", fullscreen_monitor, wnd->m_Window);
+        wnd->m_AuxWindow = glfwCreateWindow(1, 1, "aux_window", NULL, wnd->m_Window);
+
+        glfwShowWindow(wnd->m_Window);
```
Comment (AGulev) [inline engine/platform/src/platform_window_glfw3.cpp:198]: The actual fix: show window after creation

File: engine/platform/src/platform_window_glfw3.cpp [hunk 2]
```diff
@@ -203,13 +205,21 @@ namespace dmPlatform
...
         glfwWindowHint(GLFW_SAMPLES, params.m_Samples);
 
-        wnd->m_Window = glfwCreateWindow(params.m_Width, params.m_Height, params.m_Title, NULL, NULL);
+        GLFWmonitor* fullscreen_monitor = NULL;
+        if (params.m_Fullscreen)
+        {
+            fullscreen_monitor = glfwGetPrimaryMonitor();
+        }
+
+        wnd->m_Window = glfwCreateWindow(params.m_Width, params.m_Height, params.m_Title, fullscreen_monitor, NULL);
```
Comment (AGulev) [inline engine/platform/src/platform_window_glfw3.cpp:214]: Add fullscreen for vulkan

File: engine/platform/src/platform_window_glfw3.cpp [hunk 3]
```diff
@@ -221,6 +227,10 @@ namespace dmPlatform
         }
 
         glfwWindowHint(GLFW_FOCUSED, GLFW_TRUE);
+        // This hint saves both size and position, but we need only position
+        // That's why we hide window here and then later set default size and show window
+        glfwWindowHintString(GLFW_COCOA_FRAME_NAME, params.m_Title);
+        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
```
Comment (AGulev) [inline engine/platform/src/platform_window_glfw3.cpp:233]: This hint turn saves for the window frame (position and size). But we need only position save. 
So we don't auto-show window on creation using `GLFW_VISIBLE` and then show later after we change size back

File: engine/platform/src/platform_window_glfw3.cpp [hunk 4]
```diff
@@ -237,6 +247,10 @@ namespace dmPlatform
 
         if (res == PLATFORM_RESULT_OK)
         {
+            // Set size from settings, and show window
+            glfwSetWindowSize(window->m_Window, params.m_Width, params.m_Height);
+            glfwShowWindow(window->m_Window);
```
Comment (AGulev) [inline engine/platform/src/platform_window_glfw3.cpp:252]: When we apply window size, we show window. 
also calling of `glfwShowWindow` is the fix for the initial issue with invisible window after restart.

File: engine/platform/src/platform_window_glfw3.cpp (hunk 3 above)
Comment (AGulev) [reply engine/platform/src/platform_window_glfw3.cpp:233]: This whole workaround is needed to prevent behavior when each restart moves window a little bit bottom and right:

https://github.com/defold/defold/assets/2209596/317466ca-f340-40e9-84c2-b959a1bb820a

As a side effect we get window position save function on mac. This feature were requested a few times.

**Review by britzl — APPROVED** [review]
