### PR TITLE
Remove old `rig.max_instance_count` counter.

### LINKED ISSUE #7130: model.max_count can't be lower 128
### Expected behaviour
Do not create model components when game not use models.
### Actual behaviour
Model component have minimum value 128.
https://github.com/defold/defold/blob/cc592848a95ccbef8c098e9ed0ec50ad0d70a43c/engine/engine/src/engine.cpp#L1015
```
        // rig.max_instance_count is deprecated in favour of component specific max count values.
        // For backwards combatibility we get the rig generic value and take the max of it and each
        // specific component max value.
        int32_t max_rig_instance = dmConfigFile::GetInt(engine->m_Config, "rig.max_instance_count", 128);
        int32_t max_model_count = dmMath::Max(dmConfigFile::GetInt(engine->m_Config, "model.max_count", 128), max_rig_instance);
```
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-11-02T11:44:12.649507</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>1dbf756283bc3aaa74552b8959569f051023b842</td></tr>
<tr><td>Defold engine sha</td><td>1dbf756283bc3aaa74552b8959569f051023b842</td></tr>
<tr><td>Defold version</td><td>1.4.0</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14756 Compatibility Profile Context 20.40.64 27.20.14064.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Remove old deprecated max counter `rig.max_instance_count` which was the reason of minimum 128 `max_count` for model component.

Fix https://github.com/defold/defold/issues/7130

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -1009,10 +1009,10 @@ namespace dmEngine
         }
 
         // rig.max_instance_count is deprecated in favour of component specific max count values.
-        // For backwards combatibility we get the rig generic value and take the max of it and each
-        // specific component max value.
-        int32_t max_rig_instance = dmConfigFile::GetInt(engine->m_Config, "rig.max_instance_count", 128);
-        int32_t max_model_count = dmMath::Max(dmConfigFile::GetInt(engine->m_Config, "model.max_count", 128), max_rig_instance);
+        if (dmConfigFile::GetInt(engine->m_Config, "rig.max_instance_count", -1) != -1)
+        {
+            dmLogWarning("`rig.max_instance_count` deprecated. Use component specific counters.");
```
Comment (britzl) [inline engine/engine/src/engine.cpp:1014]: Could we name the specific counters that can be used?

**Review by britzl — APPROVED** [review]

File: engine/engine/src/engine.cpp (hunk 1 above)
Comment (AGulev) [reply engine/engine/src/engine.cpp:1014]: for now it's model.max_counter
But it depends on when we decde to use rig in the future, so I'm not sure if we wanna hardcode it here
