### PR TITLE
Issue-6883 Fix rare crash in profiler

### LINKED ISSUE #6883: Profiler random crash #3
**Describe the bug (REQUIRED)**
We have another crash while testing our game.

```
Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   libFamilyIsland.so              0x70b9b08b50        [inlined] dmScript::ConcatString (script.cpp:1823)
1   libFamilyIsland.so              0x70b9b08b50        dmScript::GetProfilerString (script.cpp:1883)
2   libFamilyIsland.so              0x70b9a8c038        dmGameObject::RunScript (comp_script.cpp:132)
3   libFamilyIsland.so              0x70b9a8c354        dmGameObject::CompScriptUpdateInternal (comp_script.cpp:232)
4   libFamilyIsland.so              0x70b9a7cd00        [inlined] dmGameObject::Update (gameobject.cpp:2511)
5   libFamilyIsland.so              0x70b9a7cd00        dmGameObject::Update (gameobject.cpp:2602)
6   libFamilyIsland.so              0x70b9a9fef0        dmGameSystem::CompCollectionProxyUpdate (comp_collection_proxy.cpp:285)
7   libFamilyIsland.so              0x70b9a7cd00        [inlined] dmGameObject::Update (gameobject.cpp:2511)
8   libFamilyIsland.so              0x70b9a7cd00        dmGameObject::Update (gameobject.cpp:2602)
9   libFamilyIsland.so              0x70b9a62ab4        [inlined] dmEngine::StepFrame (engine.cpp:1563)
10  libFamilyIsland.so              0x70b9a62ab4        dmEngine::Step (engine.cpp:1741)
11  libFamilyIsland.so              0x70b9a63068        dmEngineUpdate (engine.cpp:2094)
12  libFamilyIsland.so              0x70b9a5f9ac        dmEngine::RunLoop (engine_loop.cpp:83)
13  libFamilyIsland.so              0x70b9a5f930        [inlined] EngineMain (engine_main.cpp:49)
14  libFamilyIsland.so              0x70b9a5f930        EngineMainThread (engine_main.cpp:70)
15  libFamilyIsland.so              0x70b9b8f9b0        dmThread::ThreadStartProxy (thread.cpp:48)
16  libc.so                         0x74458ca084        __pthread_start
17  libc.so                         0x744586a404        __start_thread
```

**To Reproduce (REQUIRED)**
I try to receive additional information about this crash. But i think we don't have any specific steps to reproduce. 

**Defold version (REQUIRED):**
  - Version 1.3.4 (https://github.com/defold/defold/commit/bd56d557d6dca58aa77b12b267ff349306551ff5)

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Android 11
 - Device: KB2003

### PR DESCRIPTION
**Pull request by AGulev**
Make sure that profiler doesn't crash if Lua doesn't provide information about function source.

Fix https://github.com/defold/defold/issues/6883

### CODE REVIEW

File: engine/script/src/script.cpp [hunk 1]
```diff
@@ -1820,7 +1820,7 @@ namespace dmScript
     // to calculate the length of the input string or output string
     static char* ConcatString(char* w_ptr, const char* w_ptr_end, const char* str)
     {
-        while ((w_ptr != w_ptr_end) && *str)
+        while ((w_ptr != w_ptr_end) && str && *str)
```
Comment (AGulev) [inline engine/script/src/script.cpp:1823]: As I see the only thing may be cause of the crash in this line is deref of the str  if it’s `NULL`
->
Exception Type: Unknown (SIGSEGV))

So this while should help

File: engine/script/src/script.cpp [hunk 2]
```diff
@@ -1850,7 +1850,10 @@ namespace dmScript
             LuaFunctionInfo fi;
             if (dmScript::GetLuaFunctionRefInfo(L, optional_callback_index, &fi))
             {
-                function_source = fi.m_FileName;
+                if (fi.m_FileName)
+                {
+                    function_source = fi.m_FileName;
+                }
```
Comment (AGulev) [inline engine/script/src/script.cpp:1856]: I added one more checking to use `source` from lua_getinfo only if it exists.
There are a few possible values in `source`  one of them is a special `=(tail call)` value which (as I assume) may be  opt out in LuaJit.

File: engine/script/src/script.cpp (hunk 1 above)
Comment (JCash) [reply engine/script/src/script.cpp:1823]: But, this is still just guesswork?

File: engine/script/src/script.cpp (hunk 2 above)
Comment (JCash) [reply engine/script/src/script.cpp:1856]: Is it possible for the filename to be null?

**Review by JCash — APPROVED** [review]

File: engine/script/src/script.cpp (hunk 1 above)
Comment (AGulev) [reply engine/script/src/script.cpp:1823]: sure, we don't have a repo case, but we know the crash happens in this particular line

File: engine/script/src/script.cpp (hunk 2 above)
Comment (AGulev) [reply engine/script/src/script.cpp:1856]: `m_FileName` is `source` from `lua_Debug` struct which we get using `lua_getinfo`.

according to doc:
```
source: If the function was defined in a string, then source is that string. If the function was defined in a file, then source starts with a '@' followed by the file name.
```

But reading Lua code I found there is a special branch of logic for tail function:
```
static void info_tailcall (lua_Debug *ar) {
  ar->name = ar->namewhat = "";
  ar->what = "tail";
  ar->lastlinedefined = ar->linedefined = ar->currentline = -1;
  ar->source = "=(tail call)";
  luaO_chunkid(ar->short_src, ar->source, LUA_IDSIZE);
  ar->nups = 0;
}

...
  if (f == NULL) {
    info_tailcall(ar);
    return status;
  }
...
```

Also we know (from attempt to write a Lua profiler) that LuaJit optimise tail calls, so that's why I assume `m_FileName` may be NULL
