### PR TITLE
Rebuilt spirv tools for macos 10.15

### LINKED ISSUE #9350: Build fails due to material errors on OSX 11.x. Version 1.9.2
**Description**
Running an empty project with a simple sprite crashes with the following error:
```
/builtins/materials/sprite.fp
	_generated_b7e08114.fpc:
/builtins/materials/sprite.vp
	_generated_7e90358b.vpc:
```

**To Reproduce**
1. Start a new empty project with Defold 1.9.2 on OSX 11.7.10
2. Create a new Atlas using defolds logo assets and add a default animation.
3. Add a `go` to `main.collection`
4. Add a `sprite` to the game object, and assign the previously created atlas. 
5. The sprite won't appear visible on the editor. If the game is built it will fail with an error that has an empty message.

**Expected behavior**
Sprite should be visible and the build should run with a simple sprite on screen.

**Defold version (REQUIRED):**
  - Version 1.9.2

**Platforms:**
 - Platforms: macOS
 - OS: OSX 11.7.10

**Workaround:**
Tested the same project on Defold 1.9.0 and it ran perfectly!

**Screenshots:**
Opening the first demo and attempting to run it results in all the materials failing:
Screen Shot 2024-08-27 at 17 39 29

### PR DESCRIPTION
**Pull request by JCash**
This fixes an issue on macOS 10 or 11, where shaders weren't built properly.

Fixes https://github.com/defold/defold/issues/9350

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: share/ext/glslang/.gitignore [hunk 1]
```diff
@@ -0,0 +1,2 @@
+build
+source
```
Comment (JCash) [inline share/ext/glslang/.gitignore:2]: To avoid being spammy in the ide's

File: share/ext/glslang/build_glslang.sh [hunk 2]
```diff
@@ -27,9 +27,8 @@ if [ -z "$PLATFORM" ]; then
     exit 1
 fi
 
-eval $(python ..PATH_TO../build_tools/set_sdk_vars.py VERSION_MACOSX_MIN)
-OSX_MIN_SDK_VERSION = $VERSION_MACOSX_MIN
-
+eval $(python ${DYNAMO_HOME}/../../build_tools/set_sdk_vars.py VERSION_MACOSX_MIN)
```
Comment (JCash) [inline share/ext/glslang/build_glslang.sh:30]: Using DYNAMO_HOME to find the script

File: share/ext/spirv-cross/build_spirv-cross.sh [hunk 3]
```diff
@@ -23,20 +23,25 @@ if [ -z "$PLATFORM" ]; then
     exit 1
 fi
 
+# eval $(python ${DYNAMO_HOME}/../../build_tools/set_sdk_vars.py VERSION_MACOSX_MIN)
+# OSX_MIN_SDK_VERSION=$VERSION_MACOSX_MIN
+# Until we've updated our main version, we need to use at least 10.15 due to features used in the tools
+OSX_MIN_SDK_VERSION=10.15
```
Comment (JCash) [inline share/ext/spirv-cross/build_spirv-cross.sh:29]: I guess we can't have everything 🤷

**Review by Jhonnyg — DISMISSED** [review]
