### PR TITLE
Editor: Fix crash when switching to Manual Size Mode without a texture assigned

### LINKED ISSUE #9179: Editor crash when setting Sprite component Size Mode to Manual for materials with no samplers.
**The bug**
If a material with no samplers defined is assigned to a new Sprite component, setting the Size Mode to Manual will likely crash the editor.

Please note that this will likely only work for new sprite components that never really had any "size" property set.

**Steps to reproduce**
1. Create a material with no samplers
2. Create a GO and give it a Sprite component
3. Assign the no-samplers material to the sprite component
4. Change the Size Mode in the Sprite component from Auto to Manual
5. Observe the crash

**Defold version:**
  1.9.0

**Platforms**
macOS

**Workaround**
After creating a new sprite, with a bog-standard sprite assigned to it automatically, change the Size Mode to Manual. Then assign the new, sampler-less material to it and see that there is no crash anymore. 🙌 

**Crash log**
[crash_report.txt](https://github.com/user-attachments/files/16116667/crash_report.txt)

**Repro project**
[material-error.zip](https://github.com/user-attachments/files/16116652/material-error.zip)

### PR DESCRIPTION
**Pull request by matgis**
Fixed an editor crash resulting from invalid vertex buffers when using Manual Size Mode with zero-area geometry.

Fixes #9179.

### CODE REVIEW

File: editor/src/clj/editor/slice9.clj [hunk 1]
```diff
@@ -108,8 +109,8 @@
 
 (defn vertex-data
   [{:keys [width height tex-coords] :as _frame} size slice9 pivot]
-  (let [^double texture-width (or width (first size) 1.0)
-        ^double texture-height (or height (second size) 1.0)
+  (let [texture-width (max 1.0 (double (or width (first size) 0.0)))
+        texture-height (max 1.0 (double (or height (second size) 0.0)))
```
Comment (matgis) [inline editor/src/clj/editor/slice9.clj:113]: First issue: If the manually specified `size` was zero when untextured, we'd produce infinity values resulting from divide-by-zero.

File: editor/src/clj/editor/slice9.clj [hunk 2]
```diff
@@ -220,10 +221,20 @@
...
+              (filterv
+                (fn [[[x0 y0 x1 y1] _uv-box]]
+                  (and (not= x0 x1) (not= y0 y1)))
+                empty-xy-box-coords+uv-boxes))
+            ;; We need *some* geometry, or it will eventually result in invalid
+            ;; buffers that will likely crash the GL driver. When all 9 boxes
+            ;; are empty, use the center slice. This can happen with a manual
+            ;; size of zero.
+            [(empty-xy-box-coords+uv-boxes 4)])
+
```
Comment (matgis) [inline editor/src/clj/editor/slice9.clj:237]: Second issue: If the manual `size` was zero, we'd generate no geometry. Our callees expect some geometry for populating the vertex and buffers.

File: editor/src/clj/editor/sprite.clj [hunk 3]
```diff
@@ -99,7 +99,7 @@
                         vertex-data (if (= :size-mode-auto size-mode)
                                       (texture-set/vertex-data animation-frame)
                                       (slice9/vertex-data animation-frame size slice9 :pivot-center))]
-                    (assoc vertex-data :page-index (:page-index animation-frame))))
+                    (assoc vertex-data :page-index (:page-index animation-frame 0))))
```
Comment (matgis) [inline editor/src/clj/editor/sprite.clj:102]: Unrelated fix: Avoid putting in a `nil` `:page-index` when there is no `animation-frame`.

File: editor/src/clj/editor/sprite.clj [hunk 4]
```diff
@@ -212,9 +212,7 @@
         pass (:pass render-args)
 
         renderable-datas (mapv renderable-data renderables)
-        num-vertices (count-vertices renderable-datas)
-
-        num-outline-vertices (* 6 (count-quads renderables))]
```
Comment (matgis) [inline editor/src/clj/editor/sprite.clj:217]: Unrelated cleanup: `num-outline-vertices` was unused.

**Review by vlaaad — APPROVED** [review]
LGTM!
