### PR TITLE
Fix small memory leak in `json.decode()`

### LINKED ISSUE #7685: Small memory leak in json_initialize_config
it is leaking 1 Kb for each call
image

### PR DESCRIPTION
**Pull request by AGulev**
Each `json.decode()` call allocates 1kb of memory, which should be freed after.

Fix https://github.com/defold/defold/issues/7685

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/script/src/luacjson/lua_cjson.c [hunk 1]
```diff
@@ -459,7 +459,7 @@ static void json_create_config(lua_State *l)
 #endif // DEFOLD
 
 // DEFOLD
-static void json_initialize_config(json_config_t* cfg)
+static void json_initialize_config(json_config_t* cfg, int encode_keep_buffer)
```
Comment (AGulev) [inline engine/script/src/luacjson/lua_cjson.c:462]: Here I add an ability to avoid `cfg->encode_buf` initialization in case we don't need it (when decode)

File: engine/script/src/luacjson/lua_cjson.c [hunk 2]
```diff
@@ -470,15 +470,16 @@ static void json_initialize_config(json_config_t* cfg)
...
     cfg->decode_array_with_array_mt = DEFAULT_DECODE_ARRAY_WITH_ARRAY_MT;
     cfg->encode_escape_forward_slash = DEFAULT_ENCODE_ESCAPE_FORWARD_SLASH;
 
-#if DEFAULT_ENCODE_KEEP_BUFFER > 0
-    strbuf_init(&cfg->encode_buf, 0);
-#endif
+    if (encode_keep_buffer > 0)
+    {
+        strbuf_init(&cfg->encode_buf, 0);
+    }
```
Comment (AGulev) [inline engine/script/src/luacjson/lua_cjson.c:482]: For decode this buffer unused, so we don't need to allocate it

File: engine/script/src/luacjson/lua_cjson.c [hunk 3]
```diff
@@ -532,8 +533,9 @@ static void json_initialize_config(json_config_t* cfg)
 static void json_encode_exception(lua_State *l, json_config_t *cfg, strbuf_t *json, int lindex,
                                   const char *reason)
 {
-    if (!cfg->encode_keep_buffer)
+    if (cfg->encode_keep_buffer)
         strbuf_free(json);
```
Comment (AGulev) [inline engine/script/src/luacjson/lua_cjson.c:537]: We trow an error here using `luaL_error` which will long_jmp and release the stack
We expect memory will be freed if error thrown:
https://github.com/defold/defold/blob/9123aa9aa1aa26953d396ddc8256b8d518fe805e/engine/script/src/script_json.cpp#L154-L160

File: engine/script/src/luacjson/lua_cjson.c [hunk 4]
```diff
@@ -684,7 +686,7 @@ static void json_check_encode_depth(lua_State *l, json_config_t *cfg,
     if (current_depth <= cfg->encode_max_depth && lua_checkstack(l, 3))
         return;
 
-    if (!cfg->encode_keep_buffer)
+    if (cfg->encode_keep_buffer)
         strbuf_free(json);
```
Comment (AGulev) [inline engine/script/src/luacjson/lua_cjson.c:690]: then same as prev comment. If we call lua_error - we should free buffer ourself

File: engine/script/src/luacjson/lua_cjson.c [hunk 5]
```diff
@@ -936,7 +938,7 @@ int lua_cjson_encode(lua_State *l, char** json_str, size_t* json_length)
 
     luaL_argcheck(l, lua_gettop(l) == 1, 1, "expected 1 argument");
 
-    json_initialize_config(&cfg);
+    json_initialize_config(&cfg, DEFAULT_ENCODE_KEEP_BUFFER);
```
Comment (AGulev) [inline engine/script/src/luacjson/lua_cjson.c:941]: We need this buffer for encoding

File: engine/script/src/luacjson/lua_cjson.c [hunk 6]
```diff
@@ -1558,7 +1560,7 @@ int lua_cjson_decode(lua_State *l, const char* json_string, size_t json_len)
     json_parse_t json;
     json_token_t token;
 
-    json_initialize_config(&cfg);
+    json_initialize_config(&cfg, 0);
```
Comment (AGulev) [inline engine/script/src/luacjson/lua_cjson.c:1563]: we don't need this buffer for decoding, so it's easier do not allocate it at all

File: engine/script/src/luacjson/lua_cjson.c [hunk 7]
```diff
@@ -684,8 +686,8 @@ static void json_check_encode_depth(lua_State *l, json_config_t *cfg,
     if (current_depth <= cfg->encode_max_depth && lua_checkstack(l, 3))
         return;
 
-    if (!cfg->encode_keep_buffer)
-        strbuf_free(json);
```
Comment (AGulev) [inline engine/script/src/luacjson/lua_cjson.c:688]: We should free buffers if error happened - because that's how API designed:
https://github.com/defold/defold/blob/9123aa9aa1aa26953d396ddc8256b8d518fe805e/engine/script/src/script_json.cpp#L154-L160

**Review by britzl — APPROVED** [review]
Looks good
