### PR TITLE
Issue-6354 Use Application Support folder for game logs if `./log.txt` is unavailable

### LINKED ISSUE #6354: Logging to log.txt is not implemented in the build on macOS.
**Describe the bug (REQUIRED)**
Logging to log.txt is not implemented in the build on the mac.

**To Reproduce (REQUIRED)**
1) Check 'Write logs' in project settings
2) Bundle on macOS
3) Run the app

**Expected behavior (REQUIRED)**
Logging in ~Library/Application Support/game_name/log.txt

**Defold version (REQUIRED):**
  - Version 1.2.191

**Platforms (REQUIRED):**
- macOS

### PR DESCRIPTION
**Pull request by AGulev**
Fixes path to the `log.txt` file for macOS bundle where the creation of the file in `app` is impossible.

If `project.wrile_log` checkbox is ON in `game.project`, engine writes logs in `log.txt` file.
The path to the file depends on the platform (see [manual](https://defold.com/manuals/debugging-game-and-system-logs/?q=log.txt#reading-the-game-log-from-the-log-file)).

From now on macOS the file path will be `/Users/user_name/Library/Application Support/projectname/log.txt`

Fixes https://github.com/defold/defold/issues/6354

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -692,15 +692,39 @@ namespace dmEngine
...
-            if (dmSys::GetLogPath(sys_path, sizeof(sys_path)) == dmSys::RESULT_OK) {
-                const char* path = dmConfigFile::GetString(engine->m_Config, "project.log_dir", sys_path);
-                char full[DMPATH_MAX_PATH];
-                dmPath::Concat(path, "log.txt", full, sizeof(full));
-                dmLog::SetLogFile(full);
-            } else {
+            char main_log_path[DMPATH_MAX_PATH];
+            if (dmSys::GetLogPath(sys_path, sizeof(sys_path)) == dmSys::RESULT_OK)
+            {
+                const char* main_dir = dmConfigFile::GetString(engine->m_Config, "project.log_dir", sys_path);
```
Comment (britzl) [inline engine/engine/src/engine.cpp:701]: Doesn't this mean that we won't try to write the log to `project.log_dir` if the call to `dmSys::GetLogPath()` fails?

Should we not try three paths?

1. project.log_dir
2. dmSys::GetLogPath()
3. dmSys::GetApplicationSavePath()

File: engine/engine/src/engine.cpp [hunk 2]
```diff
@@ -692,15 +692,39 @@ namespace dmEngine
...
+            }
+            else
+            {
                 dmLogFatal("Unable to get log-file path");
             }
+
+
+            char application_support_path[DMPATH_MAX_PATH];
+            char application_support_log_path[DMPATH_MAX_PATH];
+            const char* logs_dir = dmConfigFile::GetString(engine->m_Config, "project.title_as_file_name", "DefoldLogs");
```
Comment (britzl) [inline engine/engine/src/engine.cpp:714]: I'm not a big fan of mixed case folder names. I prefer "defoldlogs".

**Review by britzl — CHANGES_REQUESTED** [review]

File: engine/engine/src/engine.cpp (hunk 1 above)
Comment (AGulev) [reply engine/engine/src/engine.cpp]: I agree, Thank you!

**Review by britzl — APPROVED** [review]
I was about to comment on the use of "file_name" instead of "filename" but I realise that we're not consistent in our code at all, so I guess it's all good!
