### PR TITLE
Fix unresponsive editor gui viewport interactions

### LINKED ISSUE #10242: GUI position transform in editor is delayed as of 1.9.7
### Expected behaviour
Easiest to visualise with a video, so this is a clip from 1.9.6 when the transform is near realtime:

https://github.com/user-attachments/assets/09ea4d83-ae49-4e87-aa77-b1aa0526e060

### Actual behaviour

1.9.7 (and 1.9.8 where I captured this video), the transform takes a significant time to register, making it very hard to use well:

https://github.com/user-attachments/assets/8eaa0905-5fab-447e-90ed-4cd34dce9322

### Steps to reproduce

Select GUI node, press w, then drag.

<hr/>

<table>
<tr><td>Build time</td><td>2025-02-19T09:52:28.129046</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>36a63db66b67da8a85ac4478a7b3acd2472b855e</td></tr>
<tr><td>Defold engine sha</td><td>36a63db66b67da8a85ac4478a7b3acd2472b855e</td></tr>
<tr><td>Defold version</td><td>1.9.8</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 560.94</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Fixed a performance regression introduced by #10024 that caused viewport interactions such as moving or rotating objects inside Gui scenes to slow down drastically.

Fixes #10242

### Technical changes
* The `:layout-names` have been moved from `basic-gui-scene-info` to a new `trivial-gui-scene-info` output on the `GuiSceneNode` that propagates to `GuiNodes` along a parallel path to `basic-gui-scene-info` and `costly-gui-scene-info`.
* The previous `current-layout` and `id-prefix` outputs of `GuiSceneNode` that used to propagate to `GuiNodes` along similar paths is now bundled with the `trivial-gui-scene-info`, so the net number of connections has actually decreased somewhat.
* A `print-stack-trace!` function has been added to the `debug-util` module.

### CODE REVIEW

File: editor/src/clj/editor/gui.clj [hunk 1]
```diff
@@ -1144,78 +1150,81 @@
...
-                                         (get layout->prop->override-for-original current-layout)
-                                         prop->value))))))))
-
-                    ;; We've reached the override root. Anything not overridden
-                    ;; for the current-layout by this point will use values from
-                    ;; our default layout.
-                    (let [node (g/node-by-id basis node-id)]
-                      (coll/merge
-                        (make-prop->value-for-default-layout node)
-                        prop->value))))))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1185]: Indentation change from adding the surrounding `let` for the `current-layout`.

File: editor/src/clj/editor/gui.clj [hunk 2]
```diff
@@ -1144,78 +1150,81 @@
...
-                                    (let [layout-override-value (get prop-kw->layout-override-value prop-kw)]
-                                      (pair prop-kw
-                                            (cond-> (assoc prop-info :assoc-original-value? false) ; Disable automatic assoc in OverrideNode.produce-value. We want to manage it ourselves.
-
-                                                    (some? layout-override-value)
-                                                    (assoc :original-value layout-override-value) ; Any :original-value is fine. The key just needs to be present.
-
-                                                    (nil? layout-override-value)
-                                                    (dissoc :original-value))))))
-                                prop-kw->prop-info)))))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1218]: Indentation change from adding the surrounding `let` for the `current-layout`.

File: editor/src/clj/editor/gui.clj [hunk 3]
```diff
@@ -1033,23 +1040,24 @@
...
-                     :copy-include-fn (fn [node]
-                                        (let [node-id (g/node-id node)]
-                                          (and (g/node-instance? GuiNode node-id)
-                                               (not= node-id (g/node-value node-id :parent)))))
-                     :children node-outline-children
-                     :outline-error? (g/error-fatal? own-build-errors)
-                     :outline-overridden? (if (str/blank? current-layout)
-                                            (< 1 (count _overridden-properties)) ; :layout->prop->override will always be present, and we shouldn't count it.
-                                            (pos? (count (layout->prop->override current-layout))))}
-                    (resource/openable-resource? node-outline-link) (assoc :link node-outline-link :outline-reference? true))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1052]: Indentation change from adding the surrounding `let` for the `current-layout`.

File: editor/src/clj/editor/gui.clj [hunk 4]
```diff
@@ -1987,8 +1996,7 @@
                                                                   [:node-msgs :scene-node-msgs]
                                                                   [:node-overrides :template-overrides]]]
                                                    (g/connect or-scene from self to))
-                                                 (for [[from to] [[:template-prefix :id-prefix]
-                                                                  [:current-layout :current-layout]
+                                                 (for [[from to] [[:template-trivial-gui-scene-info :aux-trivial-gui-scene-info]
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:1999]: `:id-prefix` and `:current-layout` of the imported scene is dictated by the referencing `TemplateNode`.

File: editor/src/clj/editor/gui.clj [hunk 5]
```diff
@@ -2507,10 +2520,6 @@
   (input node-ids NameNodeIds :array)
   (output node-ids NameNodeIds :cached (g/fnk [node-ids] (reduce coll/merge {} node-ids)))
 
-  (input id-prefix g/Str)
-  (output id-prefix g/Str (gu/passthrough id-prefix))
-  (input current-layout g/Str)
-  (output current-layout g/Str (gu/passthrough current-layout))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2513]: Folded into `trivial-gui-scene-info`.

File: editor/src/clj/editor/gui.clj [hunk 6]
```diff
@@ -3216,8 +3230,6 @@
   (input default-tex-params g/Any)
   (output default-tex-params g/Any (gu/passthrough default-tex-params))
   (input display-profiles g/Any)
-  (input current-layout g/Str)
-  (output current-layout g/Str (g/fnk [current-layout visible-layout] (or current-layout visible-layout)))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3220]: Folded into `trivial-gui-scene-info`, where `:current-layout` is assigned the `visible-layout` of this `GuiSceneNode`. The `:current-layout` is then replaced with the value from the referencing scene when our scene is imported as a template.

File: editor/src/clj/editor/gui.clj [hunk 7]
```diff
@@ -3321,25 +3333,41 @@
...
+            ;; scene dictates the current-layout, and imported node ids are
+            ;; prefixed with the id of the referencing template node.
+            (coll/merge-with-kv
+              (fn [key aux-value own-value]
+                (case key
+                  (:current-layout :id-prefix) aux-value ; Replaced, not merged.
+                  (coll/merge aux-value own-value)))
+              aux-trivial-gui-scene-info
+              own-trivial-gui-scene-info)))
+
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3359]: The importing `TemplateNode` provides the `aux-trivial-gui-scene-info`.

File: editor/src/clj/editor/gui.clj [hunk 8]
```diff
@@ -3321,25 +3333,41 @@
...
   (input aux-basic-gui-scene-info BasicGuiSceneInfo)
   (output own-basic-gui-scene-info BasicGuiSceneInfo :cached
-          (g/fnk [font-names layer->index layer-names layout-names material-infos particlefx-resource-names spine-scene-names texture-page-counts texture-resource-names spine-scene-element-ids]
+          (g/fnk [font-names layer->index layer-names material-infos particlefx-resource-names spine-scene-names texture-page-counts texture-resource-names spine-scene-element-ids]
             {:font-names font-names
              :layer->index layer->index
              :layer-names layer-names
-             :layout-names layout-names
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3342]: Moved to `trivial-gui-scene-info`.

File: editor/src/clj/editor/gui.clj [hunk 9]
```diff
@@ -3348,12 +3376,12 @@
              :texture-resource-names texture-resource-names}))
   (output basic-gui-scene-info BasicGuiSceneInfo :cached
           (g/fnk [aux-basic-gui-scene-info own-basic-gui-scene-info]
-            ;; Note: The layer configurations of any template sources are
-            ;; covered up by the layer configuration of the referencing scene.
+            ;; Note: When our scene is imported as a template, the layer
+            ;; configuration of the referencing scene replaces our own.
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:3375]: Clarified these comments somewhat.

File: editor/src/clj/util/debug_util.clj [hunk 10]
```diff
@@ -74,21 +74,46 @@
...
+  ([^String line-prefix ^Thread thread]
+   (let [own-fn-class-name (.getName (class print-stack-trace!))
+         trimmed-fn-class-names-set #{own-fn-class-name}
+         stack-trace (stack-trace-impl thread trimmed-fn-class-names-set)
+         print-line! (if (empty? line-prefix)
+                       println
+                       (fn print-fn [^String line]
+                         (print line-prefix)
+                         (println line)))]
+     (run! print-line! stack-trace))))
```
Comment (matgis) [inline editor/src/clj/util/debug_util.clj:116]: I used this when diagnosing the issue, so decided to add it to the `debug-util` module.

File: editor/test/integration/gui_test.clj [hunk 11]
```diff
@@ -39,10 +39,10 @@
   (test-util/prop! node-id label val))
 
 (defn- gui-node [scene id]
-  (let [id->node (->> (get-in (g/node-value scene :node-outline) [:children 0])
+  (let [id->node (->> (get-in (g/valid-node-value scene :node-outline) [:children 0])
                       (tree-seq fn/constantly-true :children)
                       (map :node-id)
-                      (map (fn [node-id] [(g/node-value node-id :id) node-id]))
+                      (map (fn [node-id] [(g/valid-node-value node-id :id) node-id]))
```
Comment (matgis) [inline editor/test/integration/gui_test.clj:45]: Just to avoid confusion if these evaluations somehow produce an `ErrorValue`.

File: editor/test/integration/gui_test.clj [hunk 12]
```diff
@@ -1149,23 +1149,23 @@
...
+              (is (has-successor? [referencing-scene-node-tree :trivial-gui-scene-info] [referencing-scene-button :trivial-gui-scene-info]))
+              (is (has-successor? [referencing-scene-button :template-trivial-gui-scene-info] [referencing-scene-referenced-scene :trivial-gui-scene-info]))
+              (is (has-successor? [referencing-scene-referenced-scene :trivial-gui-scene-info] [referencing-scene-referenced-scene-node-tree :trivial-gui-scene-info]))
+              (is (has-successor? [referencing-scene-referenced-scene-node-tree :trivial-gui-scene-info] [referencing-scene-referenced-scene-text :trivial-gui-scene-info]))
+              (is (has-successor? [referencing-scene-referenced-scene-node-tree :trivial-gui-scene-info] [referencing-scene-referenced-scene-added-text :trivial-gui-scene-info]))
+              (is (has-successor? [referencing-scene-referenced-scene-text :trivial-gui-scene-info] [referencing-scene-referenced-scene-text :prop->value]))
+              (is (has-successor? [referencing-scene-referenced-scene-added-text :trivial-gui-scene-info] [referencing-scene-referenced-scene-added-text :prop->value])))
```
Comment (matgis) [inline editor/test/integration/gui_test.clj:1168]: These tests are a bit intrusive, but on the other hand they can be quite helpful to diagnose issues.

**Review by vlaaad — APPROVED** [review]
LGTM!
