### PR TITLE
Issue 5739: Sprite component no longer updates vertex/index buffer with no data (HTML5 fix)

### LINKED ISSUE #5739: dmGraphics::SetIndexBufferData takes 80ms on html5
The setup is that there are two sprite worlds, and one is empty.
The empty one still updates the vertex data (which for some reason doesn't take any time)
as well as the index data.
The SetIindexData seem to take a large amount of time if there is no data?
Only happens on WebGL 2, not on WebGL 1.

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -163,7 +163,7 @@ namespace dmGameSystem
                 sprite_world->m_IndexBuffer = 0;
             }
 
-            sprite_world->m_IndexBuffer = dmGraphics::NewIndexBuffer(dmRender::GetGraphicsContext(render_context), indices_size, (void*)sprite_world->m_IndexBufferData, dmGraphics::BUFFER_USAGE_STATIC_DRAW);
+            sprite_world->m_IndexBuffer = dmGraphics::NewIndexBuffer(dmRender::GetGraphicsContext(render_context), indices_size, (void*)sprite_world->m_IndexBufferData, dmGraphics::BUFFER_USAGE_DYNAMIC_DRAW);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:166]: It's more correct, since we're updating it every frame.

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 2]
```diff
@@ -857,16 +857,25 @@ namespace dmGameSystem
...
+                }
 
                 if (world->m_UseGeometries)
                 {
                     uint32_t index_size = (world->m_IndexBufferWritePtr - world->m_IndexBufferData);
-                    dmGraphics::SetIndexBufferData(world->m_IndexBuffer, index_size, world->m_IndexBufferData, dmGraphics::BUFFER_USAGE_STATIC_DRAW);
-                    DM_COUNTER("SpriteIndexBuffer", index_size);
+                    if (index_size)
+                    {
+                        dmGraphics::SetIndexBufferData(world->m_IndexBuffer, index_size, world->m_IndexBufferData, dmGraphics::BUFFER_USAGE_DYNAMIC_DRAW);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:876]: For some reason, this call take an extremely large amount of time on WebGL 2 when given an empty buffer.

Comment (britzl) [reply engine/gamesys/src/gamesys/components/comp_sprite.cpp:876]: Huh, that's weird!

**Review by britzl — APPROVED** [review]
