### PR TITLE
Fix issue when `CMD+H` doesn't hide the editor on MacOS

### LINKED ISSUE #7528: Can't hide current window:  M1 Mac Pro 14 MacOS 13.3 Defold 1.4.4
### Expected behavior
Pressing the <command> + h key should hide the current windows to the background.

### Actual behavior
Pressing the <command> + h key launches the Help > About window. 

### Steps to reproduce
Launch defold
create project [in my case the tutorial {example} project "War battles tutorial"]
when the editor finishes launching, press <command> + h
<hr/>

<table>
<tr><td>Build time</td><td>2023-03-31T16:41:03.171182</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>36f9bd22f8a5d442728986d23a96794004ed0640</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.3</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Fixed issue when `CMD+H`on MacOS shows Java About window instead of application hiding. 

Fix https://github.com/defold/defold/issues/7528

## PR checklist

* [x] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: editor/src/java/com/defold/editor/Start.java [hunk 1]
```diff
@@ -117,20 +120,13 @@ private void prunePackages() {
...
-
-              Background
-              Before the mysterious line below Command-H on OSX would open a generic Java about dialog instead of hiding the application.
-              The hypothosis is that awt must be initialized before JavaFX and in particular on the main thread as we're pooling stuff using
-              a threadpool.
-              Something even more mysterious is that if the construction of the buffered image is moved to "static void main(.." we get a null pointer in
-              clojure.java.io/resource..
-            */
-
-            new BufferedImage(1, 1, BufferedImage.TYPE_3BYTE_BGR);
```
Comment (AGulev) [inline editor/src/java/com/defold/editor/Start.java:132]: This old hack doesn't work anymore, but using of `Desktop.getDesktop().setAboutHandler(null);` helps and CMD+H works fine

**Review by britzl — APPROVED** [review]
