### PR TITLE
Use PushbackReader when listing iOS devices

### LINKED ISSUE #9837: Use PushbackReader when listing devices with `ios-deploy`
**Task (REQUIRED):**
The updated JSON library requires a pushback reader to read multiple JSON documents from the same source (which is the case when we list devices using `ios-deploy`). Currently, it fails with the following message:
```
Resolving ios-deploy location...
Resolved to '/opt/homebrew/bin/ios-deploy'
Listing devices...
JSON error (unexpected character): K
```

**Expected outcome (REQUIRED):**
`ios-deploy` works correctly.

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #9837

### CODE REVIEW

File: editor/src/clj/editor/ios_deploy.clj [hunk 1]
```diff
@@ -40,7 +41,7 @@
 (defn- json-stream [input & {:as json-opts}]
   (reify IReduceInit
     (reduce [_ f init]
-      (with-open [reader (io/reader input)]
+      (with-open [reader (PushbackReader. (io/reader input) 64)]
```
Comment (vlaaad) [inline editor/src/clj/editor/ios_deploy.clj:44]: The pushback buffer size has to be at least 64 chars. The new `data.json` lib version has some performance optimizations for faster string reading. This is only needed for repeated JSON reads from a stream, which seems to be the only place where we do it in the editor.

**Review by matgis — APPROVED** [review]
Ship it!
