### PR TITLE
Changing from a material with an overridden vertex attribute causes an assert

### LINKED ISSUE #8869: Can't change from a material with vertex color to a material without vertex color.
### Expected behaviour
I change material to any other without issues

### Actual behaviour
If I change the material from one that has a vertex attribute to one without a vertex attribute, I get an error, and my project is broken after that.

### Steps to reproduce
1. Open this project  
[change_material.zip](https://github.com/defold/defold/files/15152630/change_material.zip)
2. open main.collection -> go -> sprite
3. change material to the builtins sprite material

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-29T09:28:08.092096</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5883d3d4e3f4053fe851fb88b2918ddd19b51e9b</td></tr>
<tr><td>Defold engine sha</td><td>fd3b8c652df601220d8651f581fa2fada8205237</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"220b06f788ec4bcb8c270603162a9b68"'>220b06f788ec4bcb8c270603162a9b68</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.4.1</td></tr>
<table>

### PR DESCRIPTION
**Pull request by Jhonnyg**
Fixed an issue where a component has an overridden vertex attribute and the user changes the material where the attribute doesn't exist. In this case the editor triggers an assert which leaves the editor in a bad state.

Fixes #8869

### CODE REVIEW

File: editor/src/clj/editor/graphics.clj [hunk 1]
```diff
@@ -153,7 +153,6 @@
 
 (defn resize-doubles [double-values semantic-type ^long new-element-count]
   {:pre [(vector? double-values)
-         (keyword? semantic-type)
```
Comment (Jhonnyg) [inline editor/src/clj/editor/graphics.clj:156]: In the case where the component has an overridden vertex attribute and changes material, the intention is to still show the property in the property view, but if the 'incoming' material doesn't have the overridden vertex attribute in its attribute table this assert will be triggered since the component attribute doesn't have any semantic types.

Comment (matgis) [reply editor/src/clj/editor/graphics.clj:156]: ```(or (nil? semantic-type) (keyword? semantic-type))```
Might be preferable so that we can still catch bugs as intended?

**Review by matgis — CHANGES_REQUESTED** [review]

File: editor/src/clj/editor/graphics.clj (hunk 1 above)
Comment (Jhonnyg) [reply editor/src/clj/editor/graphics.clj:156]: Sure, sounds reasonable!

**Review by matgis — APPROVED** [review]
Ship it!
