### PR TITLE
fix buffer size

### LINKED ISSUE #8623: Error when using image.load_buffer()
From forum: https://forum.defold.com/t/defold-1-7-0-beta/76105/33?u=britzl

I found a small bug when using `image.load_buffer`.
Buffer returns sting with wrong length when using `buffer.get_bytes(data.buffer, hash("data"))`.
This happens because after the changes the `count` parameter in the stream has been changed, but the `size` of the array remains the same.

Image: 100x100 RGB

With this code I get an error: `ERROR:GUI: Invalid image buffer size. Expected 30000, got 90000`

    local img_data = image.load_buffer(png_data, {flip_vertically = true})
    local data = buffer.get_bytes(img_data.buffer, hash("data"))
    gui.new_texture("any", img_data.width, img_data.height, img_data.type, data, true)

Buffer details:

    { --[[00000211656F4F10]]
      width = 100,
      type = "rgb",
      buffer = buffer.buffer(count = 30000, version = 0, handle = 131073, { hash("data"), buffer.VALUE_TYPE_UINT8, 3 }),
      height = 100
    }

As you can see, the buffer has a size of `30000` and a `count` value of `3` in the stream.
It should be:
1. `size = width * height` and `count = 3`
2. `size = width * height * 3` and `count = 1`

Moreover, if I cut the string myself, then everything will work.

    string.sub(data, 1, 30000)

### PR DESCRIPTION
**Pull request by AGulev**
Fix buffer size

Fix https://github.com/defold/defold/issues/8623
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/scripts/script_image.cpp [hunk 1]
```diff
@@ -294,33 +294,17 @@ namespace dmGameSystem
...
-                case dmImage::TYPE_RGBA:
-                    num_components = 4;
-                    break;
-                case dmImage::TYPE_LUMINANCE:
-                    num_components = 1;
-                    break;
-                case dmImage::TYPE_LUMINANCE_ALPHA:
-                    num_components = 2;
-                default:break;
-            }
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/scripts/script_image.cpp:316]: This is the same what `dmImage::BytesPerPixel` does

File: engine/gamesys/src/gamesys/scripts/script_image.cpp [hunk 2]
```diff
@@ -294,33 +294,17 @@ namespace dmGameSystem
...
-
             dmBuffer::StreamDeclaration streams_decl[] = {
-                { dmHashString64("data"), dmBuffer::VALUE_TYPE_UINT8, num_components }
+                { dmHashString64("data"), dmBuffer::VALUE_TYPE_UINT8, bytes_per_pixel }
             };
 
             dmBuffer::HBuffer buffer = 0;
-            dmBuffer::Create(datasize, streams_decl, 1, &buffer);
+            dmBuffer::Create(imagesize, streams_decl, 1, &buffer);
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/scripts/script_image.cpp:307]: The issue here. Buffer size should be `imagesize` not `datasize`, because `bytes_per_pixel` already taken into account in stream.

**Review by Jhonnyg — APPROVED** [review]
