### PR TITLE
Fixed a regression in panning volume

### LINKED ISSUE #10879: Sounds panning does not work
**Describe the bug (REQUIRED)**
In version 1.10.2, the sound panning does not function properly, causing the sounds to become even louder. I prepared a test project (gain of the sounds are `1.0`, `use_linear_gain` is true, i.e. default), recorded a video with audio, and opened the result in Adobe Audition. 

### 1.9.1 - OK

Image

### 1.10.1 - OK

Image

### 1.10.2 - OK, I suppose (3dB is back)

Image

### 1.9.1 - OK

Image

### 1.10.1 - OK

Image

### 1.10.2 - The audio in the left channel is still here, the volume in the right channel is excessive

Image

**To Reproduce (REQUIRED)**
Run the project.

**Expected behavior (REQUIRED)**
The behaviour should be the same as in the previous version or the team should state the change is breaking.

**Defold version (REQUIRED):**
  - Version: 1.10.2

**Platforms (REQUIRED):**
 - Platforms: Windows. Other platforms were not tested.

**Minimal repro case project (OPTIONAL):**

[issue_audio_gain_on_desktop.zip](https://github.com/user-attachments/files/20871532/issue_audio_gain_on_desktop.zip)

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/10879

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/sound/src/sound.cpp [hunk 1]
```diff
@@ -1199,11 +1199,10 @@ namespace dmSound
...
                 float rs, ls;
-                GetPanScale(dmMath::Max(0.0f, instance->m_Pan.m_Current - 0.5f), &ls, &rs);
+                GetPanScale(instance->m_Pan.m_Current, &ls, &rs);
                 instance->m_ScaleL[0].Set(ls * gain, reset);
-                instance->m_ScaleR[0].Set(rs * gain, reset);
-                GetPanScale(dmMath::Min(instance->m_Pan.m_Current + 0.5f, 1.0f), &ls, &rs);
-                instance->m_ScaleL[1].Set(ls * gain, reset);
+                instance->m_ScaleR[0].Set(0.0f, reset);
+                instance->m_ScaleL[1].Set(0.0f, reset);
                 instance->m_ScaleR[1].Set(rs * gain, reset);
```
Comment (JCash) [inline engine/sound/src/sound.cpp:1206]: This is how it used to work.
Drawback is that we lose the 3dB again (so get that issue back)

**Review by britzl — DISMISSED** [review]

File: engine/sound/src/sound.cpp (hunk 1 above)
Comment (thengel01) [reply engine/sound/src/sound.cpp:1206]: Indeed :-/
