### PR TITLE
Issue-5016 Single layout gui generates layout changed message

### LINKED ISSUE #5016: Single gui layout generates layout_changed message
**Describe the bug (REQUIRED)**
For single layout in gui scene it’s not expected to catch layout_changed. 

**To Reproduce (REQUIRED)**
https://forum.defold.com/t/text-node-is-recreating-after-minimizing-window-def-2520/6826/14?u=britzl

**Expected behavior (REQUIRED)**
No "layout_changed" message should be generated if the gui has only one layout

**Defold version (REQUIRED):**
  - Version 1.2.170

**Platforms (REQUIRED):**
 - Windows

**Minimal repro case project (OPTIONAL):**
https://forum.defold.com/t/text-node-is-recreating-after-minimizing-window-def-2520/6826/14?u=britzl

### PR DESCRIPTION
**Pull request by britzl**
Fixes #5016

### CODE REVIEW

File: engine/render/src/render/display_profiles.cpp [hunk 1]
```diff
@@ -158,7 +158,7 @@ namespace dmRender
         float width_f = (float) width;
         float height_f = (float) height;
         float match_area = width_f * height_f;
-        float match_ratio = width_f / height_f;
+        float match_ratio = height_f > 0.0f ? (width_f / height_f) : 0.0f;
```
Comment (britzl) [inline engine/render/src/render/display_profiles.cpp:161]: When minimizing on windows both width and height becomes 0 and match_ratio becomes NaN.

**Review by JCash — APPROVED** [review]
