### PR TITLE
Fix search in files after deleting files

### LINKED ISSUE #9449: Error choosing File | Search in Files
### Expected behaviour
Search files
### Actual behaviour
Error pops up
### Steps to reproduce
Watch included video.

https://github.com/user-attachments/assets/8305613b-3ae5-4fb0-95d7-42f6e85a24a3

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-18T06:37:05.372838</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9c546b9847c68d50a21a8c6c5d7357ba1d9f32d1</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6038f361d6ba49c38f641a3550b9f658"'>6038f361d6ba49c38f641a3550b9f658</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 561.09</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #9449

### CODE REVIEW

File: editor/src/clj/editor/defold_project_search.clj [hunk 1]
```diff
@@ -44,6 +44,7 @@
                                          search-value-fn (when (:search-fn resource-type)
                                                            (:search-value-fn resource-type))]
                                      (when (and search-value-fn
+                                                (resource/exists? resource)
```
Comment (vlaaad) [inline editor/src/clj/editor/defold_project_search.clj:47]: After deleting the file, node-id and resource continue to exist in the graph, but the resource file no longer exists on disk. `textual?` on the line below attempts to read from disk.

**Review by matgis — APPROVED** [review]
LGTM!
