### PR TITLE
Initial fixed update of proxy collections is synced to parent collection

### LINKED ISSUE #6535: Visible stutter in proxied collection
**Describe the bug (REQUIRED)**
(The video is slowed down x2 for convenience):

https://user-images.githubusercontent.com/193258/163954439-596c75d2-1faa-464d-9fad-3ef46993b5b6.mp4

Collection proxies have their own update loop or their own time accumulator or something like that. And that update loop causes jittering/stutter.

More information:
* https://forum.defold.com/t/defold-1-3-1-beta/70594/39
* https://forum.defold.com/t/defold-1-3-1-beta/70594/51

**To Reproduce (REQUIRED)**
Run a collection from a collection proxy and update object's position in `fixed_update`.

**Expected behavior (REQUIRED)**
Proxied collection should run smoothly as the bootstrap collection, i.e. without jittering.

**Defold version (REQUIRED):**
  - Version: 1.3.1

**Platforms (REQUIRED):**
 - Platforms: All

**Minimal repro case project (OPTIONAL):**

https://github.com/aglitchman/defold-fixedupdate-131-test

If you run it, you will see three sprites (“anchors”) that infinitely fall from the top to the bottom. Look at the `test2/test.script` to see how they are animated - the script adds fixed step every `fixed_update`.

- Left: it is created from a collection factory and runs on the main timeline.
- Center: it runs from a collection proxy.
- Right: the same as the central sprite, but with interpolation of position and rotation.

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/engine/src/engine.cpp [hunk 1]
```diff
@@ -1545,6 +1545,7 @@ namespace dmEngine
                 update_context.m_TimeScale = 1.0f;
                 update_context.m_DT = dt;
                 update_context.m_FixedUpdateFrequency = engine->m_FixedUpdateFrequency;
+                update_context.m_AccumFrameTime = engine->m_AccumFrameTime;
```
Comment (JCash) [inline engine/engine/src/engine.cpp:1548]: Pass the accumulation time along

File: engine/gameobject/src/gameobject/gameobject.cpp [hunk 2]
```diff
@@ -2464,6 +2465,20 @@ namespace dmGameObject
...
         bool ret = true;
 
+
+        UpdateContext dynamic_update_context;
+        dynamic_update_context = *update_context;
+
+        // pass it as unscaled time
+        if (update_context->m_TimeScale > 0.001f )
+        {
+            dynamic_update_context.m_AccumFrameTime = collection->m_FixedAccumTime / update_context->m_TimeScale;
```
Comment (JCash) [inline engine/gameobject/src/gameobject/gameobject.cpp:2475]: The collection has time scaled accumulated time, and we need to pass unscaled time down through the hierarchy (to other collection proxies)

File: engine/gameobject/src/gameobject/gameobject.cpp [hunk 3]
```diff
@@ -2505,6 +2520,12 @@ namespace dmGameObject
 
         if (update_context->m_FixedUpdateFrequency != 0)
         {
+            if (collection->m_FirstUpdate)
+            {
+                collection->m_FirstUpdate = 0;
+                collection->m_FixedAccumTime = update_context->m_AccumFrameTime * update_context->m_TimeScale;
+            }
```
Comment (JCash) [inline engine/gameobject/src/gameobject/gameobject.cpp:2527]: If it's the first update, we want to make the accumulated time the same as the parent collection.

That way, if the time scale is 1, we can get the fixed update calls in the same frame.

File: engine/gameobject/src/gameobject/gameobject.cpp [hunk 4]
```diff
@@ -2464,6 +2465,20 @@ namespace dmGameObject
 
         bool ret = true;
 
+
+        UpdateContext dynamic_update_context;
+        dynamic_update_context = *update_context;
+
+        // pass it as unscaled time
+        if (update_context->m_TimeScale > 0.001f )
```
Comment (britzl) [inline engine/gameobject/src/gameobject/gameobject.cpp:2473]: Why 0.001f specifically?

**Review by britzl — COMMENTED** [review]
I think I understand the logic and as far as I can tell it looks good. I have a a question about the 0.001f check though.

File: engine/gameobject/src/gameobject/gameobject.cpp (hunk 4 above)
Comment (JCash) [reply engine/gameobject/src/gameobject/gameobject.cpp:2473]: It's just a threshold value. A sufficiently low value, have to pick one since it cannot be zero.

**Review by britzl — APPROVED** [review]
