### PR TITLE
Fix for models with multiple meshes and mixed coordinate spaced materials

### LINKED ISSUE #9647: glb with 2 models is wrong render in editor.
### Steps to reproduce
I am not sure why this happened.
In my game i use that door. But when i set 2 different materials(base and transparent) window in door is not rendered
-base base

-transparent base

I tryed to make repro case. I am not sure but i think problem is than one material use local and second use world.

[model_2_materials_errors.zip](https://github.com/user-attachments/files/17511555/model_2_materials_errors.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2024-10-23T14:41:30.540039</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ed533d8f5deef70915d1cd4bf129998ade7bea80</td></tr>
<tr><td>Defold engine sha</td><td>a9277779d1c23b0712a5959314b9508d2e802efb</td></tr>
<tr><td>Defold version</td><td>1.9.4</td></tr>
<tr><td>GPU</td><td>Intel(R) RaptorLake-S Mobile Graphics Controller</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.5186</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by Jhonnyg**
Models that use .gltf files that use materials with different coordinate spaces can now be batched correctly.

Fixes #9647

### CODE REVIEW

File: engine/gamesys/src/gamesys/test/create_prebuilts.sh [hunk 1]
```diff
@@ -72,3 +72,9 @@ cp build/default/model/dynamic_vertex_attributes.skeletonc ../model/dynamic_vert
 # Texture transform (models) - uses aabb_model.gltf mesh; meshsetc/skeletonc come from that gltf (aabb_model.*), already copied above
 cp build/default/model/texture_transform_model.modelc ../model/texture_transform_model.prebuilt_modelc
 cp build/default/model/texture_transform_model.rigscenec ../model/texture_transform_model.prebuilt_rigscenec
+
+# One mesh two materials (models)
+cp build/default/model/one_mesh_two_materials.modelc ../model/one_mesh_two_materials.prebuilt_modelc
+cp build/default/model/one_mesh_two_materials.rigscenec ../model/one_mesh_two_materials.prebuilt_rigscenec
+cp build/default/model/one_mesh_two_materials.meshsetc ../model/one_mesh_two_materials.prebuilt_meshsetc
+cp build/default/model/one_mesh_two_materials.skeletonc ../model/one_mesh_two_materials.prebuilt_skeletonc
```
Comment (Jhonnyg) [inline engine/gamesys/src/gamesys/test/create_prebuilts.sh:80]: It would be nice to remove this "prebuilt" project. Not sure what's stopping us, but it's geting bigger and bigger :(

**Review by JCash — DISMISSED** [review]
