### PR TITLE
Make commands that request outline selection work outside outline again

### LINKED ISSUE #12030: BETA branch - Selecting objects in the view no longer counts for editor scripts `selection = {type = "outline"`
Works as expected in `1.12.2` broken in `1.12.3`

### Expected behaviour
Selecting objects within the view (editor) should count for selecting them in the outline.

### Actual behaviour
It has stopped behaving like it.

### Steps to reproduce
1. Add a editor script.
```lua
local M = {}

function M.get_commands()
    return {
        {
            label="Test",
            locations = {"Edit"},
            query = {
                selection = {type = "outline", cardinality = "many"}
            },
            run = function(opts)
                return nil
            end
        },
    }
end

return M
```
2. Create a gui file
3. Create two nodes

### Works
1. Select them in the outline
2. Look under the edit menu - the option is there

### Doesn't work
1. Select them in the view/editor
2. Look under the edit menu - the option is not there

<hr/>

<table>
<tr><td>Build time</td><td>2026-03-12T10:24:30.868161</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>5b88a23a8f7e11e8f0f6fa61c4829adaab3bb935</td></tr>
<tr><td>Defold engine sha</td><td>5b88a23a8f7e11e8f0f6fa61c4829adaab3bb935</td></tr>
<tr><td>Defold version</td><td>1.12.3</td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 20.1.2, DRM 3.64, 6.17.0-14-generic)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 25.2.8-0ubuntu0.24.04.1</td></tr>
<tr><td>Java version</td><td>25+36-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.17.0-14-generic</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
Fix #12030

### CODE REVIEW

File: editor/src/clj/editor/editor_extensions/commands.clj [hunk 1]
```diff
@@ -87,18 +87,20 @@
...
+                                                     (contains? % :node-id-path))
+                                               selection)
+                                (some-> selection
+                                        (coll/into-> []
+                                          (map #(editor-lookup-userdata (graph/node-id-with-ancestors (:node-id %) (pop (:node-id-path %))))))
+                                        coll/not-empty
+                                        (ensure-selection-cardinality q))
+                                (some-> selection
+                                        (handler/adapt-every Long evaluation-context)
+                                        (node-ids->lua-selection q)))]
```
[the remark this answers is not in the document]
Comment (vlaaad) [reply editor/src/clj/editor/editor_extensions/commands.clj:103]: This is the intended behavior.

File: editor/test/integration/editor_extensions_test.clj [hunk 2]
```diff
@@ -352,7 +352,20 @@
...
+                              (:command (last (handler/realize-menu :editor.app-view/edit-end)))
+                              (eval-handler-contexts :global [sprite-node-id])
+                              {})]
+        (is (some? handler+context))
+        (is (handler/enabled? handler+context))
+        (is (nil?
+              (try
+                @(handler/run handler+context)
+                nil
+                (catch Throwable e e))))
```
Comment (matgis) [inline editor/test/integration/editor_extensions_test.clj:378]: I suppose `(is (any? ...))` would let you remove the `nil` from the `try` block? 🤔

Don't mind me, I'm just excited to find `any?` useful for something! 😅

File: editor/test/integration/editor_extensions_test.clj [hunk 3]
```diff
@@ -352,7 +352,20 @@
                 @(handler/run handler+context)
                 nil
                 (catch Throwable e e))))
-        (is (= [2 2 2] (test-util/prop sprite-node-id :scale)))))))
+        (is (= [2 2 2] (test-util/prop sprite-node-id :scale))))
```
Comment (matgis) [inline editor/test/integration/editor_extensions_test.clj]:
```suggestion
        (is (= [2.0 2.0 2.0] (test-util/prop sprite-node-id :scale))))
```

File: editor/test/integration/editor_extensions_test.clj [hunk 4]
```diff
@@ -352,7 +352,20 @@
...
+                              {})]
+        (is (some? handler+context))
+        (is (handler/enabled? handler+context))
+        (is (nil?
+              (try
+                @(handler/run handler+context)
+                nil
+                (catch Throwable e e))))
+        (is (= [3 3 3] (test-util/prop sprite-node-id :position)))
+        (is (= 4 (test-util/prop sprite-node-id :playback-rate)))))))
```
Comment (matgis) [inline editor/test/integration/editor_extensions_test.clj]:
```suggestion
        (is (= [3.0 3.0 3.0] (test-util/prop sprite-node-id :position)))
        (is (= 4.0 (test-util/prop sprite-node-id :playback-rate)))))))
```

**Review by matgis — DISMISSED** [review]
It might be nice to have some comments to the test regarding what changes the executed handlers are doing.

File: editor/test/integration/editor_extensions_test.clj (hunk 2 above)
Comment (vlaaad) [reply editor/test/integration/editor_extensions_test.clj:378]: Unfortunately, it won't work here: this is basically a test assertion that the handler does not throw (`any?` on `Throwable` returns true, which is not what we want).

I think `any?` is a good fallback as a default pred arg to functions that receive optional preds...

File: editor/test/integration/editor_extensions_test.clj (hunk 4 above)
Comment (vlaaad) [reply editor/test/integration/editor_extensions_test.clj]: This fails the tests since editor scripts actually set values to Longs. I created https://github.com/defold/defold/issues/12074
