### PR TITLE
Issue 5499: dmSys::LoadResource can load from both the android assets…

### LINKED ISSUE #5499: Investigate issue with LiveUpdate
**Describe the bug (REQUIRED)**
Live Update is giving different kinds of errors:

"Doesn’t want to save the manifest, says there are no resources"

**To Reproduce (REQUIRED)**
See attached repro case.

* You need to set the SERVER_URL global variable in launcher.gui_script to play.
* Then create android build apk and liveupdate in zip mod.
* Extract the liveupdate to the folder path: {http server root}/{debug or release folder}/{build architecture, here android}/{there are many unzipped files}.
* After that you should also create a file named ‘liveupdate_version’ here without an extension with one line {“value”: “1.1.1.3”} - to compare whether you need to re-download liveupdate if different.
* Run the http server from root folder.
* Now the android app should download the liveupdate successfully, BUT the second and subsequent launches will have random errors.

**Expected behavior (REQUIRED)**
It should work :-)

**Defold version (REQUIRED):**
  - Version 1.2.173-1.2.178

**Platforms (REQUIRED):**
 - Platforms: Android (possibly others)

**Minimal repro case project (OPTIONAL):**
Attached

**Additional context (OPTIONAL):**
Forum post: https://forum.defold.com/t/liveupdate-strange-behavior/65802/33?u=britzl
[LUTest.zip](https://github.com/defold/defold/files/5856938/LUTest.zip)

### PR DESCRIPTION
**Pull request by JCash**
… and also regular files

### CODE REVIEW

File: engine/dlib/src/dlib/sys.cpp [hunk 1]
```diff
@@ -898,10 +891,8 @@ namespace dmSys
             }
             *resource_size = asset_size;
             return RESULT_OK;
-        } else {
-            return RESULT_NOENT;
         }
-#else
+#endif
```
Comment (JCash) [inline engine/dlib/src/dlib/sys.cpp:895]: I think these functions FileExists, ResourceSize and LoadResource should be able to find files on disc on all platforms, including Android.

This issue came after refactoring the archive loading code to use these functions as opposed to specific "fopen" et al.

File: engine/liveupdate/src/liveupdate_archive.cpp [hunk 2]
```diff
@@ -183,7 +183,7 @@ namespace dmLiveUpdate
             dmPath::Concat(app_support_path, names[i], path, DMPATH_MAX_PATH);
             if (FileExists(path))
             {
-                dmLogDebug("Cleaning up %s", path);
+                dmLogInfo("Cleaning up %s", path);
```
Comment (JCash) [inline engine/liveupdate/src/liveupdate_archive.cpp:186]: I'd rather see it in the logs.

**Review by britzl — APPROVED** [review]
