### PR TITLE
Issue 5063 - Vulkan cubemap support

### LINKED ISSUE #5063: Support cube mapping for Vulkan backend
**Task (REQUIRED):**
Add support for using cube maps in the Vulkan renderer. Right now the SPIR-v pipeline fails when using a samplerCube in a shader.

**Expected outcome (REQUIRED):**
Cube maps should be uploaded and rendered correctly using the vulkan backend.

### PR DESCRIPTION
**Pull request by Jhonnyg**
This PR fixes #5063

### CODE REVIEW

File: engine/graphics/src/vulkan/graphics_vulkan_private.h [hunk 1]
```diff
@@ -430,7 +430,7 @@ namespace dmGraphics
     // Misc functions
     VkResult TransitionImageLayout(VkDevice vk_device, VkCommandPool vk_command_pool, VkQueue vk_graphics_queue, VkImage vk_image,
         VkImageAspectFlags vk_image_aspect, VkImageLayout vk_from_layout, VkImageLayout vk_to_layout,
-        uint32_t baseMipLevel = 0, uint32_t levelCount = 1);
```
Comment (Jhonnyg) [inline engine/graphics/src/vulkan/graphics_vulkan_private.h:433]: levelCount was never used it seems..

**Review by JCash — APPROVED** [review]
