### PR TITLE
Fixed the issue where the Tilemap was not using flip and rotate attributes for physics

### LINKED ISSUE #8971: Tilemap not use flip and rotate attributes for physics
Yes, the Defold visually rotates and flip tiles, but the assigned physics on the tiles remains not rotated
Tilemap exported from Tiled(for example) has contain next attributes:
```
...
cell {
    x: 3
    y: 6
    tile: 1
    h_flip: 1
    v_flip: 1
    rotate90: 1
  }
...
```
but at runtime we have:
tile_issue

**To Reproduce**
- Just run example project

**Expected behavior**
Physics use rotate and flip attributes

**Defold version:**
  - Version 1.8.0 (9141d9d3605e3f5d51c71293116d769da2613d39)

**Platforms:**
 - Platforms: Linux, Adroid

**Minimal repro case project:**
[tile_bug_issue.tar.gz](https://github.com/defold/defold/files/15414435/tile_bug_issue.tar.gz)

### PR DESCRIPTION
**Pull request by AGulev**
Fixed the issue where tile rotation and flip were applied for the visualization of the tile but not for physics.

Fix https://github.com/defold/defold/issues/8971
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 1]
```diff
@@ -343,6 +343,9 @@ namespace dmGameSystem
                     {
                         uint32_t cell_x = cell->m_X - tile_grid_resource->m_MinCellX;
                         uint32_t cell_y = cell->m_Y - tile_grid_resource->m_MinCellY;
+                        flags.m_FlipHorizontal = cell->m_HFlip;
+                        flags.m_FlipVertical = cell->m_VFlip;
+                        flags.m_Rotate90 = cell->m_Rotate90;
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:348]: We never fill the flags. It seems like this was the issue for years and I missed it as well last time I worked on it.

**Review by britzl — APPROVED** [review]
