### PR TITLE
Fixed issue when `sys.open_url()` reports false when a url is opened on Windows

### LINKED ISSUE #5549: sys.open_url reports false when a url is opened on Windows 10
**Describe the bug (REQUIRED)**
On Windows 10, even though the url is opened successfully, it still reports as not successful
```
local success = sys.open_url("http://www.defold.com", {target = "_blank"})
if not success then
  print("failed to open url")
end
```

**Expected behavior (REQUIRED)**
If a target can't detect that a URL was actually opened it should assumed it did assuming there are no other errors in the process

**Defold version (REQUIRED):**
1.2.179

### PR DESCRIPTION
**Pull request by AGulev**
Fix https://github.com/defold/defold/issues/5549

### CODE REVIEW

File: engine/dlib/src/dlib/sys_posix.cpp [hunk 1]
```diff
@@ -329,7 +329,7 @@ namespace dmSys
     Result OpenURL(const char* url, const char* target)
     {
         intptr_t ret = (intptr_t) ShellExecuteA(NULL, "open", url, NULL, NULL, SW_SHOWNORMAL);
-        if (ret == 32)
+        if (ret > 32)
```
Comment (AGulev) [inline engine/dlib/src/dlib/sys_posix.cpp:332]: >If the function succeeds, it returns a value greater than 32.

https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea

**Review by ekharkunov — APPROVED** [review]
👍
