### PR TITLE
Issue 5010: Fixed crash issue with lingering http request at shutdown

### LINKED ISSUE #5010: Crash Android (dns.cpp:120)
**Describe the bug (REQUIRED)**
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.potatojam.onet_paradise.match_two_tiles <<<

backtrace:
  #00  pc 0000000000132378  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmDNS::ares_addrinfo_callback(void*, int, int, ares_addrinfo*)) (SourceCode: /home/runner/work/defold/defold/engine/dlib/build/../src/dlib/dns.cpp:120)
  #00  pc 00000000001ed2ac  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (end_hquery)
  #00  pc 00000000001edbf0  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (host_callback)
  #00  pc 00000000001ec310  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (qcallback)
  #00  pc 00000000001e7bd0  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (ares_destroy)
  #00  pc 0000000000131f4c  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmDNS::DeleteChannel(dmDNS::Channel*)) (SourceCode: /home/runner/work/defold/defold/engine/dlib/build/../src/dlib/dns.cpp:280)
  #00  pc 00000000000e798c  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmHttpService::Delete(dmHttpService::HttpService*)) (SourceCode: /home/runner/work/defold/defold/engine/script/build/../src/http_service.cpp:406)
  #00  pc 00000000000d51f0  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmScript::HttpFinalize(dmScript::Context*)) (SourceCode: /home/runner/work/defold/defold/engine/script/build/../src/script_http.cpp:255)
  #00  pc 00000000000cef3c  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmScript::Finalize(dmScript::Context*)) (SourceCode: /home/runner/work/defold/defold/engine/script/build/../src/script.cpp:233)
  #00  pc 0000000000043520  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmEngine::Delete(dmEngine::Engine*)) (SourceCode: /home/runner/work/defold/defold/engine/engine/build/../src/engine.cpp:289)
  #00  pc 0000000000046550  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmEngine::InitRun(dmEngineService::EngineService*, int, char**, void (*)(dmEngine::Engine*, void*), void (*)(dmEngine::Engine*, void*), void*)) (SourceCode: /home/runner/work/defold/defold/engine/engine/build/../src/engine.cpp:1554)
  #00  pc 0000000000046550  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (dmEngine::Launch(int, char**, void (*)(dmEngine::Engine*, void*), void (*)(dmEngine::Engine*, void*), void*)) (SourceCode: /home/runner/work/defold/defold/engine/engine/build/../src/engine.cpp:1569)
  #00  pc 0000000000042fa0  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (engine_main(int, char**)) (SourceCode: /home/runner/work/defold/defold/engine/engine/build/../src/engine_main.cpp:47)
  #00  pc 0000000000042ee0  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (main) (SourceCode: /tmp/job2830209765871841154/build/main.cpp:54)
  #00  pc 00000000001977b8  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (_glfwPreMain) (SourceCode: /home/runner/work/defold/defold/engine/glfw/build/../lib/android/android_init.c:664)
  #00  pc 0000000000042f04  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (android_main) (SourceCode: /tmp/job2830209765871841154/build/main.cpp:71)
  #00  pc 0000000000199bcc  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm64/libOnetParadise.so (android_app_entry) (SourceCode: /home/runner/work/defold/defold/engine/glfw/build/../lib/android/android_native_app_glue.c:245)
  #00  pc 00000000000689ac  /system/lib64/libc.so (__pthread_start(void*)+196)
  #00  pc 000000000001de40  /system/lib64/libc.so (__start_thread+16)
```

image

**To Reproduce (REQUIRED)**
Unfortunately I don't know how to reproduce this issue, I see this crash in Google Console.
By call stack, it seems like it happens when a user exits the application. 

So, it's not critical but affects Android Vitals Metrics in Google Console.

**Defold version (REQUIRED):**
  - Version: 1.2.169

**Platforms (REQUIRED):**
 - Platforms:  Android
 - OS: 
Android 7.1 (SDK 25)
Android 8.1 (SDK 27)
Android 9 (SDK 28)
Android 10 (SDK 29)
 - Devices: 
Oppo CPH1801
Vivo vivo 1820
Samsung Galaxy A50s
Samsung Galaxy A50

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/dlib/src/dlib/dns.cpp [hunk 1]
```diff
@@ -405,6 +405,7 @@ namespace dmDNS
             if ((dmTime::GetTime() - request_started) > request_timeout)
             {
                 req.m_Status = ARES_ETIMEOUT;
+                ares_cancel(dns_channel->m_Handle);
```
Comment (JCash) [inline engine/dlib/src/dlib/dns.cpp:408]: When hitting the timeout, just after the host lookup has started, we were missing a ares_cancel.

File: engine/dlib/src/dlib/http_client.h [hunk 2]
```diff
@@ -100,7 +100,7 @@ namespace dmHttpClient
      */
     enum Option
     {
-        /// Maximum number of retries for GET-request. Default is 4.
+        /// Maximum number of retries for GET-request. Default is 1.
```
Comment (JCash) [inline engine/dlib/src/dlib/http_client.h:103]: Incorrect comment

**Review by britzl — APPROVED** [review]
Great stuff!
