### PR TITLE
Material constants now contain no duplicates

### LINKED ISSUE #10456: Undefined uniform value when using the same name in vertex and fragment shaders
**Describe the bug (REQUIRED)**
I haven't updated all shaders in old games to version 140 yet, and when testing our games on Vulkan macOS, I discovered that most of our materials don't look as they should.

I checked all the shaders and realized that the problem is that I use the same names for uniforms in vertex and fragment shaders, as I use the value of one uniform in both shaders.

1) This works perfectly if the shader is an old version and the renderer is OpenGL (or WebGL).
2) When specifying shader version 140 and using OpenGL renderer, only the vertex shader receives the uniform value, while the fragment shader receives a value of `vec4(0.0, 0.0, 0.0, 0.0)`.
3) With Vulkan renderer, regardless of shader version, only the vertex shader receives the uniform value, while the fragment shader receives a value of `vec4(0.0, 0.0, 0.0, 0.0)`.
4) <!> In all variants above, if you set a new uniform value from a script using `go.set()`, then both shaders receive the new value.

Question: which behavior is correct? I believe that both shaders should receive the uniform value specified in the material, as it was for older shader versions and OpenGL backend - this doesn't violate standards, as far as I can tell.

**Defold version (REQUIRED):**
  - Version: 1.9.8, 1.10.0

**Platforms (REQUIRED):**
 - Platforms: Windows, macOS, HTML5

**Minimal repro case project (OPTIONAL):**
The project: 

[test_model_tint_new_vs_old.zip](https://github.com/user-attachments/files/19639351/test_model_tint_new_vs_old.zip)

From my point of view, the demo should look like that:
Image

In reality, it looks like that on OpenGL (Windows):
Image

On Vulkan (Windows):
Image

Screenshot from RenderDoc (sorry, not from the repro project, but from my game - but the point is to show that the value of uniform is `vec4(0.0)`):
Image

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/10456

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/render/src/render/program_utils.cpp [hunk 1]
```diff
@@ -236,23 +248,38 @@ namespace dmRender
             if (uniform_desc.m_Type == dmGraphics::TYPE_FLOAT_VEC4 || uniform_desc.m_Type == dmGraphics::TYPE_FLOAT_MAT4)
             {
                 HConstant render_constant = dmRender::NewConstant(uniform_desc.m_NameHash);
+
                 dmRender::SetConstantLocation(render_constant, uniform_desc.m_Location);
 
-                if (uniform_desc.m_Type == dmGraphics::TYPE_FLOAT_MAT4)
+                // We are be about to add a duplicate. Make sure to reuse the data
+                HConstant prev_constant = FindConstant(constants, uniform_desc.m_NameHash);
+                if (prev_constant != 0)
```
Comment (JCash) [inline engine/render/src/render/program_utils.cpp:256]: When creating the initial material constants (when loading the material), we check if there are duplicates.
If so, we make sure it uses the same memory as the first constant (with the same name).

This makes sure we can have multiple uniforms (vs + fs) with different locations, but still use get/set the same values.

File: engine/render/src/render/program_utils.cpp [hunk 2]
```diff
@@ -236,23 +248,38 @@ namespace dmRender
...
-                    num_values *= 4;
-                    dmRender::SetConstantType(render_constant, dmRenderDDF::MaterialDesc::CONSTANT_TYPE_USER_MATRIX4);
-                }
+                    uint32_t prev_num_values;
+                    dmVMath::Vector4* prev_values = GetConstantValues(prev_constant, &prev_num_values);
 
-                // Set correct size of the constant (Until the shader builder provides all the default values)
-                if (num_values > default_values_capacity)
+                    dmRender::SetConstantValuesRef(render_constant, prev_values, prev_num_values);
+                    dmRender::SetConstantType(render_constant, GetConstantType(prev_constant));
```
Comment (JCash) [inline engine/render/src/render/program_utils.cpp:262]: I do believe we need to check mor thoroughly in editor/bob for mismatching types etc.
For now, we use the type of the first uniform (as we are using an existing pointer to the data)

File: engine/render/src/render/program_utils.cpp [hunk 3]
```diff
@@ -236,23 +248,38 @@ namespace dmRender
...
+                }
+                else
                 {
-                    default_values_capacity = num_values;
-                    delete[] default_values;
-                    default_values = new dmVMath::Vector4[default_values_capacity];
-                    memset(default_values, 0, default_values_capacity * sizeof(dmVMath::Vector4));
+                    if (uniform_desc.m_Type == dmGraphics::TYPE_FLOAT_MAT4)
```
Comment (JCash) [inline engine/render/src/render/program_utils.cpp:266]: Not a duplicate, then do the things we did before...

File: engine/render/src/render/program_utils.cpp (hunk 2 above)
Comment (AGulev) [reply engine/render/src/render/program_utils.cpp:262]: Could you please create a task for bob?

**Review by AGulev — DISMISSED** [review]
lgtm
