### PR TITLE
Fix for collection factory script instances having separate property sets

### LINKED ISSUE #9131: Crash when using collection factories with properties (1.9.0)
**Describe the bug**
The engine crashes when using properties and the collection factory on a collection with multiple components.

**To Reproduce**
1. Run the attached project on the 1.9.0 engine.
2. Close the project window (this also happens when deleting a collection created by the factory, but I simplified the example as much as possible)
3. Watch the crash report

**Expected behavior**
Should not crash

**Defold version:**
  - Version 1.9.0

**Platforms:**
 - Platforms: macOS - crash report, Windows - silent crash

**Minimal repro case project:**
[Defold_1.9.0_FactoryPropsIssue.zip](https://github.com/user-attachments/files/16008803/Defold_1.9.0_FactoryPropsIssue.zip)

**Crash call stack:**

```
ERROR:CRASH: 0   dmengine                            0x0000000100bf394c _ZN7dmCrash7OnCrashEi + 104
ERROR:CRASH: 1   libsystem_platform.dylib            0x0000000190b37584 _sigtramp + 56
ERROR:CRASH: 2   libsystem_pthread.dylib             0x0000000190b06c20 pthread_kill + 288
ERROR:CRASH: 3   libsystem_c.dylib                   0x0000000190a13a30 abort + 180
ERROR:CRASH: 4   libsystem_malloc.dylib              0x0000000190923dc4 malloc_vreport + 896
ERROR:CRASH: 5   libsystem_malloc.dylib              0x0000000190927430 malloc_report + 64
ERROR:CRASH: 6   libsystem_malloc.dylib              0x0000000190941494 find_zone_and_free + 528
ERROR:CRASH: 7   dmengine                            0x00000001009c8234 _ZN12dmGameObject16DeletePropertiesEPNS_10PropertiesE + 36
ERROR:CRASH: 8   dmengine                            0x00000001009cdb38 _ZN12dmGameObject20DeleteScriptInstanceEPNS_14ScriptInstanceE + 164
ERROR:CRASH: 9   dmengine                            0x00000001009b9770 _ZN12dmGameObject17CompScriptDestroyERKNS_22ComponentDestroyParamsE + 104
ERROR:CRASH: 10  dmengine                            0x00000001009c4c3c _ZN12dmGameObjectL17DestroyComponentsEPNS_10CollectionEPNS_8InstanceE + 208
ERROR:CRASH: 11  dmengine                            0x00000001009c48b8 _ZN12dmGameObjectL16DoDeleteInstanceEPNS_10CollectionEPNS_8InstanceE + 208
ERROR:CRASH: 12  dmengine                            0x00000001009bc9ac _ZN12dmGameObject16DeleteCollectionEPNS_10CollectionE + 144
ERROR:CRASH: 13  dmengine                            0x00000001009c2ec4 _ZN12dmGameObject10PostUpdateEPNS_8RegisterE + 140
ERROR:CRASH: 14  dmengine                            0x00000001009aa8ec _ZN8dmEngine6DeleteEPNS_6EngineE + 96
ERROR:CRASH: 15  dmengine                            0x00000001009ae7e8 _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE + 156
ERROR:CRASH: 16  dmengine                            0x00000001009ae698 _Z11engine_mainiPPc + 104
ERROR:CRASH: 17  dyld                                0x000000019077e0e0 start + 2360
```

### PR DESCRIPTION
**Pull request by JCash**
This fixes a crash when two script instances tries to delete the same property set.
It was a regression from 1.8.1.

Fixes https://github.com/defold/defold/issues/9131

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

**Review by britzl — APPROVED** [review]

File: engine/gameobject/src/gameobject/gameobject.cpp [hunk 1]
```diff
@@ -1510,7 +1510,9 @@ namespace dmGameObject
                         {
                             if (strcmp(type->m_Name, "scriptc") == 0)
                             {
-                                lua_properties = *instance_properties;
+                                // TODO: Investigate if it's enough to have one property set, (to save time/memory)
+                                // and only register the Free function once (letting the first instance "own" it)
+                                lua_properties = PropertyContainerCopy(*instance_properties);
```
Comment (AGulev) [inline engine/gameobject/src/gameobject/gameobject.cpp:1515]: What if the first instance will be removed while the other instances still exist?

Comment (JCash) [reply engine/gameobject/src/gameobject/gameobject.cpp:1515]: I'm guessing you're referring to the TODO?
That's why it's left as a to do, I don't want to spend time on that right now.
