### PR TITLE
Fixed the issue where horizontal scrolling in the text editor doesn't account for changes in code font size

### LINKED ISSUE #10002: Sometimes horizontal Scrolling doesn't work AND horizontal Scroll Bar just doesn't appear too
**Describe the bug (REQUIRED)**
Sometimes, I can't see end of my code line in the Code Editor because Horizontal scrolling just don't work and also horizontal Scroll Bar don't appear too while the Code Overview prevent to see it.

**To Reproduce (REQUIRED)**
1. Go to Code Editor
2. Scroll to the end of the code line by clicking on right arrow on keyboard
3. Code Overview prevent to see the end of code line

**Expected behavior (REQUIRED)**
See the end of my code.

**Defold version (REQUIRED):**
  - Version 1.9.6

**Platforms (REQUIRED):**
 - Platforms: Linux, KDE Plasma 6.2.5 Wayland session
 - OS: EndeavourOS
 - Device: Lenovo B590
 - Display: 1366x768

**Video:**

https://github.com/user-attachments/assets/adbd7e50-8a6b-4534-a670-203eca5c6994

### PR DESCRIPTION
**Pull request by AGulev**
Fix https://github.com/defold/defold/issues/10002

### CODE REVIEW

File: editor/src/clj/editor/code/view.clj [hunk 1]
```diff
@@ -676,6 +676,10 @@
 (g/defnk produce-indent-level-pattern [tab-spaces]
   (data/indent-level-pattern tab-spaces))
 
+(g/defnk produce-document-width [glyph-metrics tab-spaces lines]
+  (let [tab-stops (data/tab-stops glyph-metrics tab-spaces)]
+    (data/max-line-width glyph-metrics tab-stops lines)))
```
Comment (AGulev) [inline editor/src/clj/editor/code/view.clj:681]: `document-width` shuold be updated if text metrics changes, so we show horizontal scrollbar in time. We can do it using a listener for change text size event (I did it initially), or using graph and dependencies

**Review by matgis — CHANGES_REQUESTED** [review]
You've correctly identified the issue, in that we must account for the updated `glyph-metrics` to calculate the document width. However, the new implementation is rather inefficient since it will measure all the lines of the whole document whenever the user edits the file.

Previously (and still, presumably broken?), the `document-width` property was adjusted to grow by considering the previous width and the new widths of just the lines affected by each edit in the `code.data/update-document-width-after-splice` function.

Your approach of calculating the `document-width` in an output is more elegant and in-line with how we typically want to solve this sort of thing in the graph. However, to remain efficient when typing into large files, it would be better to retain the `document-width` property and also update it in `set` clauses added to the `font-name` and `font-size` properties.

File: editor/src/clj/editor/code/view.clj [hunk 2]
```diff
@@ -1136,8 +1146,13 @@
...
 
-  (property font-name g/Str (default "Dejavu Sans Mono"))
-  (property font-size g/Num (default (g/constantly default-font-size)))
+  (property font-name g/Str (default "Dejavu Sans Mono")
+            (set (fn [evaluation-context self _old-value _new-value]
+                   (update-document-width evaluation-context self))))
+  (property font-size g/Num
+            (default (g/constantly default-font-size))
+            (set (fn [evaluation-context self _old-value _new-value]
+                   (update-document-width evaluation-context self))))
```
Comment (AGulev) [inline editor/src/clj/editor/code/view.clj:1155]: I'm not happy with the result, because `tab-spaces` should be taken into account as well.  
Also, I see that we have `produce-layout`, which is called with all the same values—maybe it's a bit more lightweight.

The current implementation fixes the main issue, though.

**Review by matgis — APPROVED** [review]
LGTM! ❤️
