### PR TITLE
Fix a crash that can occur during GameObject parenting or deletion under specific rare conditions

### LINKED ISSUE #12247: Crash in GameObject Parenting / Deletion
Hi, we’re experiencing a frequent and seemingly random crash in our project:
https://store.steampowered.com/app/3818770/SuperWEIRD_Automation_Roguelite/

 #### Crash Details

The crash is caused by the following assertion:
```
Assertion failed: child->m_Parent == instance->m_Index, file ..\src\gameobject\gameobject.cpp, line 1323
INFO:CRASH: Successfully wrote Crashdump to file: C:/Users/HELIO_~1/AppData/Roaming/Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF6356DF9B0 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:143
ERROR:CRASH:  1 0x7FF6356E0050 dmCrash::SignalHandler D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:294
ERROR:CRASH:  2 0x7FF635C809F0 raise /tmp/job15969021810638547612/minkernel/crts/ucrt/src/appcrt/misc/signal.cpp:547
ERROR:CRASH:  3 0x7FF635C712AC abort /tmp/job15969021810638547612/minkernel/crts/ucrt/src/appcrt/startup/abort.cpp:71
ERROR:CRASH:  4 0x7FF635C6F660 common_assert_to_stderr<wchar_t> /tmp/job15969021810638547612/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:186
ERROR:CRASH:  5 0x7FF635C6F178 _wassert /tmp/job15969021810638547612/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:443
ERROR:CRASH:  6 0x7FF6356912B0 dmGameObject::ReparentChildNodes D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:1324
ERROR:CRASH:  7 0x7FF63568F1F0 dmGameObject::DoDeleteInstance D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2029
ERROR:CRASH:  8 0x7FF6356946A0 dmGameObject::PostUpdate D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2895
ERROR:CRASH:  9 0x7FF635784250 dmGameSystem::CompCollectionProxyPostUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_collection_proxy.cpp:414
ERROR:CRASH: 10 0x7FF6356946A0 dmGameObject::PostUpdate D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2850
ERROR:CRASH: 11 0x7FF635750CA0 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:2087
ERROR:CRASH: 12 0x7FF63574AA80 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2609
ERROR:CRASH: 13 0x7FF6357519B0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:86
ERROR:CRASH: 14 0x7FF635634580 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:153
ERROR:CRASH: 15 0x7FF635C23990 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 16 0x7FFD3182E8C0 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 17 0x7FFD332EC3D0 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

```

 #### Observations
The crash appears to occur during object deletion and/or reparenting.
Based on investigation, it may be related to a sequence involving:
go.set_parent
go.delete
However, we have not been able to identify a precise reproduction pattern.

 #### Reproduction Attempts

I created a minimal test project to isolate the issue:
https://github.com/ivolff/set_parent_example

This project randomly executes sequences of:

factory.create
go.delete
go.set_parent

The crash reliably occurs after ~200–400 iterations.
The assertion is identical to the one seen in our main project.
Despite this, I haven’t been able to determine the exact sequence that triggers the crash.

<hr/>

<table>
<tr><td>Build time</td><td>2026-02-05T21:58:17.775459</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>16c6fd602f32de4814660672c38ce3ccbbc1fb59</td></tr>
<tr><td>Defold engine sha</td><td>16c6fd602f32de4814660672c38ce3ccbbc1fb59</td></tr>
<tr><td>Defold version</td><td>1.12.1</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 560.94</td></tr>
<tr><td>Java version</td><td>25+36-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Fixed a crash that could happen when game objects were repeatedly reparented and deleted in the same collection.

Fix https://github.com/defold/defold/issues/12247

### CODE REVIEW

File: engine/gameobject/src/gameobject/gameobject.cpp [hunk 1]
```diff
@@ -3241,6 +3241,9 @@ namespace dmGameObject
             Unlink(collection, child);
         }
 
+        // Root instances may carry a stale sibling link from a deleted parent.
+        child->m_SiblingIndex = INVALID_INSTANCE_INDEX;
```
Comment (AGulev) [inline engine/gameobject/src/gameobject/gameobject.cpp:3245]: This is the fix.

There are 3 cases:

1. Root -> parent

```cpp
child->m_Parent == INVALID_INSTANCE_INDEX
parent != 0
```

This is the important issue #12247 path. Unlink() is not called because the child is already under root, so any stale m_SiblingIndex survives unless we clear it here.

2. Parent A -> parent B

```cpp
child->m_Parent != INVALID_INSTANCE_INDEX
parent != 0
```

Unlink() runs first and already clears m_SiblingIndex. The new clear is redundant here, but harmless. Then insertion under parent B either leaves it invalid if B has no children, or sets it to B’s old first child.

3. Parent -> root

```cpp
child->m_Parent != INVALID_INSTANCE_INDEX
parent == 0
```

Unlink() runs first and clears m_SiblingIndex. The new clear is again redundant. Then SetParent() removes/reinserts the child in m_LevelIndices[0].

**Review by JCash — APPROVED** [review]
