### PR TITLE
Fix WebGPU detection

### LINKED ISSUE #10368: [1.9.8] WebGPU crashes on start on Safari
**Describe the bug (REQUIRED)**
A WebGPU + WebGL build crashes on start on Safari. On Chrome it runs fine.

**To Reproduce (REQUIRED)**
1. Enabled WebGL + WebGPU from app manifest
2. Build app for web
3. Try to open app in Safari

**Expected behavior (REQUIRED)**
The engine should boot

**Defold version (REQUIRED):**
  - Version 1.9.8

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Safari 18.0.1 (20619.1.26.31.7)
 - Device: M1 Macbook Air

**Logs (OPTIONAL):**
Image

[crash.zip](https://github.com/user-attachments/files/19403115/crash.zip)

**Workaround (OPTIONAL):**
Use a WebGL-only build instead

### PR DESCRIPTION
**Pull request by ekharkunov**
Fixes #10368 

### Technical changes

Were 2 issues:
1. `IsSupported()` function always return true
2. If several graphics adapters can be supported by platfrom and the first adapter isn't supported by device - that adapter is always selected.

Screenshot 2025-03-25 at 21 49 52

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   3. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/graphics/src/graphics.cpp [hunk 1]
```diff
@@ -75,12 +75,12 @@ namespace dmGraphics
...
     {
         GraphicsAdapter* next     = g_adapter_list;
-        GraphicsAdapter* selected = next;
+        GraphicsAdapter* selected = 0x0;
 
         while(next)
         {
             bool is_supported = next->m_IsSupportedCb();
-            if (next->m_Priority < selected->m_Priority && is_supported)
+            if (is_supported && ((selected != 0x0 && next->m_Priority < selected->m_Priority) || selected == 0x0))
```
Comment (ekharkunov) [inline engine/graphics/src/graphics.cpp:83]: In case if first graphics adapter is not supported by platform but has highest priority - it was selected.
Current case:
1. First adapter is WebGPU.
2. WebGPU has priority 0, OpenGL - 1
3. WebGPU isn't supported by browser.
4. OpenGL can't be selected because it has lower priority.
5. As result - error at runtime.

File: engine/graphics/src/webgpu/graphics_webgpu.cpp [hunk 2]
```diff
@@ -1176,7 +1176,13 @@ static HContext WebGPUNewContext(const ContextParams& params)
 static bool WebGPUIsSupported()
 {
     TRACE_CALL;
-    return true;
+    return MAIN_THREAD_EM_ASM_INT({
```
Comment (ekharkunov) [inline engine/graphics/src/webgpu/graphics_webgpu.cpp:1179]: Use `MAIN_THREAD_EM_ASM_INT` here just in case if web build will support multithreading in the future. Because `Module.hasWebGPUSupport()` manipulates DOM tree (creates temp canvas and tries obtain context) so need to run in main thread.

**Review by Jhonnyg — APPROVED** [review]
