### PR TITLE
Force 3D physics body activation to wake it up

### LINKED ISSUE #6576: physics.wakeup() doesn't work for a kinematic collision object in 3D
**Describe the bug (REQUIRED)**
Every 3 seconds a kinematic body goes to sleepeng and `physics.wakeup()` call doesn't help. It wakes up only by collisions or meaningful movement with a speed more than 0.3 units per second.

**To Reproduce (REQUIRED)**
1. Place a 3D kinematic collision object on the scene.
2. Call `physics.wakeup(collision_url)` in the `update()` function.

**Expected behavior (REQUIRED)**
The collision object will never fall asleep.

**Defold version (REQUIRED):**
  - Version 1.2.192

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: macOS Big Sur
 - Device: Macbook Air M1

**Workaround (OPTIONAL):**
Periodically pushing the kinematic body just for awakening the first one.

### PR DESCRIPTION
**Pull request by aglitchman**
This fixes an issue where `physics.wakeup(url)` didn't wake up dynamic 3D physics bodies.

Fixes https://github.com/defold/defold/issues/6576

### CODE REVIEW

File: engine/physics/src/physics/physics_3d.cpp [hunk 1]
```diff
@@ -1017,7 +1017,7 @@ namespace dmPhysics
     void Wakeup3D(HCollisionObject3D collision_object)
     {
         btCollisionObject* co = GetCollisionObject(collision_object);
-        co->activate();
+        co->activate(true);
```
Comment (JCash) [inline engine/physics/src/physics/physics_3d.cpp:1020]: +1
