### PR TITLE
Set window background color

### LINKED ISSUE #5419: Improve launching on desktop (DEF-3442)
Right now even if your main collection is empty the game hangs on a blank white screen (at least on windows) for a few moments

2017-10-07 18_22_27-defold editor 2 0 - project

A black screen instead would be better, what would be best is if we had some control over what is displayed at this point such as an image over a solid color, and making the window appear to hang (windows wait cursor icon shows instead of normal cursor) is also bad because along with the white window it gives a bad first impression.

fmksr

If, in the bundle process, you could hex edit the binary so that the default "GLFW Window" text is the game project title text that would also be useful. Or just edit the source/binary for GLFW so that this text is not displayed (no text) or displays something more useful such as "Loading..."

### LINKED ISSUE #6142: Black screen blinking on iOS with a custom LaunchScreen.storyboard
**Describe the bug (REQUIRED)**
Launch screen `blinks to the black screen and then` fades to the game screen with the ‘clear_color’ background.

**To Reproduce (REQUIRED)**
Bundle the repro project to iOS device and run.

**Expected behavior (REQUIRED)**
Launch screen fades to the game screen with the ‘clear_color’ background.

**Defold version (REQUIRED):**
  - Defold 1.2.186

**Platforms (REQUIRED):**
 - Platforms: iOS
 - OS: iOS 15
 - Device: iPhone 12 mini

**Minimal repro case project (OPTIONAL):**
[ios-launch-screen-black-blink.zip](https://github.com/defold/defold/files/7429106/ios-launch-screen-black-blink.zip)

**Workaround (OPTIONAL):**
Use the black launch screen only?

**Screenshots (OPTIONAL):**
https://user-images.githubusercontent.com/4752473/139141693-fe007b56-3d7c-4f97-b408-5ab3a245a8b9.MP4

**Additional context (OPTIONAL):**
What If we add the backgroundColor with clear_color value to the [ViewController.m](https://github.com/defold/defold/blob/3e5fda5b774763bf1390b32ad7246024a8a3dc25/engine/glfw/lib/ios/app/ViewController.m) view? This will indirectly fix the situation if this blink is the black color of the UIWindow, but I don't now exactly what is it.

### PR DESCRIPTION
**Pull request by britzl**
Fixes #5419

### CODE REVIEW

File: engine/glfw/lib/ios/app/ViewController.m [hunk 1]
```diff
@@ -261,6 +261,10 @@ void _glfwPlatformSetViewType(int view_type)
     g_view_type = view_type;
 }
 
+void _glfwPlatformSetWindowBackgroundColor(int color)
+{
+}
+
```
Comment (AGulev) [inline engine/glfw/lib/ios/app/ViewController.m:267]: hmm, meybe we an change color here as well? https://github.com/defold/defold/issues/6142

Comment (britzl) [reply engine/glfw/lib/ios/app/ViewController.m:267]: Yes, absolutely! I've so far only focused on Windows in this PR

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 2]
```diff
@@ -1178,3 +1178,11 @@ void _glfwPlatformSetViewType(int view_type)
 GLFWAPI void glfwAccelerometerEnable()
 {
 }
+
+void _glfwPlatformSetWindowBackgroundColor(int color)
```
Comment (JCash) [inline engine/glfw/lib/cocoa/cocoa_window.m:1182]: I would use an "unsigned int" to assure there's no strange things happening with the signed bit.
It might work well, since we currently don't use alpha. (why not?)

File: engine/glfw/lib/ios/app/ViewController.m (hunk 1 above)
Comment (JCash) [reply engine/glfw/lib/ios/app/ViewController.m:273]: color + colour :)

File: engine/glfw/lib/ios/app/ViewController.m [hunk 3]
```diff
@@ -261,6 +261,16 @@ void _glfwPlatformSetViewType(int view_type)
     g_view_type = view_type;
 }
 
+void _glfwPlatformSetWindowBackgroundColor(int color)
+{
+    float r = (color & 0xff) / 255.0f;
+    float g = ((color >> 8) & 0xff) / 255.0f;
+    float b = ((color >> 16) & 0xff) / 255.0f;
+    UIColor *colour = [[UIColor alloc]initWithRed:r green:g blue:b alpha:1.0];
```
Comment (JCash) [inline engine/glfw/lib/ios/app/ViewController.m:269]: Why not set the alpha if the user specified it?

File: engine/glfw/lib/win32/win32_window.c [hunk 4]
```diff
@@ -2029,3 +2028,12 @@ void _glfwPlatformSetViewType(int view_type)
 GLFWAPI void glfwAccelerometerEnable()
 {
 }
+
+void _glfwPlatformSetWindowBackgroundColor(int color)
+{
+    int r = color & 0xff;
+    int g = (color >> 8) & 0xff;
+    int b = (color >> 16) & 0xff;
+    HBRUSH brush = CreateSolidBrush(RGB(r, g, b));
```
Comment (JCash) [inline engine/glfw/lib/win32/win32_window.c:2037]: Alpha?

**Review by JCash — CHANGES_REQUESTED** [review]

File: engine/glfw/lib/x11/x11_window.c [hunk 5]
```diff
@@ -2058,3 +2058,23 @@ GLFWAPI void glfwAccelerometerEnable()
...
+
+void _glfwPlatformSetWindowBackgroundColor(unsigned int color)
+{
+    // red, green, blue in the 0-65536 range
+    // the values will be mapped to the correct range based on display properties
+    XColor xc;
+    xc.red = (color & 0xff) << 8;
+    xc.green = ((color >> 8) & 0xff) << 8;
+    xc.blue = ((color >> 16) & 0xff) << 8;
+    // XSetWindowBackground(_glfwLibrary.display, _glfwWin.window, xc.pixel);
```
Comment (JCash) [inline engine/glfw/lib/x11/x11_window.c:2070]: dead code?

File: engine/graphics/src/graphics.h [hunk 6]
```diff
@@ -300,6 +300,9 @@ namespace dmGraphics
         bool                    m_PrintDeviceInfo;
 
         bool                    m_HighDPI;
+
+        // Window background color, RGBA 0xAAGGBBRR
```
Comment (JCash) [inline engine/graphics/src/graphics.h:304]: Or perhaps "0x00GGBBRR" since the alpha isn't used?

**Review by JCash — DISMISSED** [review]

**Review by JCash — APPROVED** [review]

**Comment by astrochili** [comment]
By the way, what else is needed to accept this request? :)

**Comment by britzl** [comment]
> By the way, what else is needed to accept this request? :)

I needed some verification for Linux, and this was provided recently on Discord. merging now.
