### PR TITLE
Show errors from exceptions thrown during tile source texture layout

### LINKED ISSUE #11400: Grid error exceeded
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2025-09-08T11:24:55.343573</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7c81792859a6da7f7401c0ac37a4cc83bb500ff6</td></tr>
<tr><td>Defold engine sha</td><td>7c81792859a6da7f7401c0ac37a4cc83bb500ff6</td></tr>
<tr><td>Defold version</td><td>1.11.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7e1569131b0b40dda8119606b3dd6a12"'>7e1569131b0b40dda8119606b3dd6a12</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 4070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 572.83</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Fixes #11400.

### CODE REVIEW

File: editor/src/clj/editor/tile_source.clj [hunk 1]
```diff
@@ -675,7 +676,12 @@
   (output tile-source-attributes g/Any :cached produce-tile-source-attributes)
   (output tile->collision-group-node g/Any :cached produce-tile->collision-group-node)
 
-  (output layout-result g/Any :cached (g/fnk [tile-source-attributes] (texture-set-gen/calculate-layout-result tile-source-attributes)))
+  (output layout-result g/Any :cached
+          (g/fnk [_node-id image-resource tile-source-attributes]
+            (try
+              (texture-set-gen/calculate-layout-result tile-source-attributes)
+              (catch CompileExceptionError error
+                (g/->error _node-id :image :fatal image-resource (ex-message error))))))
```
Comment (matgis) [inline editor/src/clj/editor/tile_source.clj:684]: The Java method we call to generate a tile source grid layout throws a `CompileExceptionError` if the resulting texture image exceeds the allowed dimensions. We now catch it convert it to an `ErrorValue` that will show up in the Scene View and as a clickable error in the Build Errors view.

**Review by JosephFerano — APPROVED** [review]
image

LGTM
