### PR TITLE
Fixed models not rendering in the editor in some situations

### LINKED ISSUE #10545: The editor does not show models if samplers filter is set as default
The editor does not show models if samplers filter is set as `default` value in the material. But all ok in runtime.
Other components are shown when setting the `default` value in the material. 

https://github.com/user-attachments/assets/7eec78d1-f9f7-4d5f-8390-34325e65216d

<hr/>

<table>
<tr><td>Build time</td><td>2025-04-14T16:43:16.224873</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>591eb496d52f4140bc2c7de547131f1b9408b9b4</td></tr>
<tr><td>Defold engine sha</td><td>a8219fe5a1973a83341334af50017005f34bbb1f</td></tr>
<tr><td>Defold version</td><td>1.10.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.85</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
* Fixed an issue where model materials whose texture samplers were configured to use the project default filtering setting would not render in the editor viewport.
* Fixed an issue where model materials whose shaders used attributes that were not declared in the material or present in the mesh data would not render in the editor viewport.

Fixes #10545

### Technical changes
* The `:settings` output of the `Project` node will now output default settings if the `game.project` resource has not been loaded yet.
* The `:samplers` output of `Material` nodes will now resolve the `:filter-mag` and `:filter-min` settings to the project default filtering settings when set to `:filter-mode-mag-default` or `:filter-mode-min-default`, respectively.
* The `:mag-filter` and `:min-filter` in the map returned by `material/sampler->tex-params` will now always have valid default GL filter modes rather than `nil`.

### CODE REVIEW

File: editor/src/clj/editor/graphics.clj [hunk 1]
```diff
@@ -1137,18 +1147,23 @@
...
+                      attribute-byte-offset put-attribute-bytes!
+                      (fn renderable-data->attribute-bytes [renderable-data]
+                        (let [vertex-count (count (:position-data renderable-data))
+                              attribute-bytes (get (:vertex-attribute-bytes renderable-data) name-key default-attribute-bytes)]
+                          ;; Clamp the buffer if the container format is smaller than specified in the material
+                          (if (> (count attribute-bytes) attribute-byte-count-max)
+                            (let [attribute-bytes-clamped (byte-array attribute-byte-count-max)]
+                              (System/arraycopy attribute-bytes 0 attribute-bytes-clamped 0 attribute-byte-count-max)
+                              (repeat vertex-count attribute-bytes-clamped))
+                            (repeat vertex-count attribute-bytes)))))))
```
Comment (matgis) [inline editor/src/clj/editor/graphics.clj:1166]: Mostly an indentation change from introducing the surrounding `let`, but we now use the `default-attribute-bytes` if we cannot find any attribute bytes in the `renderable-data`.

File: editor/src/clj/editor/material.clj [hunk 2]
```diff
@@ -78,7 +78,7 @@
 (defn- build-target-attributes [attribute-infos]
   (mapv graphics/attribute-info->build-target-attribute attribute-infos))
 
-(g/defnk produce-base-pb-msg [name vertex-program fragment-program vertex-constants fragment-constants samplers tags vertex-space max-page-count]
+(g/defnk produce-base-pb-msg [name vertex-program fragment-program vertex-constants fragment-constants ^:raw samplers tags vertex-space max-page-count]
```
Comment (matgis) [inline editor/src/clj/editor/material.clj:81]: Use the `^:raw` property value that may contain `:filter-mode-mag-default` or `:filter-mode-min-default` values when building, editing and saving.

The protobuf form editor is a bit inflexible in how it can present data for editing, so using the `^:raw` tag was the easiest way to separate uses of the property value and the newly introduced output that resolve the sampler filter modes to the the `game.project` setting.

The alternative would be to rename the output, but it is used in a bunch of places, including in the editor extensions.

File: editor/src/clj/editor/material.clj [hunk 3]
```diff
@@ -439,21 +459,21 @@ there is no way a user can know what the generated id will be for older shaders.
...
+    GL2/GL_NEAREST_MIPMAP_LINEAR))
 
 (defn- filter-mode-mag->gl [filter-mag default-tex-params]
   (case filter-mag
-    :filter-mode-mag-default (:mag-filter default-tex-params)
+    :filter-mode-mag-default (or (:mag-filter default-tex-params) GL2/GL_LINEAR)
     :filter-mode-mag-nearest GL2/GL_NEAREST
     :filter-mode-mag-linear GL2/GL_LINEAR
-    nil))
+    GL2/GL_LINEAR))
```
Comment (matgis) [inline editor/src/clj/editor/material.clj:476]: Always produce a valid default from these. `GL_LINEAR` is the default filtering mode in OpenGL.

File: editor/src/clj/editor/material.clj [hunk 4]
```diff
@@ -556,6 +576,7 @@ there is no way a user can know what the generated id will be for older shaders.
 
   (output form-data g/Any :cached produce-form-data)
 
+  (input default-sampler-filter-modes g/Any)
```
Comment (matgis) [inline editor/src/clj/editor/material.clj:579]: We get this input from the `Project` node now. It looks something like this:
```clj
{:filter-mode-mag-default :filter-mode-mag-nearest
 :filter-mode-min-default :filter-mode-min-nearest-mipmap-nearest}
```

File: editor/src/clj/editor/material.clj [hunk 5]
```diff
@@ -566,27 +587,29 @@ there is no way a user can know what the generated id will be for older shaders.
...
+        vertex-program (resolve-resource :vertex-program)
+        fragment-program (resolve-resource :fragment-program)
+        vertex-constants (render-program-utils/constants->editable-constants :vertex-constants)
+        fragment-constants (render-program-utils/constants->editable-constants :fragment-constants)
+        attributes (attributes->editable-attributes :attributes)
+        name :name
+        samplers (render-program-utils/samplers->editable-samplers :samplers)
+        tags :tags
+        vertex-space :vertex-space
+        max-page-count :max-page-count))))
```
Comment (matgis) [inline editor/src/clj/editor/material.clj:612]: Indentation change from adding the `:default-sampler-filter-modes` connection from the `Project` node.

File: editor/src/clj/editor/game_project_core.clj [hunk 6]
```diff
@@ -24,7 +24,7 @@
 
 (def meta-settings (:settings basic-meta-info))
 
-(defn default-settings []
+(def default-settings
```
Comment (matgis) [inline editor/src/clj/editor/game_project_core.clj:27]: Changed this from a function to a constant since it will produce the same value every time.

**Review by vlaaad — APPROVED** [review]
LGTM! Ship it!
