### PR TITLE
Editor: Ensure correct numeric types in settings-based file formats

### LINKED ISSUE #9169: Exception thrown when editing integer value in `game.project`
**Describe the bug (REQUIRED)**
Editing or resetting an integer field in a settings-based file format such as `game.project` throws an exception. This regression was introduced by #9081.

**To Reproduce (REQUIRED)**
1. Open `game.project` in the editor.
2. Go to the HTML 5 section.
3. Type a new value into the Heap Size field and press Enter.

**Expected behavior (REQUIRED)**
The field accepts the new value.

### PR DESCRIPTION
**Pull request by matgis**
This PR ensures we always use 32-bit integer and floating point values for numeric settings inside settings-based file formats. Before this change, it was inconsistent, and editing an integer field would throw an exception due to a type mismatch between the default, read as a 64-bit `long` from an `.edn` file, and the parsed 32-bit `int` produced by the text field. The mismatch caused us to try to replace the `StringConverter` we configured for the default `long` value with a different `StringConverter` configured to handle `int` values for the edited field, which isn't allowed.

The change ensures we use 32-bit numbers throughout all interactions with settings files.

Fixes #9169

### CODE REVIEW

File: editor/src/clj/editor/settings_core.clj [hunk 1]
```diff
@@ -175,39 +177,51 @@
...
+(defn- ensure-type-defaults [meta-info]
+  (update meta-info :settings
+          (fn [settings]
+            (mapv (fn [{:keys [type] :as meta-setting}]
+                    (update meta-setting :default
+                            (fn [default]
+                              (if (some? default)
+                                (sanitize-default default type)
+                                (type-defaults type)))))
+                  settings))))
```
Comment (matgis) [inline editor/src/clj/editor/settings_core.clj:198]: Instead of just adding missing type defaults, we now sanitize the defaults to ensure they have the correct numeric types.

File: editor/src/clj/editor/settings_core.clj [hunk 2]
```diff
@@ -175,39 +177,51 @@
...
-                    settings))))
+  (update meta-info :settings
+          (fn [settings]
+            (mapv (fn [meta-setting]
+                    (if (contains? meta-setting :options)
+                      (assoc meta-setting
+                        :from-string #(parse-setting-value meta-setting %)
+                        :to-string #(render-raw-setting-value meta-setting %))
+                      meta-setting))
+                  settings))))
```
Comment (matgis) [inline editor/src/clj/editor/settings_core.clj:211]: Indentation change due to cleanup:  Use `update` and `mapv` instead of `update-in` and `map`.

File: editor/src/clj/editor/settings_core.clj [hunk 3]
```diff
@@ -175,39 +177,51 @@
...
-                          (dissoc meta-setting :from-string :to-string))
-                        meta-setting))
-                    settings))))
+  (update meta-info :settings
+          (fn [settings]
+            (mapv (fn [meta-setting]
+                    (if (contains? meta-setting :options)
+                      (dissoc meta-setting :from-string :to-string)
+                      meta-setting))
+                  settings))))
```
Comment (matgis) [inline editor/src/clj/editor/settings_core.clj:220]: Indentation change due to cleanup:  Use `update` and `mapv` instead of `update-in` and `map`.

**Review by britzl — APPROVED** [review]
