### PR TITLE
Disable Show/Hide Selected Objects command when nothing is selected

### LINKED ISSUE #8128: Show/Hide Selected Objects is producing error, when no objects are selected.
There is a problem, when using Ctrl+E shortcut or option View->Show/Hide Selected Objects, when no objects are created, e.g. when script editor is opened. This is obviously a not an intended context for this option, so it's a low priority issue, but worth noting.

### Expected behaviour
No error.

### Actual behaviour
Error is shown.

### Steps to reproduce
1. Open Defold and create and open a script file.
2. When in Script Editor, use shortcut Ctrl+E or option View->Show/Hide Selected Objects.

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-06T10:00:24.855519</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3584a3360b63a831529a2df7de0cb0c715374cc0</td></tr>
<tr><td>Defold engine sha</td><td>d9e9c49ab946c058f29a8b688c862d70f30e9c43</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-86-generic</td></tr>
<table>

### LINKED ISSUE #8210: Command+E - Error
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-24T14:31:10.014593</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b364f346962cf24b6845a52c0c97beb5deb7a8f1</td></tr>
<tr><td>Defold engine sha</td><td>a90c50928623cf23b3687a7eec05972d11427202</td></tr>
<tr><td>Defold version</td><td>1.6.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3cb6e896ec9a4462b266ff1bb8002741"'>3cb6e896ec9a4462b266ff1bb8002741</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.1</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
The **Show/Hide Selected Objects** command is now disabled unless something is selected. Invoking it with no selection used to cause an error.

Fixes #8128
Fixes #8210

### CODE REVIEW

File: editor/src/clj/editor/debug_view.clj [hunk 1]
```diff
@@ -47,7 +47,7 @@
 (def ^:private break-label "Break")
 (def ^:private continue-label "Continue")
 (def ^:private detach-debugger-label "Detach Debugger")
-(def ^:private start-debugger-label "Start / Attach")
+(def ^:private start-debugger-label "Start/Attach")
```
Comment (matgis) [inline editor/src/clj/editor/debug_view.clj:50]: Unrelated: Fixed inconsistent spacing around slash. I checked a bunch of other applications, and apparently there shouldn't be spaces around the slash when used like this.

File: editor/src/clj/editor/scene_visibility.clj [hunk 2]
```diff
@@ -241,8 +241,11 @@
   (run [scene-visibility] (hide-outline-name-paths! scene-visibility (g/node-value scene-visibility :unselected-hideable-outline-name-paths))))
 
 (handler/defhandler :hide-toggle-selected :workbench
-  (active? [scene-visibility evaluation-context] true)
-  (enabled? [scene-visibility evaluation-context] true)
+  (active? [scene-visibility evaluation-context]
+           (g/node-value scene-visibility :active-scene-resource-node evaluation-context))
+  (enabled? [scene-visibility evaluation-context]
+            (or (g/node-value scene-visibility :selected-hideable-outline-name-paths evaluation-context)
+                (g/node-value scene-visibility :selected-showable-outline-name-paths evaluation-context)))
```
Comment (matgis) [inline editor/src/clj/editor/scene_visibility.clj:248]: The command shouldn't be enabled unless something is selected, as invoking it will cause an error. We also hide the command unless we're in the Scene View.

**Review by vlaaad — APPROVED** [review]
LGTM!
