### PR TITLE
Fix bug when `Display->Fullscreen` has no effect

### LINKED ISSUE #9150: Display -> Fullscreen has no effect
I know Defold has a problematic history with the built-in `game.project -> Display -> Fullscreen` setting. 
Since GLFW is updated for MacOS, I would like to give it a try, but it has no effect when building with Vulkan or OpenGL. 
I guess this is a [known issue](https://github.com/defold/defold/issues/8100#issuecomment-1751112437), but as a friendly reminder, I want to open an issue. 

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-29T07:36:54.365170</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>605867c347e5dc4b2d8ebf6871c61018133fa69e</td></tr>
<tr><td>Defold engine sha</td><td>605867c347e5dc4b2d8ebf6871c61018133fa69e</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Fixed issue when `Display->Fullscreen` has no effect on macOS. 

Fix https://github.com/defold/defold/issues/9150

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/platform/src/platform_window_glfw3.cpp [hunk 1]
```diff
@@ -186,8 +186,14 @@ namespace dmPlatform
...
 
+        GLFWmonitor* fullscreen_monitor = NULL;
+        if (params.m_Fullscreen)
+        {
+            fullscreen_monitor = glfwGetPrimaryMonitor();
+        }
+
         // Note: We can't create a 0x0 window
-        wnd->m_AuxWindow = glfwCreateWindow(1, 1, "aux_window", NULL, wnd->m_Window);
+        wnd->m_AuxWindow = glfwCreateWindow(1, 1, "aux_window", fullscreen_monitor, wnd->m_Window);
```
Comment (AGulev) [inline engine/platform/src/platform_window_glfw3.cpp:196]: Moving from GLFW 2 to 3:
https://www.glfw.org/docs/latest/moving_guide.html#moving_monitor

**Review by britzl — APPROVED** [review]
