### PR TITLE
Setting 'highest available' opengl ctx is not supported on osx

### LINKED ISSUE #9716: gdc-macos v1.9.5  fails to run
This was fixed a few times before but comes back again.

https://github.com/defold/defold/issues/8805
https://github.com/defold/defold/issues/8564

```
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
[1]    1435 segmentation fault  gdc-macos
```

```
0   libsystem_platform.dylib      	    0x7ff802208b32 _platform_strlen + 18
1   gdc-macos1                    	       0x100dfc2a7 dmGraphics::OpenGLNewContext(dmGraphics::ContextParams const&) + 263
2   gdc-macos1                    	       0x100dd11df main + 255
3   dyld                          	       0x2010bc345 start + 1909
```

<hr/>

<table>
<tr><td>Build time</td><td>2024-11-09T09:12:50.952433</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>4f13aa283b0964053981abb3d43d4569676304da</td></tr>
<tr><td>Defold engine sha</td><td>4f13aa283b0964053981abb3d43d4569676304da</td></tr>
<tr><td>Defold version</td><td>1.9.5</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.7.1</td></tr>
<table>

### PR DESCRIPTION
**Pull request by Jhonnyg**
Fixed an issue where projects using the "use highest available" opengl version hint on OSX caused runtime crashes. Using highest available version on OSX is not supported, so we fallback to the default version in that case instead.

Fixes #9716

### CODE REVIEW

File: engine/platform/src/platform_window_opengl.h [hunk 1]
```diff
@@ -23,7 +23,15 @@ namespace dmPlatform
...
-        if (version == 0 ||                                    // Highest available
+
+        bool use_highest_version_supported = true;
+
+        // Osx doesn't support using the "highest version available"
+    #ifdef __MACH__
+        use_highest_version_supported = false;
+    #endif
+
+        if (version == 0 && use_highest_version_supported ||   // Highest available
```
Comment (JCash) [inline engine/platform/src/platform_window_opengl.h:34]: Perhaps an extra () to just make it a bit clearer when reading.

**Review by JCash — DISMISSED** [review]
