### PR TITLE
[DEFEDIT] Fix slowdown when editing atlas animation properties

### LINKED ISSUE #5755: Editor keeps freezing
**Describe the bug (REQUIRED)**
The editor freezes whenever i try to open and atlas file or change any properties within the atlas file including animation groups, FPS etc. Editor is also freezing when opening collection files. scripts also take a while to load but much faster then the others

**To Reproduce (REQUIRED)**
Steps to reproduce the behaviour:
 1.Click on atlas file
 2. editor not responding
 3. 50 seconds later
 4. opens atlas
 5.change anything and the editor starts not responding

**Expected behaviour (REQUIRED)**
I do not expect the editor to be this slow on a
[Desktop game.zip](https://github.com/defold/defold/files/6330429/Desktop.game.zip)
 gaming PC with all requirements met.

**Defold version (REQUIRED):**
  - I download through steam I believe it is the latest version  

**Platforms (REQUIRED):**
Windows 10

**Additional context (OPTIONAL):**
I have attached my game, pretty early stages so it should be to big

### PR DESCRIPTION
**Pull request by matgis**
Partially fixes #5755.

### User-facing changes
Editing properties on an animation inside an atlas would invalidate the atlas layout, despite the fact that the animation properties cannot affect the layout of the atlas.

### Technical changes
* Refactored connections between `AltasNode`, `AtlasImage`, and `AtalsAnimationNode` to break dependencies between animation properties and the generated layout.
* Re-wrote successor query functions in `dev.clj` to more accurately report graph dependencies.

### CODE REVIEW

File: editor/src/clj/editor/atlas.clj [hunk 1]
```diff
@@ -473,15 +486,66 @@
 (defn- call-generator [generator]
   ((:f generator) (:args generator)))
 
-(defn- generate-packed-image [{:keys [_node-id image-resources texture-set-data-generator]}]
+(defn- generate-packed-image [{:keys [_node-id image-resources layout-data-generator]}]
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj:489]: We don't need the fully compiled `TextureSetResult` in order to generate the packed image - only the layout-related parts of it.

File: editor/src/clj/editor/atlas.clj [hunk 2]
```diff
@@ -530,28 +594,18 @@
...
-                                                                             (keep (fn [[v name]]
-                                                                                     (validation/prop-error :fatal _node-id :layout-result validation/prop-negative? v name)))
-                                                                             not-empty)]
-                                                        (g/error-aggregate errors))
-                                                      {:f    generate-texture-set-data
-                                                       :args (assoc args
-                                                               :workspace (resource/workspace resource))})))
-
-  (output texture-set-data g/Any               :cached (g/fnk [texture-set-data-generator] (call-generator texture-set-data-generator)))
-  (output layout-size      g/Any               (g/fnk [texture-set-data] (:size texture-set-data)))
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj:549]: The `texture-set-data-generator` has now become the `layout-data-generator` below. The `texture-set-data` and `layout-size` implementations have changed and are a few lines down from here.

File: editor/src/clj/editor/atlas.clj [hunk 3]
```diff
@@ -530,28 +594,18 @@
...
+
+  (output layout-data-generator g/Any          produce-layout-data-generator)
+  (output texture-set-data g/Any               :cached produce-texture-set-data)
+  (output layout-data      g/Any               :cached (g/fnk [layout-data-generator] (call-generator layout-data-generator)))
+  (output layout-size      g/Any               (g/fnk [layout-data] (:size layout-data)))
   (output texture-set      g/Any               (g/fnk [texture-set-data] (:texture-set texture-set-data)))
-  (output uv-transforms    g/Any               (g/fnk [texture-set-data] (:uv-transforms texture-set-data)))
-  (output layout-rects     g/Any               (g/fnk [texture-set-data] (:rects texture-set-data)))
+  (output uv-transforms    g/Any               (g/fnk [layout-data] (:uv-transforms layout-data)))
+  (output layout-rects     g/Any               (g/fnk [layout-data] (:rects layout-data)))
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj:606]: We don't need the full `texture-set-data` for this, the `layout-data` (which is not dependent on the animation metadata) will suffice.

File: editor/src/clj/editor/atlas.clj [hunk 4]
```diff
@@ -530,28 +594,18 @@
...
 
-  (output packed-image-generator g/Any (g/fnk [_node-id extrude-borders image-resources inner-padding margin texture-set-data-generator]
+  (output packed-image-generator g/Any (g/fnk [_node-id extrude-borders image-resources inner-padding margin layout-data-generator]
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj:608]: Similarly, here's the heart of the matter - we don't need the fully-formed `TextureSetResult` from the `texture-set-data-generator` (which, remember, is dependent on the animation metadata) here. We can produce the image as long as we have the `layout-data` (which is not dependent on the animation metadata).

File: editor/src/clj/editor/atlas.clj [hunk 5]
```diff
@@ -791,16 +845,16 @@
   (active? [selection] (move-active? selection))
   (enabled? [selection] (let [node-id (selection->image selection)
                               parent (core/scope node-id)
-                              children (vec (g/node-value parent :nodes))
-                              node-child-index (.indexOf ^java.util.List children node-id)]
+                              ^List children (vec (g/node-value parent :nodes))
+                              node-child-index (.indexOf children node-id)]
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj:849]: Fixed reflection warning.

File: editor/src/clj/editor/atlas.clj [hunk 6]
```diff
@@ -791,16 +845,16 @@
...
   (run [selection] (move-node! (selection->image selection) -1)))
 
 (handler/defhandler :move-down :workbench
   (active? [selection] (move-active? selection))
   (enabled? [selection] (let [node-id (selection->image selection)
                               parent (core/scope node-id)
-                              children (vec (g/node-value parent :nodes))
-                              node-child-index (.indexOf ^java.util.List children node-id)]
+                              ^List children (vec (g/node-value parent :nodes))
+                              node-child-index (.indexOf children node-id)]
```
Comment (matgis) [inline editor/src/clj/editor/atlas.clj:858]: Fixed reflection warning.

File: editor/src/clj/editor/engine.clj [hunk 7]
```diff
@@ -208,24 +208,23 @@
       (fs/set-executable! engine-file)
       engine-file)))
 
-(defn- zip-entries! [zipfile]
+(defn- zip-entries! [^ZipFile zipfile]
```
Comment (matgis) [inline editor/src/clj/editor/engine.clj:211]: Fixed reflection warning.

File: editor/src/clj/editor/engine.clj [hunk 8]
```diff
@@ -208,24 +208,23 @@
...
   (enumeration-seq (.entries zipfile)))
 
 (defn- unpack-build-zip!
   [^File engine-archive dir]
   (with-open [zip-file (ZipFile. engine-archive)]
-    (doseq [entry (zip-entries! zip-file)]
+    (doseq [^ZipEntry entry (zip-entries! zip-file)]
```
Comment (matgis) [inline editor/src/clj/editor/engine.clj:217]: Fixed reflection warning.

File: editor/src/clj/editor/engine.clj [hunk 9]
```diff
@@ -208,24 +208,23 @@
...
             (.mkdirs saveFile))
           (let [parentDir (File. (.substring savePath 0 (.lastIndexOf savePath (int File/separatorChar))))
                 stream (.getInputStream zip-file entry)]
-            (if-not (.exists parentDir) (.mkdirs parentDir))
-            (clojure.java.io/copy stream saveFile)))
-      ))))
-
+            (when-not (.exists parentDir)
+              (.mkdirs parentDir))
+            (io/copy stream saveFile)))))))
```
Comment (matgis) [inline editor/src/clj/editor/engine.clj:227]: Fixed syntax. Also, we try to use `when` instead of `if` for side-effects. `ìf` should be seen as the ternary operator (I.e. `true ? 1 : 0`), because it always returns a value.

File: editor/src/clj/editor/gui.clj [hunk 10]
```diff
@@ -2992,7 +2992,7 @@
                               parent (core/scope selected-node-id)
                               node-child-index (g/node-value selected-node-id :child-index)
                               child-indices (g/node-value parent :child-indices)]
-                          (< node-child-index (dec (.size child-indices)))))
+                          (< node-child-index (dec (count child-indices)))))
```
Comment (matgis) [inline editor/src/clj/editor/gui.clj:2995]: Fixed reflection warning.

File: editor/src/clj/prof.clj [hunk 11]
```diff
@@ -24,10 +24,10 @@
   (future
     (try
       (.browse (Desktop/getDesktop) uri)
-      nil
       (catch Throwable error
         (println (str "Failed to open URI " uri))
-        (println (.getMessage error))))))
+        (println (.getMessage error)))))
+  nil)
```
Comment (matgis) [inline editor/src/clj/prof.clj:30]: This file contains profiling functions that are never called by the editor. This function was erroneously returning the `future` it created. Fixed to return `nil`.

**Review by JCash — APPROVED** [review]
