### PR TITLE
Fixed handling of log messages when the log system is shutting down

### LINKED ISSUE #7298: Crash in log system when shutting down the engine
A crash in the log system at address `0x38` and a cryptic message from the log system "Too many log connections opened" led us to investigate if there is an issue of logging messages while shutting down the log system.

By adding a unit test which spams messages while the log system is shut down, a crash was 100% reproducible.
(See PR)

### PR DESCRIPTION
**Pull request by JCash**
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/dlib/src/dlib/log.cpp [hunk 1]
```diff
@@ -189,24 +196,34 @@ static dmSocket::Result SendAll(dmSocket::Socket socket, const char* buffer, int
...
 static void dmLogUpdateNetwork()
 {
-    dmLogServer* self = g_dmLogServer;
-    if (self->m_ServerSocket == dmSocket::INVALID_SOCKET_HANDLE)
+    dmSocket::Socket server_socket = dmSocket::INVALID_SOCKET_HANDLE;
+    bool connections_full = false;
+    {
+        DM_SPINLOCK_SCOPED_LOCK(g_LogServerLock);
+        if (!IsServerInitialized())
+            return;
```
Comment (JCash) [inline engine/dlib/src/dlib/log.cpp:204]: Having locks sprinkled throughout the code isn't very nice looking, but we also want to avoid holding the lock for very long.

File: engine/dlib/src/dlib/log.cpp [hunk 2]
```diff
@@ -365,20 +409,22 @@ static void dmLogThread(void* args)
...
+        dmMessage::Dispatch(server->m_MessageSocket, dmLogDispatch, (void*) &run);
     }
 }
 
 void LogInitialize(const LogParams* params)
 {
     g_TotalBytesLogged = 0;
 
-    if (g_dmLogServer)
+    if (dmAtomicGet32(&g_LogServerInitialized) != 0)
```
Comment (JCash) [inline engine/dlib/src/dlib/log.cpp:420]: We introduce an atomic to hold the initialized state.

File: engine/dlib/src/dlib/log.cpp [hunk 3]
```diff
@@ -365,20 +409,22 @@ static void dmLogThread(void* args)
...
     {
         fprintf(stderr, "ERROR:DLIB: dmLog already initialized\n");
         return;
     }
 
+    dmSpinlock::Init(&g_LogServerLock);
```
Comment (JCash) [inline engine/dlib/src/dlib/log.cpp:426]: ...and a spin lock to make sure no one is logging/shutting down the log system at the same time.

File: engine/dlib/src/test/test_httpclient.cpp [hunk 4]
```diff
@@ -933,8 +933,9 @@ INSTANTIATE_TEST_CASE_P(dmHttpClientTest, dmHttpClientTest, jc_test_values_in(pa
 // NOTE: These buckets might expire. If so, we'll have to disable that server test
 const char* params_http_client_external_test[] = {  // They expire after a few days, but I keep it here in case you wish to test with it
 													// during development "https://hookb.in/je1lZ3X0ngTobX0plMME",
-                                                    "https://httpbin.org/post",
-                                                    "https://webhook.site/e22f2d03-abf4-4f23-a8dc-7e24126cefab"};
+                                                    //                    "https://webhook.site/e22f2d03-abf4-4f23-a8dc-7e24126cefab",
```
Comment (JCash) [inline engine/dlib/src/test/test_httpclient.cpp:936]: This server is constantly giving me grief, so I've now disabled it.

File: engine/dlib/src/test/test_log.cpp [hunk 5]
```diff
@@ -258,6 +259,51 @@ TEST(dmLog, TestCapture)
...
+
+    g_LogThreadWithLogCallsCount = 0;
+    dmLogRegisterListener(LogThreadWithLogCallsListener);
+
+    while (g_LogThreadWithLogCallsCount < 40)
+        dmTime::Sleep(1000);
+
+    dmLog::LogFinalize();
+
+    dmTime::Sleep(1000); // make sure we write some more logs
```
Comment (JCash) [inline engine/dlib/src/test/test_log.cpp:299]: Here we make sure we log a lot of info before and after the log system is initialized/finalized.

Without the fixes, it would crash on using the server pointer after deletion.

**Review by AGulev — DISMISSED** [review]
I'm not a pro here, it looks valid and covered with tests  
if server can be shutdown any time while we are working with it, we should be protective
