### PR TITLE
Registed exported symbols at the start of the gdc app

### LINKED ISSUE #8805: GDC Error macOS Sonoma
**Describe the bug**
Attempting to run the gdc-macos tool from the [1.8.0 Beta](https://forum.defold.com/t/defold-1-8-0-beta/76535/61) on macOS Sonoma results in the following error:

> ERROR:GRAPHICS: Could not install a graphics adapter. No compatible adapter was found.
> zsh: segmentation fault  gdc

It never launches and just exits to the command prompt.

**To Reproduce :**
1. Download [gdc-macos](https://github.com/defold/defold/releases/download/1.8.0-beta/gdc-macos) from the 1.8.0 beta release assets.
2. Release it from quarantine; > sudo xattr -r -d com.apple.quarantine ./gdc-macos
3. Set it to executable. > chmod +x ./gdc-macos
4. Run gdc-macos. > ./gdc-macos

**Expected behaviour:**
To launch the tiny window are return game controller data via the terminal.

**Defold version:**
  - 1.8.0 Beta
  - macOS Sonoma 14.4.1
  - MacBook Pro, M1 Pro, 32GB RAM

FWIW it seems similar to #8564 that I reported with the 1.6.4 release.

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/8805

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/tools/src/gdc/main.cpp [hunk 1]
```diff
@@ -32,6 +32,8 @@
 #include <hid/hid.h>
 #include <input/input_ddf.h>
 
+extern "C" void dmExportedSymbols();
```
Comment (JCash) [inline engine/tools/src/gdc/main.cpp:35]: In this release, we've removed the "magic" registering of exported symbols (that used c++ global constructors), in favor of actually calling this generated function.

It will help us support extensions on more languages+platforms.

**Review by ekharkunov — APPROVED** [review]
