### PR TITLE
Fixed a fullscreen issue for newer macOS versions

### LINKED ISSUE #7922: Fullscreen setting results in blank screen.
**Describe the bug**
Selecting fullscreen in the game.project Display settings results in a blank screen.

**To Reproduce**
1. Create a simple project with something visible on screen.
2. Select 'fullscreen' in game.project Display settings.
3. Build and run the project.
4. Stare a blank screen.

**Expected behavior**
The game should display as expected.

**Defold version**
  - Versions 1.4.8 and 1.5.0 beta.

**Platforms:**
 - Platforms: macOS
 - OS: Ventura 13.5.1
 - Device: MacBook Pro M1 Pro, 32GB RAM

[Test.zip](https://github.com/defold/defold/files/12448777/Test.zip)

### PR DESCRIPTION
**Pull request by JCash**
The issue was that on macOS Ventura, the fullscreen mode would not render anything as it got a window size of (0, 0).
We now detect this case and then use the window frame rectangle.

FIxes https://github.com/defold/defold/issues/7922

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 1]
```diff
@@ -191,13 +191,13 @@ static void LogGLError(GLint err, const char* fnname, int line)
     const char* error_str = "<unknown-gl-error>";
     switch(err)
     {
-        case GL_INVALID_ENUM: 
+        case GL_INVALID_ENUM:
```
Comment (JCash) [inline engine/graphics/src/opengl/graphics_opengl.cpp:194]: No changes, I merely removed the debug prints

**Review by britzl — APPROVED** [review]
