### PR TITLE
Fix missing animation preview overlay in atlas views

### LINKED ISSUE #9304: Animation preview in atlas not working anymore
When you select an animation in an atlas Outline and press space, the animation normally previews in the main pane. This does not happen anymore.

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-12T13:14:23.195847</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7e106914636fe4f22c967d7e297f4e24a26e0198</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
The animation preview overlay is now visible again in atlas views.

Fixes #9304.

### CODE REVIEW

File: editor/src/clj/editor/texture_set.clj [hunk 1]
```diff
@@ -265,9 +265,9 @@
 
 (defn- animation-frame->vertex-pos-uv
   [animation-frame world-transform]
-  (let [^double width (:width animation-frame)
-        ^double height (:height animation-frame)
-        frame-vertex-data (frame-vertex-data animation-frame width height)
+  (let [size [(:width animation-frame)
+              (:height animation-frame)]
+        frame-vertex-data (frame-vertex-data animation-frame size :pivot-center)
```
Comment (matgis) [inline editor/src/clj/editor/texture_set.clj:270]: I changed the argument list to `frame-vertex-data` in order to support pivot transformations, but apparently I missed this call.

**Review by vlaaad — APPROVED** [review]
Shipit!
