### PR TITLE
Correctly scale convex collision shapes in nested factory created game objects

### LINKED ISSUE #6373: Scaling .convexshapes
**Describe the bug (REQUIRED)**
Collision objects using .convexshape Collision Shapes are scaled incorrectly.

**To Reproduce (REQUIRED)**
Create a collection containing the collision shape with a collectionfactory with a scale other than 1.0:
`local game_object_ids = collectionfactory.create("/go#collectionfactory", nil, nil, nil, 0.5)`

**Expected behavior (REQUIRED)**
The collision shapes should scale without distorting.

**Defold version (REQUIRED):**
1.2.191

**Platforms (REQUIRED):**
 macOS.

**Minimal repro case project (OPTIONAL):**
[ScalingCustomCollisionShapes.zip](https://github.com/defold/defold/files/7992916/ScalingCustomCollisionShapes.zip)

**Additional context (OPTIONAL):**
The issue only seems to only apply when using collection factories. All these cases work as expected:
- Scale a collection containing the collision shape inside the editor.
- Scale a game object containing the collision shape inside the editor.
- Create a game object containing the collision shape with a factory with a scale other than 1.0.

### PR DESCRIPTION
**Pull request by britzl**
Child game objects containing convex collision shapes were not correctly scaled when created using a collection factory. Previously only the first four vertices of the shape were scaled. This works for a box shape but obviously not for a more complex shape.

Fixes #6373

### CODE REVIEW

File: engine/gameobject/src/gameobject/gameobject.cpp [hunk 1]
```diff
@@ -1255,21 +1255,6 @@ namespace dmGameObject
             }
         }
 
-        if (success)
```
Comment (britzl) [inline engine/gameobject/src/gameobject/gameobject.cpp:1258]: What's the point of doing this if we exit early in the lines below?

File: engine/physics/src/physics/physics_2d.cpp [hunk 2]
```diff
@@ -386,7 +386,7 @@ namespace dmPhysics
             else if (fix->GetShape()->GetType() == b2Shape::e_polygon) {
                 b2PolygonShape* pshape = (b2PolygonShape*)shape;
                 float s = object_scale / shape->m_creationScale;
-                for( int i = 0; i < 4; ++i)
+                for( int i = 0; i < b2_maxPolygonVertices; ++i)
```
Comment (britzl) [inline engine/physics/src/physics/physics_2d.cpp:389]: The fix

File: engine/gameobject/src/gameobject/gameobject.cpp [hunk 3]
```diff
@@ -1282,6 +1267,19 @@ namespace dmGameObject
             return false;
         }
 
+        // Update the transform for all parent-less objects
+        for (uint32_t i=0;i!=new_instances.Size();i++)
+        {
+            if (!GetParent(new_instances[i]))
+            {
+                new_instances[i]->m_Transform = dmTransform::Mul(transform, new_instances[i]->m_Transform);
+                dmLogInfo("CollectionSpawnFromDescInternal new_instances scale x: %f y: %f z: %f", new_instances[i]->m_Transform.GetScale().getX(), new_instances[i]->m_Transform.GetScale().getY(), new_instances[i]->m_Transform.GetScale().getZ());
```
Comment (JCash) [inline engine/gameobject/src/gameobject/gameobject.cpp:1276]: This log info feels a bit redundant imho.
If some issue pops up, we can debug it anyways.

**Review by JCash — CHANGES_REQUESTED** [review]

File: engine/gameobject/src/gameobject/gameobject.cpp (hunk 3 above)
Comment (britzl) [reply engine/gameobject/src/gameobject/gameobject.cpp:1276]: Oh, that's my debugging log! I will remove it!

**Review by JCash — APPROVED** [review]
