### PR TITLE
Issue-6551 Fix issue when `gui.get_flipbook()` returns empty string for a node created in the editor

### LINKED ISSUE #6551: gui.get_flipbook() return empty string for box created in editor
**Describe the bug (REQUIRED)**
gui.get_flipbook() return empty string for box created in editor,
but if set sprite with gui.play_flipbook() then gui.get_flipbook() return sprite name

**To Reproduce (REQUIRED)**
1. Create box in gui, set any sprite
2. in code write pprint(gui.get_flipbook(gui.get_node("box")))
3. in console see DEBUG:SCRIPT: hash: []

**Expected behavior (REQUIRED)**
should return name of current animation

**Defold version (REQUIRED):**
  Defold Engine 1.3.1 (06bc078)

**Platforms (REQUIRED):**
 - Platforms:  Windows
 - OS:  Windows 10

**Additional context (OPTIONAL):**
But if in code set up gui.play_flipbook(node, animation) then gui.get_flipbook() return correct animation name

### PR DESCRIPTION
**Pull request by AGulev**
Fix issue when `gui.get_flipbook()` returns empty string for a box node created in the editor.

Fix https://github.com/defold/defold/issues/6551

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_gui.cpp [hunk 1]
```diff
@@ -306,9 +306,11 @@ namespace dmGameSystem
                     // animation. Instead we can immediately cancel the animation and the node will
                     // still have the correct image.
                     // By doing this we'll not take up an animation slot (there's a max animation cap).
+                    // Even though we cancel animation we still need flipbook hash:
+                    // https://github.com/defold/defold/issues/6551
                     if (dmGui::GetNodeAnimationFrameCount(scene, n) == 1)
                     {
-                        dmGui::CancelNodeFlipbookAnim(scene, n);
+                        dmGui::CancelNodeFlipbookAnim(scene, n, true);
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_gui.cpp:313]: This logic only uses dmGui functions.

Perhaps we can move this into the `dmGui::PlayNodeFlipbookAnim()`  ?
That way we don't need to deal with it here, and we don't need the weird "keep_anim_hash" argument.

Comment (AGulev) [reply engine/gamesys/src/gamesys/components/comp_gui.cpp:313]: Unfortunately we can't.
That was my first assumption I worked on yesterday.
If we do so we break all the one-frame animations because they will never play. In this case we cancel one-frame animation ONLY when we initially setup node.

Comment (JCash) [reply engine/gamesys/src/gamesys/components/comp_gui.cpp:313]: Feels like a good code comment.

Comment (AGulev) [reply engine/gamesys/src/gamesys/components/comp_gui.cpp:316]: Done! Thank you!

**Review by britzl — APPROVED** [review]
