### PR TITLE
Issue 5216: Back button again works as intended on Android

### LINKED ISSUE #5216: Wrong behavior of Back button on Android
**Describe the bug (REQUIRED)**
If we build Android application in 1.2.173 (1.2.172 works fine), launch on Android phone with Back button and tap Back button, application goes to background. If we try to open application again we see only black screen there.

**To Reproduce (REQUIRED)**
1. Launch app on Android
2. Tap back button 
3. Application goes to background it doesn't matter if we have or doesn't have any functionality on this button

**Expected behaviour (REQUIRED)**
The application should handle Back button as before (do nothing if we don't have an action in bindings or call on_input if we do have an action in bindings)

**Defold version (REQUIRED):**
  - Version 1.2.173 (works fine on 1.2.172)

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: any
 - Device: any phone with hardware or virtual back button

**Minimal repro case project (OPTIONAL):**
Any project, even empty project

**Workaround (OPTIONAL):**
No

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/glfw/lib/android/android_init.c [hunk 1]
```diff
@@ -708,7 +708,6 @@ static int32_t addInputEvents(struct android_app* app, const AInputEvent* event,
         out->m_DownTime = AKeyEvent_getDownTime(event);
         out->m_EventTime = AKeyEvent_getEventTime(event);
         (*out_count)++;
-        out++;
```
Comment (JCash) [inline engine/glfw/lib/android/android_init.c:711]: We were reading the values from the wrong pointer.

Comment (britzl) [reply engine/glfw/lib/android/android_init.c:711]: Oh, yeah, that's not good :-) And this problem was introduced during the engine refactor?

**Review by britzl — APPROVED** [review]
