### PR TITLE
Use stat64 on windows

### LINKED ISSUE #11923: Error building project after version upgrade - "unable to resolve build target from value {:FileResource ...}"
### Actual behaviour
Error building my project from Defold editor 1.12.2 beta
This appears to also reproduce in 1.12.1, but not in 1.12.0. The screenshot/bugreport were produced by 1.12.2 beta.

Image

### Steps to reproduce
Load my project in Defold 1.12.1 or 1.12.2 beta
Build
Get error

<hr/>

<table>
<tr><td>Build time</td><td>2026-02-18T09:22:48.667685</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>31e1a6b7a7b1d217e277a5a2956c18dfacff1618</td></tr>
<tr><td>Defold engine sha</td><td>31e1a6b7a7b1d217e277a5a2956c18dfacff1618</td></tr>
<tr><td>Defold version</td><td>1.12.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d2c7cb1dcb5b4fab97dce011b1672fe8"'>d2c7cb1dcb5b4fab97dce011b1672fe8</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 770</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 32.0.101.6987</td></tr>
<tr><td>Java version</td><td>25+36-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by Jhonnyg**
We now use the 64-bit version of stat in the engine on windows. This means that we can load resources larger than 2gb.

Fixes #11923

### CODE REVIEW

File: engine/dlib/src/dlib/sys_win32.cpp [hunk 1]
```diff
@@ -346,17 +345,23 @@ namespace dmSys
...
+        struct __stat64 file_stat;
+        if (_stat64(path, &file_stat) == 0) {
             if (!S_ISREG(file_stat.st_mode)) {
                 return RESULT_NOENT;
             }
+
+            if (file_stat.st_size > UINT_MAX)
+            {
+                return RESULT_FBIG;
+            }
```
Comment (Jhonnyg) [inline engine/dlib/src/dlib/sys_win32.cpp:363]: I wonder if this is documented somewhere that we only support loading 4gb files 🤔

**Review by JCash — APPROVED** [review]
lgtm.
are there any other functions that needs updating in this file? (other than stat() that is)
