### PR TITLE
Fix for calculating the glyph cache correctly

### LINKED ISSUE #9720: Font flickering due to glyph cache being filled in single frame
Fonts with 0 in cache_width and cache_height are sometimes flickering in bundles. This only appears to happen in bundles, not in builds triggered in editor. 

When the issue occurs in a debug bundle, you get a message like:
```
WARNING:RENDER: Entire font glyph cache (1024 x 2048) is filled in a single frame 11374 (' ' 53412). Consider increasing the cache for <fontfile>
```

If you set the font cache_width and cache_height to 1024 x 2048 in an editor build, the issue does not appear. However, if you set it to a low value (e.g. 512 x 512) you do get the flickering and warning message.

### Steps to reproduce
Repro project: 
[glyph_repro.zip](https://github.com/user-attachments/files/17704487/glyph_repro.zip)
Repro bundle: 
[glyph_bundle.zip](https://github.com/user-attachments/files/17704491/glyph_bundle.zip)

Potentially related to https://github.com/defold/defold/issues/9631

<table>
<tr><td>Build time</td><td>2024-11-08T09:48:06.519625</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>415b7a13d96c14dcce3239089b33736cfba4325e</td></tr>
<tr><td>Defold engine sha</td><td>edfdbe31830c1f8aa4d96644569ae87a8ea32672</td></tr>
<tr><td>Defold version</td><td>1.9.4</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 560.94</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by JCash**
This fixes an issue where the glyph cache was erroneously recreated, and also to the wrong size.

### Technical changes

Partly fixes https://github.com/defold/defold/issues/9720

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/render/src/render/font.cpp [hunk 1]
```diff
@@ -238,7 +238,7 @@ namespace dmRender
     {
         font_map->m_IsCacheSizeDirty = 1;
 
-        SetupCache(font_map, font_map->m_CacheWidth, font_map->m_CacheWidth,
+        SetupCache(font_map, font_map->m_CacheWidth, font_map->m_CacheHeight,
```
Comment (JCash) [inline engine/render/src/render/font.cpp:241]: Copy paste!!

File: engine/render/src/render/font_renderer_private.h [hunk 2]
```diff
@@ -63,7 +63,8 @@ namespace dmRender
         , m_CacheCellCount(0)
         , m_CacheCellPadding(0)
         , m_LayerMask(FACE)
-        , m_IsMonospaced(false)
+        , m_IsMonospaced(0)
+        , m_IsCacheSizeDirty(0)
```
Comment (JCash) [inline engine/render/src/render/font_renderer_private.h:67]: Uninitialized variable :/

**Review by ekharkunov — APPROVED** [review]
