### PR TITLE
Fixed trigger_response message appearing upon leaving even when `Generate Trigger Events` is turned off

### LINKED ISSUE #11257: "Generate Trigger Events" is disabled but trigger_response is still created when object leaves
**Describe the bug (REQUIRED)**
I have 2 collision objects, Dynamic cube and Trigger zone, both of them with "Generate Trigger Events" disabled.
When cube enters zone, nothing happens, but when it leaves, `trigger_response` with `enter = false` is generated on both sides.

**To Reproduce (REQUIRED)**
1. Create a game object `cube`, add collision object with `type = Dynamic`, all `Generate Events` set to off, add a box collision shape.  
Create a simple script to print the messages and attach it to the object:
```
function on_message(self, message_id, message, sender)
	print(go.get_id(), message_id, message.enter)
end
```
1. Copy cube, rename it to `zone`, set collision object's `type` to `Trigger`, leave position the same.
1. Start the game. 
1. After the cube falls out of the trigger zone, there should be 2 `trigger_response` messages in the console.

**Expected behavior (REQUIRED)**
There shouldn't be trigger_response when "Generate Trigger Events" is disabled.

**Defold version (REQUIRED):**
1.11.0

**Platforms (REQUIRED):**
Windows 10

**Minimal repro case project (OPTIONAL):**
(https://github.com/pezeee001/defold_trigger_bug

**Logs (OPTIONAL):**
INFO:DLIB: Log server started on port 57234
INFO:ENGINE: Target listening with name: WIN-G97MTTBLU2N - fe80::fde0:2fe1:d6d7:10fc - Windows
INFO:ENGINE: Engine service started on port 57235
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
INFO:ENGINE: Defold Engine 1.11.0 (7c81792)
INFO:PROFILER: Initialized Remotery (ws://127.0.0.1:17815/rmt)
INFO:ENGINE: Loading data from: build/default
INFO:SOUND: Mix format:
INFO:SOUND:   wFormatTag:       fffe  IEEE_FLOAT/PCM/EXTENSIBLE: 3 / 1 / fffe
INFO:SOUND:   nChannels:        2
INFO:SOUND:   nSamplesPerSec:   44100
INFO:SOUND:   nAvgBytesPerSec:  352800
INFO:SOUND:   nBlockAlign:      8
INFO:SOUND:   wBitsPerSample:   32
INFO:SOUND:   -> Format:        3  IEEE_FLOAT/PCM/EXTENSIBLE: 3 / 1 / fffe
INFO:SOUND:   DSP backend: SSE
INFO:SOUND: Sound
INFO:SOUND:   nSamplesPerSec:   44100
INFO:ENGINE: Initialised sound device 'default'
INFO:DLIB: SSDP: Started on address 172.23.96.1
INFO:DLIB: SSDP: Started on address 172.30.208.1
INFO:DLIB: SSDP: Started on address 192.168.0.120
INFO:DLIB: SSDP: Started on address 192.168.56.1
INFO:DLIB: SSDP: Started on address 192.168.192.1
DEBUG:SCRIPT: hash: [/cube]	hash: [trigger_response]	false
DEBUG:SCRIPT: hash: [/zone]	hash: [trigger_response]	false
INFO:DLIB: SSDP: Done on address 172.23.96.1
INFO:DLIB: SSDP: Done on address 172.30.208.1
INFO:DLIB: SSDP: Done on address 192.168.0.120
INFO:DLIB: SSDP: Done on address 192.168.56.1
INFO:DLIB: SSDP: Done on address 192.168.192.1

### PR DESCRIPTION
**Pull request by pezeee001**
Fixes #11257

Technical notes:
Just copied the SupportsEvent logic from TriggerEntered. ~A unit test would be nice but I couldn't figure out how the C++ part works~ Figured it out.

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 1]
```diff
@@ -507,6 +507,12 @@ namespace dmGameSystem
         CollisionWorld* world = (CollisionWorld*)user_data;
         CollisionComponent* component_a = (CollisionComponent*)trigger_exit.m_UserDataA;
         CollisionComponent* component_b = (CollisionComponent*)trigger_exit.m_UserDataB;
+
+        bool event_supported_a = SupportsEvent(component_a, EVENT_MASK_TRIGGER);
+        bool event_supported_b = SupportsEvent(component_b, EVENT_MASK_TRIGGER);
+        if (!event_supported_a && !event_supported_b)
+            return; // We early out because neither supported this event
+
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:515]: Yeah, seems we missed this part in the update :/

File: engine/gamesys/src/gamesys/test/test_gamesys.cpp [hunk 2]
```diff
@@ -2702,6 +2702,46 @@ TEST_F(CollisionObject2DTest, PropertiesTest)
     ASSERT_TRUE(dmGameObject::Final(m_Collection));
 }
 
+TEST_F(Trigger2DTest, EventTriggerFalseTest)
```
Comment (JCash) [inline engine/gamesys/src/gamesys/test/test_gamesys.cpp:2705]: ❤️

**Review by JCash — APPROVED** [review]
