### PR TITLE
Make it possible to work with rotated images in runtime-created atlases

### LINKED ISSUE #8784: Gui node width and height not correct after resource.set_atlas if image in atlas rotated
**Describe the bug (REQUIRED)**
Gui node width and height not correct after resource.set_atlas if image in atlas rotated

Look at second node. Width and height are swapped.

I use 3 atlases.

Also i try reproduce this in gui and in sprites.
Sprites not worked when i change atlas https://github.com/defold/defold/issues/8783
So for now sprites use "assets/skins.atlas"

```lua
go.property("atlas_empty", resource.atlas("/assets/skins_empty.atlas"))
go.property("atlas_empty_fixed", resource.atlas("/assets/skins_empty_fixed.atlas"))
go.property("atlas", resource.atlas("/assets/skins.atlas"))

function init(self)
	local atlas = resource.get_atlas(self.atlas)
	resource.set_atlas(self.atlas_empty, atlas)


	for idx, geometry in ipairs(atlas.geometries) do
		local anim = atlas.animations[idx]
		local data = {
			id = anim.id,
		}

		if geometry.uvs[1] ~= geometry.uvs[3] then
			data.need_rotate = true
			local tc = geometry.vertices
			--add rotation to geometry
			local new_vertices = {
				tc[3], tc[4],
				tc[5], tc[6],
				tc[7], tc[8],
				tc[1], tc[2],
			}

			geometry.vertices = new_vertices
			--now rotate uv and vertices to by 90
		end
	end
	resource.set_atlas(self.atlas_empty_fixed, atlas)

	timer.delay(1, false, function()
		factory.create("/factories#factory1",vmath.vector3(480-100,170,0))
		factory.create("/factories#factory2",vmath.vector3(480,170,0))
		factory.create("/factories#factory3",vmath.vector3(480+100,170,0))
	end)

end

```

**To Reproduce (REQUIRED)**
See repro case. 

**Expected behavior (REQUIRED)**
If i change atlas gui nodes show it correctly.

**Defold version (REQUIRED):**
  - Version 1.7,0

**Platforms (REQUIRED):**
 - Platforms:Windows

**Minimal repro case project (OPTIONAL):**

[gui_width_height_not_correct.zip](https://github.com/defold/defold/files/14943303/gui_width_height_not_correct.zip)

**Additional context (OPTIONAL):**
https://forum.defold.com/t/replace-atlast-with-liveupdate-version/76540/3

### PR DESCRIPTION
**Pull request by AGulev**
With this fix, `resource.get_atlas()` returns the `rotated` flag for geometries, and it's now necessary to add the `rotated` flag for geometries in `resource.set_atlas()`.  
This resolves issues with rotated images in some GUI cases.

Fix https://github.com/defold/defold/issues/10840
Fix https://github.com/defold/defold/issues/8784

### CODE REVIEW

File: engine/gamesys/src/gamesys/scripts/script_resource.cpp [hunk 1]
```diff
@@ -2208,19 +2212,35 @@ static void MakeTextureSetFromLua(lua_State* L, dmhash_t texture_path_hash, dmGr
 
             // From texture_set_ddf.proto:
             // For unrotated quads, the order is: [(minU,maxV),(minU,minV),(maxU,minV),(maxU,maxV)]
+            // For rotated quads, the order is: [(minU,minV),(maxU,minV),(maxU,maxV),(minU,maxV)]
             // Note that we need to invert the V coordinates here to account for the texture coordinate space
-            // NOTE: We could perhaps do it in the loop above by swapping the V min and max coordinates
-            geometry_scratch_cursor[0] = min_uv_u;
-            geometry_scratch_cursor[1] = 1.0 - max_uv_v;
+            if (rotated) {
```
Comment (britzl) [inline engine/gamesys/src/gamesys/scripts/script_resource.cpp]: Put curly braces on their own lines to maintain the overall code style of our cpp code.

**Review by britzl — DISMISSED** [review]
Looks goos but please check comment about curly brace on own lines

File: engine/gamesys/src/gamesys/scripts/script_resource.cpp (hunk 1 above)
Comment (AGulev) [reply engine/gamesys/src/gamesys/scripts/script_resource.cpp]: fixed!
