### PR TITLE
Fix `Project → Live Update Settings` command when live update setting is cleared

### LINKED ISSUE #11581: live update what
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2025-11-05T11:25:20.187937</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cddb6eb43c32e4930257fcbbb30f19cf28deb081</td></tr>
<tr><td>Defold engine sha</td><td>cddb6eb43c32e4930257fcbbb30f19cf28deb081</td></tr>
<tr><td>Defold version</td><td>1.11.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"556be58f8a2944409dbb29cbffd10242"'>556be58f8a2944409dbb29cbffd10242</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Arc(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 32.0.101.8331</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #11581

### CODE REVIEW

**Review by matgis — CHANGES_REQUESTED** [review]
It looks like I need to have the live update settings path configured in `game.project` to be able to go into the live update settings after this change?

But the intended behavior is that the file should be created automatically if the user goes into the live update settings. And the `game.project` setting is only there to allow projects to override the default path.

File: editor/src/clj/editor/live_update_settings.clj [hunk 1]
```diff
@@ -119,9 +119,11 @@
...
     :view-types [:cljfx-form-view :text]))
 
+(defn has-live-update-settings-path? [project evaluation-context]
+  (some? (get (project/settings project evaluation-context) ["liveupdate" "settings"])))
+
 (defn get-live-update-settings-path [project]
-  (let [project-settings (project/settings project)
-        file-resource (get project-settings ["liveupdate" "settings"])]
+  (when-let [file-resource (get (project/settings project) ["liveupdate" "settings"])]
     (if (resource/exists? file-resource)
```
Comment (matgis) [inline editor/src/clj/editor/live_update_settings.clj]: I think the fix should only be to return `"/liveupdate.settings"` if `file-resource` is `nil` here.

**Review by matgis — APPROVED** [review]
Ship it! ❤️
