### PR TITLE
Fix issue where HTML5 build reports `Unknown` instead of compilation shader errors

### LINKED ISSUE #9146: Shader program errors no longer appear for HTML5 and Android builds (and possibly other platforms)
**Describe the bug (REQUIRED)**
In Defold 1.8.1, when a fragment script was unable to compile, the console would print the error. Now, in Defold 1.9.0, the error is hidden as "Error: Unknown".

**To Reproduce (REQUIRED)**
1. Download Defold 1.9.0
2. Create a fragment program and use an unsupported function (max, pow, etc), put it in a material and have a sprite use that material or compare a float and integer in an if statement.
3. Build to HTML5 or Android

**Expected behavior (REQUIRED)**
When the fragment program is unable to be compile, it should print out the error preventing it to be compiled.

**Defold version (REQUIRED):**
  - Version 1.9.0

**Platforms (REQUIRED):**
 - Platforms: HTML5 and Android (known)
 - OS: Android, Windows 10
 - Device: Samsung Galaxy A13 5G

**Minimal repro case project (OPTIONAL):**
https://github.com/mchlkpng/shader-test

**Logs (OPTIONAL):**
How it should work:
```
INFO:ENGINE: Defold Engine 1.8.1 (fd1ad4c)
06-29 17:56:29.514 27054 27177 I defold  : INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
06-29 17:56:29.554 27054 27177 I defold  : INFO:ENGINE: Loading data from: archive:game.dmanifest
06-29 17:56:29.555 27054 27177 I defold  : INFO:LIVEUPDATE: Liveupdate folder located at: /data/user/0/mchlkpng.shadertest/files
06-29 17:56:29.556 27054 27177 I defold  : INFO:LIVEUPDATE: Found no legacy liveupdate zip file references
06-29 17:56:29.556 27054 27177 I defold  : INFO:LIVEUPDATE: Found no legacy liveupdate index paths
06-29 17:56:29.594 27054 27177 I defold  : INFO:ENGINE: Initialised sound device 'default'
06-29 17:56:29.675 27054 27177 W defold  : WARNING:INPUT: No gamepad map found for gamepad 0 (Virtual). The raw gamepad map will be used.
06-29 17:56:29.940 27054 27177 E defold  : ERROR:GRAPHICS: Unable to compile fragment shader.
06-29 17:56:29.940 27054 27177 E defold  : ERROR:GRAPHICS: 0:23: S0001: Type mismatch, cannot convert from 'int' to 'float'
06-29 17:56:29.940 27054 27177 W defold  : WARNING:RESOURCE: Unable to create resource: /main/materials/newsprite/newsprite.fpc: FORMAT_ERROR
06-29 17:56:29.940 27054 27177 W defold  : WARNING:RESOURCE: Unable to create resource: /main/materials/newsprite/newsprite.materialc: FORMAT_ERROR
06-29 17:56:29.940 27054 27177 W defold  : WARNING:RESOURCE: Unable to create resource: /_generated_4e94e21e40197199.spritec: FORMAT_ERROR
06-29 17:56:29.940 27054 27177 W defold  : WARNING:RESOURCE: Unable to create resource: /_generated_bc3c29d316ac2ed4.goc: FORMAT_ERROR
06-29 17:56:29.940 27054 27177 E defold  : ERROR:GAMEOBJECT: Could not instantiate game object from prototype /_generated_bc3c29d316ac2ed4.goc.
06-29 17:56:29.940 27054 27177 W defold  : WARNING:RESOURCE: Unable to create resource: /main/main.collectionc: FORMAT_ERROR
```

How it currently works:
```
06-29 18:05:24.854 29824 29888 I defold  : INFO:ENGINE: Defold Engine 1.9.0 (d6882f4)
06-29 18:05:24.950 29824 29888 I defold  : INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
06-29 18:05:24.965 29824 29888 I defold  : INFO:ENGINE: Loading data from: http://192.168.1.67:49765/build
06-29 18:05:24.985 29824 29888 I defold  : INFO:ENGINE: Initialised sound device 'default'
06-29 18:05:32.317 29824 29888 E defold  : ERROR:GAMESYS: Failed to create fragment program '/_generated_d996217f.fpc': Unable to compile fragment shader.
06-29 18:05:32.317 29824 29888 E defold  : Error: Unknown
06-29 18:05:32.317 29824 29888 W defold  : WARNING:RESOURCE: Unable to create resource: /_generated_d996217f.fpc: FORMAT_ERROR
06-29 18:05:32.317 29824 29888 W defold  : WARNING:RESOURCE: Unable to create resource: /main/materials/newsprite/newsprite.materialc: FORMAT_ERROR
06-29 18:05:32.317 29824 29888 W defold  : WARNING:RESOURCE: Unable to create resource: /_generated_9923214b.spritec: FORMAT_ERROR
06-29 18:05:32.318 29824 29888 W defold  : WARNING:RESOURCE: Unable to create resource: /_generated_5d98418d.goc: FORMAT_ERROR
06-29 18:05:32.318 29824 29888 E defold  : ERROR:GAMEOBJECT: Could not instantiate game object from prototype /_generated_5d98418d.goc.
06-29 18:05:32.318 29824 29888 W defold  : WARNING:RESOURCE: Unable to create resource: /main/main.collectionc: FORMAT_ERROR
06-29 18:05:32.358 29824 29888 I defold  : INFO:DLIB: SSDP: Done on address 192.168.1.140
```

**Workaround (OPTIONAL):**
Use Defold 1.8.1 if there's an issue with a shader program for different platforms

### PR DESCRIPTION
**Pull request by AGulev**
Fixed the issue where the HTML5 bundle reports `Unknown` instead of shader compilation errors. Additionally, as part of this fix, multiline output has been added for errors in HTML5 bundles.

Fix https://github.com/defold/defold/issues/9146

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 1]
```diff
@@ -1807,8 +1807,8 @@ static void LogFrameBufferError(GLenum status)
             glGetShaderiv(shader_id, GL_INFO_LOG_LENGTH, &logLength);
             if (logLength > 0)
             {
-                GLchar *log = (GLchar *)malloc(logLength);
-                glGetShaderInfoLog(shader_id, logLength, &logLength, log);
+                log_str = (GLchar *)malloc(logLength);
+                glGetShaderInfoLog(shader_id, logLength, &logLength, log_str);
```
Comment (AGulev) [inline engine/graphics/src/opengl/graphics_opengl.cpp:1811]: This is the main fix. `log_str` were created to read errors there, but never actually used.

File: engine/dlib/src/dlib/log.cpp [hunk 2]
```diff
@@ -303,11 +306,16 @@ static void DoLogPlatform(LogSeverity severity, const char* output, int output_l
 #endif
 
 #ifdef __EMSCRIPTEN__
+
         //Emscripten maps stderr to console.error and stdout to console.log.
         if (severity == LOG_SEVERITY_ERROR || severity == LOG_SEVERITY_FATAL){
-            fwrite(output, 1, output_len, stderr);
```
Comment (AGulev) [inline engine/dlib/src/dlib/log.cpp:308]: With this approach, each new line symbol `\n` creates a new error it makes it hard to collect such errors also it looks not that well:
CleanShot 2024-07-02 at 18 54 01@2x

File: engine/dlib/src/dlib/log.cpp [hunk 3]
```diff
@@ -303,11 +306,16 @@ static void DoLogPlatform(LogSeverity severity, const char* output, int output_l
...
+            EM_ASM_({
+                Module.printErr(UTF8ToString($0));
+            }, output);
         } else {
-            fwrite(output, 1, output_len, stdout);
+            EM_ASM_({
+                Module.print(UTF8ToString($0));
+            }, output);
```
Comment (AGulev) [inline engine/dlib/src/dlib/log.cpp:318]: This approach allows to print full message as one console entity:
CleanShot 2024-07-02 at 18 53 36@2x

**Review by JCash — APPROVED** [review]
