### PR TITLE
Patch reported system name for iPads running OS version 15+

### LINKED ISSUE #6343: New system_name
On the iPad, there is a new system name. Before it was "iPhone OS", now it change in "iPadOS"
image
image

**To Reproduce**
1. create a label for see on the screen
2.
```lua
local system_name = sys.get_sys_info().system_name
label.set_text("#error", "My system_name is an "..system_name)
```
3. create bundle on ios
4. running bundle on ipad

**Expected behavior**
- Add new system_name on API documentation.
https://defold.com/ref/sys/#sys.get_sys_info:
image

- If possible add or change function for OS name. Just for the path on OS. Exemple : 
image

### PR DESCRIPTION
**Pull request by britzl**
iPads with OS version 15+ are reporting a system name of "iPadOS" instead of "iPhone OS". This risks breaking a lot of user code that expects all Apple devices (phones and tablets) to report the same system name. This fix patches the reported `system_name` in `sys.get_sys_info()` such that it reports `iPhone OS` also on iPads.

Fixes #6343

### CODE REVIEW

File: engine/dlib/src/dlib/sys_cocoa.mm [hunk 1]
```diff
@@ -33,9 +33,14 @@
 {
     static inline void PatchSystemName(char *system_name, uint32_t buffer_size)
     {
+        // iPads with iOS version 15+ have started reporting iPadOS
+        if (dmStrCaseCmp(system_name, "iPadOS")==0)
```
Comment (JCash) [inline engine/dlib/src/dlib/sys_cocoa.mm:37]: If the string should always be the same thing, then why not hardcode it?
Why add extra runtime code?

```
const char* GetSystemName() {
#if defined(__arm__) || defined(__arm64__) || defined(IOS_SIMULATOR)
    const char* system_name = "iPhone OS";
#else
    const char* system_name = "Darwin";
#endif
    return system_name;
}

dmStrlCpy(info->m_SystemName, GetSystemName(), sizeof(info->m_SystemName));
```

```

**Review by JCash — CHANGES_REQUESTED** [review]

File: engine/dlib/src/dlib/sys_cocoa.mm (hunk 1 above)
Comment (britzl) [reply engine/dlib/src/dlib/sys_cocoa.mm]: Good point. I will hardcode "iPhone OS".

**Comment by britzl** [comment]
I went ahead and added a new field `os_name` with the name reported by the system (as opposed to our now hardcoded strings)

| system_name   | os_name        | os_name API                                         |
|---------------|----------------|-----------------------------------------------------|
| HTML5         | Emscripten     | utsname.h - sysname                                 |
| Android       | Android        | utsname.h - sysname                                 |
| Darwin        | Darwin         | utsname.h - sysname                                 |
| iPhone OS     | iPhone OS      | utsname.h - sysname                                 |
| iPhone OS     | iPadOS         | utsname.h - sysname                                 |
| Linux         | Linux          | utsname.h - sysname                                 |
| Windows       | Windows        | OSVERSIONINFOEXA wProductType == VER_NT_WORKSTATION |
| Windows       | Windows Server | OSVERSIONINFOEXA wProductType != VER_NT_WORKSTATION |

**Comment by britzl** [comment]
> Or is there something "better" (more correct) for instance on macOS machines?

There's `NSProcessInfo` (https://developer.apple.com/documentation/foundation/nsprocessinfo). It has fields such as `operatingSystemName` (deprecated) and `operatingSystemVersionString`.

`operatingSystemVersionString` is described as:

"The operating system version string is human readable, localized, and is appropriate for displaying to the user. This string is not appropriate for parsing."

Returned values on my mac:

* operatingSystemVersionString: Version 10.15.7 (Build 19H1615)
* operatingSystemName: NSMACHOperatingSystem

**Comment by britzl** [comment]
Question: Should `os_name` also be added to crash data (thus breaking the crash data format)?

**Comment by AGulev** [comment]
`Emscripten` is a bit strange os name.
maybe it would be better and more useful to show `navigator.userAgent` data instead?

**Comment by britzl** [comment]
> `Emscripten` is a bit strange os name.

Maybe. Emscripten is in many ways the operating system, since it replicates all of the POSIX functions in a browser.

**Review by JCash — DISMISSED** [review]

**Comment by britzl** [comment]
After discussion with @JCash we agreed to move the os_name changes to a separate branch and hold-off on adding it. Branch: https://github.com/defold/defold/tree/dev-os-name

**Review by JCash — APPROVED** [review]

**Comment by britzl** [comment]
Cherry-picking to beta as well.
