### PR TITLE
Conform 'buffer is full' error messages

### LINKED ISSUE #5252: Errors and warnings should be developer-friendly
**Task:**
Defold engine errors and warnings are not obvious at all. For example:
- `WARNING:RENDER: Out of text-render buffer` - It means that you should increase `graphics.max_characters`.
- `ERROR:PHYSICS: Physics world buffer full, world could not be created.` - It means that you can try to increase `physics.world_count` or load fewer collections via proxies.

I do think that errors and warnings should be developer-friendly as much as possible.

There are a lot of messages. We can slowly start doing pull-requests. Before that, let's discuss the structure of the messages. For example:
- Before: `WARNING:RENDER: Out of text-render buffer` 
- After:
    - `WARNING:RENDER: Out of text-render buffer. Increase graphics.max_characters (ref: https://defold.com/manuals/project-settings/).` 
    - or `WARNING:RENDER: Out of text-render buffer. It's limited by graphics.max_characters (ref: https://defold.com/manuals/project-settings/).`.

Something like that.

**Expected outcome:**
Fewer questions from newcomers 👍

### LINKED ISSUE #7237: App crash when GUI max_count reached
**Describe the bug (REQUIRED)**
I encountered some unexpected behaviour with GUI limits. When I set in `game.project` GUI max_count = 1, the app doesn't throw error with severity as for eg. resource limit, but there is only `"Assertion failed: (Capacity() - Size() > 0), function Push, file array.h, line 532."` which is followed by application crash.

**To Reproduce (REQUIRED)**
1. Go to game.project
2. In GUI section set `max_count` to 1
3. Crate and launch build debug or release

**Expected behaviour (REQUIRED)**
When limit reached, engine should present error in logs, protecting the app from crashing

**Defold version (REQUIRED):**
  - Version 1.3.7

**Platforms (REQUIRED):**
 - Platforms: macOS 
 - OS: Monterey 12.6 (21G115)

### PR DESCRIPTION
**Pull request by Jhonnyg**
When a component cannot be created we show an error message on where in the project that can be modified, but previously the messages had different wording. This change tries to conform most of these cases into the same format.

Fixes #7237 
Fixes #5252

## PR checklist (remove before merging)

* [x] Prepared the PR for release notes
	* [x] Proper description of feature or fix (see example x?)
	* [x] Added a #fixes ### if it fixes an issue
	* [x] Assigned issue to a project
* [-] Added documentation for public API changes
* [-] Is this a new feature?
	* [-] Added engine and/or editor unit tests
	* [-] Added or updated manual entry

### CODE REVIEW

**Comment by aglitchman** [comment]
The new error messages are great! Many thanks!

(look at https://github.com/defold/defold/issues/5252)

File: engine/gamesys/src/gamesys/gamesys_private.cpp [hunk 1]
```diff
@@ -59,7 +59,20 @@ namespace dmGameSystem
         dmLogError("%s", buf);
 
         va_end(lst);
+    }
 
+    void ShowFullBufferError(const char* object_name, const char* config_key, int max_count)
+    {
+        if (config_key)
+        {
+            dmLogError("%s could not be created since the buffer is full (%d). Increase the '%s' value in game.project",
```
Comment (britzl) [inline engine/gamesys/src/gamesys/gamesys_private.cpp:68]: Perhaps add link to game.project as well?

https://github.com/defold/defold/issues/5252#issuecomment-702072990
