### PR TITLE
Fix the scale tool for rotated objects in the editor

### LINKED ISSUE #9177: Scale tool In 3d, when an object is rotated 90 degrees, some handles stop working.
### Actual behaviour
https://github.com/defold/defold/assets/80172335/e590b6c6-5879-42de-a5c5-f218050dd4d6

### Steps to reproduce
When working with a mesh in 3D after rotating an object exactly 90 degrees along any axis. Scale tool loses functionality.

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-25T16:26:09.046426</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3642fa5b700b8d6e74e3f0595e75cd50eff54459</td></tr>
<tr><td>Defold engine sha</td><td>d6882f432beca85d460ec42497888157c356d058</td></tr>
<tr><td>Defold version</td><td>1.9.0</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(R) Xe Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 30.0.101.1029</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
The scale tool in the scene editor will now work regardless of how the object was initially rotated. Previously an object rotated exactly 90 degrees along any axis would not be possible to rotate using the scale tool.

Fix https://github.com/defold/defold/issues/9177

### CODE REVIEW

File: editor/src/clj/editor/scene_tools.clj [hunk 1]
```diff
@@ -457,22 +457,31 @@
...
-                           (case manip
-                             (:scale-z :scale-xz :scale-yz)
-                             (div-fn (.z delta) (.z start-delta))
-                             1.0))]
+            axis-scale (fn [axis]
+                         (let [local (case axis
+                                       :x (Vector3d. 1.0 0.0 0.0)
+                                       :y (Vector3d. 0.0 1.0 0.0)
+                                       :z (Vector3d. 0.0 0.0 1.0))]
+                           (.normalize local)
```
Comment (matgis) [inline editor/src/clj/editor/scene_tools.clj:468]: Normalizing here doesn't do anything since `local` is already a unit vector at this point. Did you mean to normalize after the `.transform` call? That would make sense, since the `world-transform` may be non-orthographic when non-uniformly scaled parents are combined with rotations.

**Review by matgis — CHANGES_REQUESTED** [review]
I think we may want to normalize the `local` vector after applying the `world-transform`? And maybe rename it `world`, since it isn't really local after that.

File: editor/src/clj/editor/scene_tools.clj [hunk 2]
```diff
@@ -460,26 +460,22 @@
...
-                                       :y (Vector3d. 0.0 1.0 0.0)
-                                       :z (Vector3d. 0.0 0.0 1.0))]
-                           (.normalize local)
-                           (.transform ^Matrix4d world-transform local)
-                           (let [start-len (.dot start-delta local)
-                                 curr-len (.dot delta local)]
-                             (if (> (Math/abs start-len) 1e-12)
-                               (/ curr-len start-len)
-                               1.0))))
+            axis-scale (fn [local]
```
Comment (matgis) [inline editor/src/clj/editor/scene_tools.clj:463]: Doesn't this give reflection errors unless you tag `^Vector3d local`? 🤔

Comment (AGulev) [reply editor/src/clj/editor/scene_tools.clj:463]: I aalways forget it =/

**Review by matgis — APPROVED** [review]
Looks good to me! ❤️
