### PR TITLE
Calculate the actual vertex count for the packed polygons in the gui

### LINKED ISSUE #13: Game crashes whe use Sprites Trim Mode - Polygon Outline
Steps to reproduce:
1. Create image of complex shape (see example project).
2. Create TP atlas.
3. Use Sprites Trim mode - Polygon Outline
image
4. Create Defold TP atlas.
5. Create GUI scene with node that use image of complex shape from TP atlas.
6. Run game

Expected result:
Game run and display gui node.

Actual result:
Game crashes.
Log:
image

Defold 1.9.5
Engine SHA d01194cf0fb576b516a1dca6af6f643e9e590051
Editor SHA fc1bfb6992ebb55b6b1abecf9e85b5404522e855
Texture Packer version 2.0.1
OS Ubuntu 24.04.1 LTS

Test project:
[gui-pivot.zip](https://github.com/user-attachments/files/18026477/gui-pivot.zip)
- Open project and Build the game.
- See the crash errors
- If in /assets/main.tps change Sprites Trim mode to "None", game will build successfully.

Note: In working project sometimes game is not crashed, but gui node has shifted position, as it was in task with "pivot point issue".

### PR DESCRIPTION
**Pull request by JCash**
Fixes: https://github.com/defold/extension-texturepacker/issues/13

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_gui.cpp [hunk 1]
```diff
@@ -1485,6 +1485,46 @@ namespace dmGameSystem
         }
     }
 
+    static uint32_t CalcVertexCount(dmGui::HScene scene, GuiWorld* gui_world, dmGraphics::HTexture texture, const dmGui::RenderEntry* entries, uint32_t node_count)
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_gui.cpp:1488]: Just like for sprites, we need to calculate the actual number of vertices needed, before we generate the vertices.

**Review by britzl — APPROVED** [review]
