### PR TITLE
Issue-6764 Make it possible to avoid filling `device_ident` value

### LINKED ISSUE #6764: Google Play (Issue found: Invalid Data safety section)
**Describe the bug (REQUIRED)**
https://forum.defold.com/t/google-play-issue-found-invalid-data-safety-section/71172

I’m updating my app in Play Market. And get warning from google
SPLIT_BUNDLE 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)

**To Reproduce (REQUIRED)**
1. Build aab.
2. Upload it to play market
3. Wait for review(~1-2h) I upload my game to “Open testing” and after review(1-2 hours) get email from google.

**Expected behavior (REQUIRED)**
No warning from google about device_id

**Defold version (REQUIRED):**
1)Defold 1.3.3
2)permissions
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```
3)Dependencies
```
dependencies#0 = https://github.com/AGulev/jstodef/archive/1.3.0.zip
dependencies#1 = https://github.com/DanEngelbrecht/LuaScriptInstance/archive/master.zip
dependencies#2 = https://github.com/d954mas/defold-box2d/archive/refs/
```

**Platforms (REQUIRED):**
 - Platforms: Android

**Workaround (OPTIONAL):**
https://stackoverflow.com/questions/71199143/action-required-your-app-is-not-compliant-with-google-play-policies-what-is-t/71234298#71234298
Fill in data safety policy that device_id is collected.

**Screenshots (OPTIONAL):**

**More info**
It mb because engine always try to get android_id
https://github.com/defold/defold/blob/6b03d6f75afb1411f62d96850cd8d94b1971916e/engine/dlib/src/dlib/sys.cpp#L754

### PR DESCRIPTION
**Pull request by AGulev**
Fixed issue when `GetSystemInfo()` (the method used internally and for `sys.get_sys_info()`) by default requests `device_ident `. On Android this is `android_id` - a value secured by OS. If an application requests this then Data Safety Section needs to be filled even if app doesn't use internet connection and any IDs at all.
If you don't need `device_ident` value just call `sys.get_sys_info()` function with `{ignore_secure = true}` parameter: `sys.get_sys_info({ignore_secure  = true})` 

Fix https://github.com/defold/defold/issues/6764

### CODE REVIEW

File: engine/script/src/script_sys.cpp [hunk 1]
```diff
@@ -702,24 +716,13 @@ union SaveLoadBuffer
...
-            api_level_android = strtol(info.m_ApiVersion, 0, 10);
-            marshmallow_or_higher = (api_level_android >= android_marshmallow_api_level);
-        }
-
-        return is_android && marshmallow_or_higher;
+        #ifdef ANDROID
+            const long android_marshmallow_api_level = 23;
+            return android_get_device_api_level() >= android_marshmallow_api_level;
+        #endif
+        return false;
```
Comment (AGulev) [inline engine/script/src/script_sys.cpp:725]: It's not directly related to the issue, I just found that using of the `GetSystemInfo()` function isn't necessary here.

File: engine/script/src/script_sys.cpp [hunk 2]
```diff
@@ -541,13 +542,26 @@ union SaveLoadBuffer
...
+        {
+            luaL_checktype(L, 1, LUA_TBOOLEAN);
+            ignore_secure_values = lua_toboolean(L, 1);
+        }
+
+        if (!ignore_secure_values)
+        {
+            dmSys::GetSecureInfo(&info);
+        } 
+
```
Comment (AGulev) [inline engine/script/src/script_sys.cpp:564]: Keep behaviour by default as it was and make getting for the secure values optional.

File: engine/script/src/script_sys.cpp [hunk 3]
```diff
@@ -495,6 +495,7 @@ union SaveLoadBuffer
      *
      * Returns a table with system information.
      * @name sys.get_sys_info
+     * @param ignore_secure_values [type:boolean] this flag ignores values might be secured by OS e.g. `device_ident`
```
Comment (britzl) [inline engine/script/src/script_sys.cpp:498]: I'm no sure if I'm overly cautious here but maybe we should use an option table instead, in case we wish to add some more option in the future?

```
sys.get_sys_info({ ignore_secure = true })
```

Comment (AGulev) [reply engine/script/src/script_sys.cpp]: No I use table with options

**Review by britzl — APPROVED** [review]
Looks good! Remember to update first post of the PR with the change!
