### PR TITLE
Issue 5933: Crash fix for macOS fullscreen mode

### LINKED ISSUE #5933: Game crashes on fullscreen on macOS
The creation of the OpenGL context fails for some reason.

https://forum.defold.com/t/crash-when-running-game-fullscreen/68843

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 1]
```diff
@@ -626,19 +626,16 @@ int  _glfwPlatformOpenWindow( int width, int height,
     if (_glfwWin.clientAPI == GLFW_OPENGL_API)
     {
         unsigned int attribute_count = 0;
-    #define ADD_ATTR(x) attributes[attribute_count++] = x
-    #define ADD_ATTR2(x, y) (void)({ ADD_ATTR(x); ADD_ATTR(y); })
     #define MAX_ATTRS 24 // urgh
         NSOpenGLPixelFormatAttribute attributes[MAX_ATTRS];
+    #define ADD_ATTR(x) assert(attribute_count < MAX_ATTRS); attributes[attribute_count++] = x
+    #define ADD_ATTR2(x, y) (void)({ ADD_ATTR(x); ADD_ATTR(y); })
```
Comment (JCash) [inline engine/glfw/lib/cocoa/cocoa_window.m:632]: Added an assert to a void a potential buffer overrun.
(it wasn't an issue, I just felt it a bit cleaner)

File: engine/glfw/lib/cocoa/cocoa_window.m [hunk 2]
```diff
@@ -626,19 +626,16 @@ int  _glfwPlatformOpenWindow( int width, int height,
...
 
         ADD_ATTR( NSOpenGLPFADoubleBuffer );
 
         if( wndconfig->mode == GLFW_FULLSCREEN )
         {
-            ADD_ATTR( NSOpenGLPFAFullScreen );
-            ADD_ATTR( NSOpenGLPFANoRecovery );
-            ADD_ATTR2( NSOpenGLPFAScreenMask,
-                       CGDisplayIDToOpenGLDisplayMask( CGMainDisplayID() ) );
+            ADD_ATTR2( NSOpenGLPFAScreenMask, CGDisplayIDToOpenGLDisplayMask( CGMainDisplayID() ) );
```
Comment (JCash) [inline engine/glfw/lib/cocoa/cocoa_window.m:638]: The other attributes didn't exist anymore, and thus failed the `initWithAttributes`.

**Review by britzl — APPROVED** [review]
Looks good!
