### PR TITLE
Editor: Correctly unpack unsigned short indices for models

### LINKED ISSUE #9183: Broken 3D models have cumulative effect and lead to errors.
[Defold_report.zip](https://github.com/user-attachments/files/16120885/Defold_report.zip)

This error happens only with one type of models, but every time.
How did it happen.
I used [Instant Meshes](https://github.com/wjakob/instant-meshes) for retopology photogrammetry models from [Scketchfab](https://sketchfab.com/3d-models/poyser-street-arch-a92dece3a87c4d3cbf8e28a4cfd934a3). I did it many times.
Same models (with baked textures) worked well at Windows and Debug mod but didn't work in HTML5.
I tried to use Blender tools to repair implicite defects of this type of models.
After about 20th attempt, Defold starts to deny this type of model with 2 types of errors on screenshots below.
I restarted computer, deleted projects, deleted Defold and downloaded it again, but nothing changes.
Another models work well.
So, I think, this broken type of models has cumulative effect.
And I don't know how to return my PC in previous condition. However it is not so important for me, I can try to search another retopology tool. 
Microsoft Surface Windows 10.
Note: models of this type looks well in Blender and Debug mod and Windows build, but they are broken implicitly. For example, after export from Blender the model distort in window of Blender, but after "Convert to mesh" looks well again.

### Expected behaviour
Models which are made in Instant Meshes and Blender work like as any other models in Defold.
### Actual behaviour
2024-07-08 Defold Report
2024-07-08 Defold Report2
At first 20 times this type of models only didn't work in HTML5, but after that, make errors on screenshorts every time. Another types of models works well.
### Steps to reproduce
Make retopology of high-poly model in Instant Meshes, export in Blender 4.1.1, bake textures from original model, export as .glb without textures, but textures themselves exporting separatly. In Defold make Game object with Model component file with this .glb file about 20 times.
<hr/>

<table>
<tr><td>Build time</td><td>2024-06-25T16:26:09.046426</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3642fa5b700b8d6e74e3f0595e75cd50eff54459</td></tr>
<tr><td>Defold engine sha</td><td>d6882f432beca85d460ec42497888157c356d058</td></tr>
<tr><td>Defold version</td><td>1.9.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1329d36a55ea436fb63155c944d6ed3c"'>1329d36a55ea436fb63155c944d6ed3c</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(R) Plus Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.2125</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #9879: Error loading GLTF model
### Expected behaviour
No error and display the model.
### Actual behaviour
It gives the error and no model is displayed.  
### Steps to reproduce
Import this model.  I just exported it from blender so it may be a bad export, but still it shouldn't error out like this.
[craps_0.zip](https://github.com/user-attachments/files/17997785/craps_0.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2024-12-02T13:30:54.865959</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a646799c3eb767cc8ea8d3bbceee820839adc62c</td></tr>
<tr><td>Defold engine sha</td><td>d01194cf0fb576b516a1dca6af6f643e9e590051</td></tr>
<tr><td>Defold version</td><td>1.9.5</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ac37021c2ce243d5abd14005de4e6c09"'>ac37021c2ce243d5abd14005de4e6c09</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 566.14</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
Correctly unpack unsigned short indices when rendering models.

Fixes #9183, #9879, #9923

### CODE REVIEW

File: editor/src/clj/editor/model_scene.clj [hunk 1]
```diff
@@ -112,7 +113,7 @@
       :indexbuffer-format-16
       (let [short-buffer (.asShortBuffer byte-buffer)]
         (dotimes [i num-indices]
-          (aset out-indices i (int (.get short-buffer i)))))
+          (aset out-indices i (int (num/ushort->long (.get short-buffer i))))))
```
Comment (matgis) [inline editor/src/clj/editor/model_scene.clj:116]: We were already unpacking shorts to ints here, but we were putting in negative indices for short indices above the signed range. This change performs some bitwise operations to convert it the unsigned short into a signed long. There is no operation to convert into a signed int directly.

Note that the signed / unsigned problem remains for meshes that use 32-bit integers. However, I'm not sure there is a good solution there because Java arrays are addressed using signed ints, not longs.

**Review by JCash — APPROVED** [review]
