### PR TITLE
Break out of loop when printing stack trace

### LINKED ISSUE #6140: HTML5: Engine crash freezes browser's page
**Describe the bug (REQUIRED)**
Any **_fatal error_** freezes the browser's page. Looks like, the engine calls the crash handler again and again (maybe in an infinite loop).

**To Reproduce (REQUIRED)**
1. Create a new empty project.
2. Make an HTML5 build (release or debug - it's not important).
3. Rename archive/game.arcd0 to archive/game.arci0 and vice-versa (It's just an easy way to crash the engine).
4. Open the game in your browser, preferably Chrome, and try to open Developers Console.
5. The engine spams the console with "CRASH" messages in an infinite loop, and it's hard to reload that page.

**Expected behavior (REQUIRED)**
The game should crash, stop its execution and not freeze the page.

**Defold version (REQUIRED):**
  - Version: 1.2.187, 1.2.188

**Platforms (REQUIRED):**
 - Platforms: HTML5.
 - Browsers: Chrome, Firefox.

**Screenshots (OPTIONAL):**
image

### PR DESCRIPTION
**Pull request by britzl**
Fixes #6140

### CODE REVIEW

File: engine/crash/src/crash.cpp [hunk 1]
```diff
@@ -334,6 +334,9 @@ namespace dmCrash
 
             dmLogError("%s\n", p);
 
+            if (!lineend)
```
Comment (JCash) [inline engine/crash/src/crash.cpp:337]: Perhaps in the future, a comment in the code might be good

**Review by JCash — APPROVED** [review]
