### PR TITLE
Fixed an issue where the game wouldn't start if the iframe didn't allow gamepad usage (HTML5).

### LINKED ISSUE #8479: HTML5: game crashes if the page isn't allowed to use Gamepad API
**Describe the bug (REQUIRED)**
HTML5 build doesn't run at all if the page is not allowed to use Gamepad API:

```
exception thrown: SecurityError: Failed to execute 'getGamepads' on 'Navigator': Access to the feature "gamepad" is disallowed by permissions policy.,Error: Failed to execute 'getGamepads' on 'Navigator': Access to the feature "gamepad" is disallowed by permissions policy.
    at Object.refreshJoysticks (<anonymous>:1:227193)
    at _glfwSetGamepadCallback (<anonymous>:1:235002)
    at wasm://wasm/006c51a6:wasm-function[3437]:0x110017
    at wasm://wasm/006c51a6:wasm-function[3429]:0x10fc51
    at wasm://wasm/006c51a6:wasm-function[4409]:0x15bdc5
    at wasm://wasm/006c51a6:wasm-function[4398]:0x159e17
    at wasm://wasm/006c51a6:wasm-function[4401]:0x15a6cb
    at wasm://wasm/006c51a6:wasm-function[2859]:0xe2189
    at wasm://wasm/006c51a6:wasm-function[2660]:0xd092c
    at Module._main (<anonymous>:1:264167)
```

More details - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/gamepad

It turned out that [FB Playable Preview tool](https://developers.facebook.com/tools/playable-preview/) doesn't allow gamepads and, therefore, any Defold game isn't able to run.

**To Reproduce (REQUIRED)**
Run the game build in an iframe where the Gamepad API is not allowed. 

**Expected behavior (REQUIRED)**
The game should run well.

**Defold version (REQUIRED):**
  - Version: 1.6.3

**Platforms (REQUIRED):**
 - Platforms: HTML5

### PR DESCRIPTION
**Pull request by AGulev**
Fixed the issue where the game doesn't start if access to gamepads is disallowed by the permissions policy.

Fix https://github.com/defold/defold/issues/8479
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: external/glfw/js/library_glfw.js [hunk 1]
```diff
@@ -563,7 +563,7 @@ var LibraryGLFW = {
 
     refreshJoysticks: function(forceUpdate) {
         // Produce a new Gamepad API sample if we are ticking a new game frame, or if not using emscripten_set_main_loop() at all to drive animation.
-        if (forceUpdate || Browser.mainLoop.currentFrameNumber !== GLFW.lastGamepadStateFrame || !Browser.mainLoop.currentFrameNumber) {
+        if (GLFW.isGamepadCallbackSet &&(forceUpdate || Browser.mainLoop.currentFrameNumber !== GLFW.lastGamepadStateFrame || !Browser.mainLoop.currentFrameNumber)) {
```
Comment (britzl) [inline external/glfw/js/library_glfw.js:566]: Oof, feels a bit complex. Can't we split this into an early exit check first and then keep the rest as it was?

```
if (!GLFW.isGamepadCallbackSet) {
   return;
}
if (forceUpdate || Browser.mainLoop.currentFrameNumber !== GLFW.lastGamepadStateFrame || !Browser.mainLoop.currentFrameNumber) {
   ... do stuff
```

**Review by britzl — CHANGES_REQUESTED** [review]
Split condition into two, one early exit and keep the rest as it was

**Review by britzl — APPROVED** [review]
