### PR TITLE
Move render-mode to SceneRenderer

### LINKED ISSUE #6595: Switch to CurveEditor tab
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-11T11:22:04.516620</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0d4cec29d936b43320715b78987297244bc29589</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b87ad801a0a74b57bbcc18b121c762b7"'>b87ad801a0a74b57bbcc18b121c762b7</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 512.59</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #6595

### CODE REVIEW

File: editor/src/clj/dynamo/graph.clj [hunk 1]
```diff
@@ -924,12 +924,6 @@
    (swap! *the-system* is/invalidate-outputs outputs)
    nil))
 
-(defn invalidate-node-outputs!
-  [node-id]
-  (let [labels (-> (node-type* node-id)
-                   (in/output-labels))]
-    (invalidate-outputs! (map (partial vector node-id) labels))))
-
```
Comment (vlaaad) [inline editor/src/clj/dynamo/graph.clj:932]: That was unused

**Review by matgis — APPROVED** [review]
Looks good to me!
