### PR TITLE
Set HTML5 AudioContext sample rate to 44100

### LINKED ISSUE #8257: HTML5: Implicitly set sample rate for AudioContext
**Describe the bug (REQUIRED)**
A brilliant Poki SDK update from @AGulev revealed a bunch of interesting new bugs that I've never seen before and had no idea that even that could be the case:

> "DEFOLD:ERROR:SOUND: Sounds with rate higher than sample-rate not supported (44100 hz > 22050 hz) (<unknown>)\n"

So, Defold doesn't want to play sounds if the sample rate of the sound (we use 44100 for everything) is less than sample rate of the audio device. At the same time, it's strange to see audio devices with sample rates below 44100 in 2023 ( is it SoundBlaster from the DOS era? 😂).

And it turns out that you can set the desired sampleRate when creating an AudioContext. **If you don't, the sampleRate could be default 44100, or it could be 8000, 16000, 22050, 32000, 48000 etc...**

Plus, all these errors are from users on macOS and iOS Safari 17.x.x.

**Expected behavior (REQUIRED)**
The game should run well on those devices. I don't know if this is a fatal error and if the game works further in these circumstances.

**Defold version (REQUIRED):**
  - Version: 1.6.1, 1.6.2

**Platforms (REQUIRED):**
 - Platforms: HTML5

**Workaround (OPTIONAL):**
I think you need to modify the AudioContext instantiation code to first try to construct it with sampleRate=44100. If it fails, then without the sampleRate parameter.

More info: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext#samplerate

PS On my Windows PC, the default sample rate is 48000:
image

### PR DESCRIPTION
**Pull request by aglitchman**
HTML5 AudioContext sample rate wasn't specified and varied depending on the output device and it could be default 44100, or it could be 8000, 16000, 22050, 32000, 48000 etc. If the sample rate of the device was less than the sample rate of your sounds, they would not be played at all. So the AudioContext is now created with sampleRate = 44100.

Fixes https://github.com/defold/defold/issues/8257

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

**Review by britzl — APPROVED** [review]
Looks good

File: engine/sound/src/js/library_sound.js [hunk 1]
```diff
@@ -25,8 +25,15 @@ var LibrarySoundDevice =
 
         if (window.AudioContext || window.webkitAudioContext) {
             if (shared.audioCtx === undefined) {
-                shared.audioCtx = new (window.AudioContext || window.webkitAudioContext)();
-            }                
+                var audioCtxCtor = window.AudioContext || window.webkitAudioContext;
+                try {
+                    // The default sampleRate varies depending on the output device and can be less than 44100.
```
Comment (JCash) [inline engine/sound/src/js/library_sound.js:30]: ❤️

**Review by JCash — APPROVED** [review]
