### PR TITLE
Issue 5825: Crash handler context fix

### LINKED ISSUE #5825: Crash handler used the wrong context
The correct context wasn't set.

### PR DESCRIPTION
**Pull request by JCash**
For platforms using backtrace_execinfo
Moved iOS to backtrace_libunwind

### CODE REVIEW

File: engine/crash/src/crash.cpp [hunk 1]
```diff
@@ -314,5 +315,31 @@ namespace dmCrash
...
+            if (lineend && lineend < end)
+                *lineend = 0;
+
+            dmLogError("%s\n", p);
+
+            p = lineend+1;
+        }
+
+        dmLogError("\n");
+        dLib::SetDebugMode(is_debug_mode);
```
Comment (JCash) [inline engine/crash/src/crash.cpp:341]: The Console.app doesn't handle new lines well, and it also truncates the output making it hard to read the Lua part of the callstack.

**Review by britzl — APPROVED** [review]
Looks good!
