### PR TITLE
Don’t apply Model material assignments unless fully-formed

### LINKED ISSUE #10600: Unable to delete old material after replacing model mesh with a different material
If the model has a material set and we replace the model mesh with a new one with a different material name, the old material cannot be deleted. The editor does not respond, does not let you save the project.

### Expected behaviour
The IDE should allow to delete the material and continue working well.

### Actual behaviour
The editor does not respond, does not let you save the project.

### Steps to reproduce

The test project - 
[material_deletion_issue.zip](https://github.com/user-attachments/files/20014653/material_deletion_issue.zip)

The video how to reproduce

https://github.com/user-attachments/assets/eb438b41-3109-41c2-aabd-c09f7fa5ba53

<hr/>

<table>
<tr><td>Build time</td><td>2025-05-01T09:37:04.865638</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>2783cc609cd52bc5ac92ec9e35b9b854f5f07882</td></tr>
<tr><td>Defold engine sha</td><td>2783cc609cd52bc5ac92ec9e35b9b854f5f07882</td></tr>
<tr><td>Defold version</td><td>1.10.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b3f95f76d4ba410794fbd30400441514"'>b3f95f76d4ba410794fbd30400441514</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Arc(TM) B580 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 32.0.101.6734</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by matgis**
The editor will no longer try to apply Model material assignments that do not refer to a `.material` resource when rendering Models in the Scene View. This fixes an issue where manually deleting the path from the material resource field of a previously assigned material, that is no longer defined in the referenced Mesh, would cause an exception that locked up the editor.

Fixes #10600

### CODE REVIEW

File: editor/src/clj/editor/model_scene.clj [hunk 1]
```diff
@@ -405,7 +405,6 @@
         (assert (every? map? material-attribute-infos))
         (assert (every? keyword? (map :name-key material-attribute-infos)))
         (assert (shader/shader-lifecycle? shader))
-        (assert (map? vertex-attribute-bytes))
```
Comment (matgis) [inline editor/src/clj/editor/model_scene.clj:408]: Unrelated: I removed this constraint, because `nil` is fine too.

File: editor/src/clj/editor/model.clj [hunk 2]
```diff
@@ -441,13 +441,7 @@
...
   (output material-name->material-scene-info g/Any :cached
           (g/fnk [material-scene-infos]
-            (let [material-scene-infos-by-material-name (coll/pair-map-by :name material-scene-infos)]
-              (fn material-name->material-scene-info [^String material-name]
-                ;; If we have no material associated with the index, we mirror the
-                ;; engine behavior by picking the first one:
-                ;; https://github.com/defold/defold/blob/a265a1714dc892eea285d54eae61d0846b48899d/engine/gamesys/src/gamesys/resources/res_model.cpp#L234-L238
-                (or (material-scene-infos-by-material-name material-name)
-                    (first material-scene-infos))))))
+            (model-scene/make-material-name->material-scene-info material-scene-infos)))
```
Comment (matgis) [inline editor/src/clj/editor/model.clj:444]: This output is used with the `model-scene/augment-scene` function when rendering the Model. I moved the implementation next to the `augment-scene` function in `model_scene.clj` for clarity.

File: editor/src/clj/editor/model_scene.clj [hunk 3]
```diff
@@ -440,6 +439,33 @@
...
+        ;; If we have no material associated with the index, we mirror the
+        ;; engine behavior by picking the first one:
+        ;; https://github.com/defold/defold/blob/a265a1714dc892eea285d54eae61d0846b48899d/engine/gamesys/src/gamesys/resources/res_model.cpp#L234-L238
+        fallback-material-scene-info
+        (first usable-material-scene-infos)
+
+        usable-material-scene-infos-by-material-name
+        (->> usable-material-scene-infos
+             (coll/pair-map-by :name)
+             (coll/not-empty))]
```
Comment (matgis) [inline editor/src/clj/editor/model_scene.clj:464]: `not-empty` because we don't need a bunch of unique empty map objects hanging around.

**Review by sprocketc — APPROVED** [review]
Confirmed that the bug is fixed!
