### PR TITLE
Fix crash in GUI when atlas changes texture resource internally

### LINKED ISSUE #8786: gui crashed if change atlas in runtime
**Describe the bug (REQUIRED)**

I am trying to replace empty atlas with existed atlas. I need this to load new atlas with liveupdate.

In game  have empty atlas then i load new atlas in liveupdate and replace empty atlas with new atlas.

I get this error in build from editor.
In this case no liveupdate archive is loading.

I only load liveupdate.collection parallel to game.collection

```
Assertion failed: i < m_Capacity, file D:\a\defold\defold\tmp\dynamo_home\include\dlib/opaque_handle_container.h, line 244
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\user\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF6ED164660 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
ERROR:CRASH:  1 0x7FF6ED49D810 raise /tmp/job2786423018271048004/minkernel/crts/ucrt/src/appcrt/misc/signal.cpp:547
ERROR:CRASH:  2 0x7FF6ED48DB68 abort /tmp/job2786423018271048004/minkernel/crts/ucrt/src/appcrt/startup/abort.cpp:71
ERROR:CRASH:  3 0x7FF6ED48CE4C common_assert_to_stderr<wchar_t> /tmp/job2786423018271048004/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:186
ERROR:CRASH:  4 0x7FF6ED48C964 _wassert /tmp/job2786423018271048004/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:443
ERROR:CRASH:  5 0x7FF6ED11FAA0 dmOpaqueHandleContainer<unsigned __int64>::Get D:\a\defold\defold\tmp\dynamo_home\include\dlib\opaque_handle_container.h:231
ERROR:CRASH:  6 0x7FF6ED12C140 dmGraphics::OpenGLGetOriginalTextureHeight D:\a\defold\defold\engine\graphics\src\opengl\graphics_opengl.cpp:3447
ERROR:CRASH:  7 0x7FF6ED13F950 dmGameSystem::SetupGuiScene D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_gui.cpp:606
ERROR:CRASH:  8 0x7FF6ED1402D0 dmGameSystem::CompGuiCreate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_gui.cpp:781
ERROR:CRASH:  9 0x7FF6ED1BD260 dmGameObject::CreateComponents D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:829
ERROR:CRASH: 10 0x7FF6ED130E70 dmGameObject::AcquireResources D:\a\defold\defold\engine\gameobject\src\gameobject\res_collection.cpp:143
ERROR:CRASH: 11 0x7FF6ED1317C0 dmGameObject::ResCollectionCreate D:\a\defold\defold\engine\gameobject\src\gameobject\res_collection.cpp:261
ERROR:CRASH: 12 0x7FF6ED1B3780 dmResource::CreateResource D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:546
ERROR:CRASH: 13 0x7FF6ED1B3C10 dmResource::PreloaderTryPruneParent D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:684
ERROR:CRASH: 14 0x7FF6ED1B3C10 dmResource::PreloaderTryPruneParent D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:686
ERROR:CRASH: 15 0x7FF6ED1B3C10 dmResource::PreloaderTryPruneParent D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:686
ERROR:CRASH: 16 0x7FF6ED1B3C10 dmResource::PreloaderTryPruneParent D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:686
ERROR:CRASH: 17 0x7FF6ED1B3DA0 dmResource::DoPreloaderUpdateOneReq D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:812
ERROR:CRASH: 18 0x7FF6ED1B40B0 dmResource::PreloaderUpdateOneItem D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:760
ERROR:CRASH: 19 0x7FF6ED1B3DA0 dmResource::DoPreloaderUpdateOneReq D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:823
ERROR:CRASH: 20 0x7FF6ED1B40B0 dmResource::PreloaderUpdateOneItem D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:760
ERROR:CRASH: 21 0x7FF6ED1B3DA0 dmResource::DoPreloaderUpdateOneReq D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:823
ERROR:CRASH: 22 0x7FF6ED1B40B0 dmResource::PreloaderUpdateOneItem D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:760
ERROR:CRASH: 23 0x7FF6ED1B3DA0 dmResource::DoPreloaderUpdateOneReq D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:823
ERROR:CRASH: 24 0x7FF6ED1B40B0 dmResource::PreloaderUpdateOneItem D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:760
ERROR:CRASH: 25 0x7FF6ED1B3DA0 dmResource::DoPreloaderUpdateOneReq D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:823
ERROR:CRASH: 26 0x7FF6ED1B40B0 dmResource::PreloaderUpdateOneItem D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:760
ERROR:CRASH: 27 0x7FF6ED1B1430 dmResource::UpdatePreloader D:\a\defold\defold\engine\resource\src\resource_preloader.cpp:951
ERROR:CRASH: 28 0x7FF6ED2C75F0 dmGameSystem::CompCollectionProxyUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_collection_proxy.cpp:250
ERROR:CRASH: 29 0x7FF6ED1C4540 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2555
ERROR:CRASH: 30 0x7FF6ED2492E0 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1642
ERROR:CRASH: 31 0x7FF6ED244200 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2177
ERROR:CRASH: 32 0x7FF6ED249D90 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83
ERROR:CRASH: 33 0x7FF6ED152250 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148
ERROR:CRASH: 34 0x7FF6ED446714 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 35 0x7FFE1DAF7330 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 36 0x7FFE1E442690 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 


```

```
local COMMON = require "libs.common"

go.property("atlas_empty", resource.atlas("/assets/images/icons/skins/skins_empty.atlas"))
go.property("atlas", resource.atlas("/assets/images/icons/skins/skins.atlas"))

function init(self)
--delay fixed it. Also when i try delay 1/60 i sometimes get error but sometimes not.
	--timer.delay(10/ 60, false, function()
		COMMON.skins_atlas = {
			animations = {}
		}
		local atlas = resource.get_atlas(self.atlas)
		for idx, geometry in ipairs(atlas.geometries) do
			local anim = atlas.animations[idx]
			local data = {
				id = anim.id,
			}
			COMMON.skins_atlas.animations[anim.id] = data
			COMMON.skins_atlas.animations[hash(anim.id)] = data
			if geometry.uvs[1] ~= geometry.uvs[3] then
				data.need_rotate = true
				local tc = geometry.vertices
				--add rotation to geometry
				local new_vertices = {
					tc[3], tc[4],
					tc[5], tc[6],
					tc[7], tc[8],
					tc[1], tc[2],
				}

				geometry.vertices = new_vertices--]]
				--now rotate uv and vertices to by 90
			end
		end
		resource.set_atlas(self.atlas_empty, atlas)
	--end)

end

```

**To Reproduce (REQUIRED)**
@Jhonnyg have access to my repository
https://github.com/d954mas/game-blocky-fighting/commit/fe20418d3216d7bae7a62620c69db20dba62d593

I try to make small repro case but i can't reproduce this error(

**Expected behavior (REQUIRED)**
Engine not crashed if i change atlas

**Defold version (REQUIRED):**
  - Version 1.7.0

**Platforms (REQUIRED):**
 - Platforms: Windown
 
**Workaround (OPTIONAL):**
I removed this atlas from game_scene.gui and also add timer.

But i can't be sure that game not crashed for users. If they open shop_scene.gui and liveupdate completed loading in same time.

**Additional context (OPTIONAL):**
https://forum.defold.com/t/replace-atlast-with-liveupdate-version/76540/9

### PR DESCRIPTION
**Pull request by Jhonnyg**
Fixed a crash where a call to resource.set_atlas(...) replaces the texture that was backing an atlas used in a GUI with a new texture resource. In this case, the engine was using the old texture resource pointer that was originally used in the atlas, whereas now we resolve the actual pointer being used instead.

Fixes #8786

### CODE REVIEW

File: engine/gamesys/src/dmsdk/gamesys/resources/res_gui.h [hunk 1]
```diff
@@ -32,29 +32,27 @@ namespace dmParticle
...
-    struct TextureResource;
-    struct TextureSetResource;
 
     struct GuiSceneTextureSetResource
     {
-        TextureSetResource* m_TextureSet;
-        TextureResource*    m_Texture;
+        void*   m_Resource;
+        uint8_t m_ResourceIsTextureSet : 1;
     };
```
Comment (Jhonnyg) [inline engine/gamesys/src/dmsdk/gamesys/resources/res_gui.h:40]: this is a dmsdk change, but nobody should be using these structs anyway. Perhaps we shouldn't even expose the struct here.

**Review by AGulev — APPROVED** [review]
