### PR TITLE
Fix crash when generating new root bone for models with multiple root bones

### LINKED ISSUE #9632: Model with 2 or more root bones crash editor
**Describe the bug (REQUIRED)**
After the update to 1.9.4 two of my projects crush when I am making a build or trying an open model with 2 or more root bones

**To Reproduce (REQUIRED)**
Add a model to the main collection with 1 or more roots bones
Another way is an open model with multiple roots 

**Expected behavior (REQUIRED)**
1. At least an error message that Defold doesn't support multiple roots

**Defold version (REQUIRED):**
1.9.4

**Platforms (REQUIRED):**
 - Platforms: Tested on Windows

**Minimal repro case project (OPTIONAL):**
I have shared a model that crushes editor on the forum:
https://forum.defold.com/uploads/short-url/c0Sambdxm5r0aEAdBFc22yDmHXW.zip

**Workaround (OPTIONAL):**
Recreate models that have one root

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/9632

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/modelc/src/modelimporter_jni.cpp [hunk 1]
```diff
@@ -194,16 +194,16 @@ static void CreateNodes(JNIEnv* env, dmModelImporter::jni::TypeInfos* types, con
 
         if (node->m_Parent != 0)
         {
-            dmJNI::SetObject(env, nodes[i], types->m_NodeJNI.parent, nodes[node->m_Parent->m_Index]);
+            dmJNI::SetObject(env, nodes[node->m_Index], types->m_NodeJNI.parent, nodes[node->m_Parent->m_Index]);
         }
 
         jobjectArray childrenArray = env->NewObjectArray(node->m_Children.Size(), types->m_NodeJNI.cls, 0);
-        for (uint32_t i = 0; i < node->m_Children.Size(); ++i)
+        for (uint32_t c = 0; c < node->m_Children.Size(); ++c)
```
Comment (JCash) [inline engine/modelc/src/modelimporter_jni.cpp:201]: Also, the loop var aliasing is unnecessarily confusing.

**Review by Jhonnyg — APPROVED** [review]
