### PR TITLE
Fix for crash caused by ray casting followed by deletion of the object

### LINKED ISSUE #3190: Crash when ray cast then delete as physics response in on_message() (DEF-3192)
STR:

1. Open project BUGS
2. Run DEF-3192
3. Wait until the two objects collide...

Boom

(LINK REMOVED)

### PR DESCRIPTION
**Pull request by AGulev**
Fixed a crash that occurs if `physics.raycast_async()` is called in the `on_message()` function and then the object is deleted immediately.

Fix https://github.com/defold/defold/issues/3190

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 1]
```diff
@@ -931,14 +927,18 @@ namespace dmGameSystem
...
+                    
                     dmPhysics::RayCastRequest request;
                     request.m_From = ddf->m_From;
                     request.m_To = ddf->m_To;
                     request.m_IgnoredUserData = sender_instance;
                     request.m_Mask = ddf->m_Mask;
                     request.m_UserId = component_index << 16 | (ddf->m_RequestId & 0xff);
-                    request.m_UserData = (void*)sender_instance;
-
+                    request.m_UserData = (void*)receiver;
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:941]: We can send URL instead of the instance. If object by URL doesn't exist, it will be just an error message, instead of crash

File: engine/gamesys/src/gamesys/components/comp_collision_object.cpp [hunk 2]
```diff
@@ -884,10 +880,10 @@ namespace dmGameSystem
             }
             else
             {
-                message_result = dmGameObject::PostDDF(&missed_ddf, 0x0, &receiver, 0x0, false);
+                message_result = dmGameObject::PostDDF(&missed_ddf, 0x0, (dmMessage::URL*)request.m_UserData, 0x0, false);
             }
         }
-
+        free(request.m_UserData);
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/components/comp_collision_object.cpp:886]: We have to free memory after allocation

**Review by britzl — APPROVED** [review]
