### PR TITLE
Some font glyphs are not rendering correctly

### LINKED ISSUE #7346: Fonts not rendering correctly when bundling project
**Describe the bug (REQUIRED)**

When bundling a project outside of the editor, the `.` character is not rendered at font size 16 px regardless of anti-aliasing.

Editor build:
c6fc9f86ecdfce9fe9b9342516d8f81f798dbf37

Release or debug build:
13f380f20e661f8c3a224e08036a186d1e0ac795

Tested on Windows and HTML. This occurred with two different fonts, so it is not a problem with the fonts themselves. Tested with both [monogram ](https://datagoblin.itch.io/monogram) and [m5x7](https://managore.itch.io/m5x7).

**To Reproduce (REQUIRED)**

1. Download example project.
2. Build for any platform outside of CTRL + B in the editor.
3. View result. The `.` characters are missing.

**Expected behavior (REQUIRED)**

All characters should be rendered at the supported font sizes.

**Defold version (REQUIRED):**

Tested on 1.4.1 and 1.4.2 (current).

**Platforms (REQUIRED):**

* Windows 11
* HTML

**Minimal repro case project (OPTIONAL):**

This project contains two GUI labels, one 32 px and one 16 px. The 16 px font does not render the `.`, but the 32 px font does. Monogram is used in this project.

Screenshot 2023-01-31 182416

Download: [example.zip](https://github.com/defold/defold/files/10552087/example.zip)

### PR DESCRIPTION
**Pull request by britzl**
Small glyphs, such as the dot (.) character, are not rendered correctly when the uncompressed size of the glyph is smaller than the compressed size. When this happens the first byte of the glyph is ignored and the glyph is rendered skewed or shifted one pixel in the font texture.

Fixes #7346

### CODE REVIEW

**Comment by britzl** [comment]
## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

File: engine/render/src/render/font_renderer.cpp [hunk 1]
```diff
@@ -664,9 +664,9 @@ namespace dmRender
 
                 uint8_t* glyph_data = (uint8_t*)(uint8_t*)font_map->m_GlyphData + g->m_GlyphDataOffset;
                 uint32_t glyph_data_size = g->m_GlyphDataSize-1; // The first byte is a header
-                uint8_t compression_type = *glyph_data++;
+                uint8_t is_compressed = *glyph_data++;
```
Comment (JCash) [inline engine/render/src/render/font_renderer.cpp:667]: Well, it _was_ intended to be compression type :)

**Review by JCash — APPROVED** [review]
