### PR TITLE
Handle 'path' option in http.request for html5 implementation.

### LINKED ISSUE #8234: Failed to rename ‘._httptmp’ to ‘’
**Describe the bug (REQUIRED)**

https://forum.defold.com/t/error-failed-to-rename-httptmp-to-n/74935

I have this error in poki dashboard.

‘’’
“DEFOLD:ERROR:SCRIPT: Failed to rename ‘._httptmp’ to ‘’\n”
‘’’
_httptmp failed to rename to empty string.

8% of user report error.
This is web build. I can't reproduce it.

https://github.com/defold/defold/blob/dev/engine/script/src/script_http_util.h#L26

Looks like path required. But you not set it value in http js version. What value have m_Path now.

So 8% of user get empty string '' in m_path, and 92% of user have 0 in m_path value.

https://github.com/defold/defold/blob/750368cbae6e010f68f8f4c71c244c59f1e0bda2/engine/script/src/script/http_ddf.proto#L40

I can be wrong but in js version of http.requests you can't use path.

Mb you need set it to 0 here?
https://github.com/defold/defold/blob/750368cbae6e010f68f8f4c71c244c59f1e0bda2/engine/script/src/script_http_js.cpp#L80

**To Reproduce (REQUIRED)**
Can't reproduce

**Expected behavior (REQUIRED)**
http.request not try to save something in path l

**Defold version (REQUIRED):**
  - Version 1.6.1

**Platforms (REQUIRED):**
 - Platforms: HTML5

### PR DESCRIPTION
**Pull request by ekharkunov**
Add 'path' parameter handling for html5 implementation in `http.request` function.

Fixes #8234 

### Technical changes
Previously #8234 can appeared because of default value in `dmHttpDDF::HttpResponse::mPath`. Here is part of generated source file
```cpp
char DM_ALIGNED(4) dmHttpDDF_HttpResponse_path_DEFAULT_VALUE[] = "\x00";
dmDDF::FieldDescriptor dmHttpDDF_HttpResponse_FIELDS_DESCRIPTOR[] = 
{
    { "status", 1, 5, 2, 0x0, (uint32_t)DDF_OFFSET_OF(dmHttpDDF::HttpResponse, m_Status), 0x0, 0, 0},
    { "headers", 2, 4, 2, 0x0, (uint32_t)DDF_OFFSET_OF(dmHttpDDF::HttpResponse, m_Headers), 0x0, 0, 0},
    { "headers_length", 3, 13, 2, 0x0, (uint32_t)DDF_OFFSET_OF(dmHttpDDF::HttpResponse, m_HeadersLength), 0x0, 0, 0},
    { "response", 4, 4, 2, 0x0, (uint32_t)DDF_OFFSET_OF(dmHttpDDF::HttpResponse, m_Response), 0x0, 0, 0},
    { "response_length", 5, 13, 2, 0x0, (uint32_t)DDF_OFFSET_OF(dmHttpDDF::HttpResponse, m_ResponseLength), 0x0, 0, 0},
    { "path", 6, 9, 2, 0x0, (uint32_t)DDF_OFFSET_OF(dmHttpDDF::HttpResponse, m_Path), dmHttpDDF_HttpResponse_path_DEFAULT_VALUE, 0, 0},
};
```
As we see default value for `m_Path` field is empty string. When we try to rename `._httptmp` to `m_Path` we checked only pointer, not content.

I've added handling of `path` property for html5 implementation because emscripten can work with fopen/fwrite api (it simulates filesystem https://emscripten.org/docs/getting_started/Tutorial.html#using-files. In my example it looks like
```lua
	http.request("", "GET", function(self, id, response)
		pprint(id)
		pprint(response)
	end, {}, nil, { path = "/data/test1.bin"})
```
Result is
Screenshot 2024-05-11 at 12 26 08

Screenshot 2024-05-11 at 12 26 28

⚠️ Pay attention that if `path` passed like './data/....' it doesn't work as expected. Path should be passed like '/data/....'.

## PR checklist

* [x] Code
	* [x] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [x] Documentation
	* [x] Make sure that API documentation is updated in code comments
	* [x] Make sure that manuals are updated (in github.com/defold/doc)
* [x] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [x] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [x] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/scripts/script_http.cpp [hunk 1]
```diff
@@ -93,7 +93,7 @@ namespace dmGameSystem
      * @param [options] [type:table] optional table with request parameters. Supported entries:
      *
      * - [type:number] `timeout`: timeout in seconds
-     * - [type:string] `path`: path on disc where to download the file. Only overwrites the path if status is 200. [icon:attention] Not available in HTML5 build
+     * - [type:string] `path`: path on disc where to download the file. Only overwrites the path if status is 200. [icon:attention] Path should be absolute
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/scripts/script_http.cpp:96]: What will happen if IndexedDB isn't supported?

Comment (ekharkunov) [reply engine/gamesys/src/gamesys/scripts/script_http.cpp:96]: https://emscripten.org/docs/api_reference/Filesystem-API.html#memfs
As I understand if no persistent storage is presented - in-memory FS will be used.

**Review by AGulev — APPROVED** [review]

File: engine/gamesys/src/gamesys/scripts/script_http_js.cpp [hunk 2]
```diff
@@ -214,6 +221,7 @@ namespace dmGameSystem
             ctx->m_Callback = callback;
             ctx->m_Requester = sender;
             ctx->m_RequestData = request_params.m_SendData;
+            ctx->m_Path = path;
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/scripts/script_http_js.cpp:224]: I got a bunch of issues using `path`: 

>"DEFOLD:ERROR:RESOURCE: Could not resolve a mount path '/dat+'\n"

>"DEFOLD:ERROR:RESOURCE: Could not resolve a mount path '�,�'\n"

>"DEFOLD:ERROR:RESOURCE: Could not resolve a mount path 'x7�'\n"

I take a look PR again, and see that we don't copy string to manage it ourself, so it's Lua that manages it.  I think we should memcopy this string as ell as we do for headers and free it when we don't need it anymore
