### PR TITLE
Visibility fixes and enhancements

### LINKED ISSUE #9818: Show/hide selected objects (Ctrl+E) does not work with models component.
Show/hide selected objects stopped working with the model component. This seems to have happened in version 1.9.5. Other components such as the GUI are hidden from the screen.

https://github.com/user-attachments/assets/833efabd-100a-4f6b-bd8a-80893bb14de5

<hr/>

<table>
<tr><td>Build time</td><td>2024-11-21T14:48:58.772099</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>addf94a3946b973a491a20b276314cb672835951</td></tr>
<tr><td>Defold engine sha</td><td>87b6907759f7b8dff830d54b2250b8d721bde291</td></tr>
<tr><td>Defold version</td><td>1.9.5</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.85</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by sprocketc**
Hide children of invisible nodes without toggling their visibility state, fix hiding models and double clicking on the visibility toggle.

Fixes #9818

### CODE REVIEW

File: editor/src/clj/editor/outline_view.clj [hunk 1]
```diff
@@ -489,7 +490,8 @@
                             (ui/add-style! "visibility-toggle")
                             (.addEventFilter MouseEvent/MOUSE_PRESSED ui/ignore-event-filter)
                             (AnchorPane/setRightAnchor 0.0))
-        text-label (Label.)
+        text-label (doto (Label.)
+                     (ui/bind-double-click! :open))
```
Comment (sprocketc) [inline editor/src/clj/editor/outline_view.clj:494]: Moved the double click handler on the label to avoid opening the resource when we double click on the visibility toggle. I think this move makes sense regardless of the bug.

**Comment by sprocketc** [comment]
This PR changes the behavior of `editor.scene-visibility` to hide children of invisible parents, without adding their `node-outline-key-path` to `hidden-outline-name-paths`. The outline tree was also modified to change the opacity of those children without displaying the toggle. I think this is more intuitive, but it might affect the current workflow of some users, so I would appreciate some feedback on this. Not persisting the visibility state when we close the editor, reduces the chance of frustration. It's probably also less prone to bugs similar to #9818, that is indirectly fixed by this PR (probably introduced [here](https://github.com/defold/defold/pull/8769/files#diff-6046ca4ceae4f8cffb0e51b10ea675540542b33302ca3f504b334e1140cd25ffR324-R342)).

File: editor/src/clj/editor/outline_view.clj [hunk 2]
```diff
@@ -134,6 +134,7 @@
                 :child-error? (boolean (some :child-error? data))
                 :child-overridden? (boolean (some :child-overridden? data))
                 :hideable? (contains? outline-name-paths (rest node-outline-key-path))
+                :hidden-parent? (scene-visibility/hidden-outline-key-path? hidden-node-outline-key-paths node-outline-key-path)
```
Comment (sprocketc) [inline editor/src/clj/editor/outline_view.clj:137]: Do we have a preference on boolean naming? I am leaning towards using a question mark on predicate methods only, but I don't mind either way. Removing `?` also feels inadequate in some cases, so having a general rule will make the decision easier.

Comment (matgis) [reply editor/src/clj/editor/outline_view.clj:137]: Yes, these days we tend to reserve the `?` suffix for predicates, and often prefixing booleans with words like `is-`, `has-`, `should-`, and `will-` when appropriate.

I don't really mind us following the convention of the surrounding code like this, though.

File: editor/src/clj/editor/scene_visibility.clj [hunk 3]
```diff
@@ -154,20 +154,12 @@
...
-                                                         (outline-name-paths-by-selection-state true)))
-
-  (output unselected-outline-name-paths OutlineNamePaths (g/fnk [outline-name-paths-by-selection-state]
-                                                           (outline-name-paths-by-selection-state false)))
+  (output selected-outline-name-paths OutlineNamePaths (g/fnk [outline-selection]
+                                                         (set (into [] (keep outline-selection-entry->outline-name-path) outline-selection))))
+
+  (output unselected-outline-name-paths OutlineNamePaths (g/fnk [selected-outline-name-paths outline-name-paths]
+                                                           (set/difference outline-name-paths selected-outline-name-paths)))
+
```
Comment (matgis) [inline editor/src/clj/editor/scene_visibility.clj:162]: I think we should `:cache` these outputs now that they are no longer trivial to evaluate?

File: editor/src/clj/editor/scene_visibility.clj [hunk 4]
```diff
@@ -260,9 +252,7 @@
            (g/node-value scene-visibility :active-scene-resource-node evaluation-context))
   (run [scene-visibility user-data]
        (let [{:keys [node-outline-key-path]} user-data
-             outline-name-paths (g/node-value scene-visibility :outline-name-paths)
-             name-path-child? #(iutil/seq-starts-with? % (rest node-outline-key-path))
-             name-paths-to-toggle (set (filter name-path-child? outline-name-paths))]
+             name-paths-to-toggle #{(vec (rest node-outline-key-path))}]
```
Comment (matgis) [inline editor/src/clj/editor/scene_visibility.clj:255]: Would it be better to use `subvec` here?

**Review by matgis — CHANGES_REQUESTED** [review]
I think we should perhaps `:cache` the `OutlineNamePaths` outputs of `SceneVisibilityNode` now that they are not trivial to produce.

**Review by matgis — APPROVED** [review]
Looks good to me! 👍
