### PR TITLE
Fix Console not working when the custom resolution feature is enabled

### LINKED ISSUE #11141: Console may not work when using custom resolution
### Expected behaviour

The console is always connected to the build.

### Actual behaviour

1. When using a custom extension, the console may not connect after assembling the build. Rebuild helps with this.
2. If the build was closed by error, the error may not be in the console. But you can find the error in the **log file**.

Example:

I have this code in the script:

```
M.GUI = {
	[M.Screen] = 1
}
```

`M.Screen` is **nil**.

1. **With custom resolution**, the application closes immediately after the build. Console info:

```
INFO:DLIB: Log server started on port 53617
INFO:ENGINE: Target listening with name: SSV-PC - 192.168.1.11 - Windows
INFO:ENGINE: Engine service started on port 53618
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
```
2. **Without custom resolution**, the application closes immediately after the build. Console info:

```
INFO:DLIB: Log server started on port 53637
INFO:ENGINE: Target listening with name: SSV-PC - 192.168.1.11 - Windows
INFO:ENGINE: Engine service started on port 53638
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
INFO:ENGINE: Defold Engine 1.10.4 (1aafd0a)
INFO:PROFILER: Initialized Remotery (ws://127.0.0.1:17815/rmt)
INFO:ENGINE: Loading data from: build/default
INFO:SOUND: Mix format:
INFO:SOUND:   wFormatTag:       fffe  IEEE_FLOAT/PCM/EXTENSIBLE: 3 / 1 / fffe
INFO:SOUND:   nChannels:        8
INFO:SOUND:   nSamplesPerSec:   44100
INFO:SOUND:   nAvgBytesPerSec:  1411200
INFO:SOUND:   nBlockAlign:      32
INFO:SOUND:   wBitsPerSample:   32
INFO:SOUND:   -> Format:        3  IEEE_FLOAT/PCM/EXTENSIBLE: 3 / 1 / fffe
INFO:SOUND:   DSP backend: SSE
INFO:SOUND: Sound
INFO:SOUND:   nSamplesPerSec:   44100
INFO:ENGINE: Initialised sound device 'default'
ERROR:SCRIPT: main/main.script:4: table index is nil
stack traceback:
  main/main.script:4: in main chunk

WARNING:RESOURCE: Unable to create resource: /main/main.scriptc: FORMAT_ERROR
WARNING:RESOURCE: Unable to create resource: /_generated_375a1225.goc: FORMAT_ERROR
ERROR:GAMEOBJECT: Could not instantiate game object from prototype /_generated_375a1225.goc.
WARNING:RESOURCE: Unable to create resource: /main/main.collectionc: FORMAT_ERROR
```

### Steps to reproduce

1. Enable "Custom Resolution" option
2. Add this code to any script:

```
M = {}

M.GUI = {
	[M.Screen] = 1
}
```

[example.zip](https://github.com/user-attachments/files/21986504/example.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2025-08-04T15:29:15.191640</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1aafd0a262ff40214ed7f51302d92fa587c607ef</td></tr>
<tr><td>Defold engine sha</td><td>1aafd0a262ff40214ed7f51302d92fa587c607ef</td></tr>
<tr><td>Defold version</td><td>1.10.4</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.11.1.231017</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Fixes the issue where logs in the Editor's console don't work when Simulated Resolution is used (Windows only).

Fix https://github.com/defold/defold/issues/11141

### CODE REVIEW

File: editor/src/clj/editor/app_view.clj [hunk 1]
```diff
@@ -809,8 +809,19 @@
...
+          (let [max-wait-ms 2000
+                step-ms 100
+                deadline (+ (System/currentTimeMillis) max-wait-ms)]
+            (loop []
+              (if (or (console/current-stream? (:log-stream @updated-target))
+                      (>= (System/currentTimeMillis) deadline))
+                (on-service-url-found @updated-target)
+                (do
+                  (Thread/sleep step-ms)
+                  (recur)))))))
```
Comment (AGulev) [inline editor/src/clj/editor/app_view.clj:824]: It is basically this logic I thought we don't need anymore https://github.com/defold/defold/pull/10759/files (with some additions)

**Review by vlaaad — APPROVED** [review]
LGTM!
