### PR TITLE
Defedit 5471 debug connect exception fix

### LINKED ISSUE #5471: Debugger fails to launch with a SocketTimeoutException error
### Expected behaviour

Defold starts the game and attaches the debugger.

### Actual behaviour

The `dmengine.exe` goes unresponsive and a `SocketTimeoutException` error occurs.

### Steps to reproduce

1. Open the `Linker sample game` project.
2. Go to Debug > Start / Attach.
3. A blank `dmengine.exe` window flashes before the "An Error Occurred"  dialog pops-up showing `java.net.SocketTimeoutException: connect timed out`. The `dmengine.exe` is unresponsive.
4. Repeated attempts consistently reproduces the error; regular builds however do seem to work just fine.

**Notes:** Firewall is opened for `dmengine.exe` as well as the Defold OpenJDK binary. I tried launching Defold as Administrator and the same thing happens. I got it to work once, one of the first times I ran it, but every subsequent attempt has failed. I ensured there were no lingering instances running (rebooted my computer and double-checked Task Manager). I'm going to try downgrading to see if it helps.

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-15T17:32:44.177461</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>15c3fb12f092d565bb8d549a961e91ff78f97528</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ac11c29f35d946deab86c4e1a6ce68e6"'>ac11c29f35d946deab86c4e1a6ce68e6</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.8935</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #5536: Timeout error
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-01T12:51:48.993319</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ce404156136f291c4f2c33a72b28f7bd923eb5e</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2d3fc2d550844bd1a0028304ef7b3e77"'>2d3fc2d550844bd1a0028304ef7b3e77</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.5129</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: editor/src/clj/editor/debugging/mobdebug.clj [hunk 1]
```diff
@@ -326,7 +326,7 @@
   (try
     (doto (Socket.)
       (.connect (InetSocketAddress. ^String address (int port)) 2000))
-    (catch java.net.ConnectException _ nil)))
+    (catch java.lang.Exception _ nil)))
```
Comment (JCash) [inline editor/src/clj/editor/debugging/mobdebug.clj:329]: We want to catch the SocketTimeoutException too

Comment (britzl) [reply editor/src/clj/editor/debugging/mobdebug.clj:329]: Good! It makes sense to have very broad exception catching in this case.

**Review by britzl — APPROVED** [review]
