### PR TITLE
Misc gpu skinning fixes

### LINKED ISSUE #10383: [1.9.9 beta] GPU skinning issues
I found the following issues:
1. if I set a simple built-in model material for a model having an animation, I get an error: `ERROR:GAMESYS: Unable to bind bone matrix cache texture for component 'id name', no free texture slot available.` It seems that there is no possibility to use simple material without skinning for models containing animation inside the file.

2. My model (made in Blockbench then re-saving .glb in Blender) doesn't work properly with GPU skinning material (looks distorted), maybe some information is missing in the model or it is in the wrong format. But it worked in the project with `world space` material and animation on CPU. I known the other devs have similar issue with their own models .
3.  Another interesting thing is that if there are two identical models on the scene, one has no animation set and the other has it, both play animation.

See the video (1-3):

https://github.com/user-attachments/assets/33e863ce-f64f-4bb7-83b0-dd43fc3aa820

4. And finally I tried adding the Rogue_Hooded.glb model from the free [KayKit Adventures kit](https://kaylousberg.itch.io/kaykit-adventurers) (model size 3.5Mb, 6k triangles) and unfortunately found that the editor shut down instantly without even saving any error to the log file on my PC. 

Image

A small project for testing. Contains only camera and one model and also contains the Rogue_Hooded.glb model.
[gpu_test.zip](https://github.com/user-attachments/files/19460650/gpu_test.zip)

Image

<hr/>

<table>
<tr><td>Build time</td><td>2025-03-25T10:24:48.959290</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>ce4a711a01b9906e1496438d9420406162f18334</td></tr>
<tr><td>Defold engine sha</td><td>ce4a711a01b9906e1496438d9420406162f18334</td></tr>
<tr><td>Defold version</td><td>1.9.9</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.85</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by Jhonnyg**
Fixes #10383

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 1]
```diff
@@ -175,8 +176,6 @@ namespace dmGameSystem
     static const dmhash_t PROP_CURSOR        = dmHashString64("cursor");
     static const dmhash_t PROP_PLAYBACK_RATE = dmHashString64("playback_rate");
 
-    static const dmhash_t NAME_POSE_MATRIX_CACHE = dmHashString64("pose_matrix_cache");
```
Comment (Jhonnyg) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:178]: Moved to render.h

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 2]
```diff
@@ -1079,6 +1089,34 @@ namespace dmGameSystem
     }
     #endif
 
+    static void SetupSkinnedMatrixCache(dmRender::RenderObject& ro, dmGraphics::HTexture cache_texture, int32_t first_free_index, dmGameObject::HInstance instance)
+    {
+        if (dmRender::GetMaterialHasSkinnedMatrixCache(ro.m_Material))
```
Comment (Jhonnyg) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:1094]: We only want to even attempt binding the cache if we _can_ do so.

File: engine/gamesys/src/gamesys/components/comp_model.cpp [hunk 3]
```diff
@@ -1092,7 +1130,7 @@ namespace dmGameSystem
 
     static inline dmGraphics::HVertexDeclaration GetBaseVertexDeclaration(ModelWorld* world, dmRender::HMaterial material, bool has_skin_data)
     {
-        return has_skin_data && dmRender::GetMaterialHasSkinnedAttributes(material) ? world->m_VertexDeclarationSkinned : world->m_VertexDeclaration;
+        return has_skin_data ? world->m_VertexDeclarationSkinned : world->m_VertexDeclaration;
```
Comment (Jhonnyg) [inline engine/gamesys/src/gamesys/components/comp_model.cpp:1133]: We need to use the skinned vertex declaration even if the material doesn't have skinned attributes. We will only bind the streams from the declaration that exist anyway.

**Review by JCash — APPROVED** [review]
