### PR TITLE
Fix performance issues when rendering many text fields

### LINKED ISSUE #11933: Enabling Profiler Causes a Huge Performance Impact on HTML5 Mobile
Enabling the profiler, building from the editor as HTML5, and running it in a mobile browser causes a huge performance drop.
This is probably related to the new font system(just guessing).

Default Basic 3D project with profiler. It works fine without it.
Image

<hr/>

<table>
<tr><td>Build time</td><td>2026-02-18T11:57:00.638558</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>099f6016f46c7188d29d7549ef4a7bcfae2d1a60</td></tr>
<tr><td>Defold engine sha</td><td>099f6016f46c7188d29d7549ef4a7bcfae2d1a60</td></tr>
<tr><td>Defold version</td><td>1.12.3</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 89.4</td></tr>
<tr><td>Java version</td><td>25+36-LTS</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>15.7.3</td></tr>
<table>

### PR DESCRIPTION
**Pull request by AGulev**
Fix performance issue when rendering many text fields on the screen

Fix https://github.com/defold/defold/issues/11933

### CODE REVIEW

File: engine/render/src/render/font/default/font_default_vertex.cpp [hunk 1]
```diff
@@ -350,20 +348,6 @@ uint32_t CreateFontVertexData(HFontRenderBackend backend, HFontMap font_map, uin
...
-    {
-        sdf_scale = dmMath::Max(sdf_scale, min_sdf_screen_scale);
-    }
-    else
-    {
-        // Fallback to local scale when screen scale is invalid.
-        const Vector4 r0 = te.m_Transform.getRow(0);
-        sdf_scale = sqrtf(r0.getX() * r0.getX() + r0.getY() * r0.getY());
-        sdf_scale = dmMath::Max(sdf_scale, min_sdf_scale);
-    }
```
Comment (AGulev) [inline engine/render/src/render/font/default/font_default_vertex.cpp:366]: Consolidate all the sdf scale related calculations in one place

File: engine/render/src/render/font/font_renderer.cpp [hunk 2]
```diff
@@ -165,36 +164,25 @@ namespace dmRender
...
-        (void)vp_y;
-
-        if (vp_w == 0 || vp_h == 0)
-        {
-            return 0.0f;
-        }
-
-        float half_w = 0.5f * (float)vp_w;
-        float half_h = 0.5f * (float)vp_h;
-
```
Comment (AGulev) [inline engine/render/src/render/font/font_renderer.cpp:184]: Move out data fetching out of the function to move out it from the for loop

File: engine/render/src/render/font/font_renderer.cpp [hunk 3]
```diff
@@ -165,36 +164,25 @@ namespace dmRender
...
         {
-            return 0.0f;
+            return dmMath::Max(scale, min_sdf_screen_scale);
         }
-        return scale;
+
+        // Fallback to local scale when screen scale is invalid.
+        const Vector4 r0 = world_transform.getRow(0);
+        float local_scale = sqrtf(r0.getX() * r0.getX() + r0.getY() * r0.getY());
+        return dmMath::Max(local_scale, min_sdf_scale);
```
Comment (AGulev) [inline engine/render/src/render/font/font_renderer.cpp:185]: moved from font_default_vertex.cpp‎

File: engine/render/src/render/font/font_renderer.cpp [hunk 4]
```diff
@@ -373,13 +361,44 @@ namespace dmRender
...
+            {
+                calc_sdf_scale = false;
+            }
+            else
+            {
+                sdf_view_proj = &render_context->m_ViewProj;
+                sdf_half_w = 0.5f * (float)vp_w;
+                sdf_half_h = 0.5f * (float)vp_h;
+            }
+        }
```
Comment (AGulev) [inline engine/render/src/render/font/font_renderer.cpp:389]: Keep only text field related math in `CalcSdfScale`

File: engine/render/src/render/font/font_renderer.cpp [hunk 5]
```diff
@@ -373,13 +361,44 @@ namespace dmRender
         // The cache size may have changed, and we need to update the font map glyph texture
         UpdateCacheTexture(font_map);
 
+        bool calc_sdf_scale = font_map->m_IsSdf;
```
Comment (AGulev) [inline engine/render/src/render/font/font_renderer.cpp:364]: Do not calculate SDF scale if it's not an SDF font

File: engine/render/src/render/font/fontmap_private.h [hunk 6]
```diff
@@ -110,6 +110,8 @@ namespace dmRender
         uint8_t                 m_DynamicCacheSize:1;
         uint8_t                 m_IsCacheSizeTooSmall:1;
         uint8_t                 m_CacheChannels:3;      // Number of channels (1-4)
+        uint8_t                 m_IsSdf:1;
+        uint8_t                 :7;
```
Comment (AGulev) [inline engine/render/src/render/font/fontmap_private.h:114]: we don't have this extra bit in the structure, it's annoying to add it, but it's per font map, we don't have that many of them

File: engine/render/src/render/font/font_renderer.cpp [hunk 7]
```diff
@@ -373,13 +361,44 @@ namespace dmRender
...
+        const Matrix4* sdf_view_proj = 0x0;
```
Comment (JCash) [inline engine/render/src/render/font/font_renderer.cpp]: In terms of optimizing, copying this onto the stack may help, as the compiler could then (possibly) detect this and make assumptions about the code flow.
If it _actually_ helps would have to be inspected in the generated code of course.

**Review by JCash — DISMISSED** [review]
lgtm.

File: engine/render/src/render/font/font_renderer.cpp (hunk 7 above)
Comment (AGulev) [reply engine/render/src/render/font/font_renderer.cpp]: you right, having it on stack help to avoid a few loads from memory operations per iteration
