### PR TITLE
Issue 5524: Make iOS Vulkan(Metal) builds work again

### LINKED ISSUE #5524: Make iOS work again with our Vulkan (Metal) backend
It builds, but when running it, it fails on:
```
On-screen rendering requires a layer of type CAMetalLayer.
ERROR:GRAPHICS: Could not create window surface for Vulkan, reason: VK_ERROR_INITIALIZATION_FAILED.
FATAL:ENGINE: Could not open window (-2).
```

It seems we don't do the correct implementation of the `layerClass`function, so that the device instead chooses the default EAGL layer.

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

File: engine/glfw/lib/ios/app/ViewController.m [hunk 1]
```diff
@@ -18,7 +18,7 @@
 #import "EAGLView.h"
 
 extern int g_IsReboot;
-static int g_view_type = GLFW_OPENGL_API;
+static int g_view_type = GLFW_NO_API;
```
Comment (JCash) [inline engine/glfw/lib/ios/app/ViewController.m:21]: Defaulting to Vulkan (Metal) lets us avoid adding the dependency of the glfw library for the graphics_vulkan.cpp. This is good since we don't want to use that for Switch.

File: engine/graphics/src/opengl/graphics_opengl.cpp [hunk 2]
```diff
@@ -307,6 +307,17 @@ static void LogFrameBufferError(GLenum status)
         } \
     } \
 
+
+    #if defined(__MACH__) && ( defined(__arm__) || defined(__arm64__) || defined(IOS_SIMULATOR) )
+    struct ChooseEAGLView
+    {
+        ChooseEAGLView() {
+            // Let's us choose the CAEAGLLayer
+            glfwSetViewType(GLFW_OPENGL_API);
```
Comment (JCash) [inline engine/graphics/src/opengl/graphics_opengl.cpp:316]: The previous call to the glfwSetViewType happened too late.

**Review by britzl — APPROVED** [review]
