### PR TITLE
Fix iOS bundling without signing

### LINKED ISSUE #9816: Can't bundle ios with unchecked option 'Sign application'
### Expected behaviour
It's possible to bundle ios application without signing it.

### Actual behaviour
When click 'Create Bundle' in the Bundle dialog error appears. Error look like
```
clojure.lang.ExceptionInfo: handler ':editor.bundle-dialog/query-output-directory' in context ':bundle-dialog' failed at ':run' with message 'Invalid new value at prefs path [:bundle :ios :code-signing-identity]: '
clojure.lang.ExceptionInfo: Invalid new value at prefs path [:bundle :ios :code-signing-identity]: 
```
Seems related to editor's preferences.

### Steps to reproduce
1. Open any project
2. Got to Project->Bundle->iOS Application
3. Uncheck 'Sign Application'
4. Click 'Create Bundle'

<hr/>

<table>
<tr><td>Build time</td><td>2024-11-15T16:18:56.086493</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f6671fed2fe0581b090687969de0d588311634e7</td></tr>
<tr><td>Defold engine sha</td><td>edfdbe31830c1f8aa4d96644569ae87a8ea32672</td></tr>
<tr><td>Defold version</td><td>1.9.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5ec53b32045342ed9890d6c3a4b7e4ca"'>5ec53b32045342ed9890d6c3a4b7e4ca</a></td></tr>
<tr><td>GPU</td><td>Apple M3 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 89.3</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>15.0.1</td></tr>
<table>

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #9816

### CODE REVIEW

File: editor/src/clj/editor/bundle_dialog.clj [hunk 1]
```diff
@@ -721,7 +721,7 @@
                           install-app-check-box
                           launch-app-check-box]
     (prefs/set! prefs [:bundle :ios :sign] (ui/value sign-app-check-box))
-    (set-string-pref! prefs [:bundle :ios :code-signing-identity] (ui/value code-signing-identity-choice-box))
+    (set-string-pref! prefs [:bundle :ios :code-signing-identity] (or (ui/value code-signing-identity-choice-box) ""))
```
Comment (vlaaad) [inline editor/src/clj/editor/bundle_dialog.clj:724]: `(ui/value code-signing-identity-choice-box)` could return `nil` if there were no code-signing identities found. In this case, we fall back to `""`. There are other choice boxes used in this file, but those all have a non-empty list of options and a default, so in the other cases it's impossible to get `nil`.

**Review by matgis — APPROVED** [review]
Ship it!
