### PR TITLE
Crash when using sound resource properties

### LINKED ISSUE #7050: App crashes when playing sound
**Describe the bug (REQUIRED)**
the android (and windows) application crashes after a few plays of the sound loaded through the resources.

**To Reproduce (REQUIRED)**
press random buttons to play a sound, after a few clicks (10-20+) the application crashes to android.
if you comment out the 7th line in the manager script file (stop the sound), then the application launched in the editor crashes to Windows with a crash too.

**Expected behavior (REQUIRED)**
app won't crash

**Defold version (REQUIRED):**
  - Version 1.3.6

**Platforms (REQUIRED):**
 - Platforms: Android, Windows

**Minimal repro case project (OPTIONAL):**
[SndCrash.zip](https://github.com/defold/defold/files/9751311/SndCrash.zip)

**Logs (OPTIONAL):**
`10-11 10:16:03.904 16564 16586 V threaded_app: New input event: type=2
10-11 10:16:03.921 16564 16588 D defold  : DEBUG:SCRIPT: play   /sounds/15.ogg
10-11 10:16:03.932 16564 16604 W defold  : WARNING:SOUND: Unable to decode file '/sounds/11.oggc'. Result -3
10-11 10:16:03.967 16564 16588 I defold  : INFO:CRASH: Successfully wrote Crashdump to file: /data/user/0/com.example.todo/files/_crash
10-11 10:16:03.967 16564 16588 E defold  : ERROR:CRASH: CALL STACK:
10-11 10:16:03.967 16564 16588 E defold  :
10-11 10:16:03.967 16564 16588 E defold  : # 0 pc     0x236d20 ...iCXXw==/lib/arm64/libSndCrash.so <unknown>+0
10-11 10:16:03.967 16564 16588 E defold  : # 1 pc        0x244 ...android.art/lib64/libsigchain.so _ZN3art11SignalChain7HandlerEiP7siginfoPv+440
10-11 10:16:03.967 16564 16588 E defold  :
10-11 10:16:03.967 16564 16588 E defold  :
10-11 10:16:03.967 16564 16588 F libc    : exiting due to SIG_DFL handler for signal 11, ucontext 0x7505fcfe20
10-11 10:16:03.983 16564 16588 I defold  : INFO:CRASH: Successfully wrote Crashdump to file: /data/user/0/com.example.todo/files/_crash
10-11 10:16:03.983 16564 16588 E defold  : ERROR:CRASH: CALL STACK:
10-11 10:16:03.983 16564 16588 E defold  :
10-11 10:16:03.983 16564 16588 E defold  : # 0 pc     0x236d20 ...iCXXw==/lib/arm64/libSndCrash.so <unknown>+0
10-11 10:16:03.983 16564 16588 E defold  : # 1 pc        0x664 [vdso] <unknown>+0
10-11 10:16:03.983 16564 16588 E defold  : # 2 pc      0x43c44 ...oid.runtime/lib64/bionic/libc.so abort+164
10-11 10:16:03.983 16564 16588 E defold  :
10-11 10:16:03.983 16564 16588 E defold  :
10-11 10:16:04.069  1548  9293 I ActivityManager: Process com.example.todo (pid 16564) has died: fg  TOP`
Crash logs (windows/android)
[crash.zip](https://github.com/defold/defold/files/9751313/crash.zip)

### PR DESCRIPTION
**Pull request by AGulev**
Fix crash that happening when set a sound resource for a sound component that has playing sounds.

Fix https://github.com/defold/defold/issues/7050

### CODE REVIEW

File: engine/gamesys/src/gamesys/resources/res_sound_data.cpp [hunk 1]
```diff
@@ -54,13 +60,20 @@ namespace dmGameSystem
 
     dmResource::Result ResSoundDataRecreate(const dmResource::ResourceRecreateParams& params)
     {
-        dmSound::HSoundData sound_data = (dmSound::HSoundData) params.m_Resource->m_Resource;
-        dmSound::Result r = dmSound::SetSoundData(sound_data, params.m_Buffer, params.m_BufferSize);
+        dmSound::SoundDataResource* sound_data_res = (dmSound::SoundDataResource*) params.m_Resource->m_Resource;
+
+        dmSound::HSoundData sound_data;
+        dmSound::SoundDataType type = dmSound::SOUND_DATA_TYPE_OGG_VORBIS;
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/resources/res_sound_data.cpp:66]: it's not done yet, I'll add a function to detect a filetype

File: engine/gamesys/src/gamesys/resources/res_sound_data.cpp [hunk 2]
```diff
@@ -18,6 +18,21 @@
 
 namespace dmGameSystem
 {
+
+    dmSound::SoundDataType TryToGetTypeFromBuffer(char* m_Buffer, dmSound::SoundDataType default_type)
+    {
+        dmSound::SoundDataType type = default_type;
+        if (m_Buffer[0] == 'O' && m_Buffer[1] == 'g' && m_Buffer[2] == 'g')
```
Comment (AGulev) [inline engine/gamesys/src/gamesys/resources/res_sound_data.cpp:25]: positions according to format spec

Comment (JCash) [reply engine/gamesys/src/gamesys/resources/res_sound_data.cpp:25]: What happens if someone sets a bad data to it, e.g. the byuffer length is smaller than 11 bytes?

Comment (JCash) [reply engine/gamesys/src/gamesys/resources/res_sound_data.cpp:25]: Also, unless the function is used in a unit test, it can be `static`

File: engine/gamesys/src/gamesys/resources/res_sound_data.h [hunk 3]
```diff
@@ -18,8 +18,18 @@
...
+namespace dmSound
+{
+    typedef struct SoundData* HSoundData;
+}
+
 namespace dmGameSystem
 {
+    struct SoundDataResource {
+        dmSound::HSoundData m_SoundData;
+        int m_Type;
```
Comment (JCash) [inline engine/gamesys/src/gamesys/resources/res_sound_data.h:30]: 👍

File: engine/sound/src/sound.cpp [hunk 4]
```diff
@@ -518,6 +520,11 @@ namespace dmSound
 
     Result DeleteSoundData(HSoundData sound_data)
     {
+        sound_data->m_RefCount --;
+        if (sound_data->m_RefCount > 0)
+        {
+            return RESULT_OK;
+        }
```
Comment (JCash) [inline engine/sound/src/sound.cpp:527]: Since it _is_ a threaded system, I would rather like it for this alteration to be done _inside_ the mutex lock.

We might move it back out later, when it's clearer how this may be used from different threads (but then I suspect we need another spinlock or something)

**Review by JCash — DISMISSED** [review]
LGTM.
A small request to move the increment/decrement within the lock scopes.

**Review by JCash — APPROVED** [review]
