### PR TITLE
Fix for double destroying the timer callback

### LINKED ISSUE #9407: Callbacks Crash
Sometimes I can get a crash. It looks like some callback has already been removed, and they are trying to remove it again.

I use the [**flow**](https://github.com/britzl/ludobits/blob/master/ludobits/m/flow.lua) module.
This happens when you click the button to go to another collection. If you call **collectgarbage**, there is no crash.

    collectgarbage()
    monarch.show(msgs.SCREEN, nil, {})

Also, the crash does not occur every time. If you wait 5-10 seconds, everything will be fine

Crash:

    INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\Sergey\AppData\Roaming\Defold/_crash
    ERROR:CRASH: CALL STACK:
    
    ERROR:CRASH:  0 0x7FF7921E1220 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
    ERROR:CRASH:  1 0x7FF792494004 _seh_filter_exe /tmp/job337407127158997133/minkernel/crts/ucrt/src/appcrt/misc/exception_filter.cpp:219
    ERROR:CRASH:  2 0x7FF7924E7411 `__scrt_common_main_seh'::`1'::filt$0 D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304
    ERROR:CRASH:  3 0x7FF792452228 __C_specific_handler D:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:389
    ERROR:CRASH:  4 0x7FFC330B2810 __chkstk <unknown>:0
    ERROR:CRASH:  5 0x7FFC330620D0 RtlRaiseException <unknown>:0
    ERROR:CRASH:  6 0x7FFC330B1410 KiUserExceptionDispatcher <unknown>:0
    ERROR:CRASH:  7 0x7FF7921D6C60 lua_gettop <unknown>:0
    ERROR:CRASH: 
    
    INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\Sergey\AppData\Roaming\Defold/_crash
    ERROR:CRASH: CALL STACK:
    
    ERROR:CRASH:  0 0x7FF7921D6C60 lua_gettop <unknown>:0
    ERROR:CRASH:  1 0x7FF792202470 dmScript::DestroyCallback D:\a\defold\defold\engine\script\src\script.cpp:1644
    ERROR:CRASH:  2 0x7FF7922DCFA0 dmScript::FreeTimer D:\a\defold\defold\engine\script\src\script_timer.cpp:176
    ERROR:CRASH:  3 0x7FF7922DC100 dmScript::UpdateTimers D:\a\defold\defold\engine\script\src\script_timer.cpp:271
    ERROR:CRASH:  4 0x7FF7922DC0A0 dmScript::TimerUpdateScriptWorld D:\a\defold\defold\engine\script\src\script_timer.cpp:466
    ERROR:CRASH:  5 0x7FF792203C70 dmScript::UpdateScriptWorld D:\a\defold\defold\engine\script\src\script.cpp:1139
    ERROR:CRASH:  6 0x7FF7921C03C0 dmGameSystem::CompGuiUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_gui.cpp:2438
    ERROR:CRASH:  7 0x7FF7922395B0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2617
    ERROR:CRASH:  8 0x7FF79234DB50 dmGameSystem::CompCollectionProxyUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_collection_proxy.cpp:381
    ERROR:CRASH:  9 0x7FF7922395B0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2617
    ERROR:CRASH: 10 0x7FF7922C5740 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1710
    ERROR:CRASH: 11 0x7FF7922C0510 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2245
    ERROR:CRASH: 12 0x7FF7922C61E0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83
    ERROR:CRASH: 13 0x7FF7921CE660 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
    ERROR:CRASH: 14 0x7FF792451DD4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    ERROR:CRASH: 15 0x7FFC31437360 BaseThreadInitThunk <unknown>:0
    ERROR:CRASH: 16 0x7FFC3305CC70 RtlUserThreadStart <unknown>:0
    ERROR:CRASH: 
 
    INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\Sergey\AppData\Roaming\Defold/_crash.dmp

[crash.zip](https://github.com/user-attachments/files/16943678/crash.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-09T09:58:13.383911</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7b332ee8234aa1a5a7e4a54f36c4eae5c623d3d7</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.11.1.231017</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### LINKED ISSUE #9491: Crash if call flow.start recursive
**Describe:**
Crash if call flow.start recursive

**To Reproduce:**
```
local flow = require("ludobits.m.flow")
function boo(on_end)
        return flow.start(
            function()
                local i = 0
                while i < 10 do
                    flow.frames(1)
                    if i % 2 == 0 then
                        boo(on_end)
                    end
                    i = i + 1
                end
            end,
            {parallel = true}
        )
end
```
Call `
boo(function()
            print("END")
        end)
` 

**Defold version:**
 - Version 1.9.3

**Platforms:**
 - Platforms: [Windows, macOS, HTML5]
 - OS: [macOS Sonoma Version 14.6.1]

**Ludobits version:**
- [Version 7.4.0](https://github.com/britzl/ludobits/releases/tag/7.4.0)

**Logs:**
[report.log](https://github.com/user-attachments/files/17160802/report.log)
[_crash.log](https://github.com/user-attachments/files/17160803/_crash.log)

### PR DESCRIPTION
**Pull request by JCash**
In rare cases, the timer callback was destroyed twice, causing a crash

Fixes https://github.com/defold/defold/issues/9491
Fixes https://github.com/defold/defold/issues/9407

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/dlib/src/dlib/set.h [hunk 1]
```diff
@@ -0,0 +1,366 @@
...
+
+#ifndef DM_SET_H
+#define DM_SET_H
+
+#include <assert.h>
+#include <stdint.h>
+#include <stdlib.h>
+#include <string.h>
+
+/*# Templatized set
```
Comment (JCash) [inline engine/dlib/src/dlib/set.h:23]: Added a Set() container.
Currently uses sorting + lower_bound as implementation, can be changed later if we need to.

Main purpose is to avoid using a HashTable to do quick lookups, as we wish to keep memory low.

File: engine/script/src/script_timer.cpp [hunk 2]
```diff
@@ -84,21 +75,22 @@ namespace dmScript
...
     struct TimerWorld
     {
-        dmArray<Timer>                      m_Timers;
-        dmArray<uint16_t>                   m_IndexLookup;
-        dmIndexPool<uint16_t>               m_IndexPool;
-        uint16_t                            m_Version;   // Incremented to avoid collisions each time we push timer indexes back to the m_IndexPool
-        uint16_t                            m_InUpdate : 1;
+        dmObjectPool<Timer> m_Timers;
+        dmSet<uint16_t>     m_Instances; // the pool indices
+        dmArray<uint16_t>   m_ScratchBuffer; // When doing operations on the timer instances, we need a copy to avoid self modification of m_Instances
```
Comment (JCash) [inline engine/script/src/script_timer.cpp:85]: The old implementation was essentially doing the same thing but more "manually".
Let's use our ObjectPool as it was intended.

File: engine/script/src/script_timer.cpp [hunk 3]
```diff
@@ -84,21 +75,22 @@ namespace dmScript
...
+        uint16_t            m_Version;   // Incremented to avoid collisions each time we push timer indexes back to the m_IndexPool
+        uint16_t            m_InUpdate : 1;
+        uint16_t            m_IsDirty : 1;
```
Comment (JCash) [inline engine/script/src/script_timer.cpp:88]: Bug fix for detecting if something was added/removed.

File: engine/script/src/script_timer.cpp [hunk 4]
```diff
@@ -198,21 +174,64 @@ namespace dmScript
...
+        {
+            tgt.SetCapacity(size);
+        }
+        tgt.SetSize(size);
+        for (uint32_t i = 0; i < size; ++i)
+        {
+            tgt[i] = src[i];
+        }
+        return size;
+    }
```
Comment (JCash) [inline engine/script/src/script_timer.cpp:211]: Since the object pool may change while iterating on it, we need to make a copy of the valid instances.
