### PR TITLE
Fixed crash when sprite material uses N samplers but shaders uses less than N samplers.

### LINKED ISSUE #8842: Adding a 3rd texture to a material results in a crash
**Describe the bug (REQUIRED)**
I have a sprite that represents a playing card that has 2 textures. One for the front and one for the back so that I can swap them in the fragment shader.
Just adding a third sampler for a normal map, makes the game crash on running.

**To Reproduce (REQUIRED)**
1. Open game.project
2. Select Project>Fetch Libraries
3. Build and run ( you should see a card back)
4. Open assets/materials/card/card.material
5. Add a 3rd sampler to Samplers using "+" called normal_sampler with the same settings as the 2 other samplers
6. Open main/objects/card/card.go
7. Select "sprite" in the outline
8. Select "assets/atlases/AC_normal.atlas" [NB: it doesn't matter which atlas is chosen] for the normal_sampler
9. Build and run to observe the crash

**Expected behavior (REQUIRED)**
No crash

**Defold version (REQUIRED):**
1.7.0

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: Sonoma
 - Device: MacBook Pro 14" M1

**Minimal repro case project (OPTIONAL):**
[Defold_multitexture_bug.zip](https://github.com/defold/defold/files/15091955/Defold_multitexture_bug.zip)

**Logs (OPTIONAL):**
INFO:DLIB: Log server started on port 50093
INFO:ENGINE: Target listening with name: orac-2.local - 10.0.0.13 - Darwin
INFO:ENGINE: Engine service started on port 50094
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
INFO:ENGINE: Defold Engine 1.7.0 (bf4dc66)
INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'
Assertion failed: (i < Size()), function operator[], file array.h, line 494.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/andy/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH: 0   dmengine                            0x000000010248cc88 _ZN7dmCrash7OnCrashEi + 104
ERROR:CRASH: 1   libsystem_platform.dylib            0x000000019f69b584 _sigtramp + 56
ERROR:CRASH: 2   libsystem_pthread.dylib             0x000000019f66ac20 pthread_kill + 288
ERROR:CRASH: 3   libsystem_c.dylib                   0x000000019f577a20 abort + 180
ERROR:CRASH: 4   libsystem_c.dylib                   0x000000019f576d10 err + 0
ERROR:CRASH: 5   dmengine                            0x00000001024d73a8 _ZN12dmGameSystem16CompSpriteRenderERKN12dmGameObject22ComponentsRenderParamsE.cold.5 + 0
ERROR:CRASH: 6   dmengine                            0x00000001022a2bc0 _ZN12dmGameSystem16CompSpriteRenderERKN12dmGameObject22ComponentsRenderParamsE + 2480
ERROR:CRASH: 7   dmengine                            0x000000010225de3c _ZN12dmGameObject6RenderEPNS_16CollectionHandleE + 176
ERROR:CRASH: 8   dmengine                            0x000000010224a3e4 _ZN8dmEngine4StepEPNS_6EngineE + 980
ERROR:CRASH: 9   dmengine                            0x000000010224a974 _Z14dmEngineUpdatePN8dmEngine6EngineE + 32
ERROR:CRASH: 10  dmengine                            0x000000010224b54c _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE + 104
ERROR:CRASH: 11  dmengine                            0x000000010224b434 _Z11engine_mainiPPc + 88
ERROR:CRASH: 12  dyld                                0x000000019f2e20e0 start + 2360
ERROR:CRASH: 

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

### PR DESCRIPTION
**Pull request by JCash**
Fixes https://github.com/defold/defold/issues/8842

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

File: engine/gamesys/src/gamesys/components/comp_sprite.cpp [hunk 1]
```diff
@@ -417,7 +412,7 @@ namespace dmGameSystem
     static inline TextureSetResource* GetTextureSet(const SpriteComponent* component, uint32_t index) {
         const SpriteResourceOverrides* overrides = component->m_Overrides;
         const SpriteTexture* texture = 0;
-        if (overrides && !overrides->m_Textures.Empty())
+        if (overrides && index < overrides->m_Textures.Size())
```
Comment (JCash) [inline engine/gamesys/src/gamesys/components/comp_sprite.cpp:415]: If the overrides doesn't have such an index, let's skip to the next check.

**Review by Jhonnyg — APPROVED** [review]
